export interface OrigamiModelConfig {
    shapeWhitelist?: string[];
    shapeBlacklist?: string[];
    materialWhitelist?: string[];
    materialBlacklist?: string[];
    fska?: string;
    fbvs?: string;
    texturePattern?: string;
    materialBind?: number;
}

// NOTE: static fbvs's are cheaper than static fska's, so fvbs is preferred
const ORIGAMI_MODEL_CONFIGS: Map<string, OrigamiModelConfig> = new Map<string, OrigamiModelConfig>([
    ["Mobj_WoodBoxA", { fbvs: "C1" }],
    ["Mobj_WoodBoxB", { fbvs: "C1" }],
    ["Mobj_BlockHatena", { fbvs: "C1" }],
    ["Mobj_BlockTomeiHatena", { fbvs: "C2" }],
    ["Mobj_BlockSave", { fbvs: "C1" }],
    ["Mobj_TreeDeku", { fbvs: "C2" }],
    ["Mobj_GrassH", { fbvs: "C1" }],
    ["Mobj_GrassC", { fbvs: "C1" }],
    ["Mobj_IndoorPlantB", { fbvs: "C1" }],
    ["Mobj_RubbleA", { fbvs: "C1" }],
    ["Mobj_PotA", { fbvs: "C1" }],
    ["Mojb_PotB", { fbvs: "C1" }],
    ["Mobj_WoodBoxAWaterWay", { materialBlacklist: ["Mt_BG", "lambert1"], fbvs: "C1" }],
    ["Mobj_RockA", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["PaperAlpha__Mt_RockA", "Wire__Mt_Wire"] }],
    ["Mobj_RockB", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["Paper__Mt_Rock", "Wire__Mt_Wire"] }],
    ["Mobj_RockC", { shapeWhitelist: ["PaperStatic__Mt_RockC", "WireStatic__Mt_Wire"] }],
    ["Mobj_BoatA", { shapeWhitelist: ["Boat__Mt_Boat"] }],
    ["Mobj_BlockPow", { shapeWhitelist: ["BlockL__Mt_PowBlock"] }],
    ["Mobj_WaterCaveBoxA", { materialWhitelist: ["Mt_WaterCaveBoxA", "Mt_Wire"], shapeWhitelist: ["BoxBase__Mt_WaterCaveBoxA", "WireBase__Mt_Wire"] }],
    ["W4C1_StoreRoom", { shapeBlacklist: ["PipeFlameB__Mt_Pipe"] }],
    ["Mobj_GrassF", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["Grass__Mt_Grass"] }],
    ["Mobj_HugeRockA", { materialWhitelist: ["Mt_HugeRockA"], shapeWhitelist: ["Rock__Mt_HugeRockA"] }],
    ["Mobj_StallObjectA", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["Box__Mt_Box"] }],
    ["Mobj_CoffinA", { shapeBlacklist: ["MarkG__Mt_OrnamentGold", "MarkA__Mt_OrnamentGold", "MarkB__Mt_OrnamentGold", "MarkC__Mt_OrnamentGold", "MarkD__Mt_OrnamentGold", "MarkE__Mt_OrnamentGold"] }],
    ["Mobj_BarrelA", { shapeWhitelist: ["Wood1__Mt_Wood", "Wire1__Mt_Wire", "Metal1__Mt_Metal"] }],
    ["Mobj_StatueBody", {
        materialBlacklist: ["Mt_EyeLight", "Mt_ColorPattern"],
        shapeBlacklist: ["TextOff__Mt_Statue", "TextOn__Mt_Statue", "PedestalC__Mt_Statue", "PedestalA__Mt_Statue", "ColorPattern__Mt_ColorPattern"]
    }],
    ["Mobj_BarrelKNP", { shapeWhitelist: ["EdgeA__Mt_Edge", "Metal1__Mt_Metal", "Wood1__Mt_Wood"] }],
    ["Mobj_IceRockA", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["IceRock__Mt_Main_Albedo_Blue", "WireBase__Mt_Wire"] }],
    ["Mobj_ParasolA", { materialBlacklist: ["Mt_ParasolClose"] }],
    ["Mobj_KinopioStatueA", { shapeBlacklist: ["BaseB__Mt_Statue"] }],
    ["W3G3_HouseA", { materialBlacklist: ["Mt_Sahdow"] }],
    ["W3G3_HouseB", { materialBlacklist: ["Mt_Sahdow"] }],
    ["Mobj_TreeMountainA", { fska: "C1" }],
    ["Mobj_TreeMountainB", { fska: "C1" }],
    ["Mobj_TreeMountainC", { fska: "C1" }],
    ["Mobj_TreeGirlA", { fska: "N_WaitB1" }],
    ["Mobj_ClockPendulumA", { fska: "C1" }],
    ["Mobj_LabMachineA", { fska: "C2" }],
    ["Mobj_FlowerC", { fska: "C1" }],
    ["Mobj_OrigamiCastle", { fska: "C1" }],
    ["Mobj_PaperTapeLockMountainA", { fska: "C1" }],
    ["Mobj_PaperTapeLockMountainB", { fska: "C1" }],
    ["Mobj_PaperTapeLockMountainC", { fska: "C1" }],
    ["Mobj_PaperTapeLockMountainD", { fska: "C1" }],
    ["Mobj_PaperTapeLockMountainE", { fska: "C1" }],
    ["Mobj_CastleFlagA", { fska: "C1" }],
    ["Mobj_HangRope", { fska: "C2_End_C1" }],
    ["Item_Coin1", { fska: "C1" }],
    ["Item_Coin10", { fska: "C1" }],
    ["Item_Coin100", { fska: "C1" }],
    ["Item_Coin10000", { fska: "C1" }],
    ["Item_PaperTank", { fska: "C1" }],
    ["Item_Hammer", { fska: "C1" }],
    ["Item_Tail", { fska: "C1" }],
    ["Item_TailSuper", { fska: "C1" }],
    ["Item_SuperKinokoSet", { fska: "C1" }],
    ["Item_Star", { fska: "C1" }],
    ["Item_PaperSmall", { fska: "C1" }],
    ["Item_PaperMiddle", { fska: "C1" }],
    ["Item_PaperLarge", { fska: "C1" }],
    ["Item_OrigamiBookWater", { fska: "C1" }],
    ["Item_OrigamiBookFire", { fska: "C1" }],
    ["Item_OrigamiBookIce", { fska: "C1" }],
    ["Item_OrigamiBookEarth", { fska: "C1" }],
    ["Item_KinokoSuper", { fska: "C1" }],
    ["Item_KinokoGreat", { fska: "C1" }],
    ["Item_KinokoDry", { fska: "C1" }],
    ["Item_Kinoko", { fska: "C1" }],
    ["Item_KinokoDoubleSet", { fska: "C1" }],
    ["Item_HPMaxUPLarge", { fska: "C1" }],
    ["Item_HPMaxUPSmall", { fska: "C1" }],
    ["Item_HPMaxUp", { fska: "C1" }],
    ["Item_HeartSmall", { fska: "C1" }],
    ["Item_HeartMiddle", { fska: "C1" }],
    ["Item_HeartLarge", { fska: "C1" }],
    ["Item_Flower", { fska: "C1" }],
    ["Item_FlowerSuper", { fska: "C1" }],
    ["Item_FireSet", { fska: "C1" }],
    ["Mobj_WaterSurfaceCastleA", { fska: "C1" }],
    ["Mobj_WaterSurfaceThirdA", { fska: "C1" }],
    ["Mobj_WaterSurfaceHelpKinopioA", { fska: "C1" }],
    ["Mobj_WaterSurfaceTurnValveA", { fska: "C1" }],
    ["Mobj_WaterSurfaceTurnValveB", { fska: "C1" }],
    ["Mobj_WaterFallTurnValveA", { fska: "C1" }],
    ["Mobj_WaterSplashA", { fska: "C1" }],
    ["Mobj_WaterSplashRippleA", { fska: "C1_Flow_C2" }], // need to look at again
    ["Mobj_TreeConiferA", { fska: "C1" }],
    ["Mobj_TreeConiferC", { fska: "C1" }],
    ["Mobj_TreeConiferD", { fska: "C1" }],
    ["Mobj_PaperTapeLockA", { fska: "C1" }],
    ["Mobj_PaperTapeLockB", { fska: "C1" }],
    ["Mobj_PaperTapeLockC", { fska: "C1" }],
    ["Mobj_PaperTapeLockD", { fska: "C1" }],
    ["Mobj_PaperTapeLockE", { fska: "C1" }],
    ["Mobj_PaperTapeLockF", { fska: "C1" }],
    ["Mobj_PaperTapeLockG", { fska: "C1" }],
    ["Mobj_PaperTapeLockH", { fska: "C1" }],
    ["Mobj_PaperTapeLockI", { fska: "C1" }],
    ["Mobj_PaperTapeLockJ", { fska: "C1" }],
    ["Mobj_PaperTapeLockR", { fska: "C1" }],
    ["Mobj_PaperTapeLockN", { fska: "C1" }],
    ["Mobj_PaperTapeLockP", { fska: "C1" }],
    ["Mobj_PaperTapeLockS", { fska: "C1" }],
    ["Mobj_PaperTapeLockT", { fska: "C1" }],
    ["Mobj_PaperTapeLockU", { fska: "C1" }],
    ["Mobj_PaperTapeLockV", { fska: "C1" }],
    ["Mobj_PaperTapeLockW", { fska: "C1" }],
    ["Mobj_PaperTapeLockX", { fska: "C1" }],
    ["Mobj_PaperTapeLockZ", { fska: "C1" }],
    ["Mobj_HillPondA", { fska: "C1" }],
    ["Mobj_HillRiverA", { fska: "C1" }],
    ["Mobj_ObservatoryRiverA", { fska: "C1" }],
    ["Mobj_PaperTapeLockTowerA", { fska: "C1" }],
    ["Mobj_PaperTapeLockTowerB", { fska: "C1" }],
    ["Mobj_PaperTapeLockTowerC", { fska: "C1" }],
    ["Mobj_PaperTapeLockTowerD", { fska: "C1" }],
    ["Mobj_PaperTapeLockTowerE", { fska: "C1" }],
    ["Mobj_PaperTapeLockTowerF", { fska: "C1" }],
    ["Mobj_TreeMapleA", { fska: "C1" }],
    ["Mobj_TreeC", { fska: "C1" }],
    ["Mobj_OarWhitecapsA", { fska: "C1" }],
    ["Mobj_BoatWaveA", { fska: "C1" }],
    ["Mobj_BoatWaveB", { fska: "C1" }],
    ["Mobj_WaterSurfaceMomijiA", { fska: "C1" }],
    ["Mobj_WaterSurfaceMomijiB", { fska: "C1" }],
    ["Mobj_RiverA", { fska: "C1" }],
    ["Mobj_RiverB", { fska: "C1" }],
    ["Mobj_RiverC", { fska: "C1" }],
    ["Mobj_RiverD", { fska: "C1" }],
    ["Mobj_WaterSplashF", { fska: "C2" }],
    ["Mobj_RiverDriftwoodA", { fska: "C1" }],
    ["Mobj_RiverDriftwoodB", { fska: "C1" }],
    ["Mobj_RiverWhirlingTidesA", { fska: "C1" }],
    ["Mobj_RiverWhirlingTidesB", { fska: "C1" }],
    ["Mobj_RiverFallingRocksA", { fska: "C2" }],
    ["Mobj_WaterSurfaceWaterCaveA", { fska: "C2" }],
    ["Mobj_WaterSurfaceWaterCaveB", { fska: "C4" }],
    ["Mobj_WaterSurfaceWaterCaveC", { fska: "C1" }],
    ["Mobj_WaterSurfaceWaterCaveD", { fska: "C1" }],
    ["Mobj_WaterFlowingA", { fska: "C2_Flowing" }],
    ["Mobj_WaterFlowingB", { fska: "C2" }],
    ["Mobj_WaterFlowingC", { fska: "C1" }],
    ["Mobj_WaterBottleA", { fska: "C4" }], // might not be matched with surface water flow level
    ["Mobj_WaterCaveTurbineA", { fska: "C2" }],
    ["Mobj_WaterCaveTurbineD", { fska: "C1_Rotation" }],
    ["Mobj_WaterCaveTurbineC", { fska: "C1_Rotation_L1" }],
    ["Mobj_WaterFlowingPuzzleA", { fska: "C2" }],
    ["Mobj_WaterFlowingPuzzleB", { fska: "C2" }],
    ["Mobj_FloatingPierA", { shapeWhitelist: ["FloatingPierA1__Mt_FloatingPierA"], fska: "C4" }],
    ["Mobj_WaterSurfaceParkA", { fska: "C1" }],
    ["Mobj_WaterSurfaceParkB", { fska: "C1" }],
    ["Mobj_WaterSurfaceParkC", { fska: "C1" }],
    ["Mobj_LanternD", { materialBlacklist: ["Mt_Shasow"], fska: "C1" }],
    ["Mobj_LanternE", { fska: "C1" }],
    ["Mobj_BlockHatenaOrigami", { fska: "C2" }],
    ["Mobj_OrigamiPakupaku", { fska: "C1" }],
    ["Mobj_AccordionWallA", { materialBlacklist: ["Mt_Shade"] }],
    ["Mobj_WaterSurfaceKoopaCastleA", { fska: "C1" }],
    ["Mobj_PaperTapeRoll", { materialBlacklist: ["Mt_ColorPattern"] }],
    ["Mobj_GearC", { fska: "C2" }],
    ["Mobj_WaterSpaA", { fska: "C1" }],
    ["Mobj_WaterSpaC", { fska: "C3" }],
    ["Mobj_WaterSpaD", { fska: "C1" }],
    ["Mobj_WaterSpaE", { fska: "C1" }],
    ["Mobj_TreeJungleA", { fska: "C1" }],
    ["Mobj_GrassB", { fska: "C1" }],
    ["Mobj_BathPlugA", { fska: "C1" }],
    ["Mobj_WaterFlowingJungleB", { fska: "C1" }],
    ["Mobj_TreePelmanismA", { fska: "C2" }],
    ["Mobj_WaterFlowingSpaA", { fska: "C2" }],
    ["Mobj_WaterFlowingSpaD", { fska: "C1" }],
    ["Mobj_WaterPondA", { fska: "C1" }],
    ["Mobj_WaterSplashC", { fska: "C1" }],
    ["Mobj_WaterSurfaceB", { fska: "C1" }],
    ["Mobj_WaterFlowingE", { fska: "C2" }],
    ["Mobj_SmallShipWhitecapsA", { fska: "C1" }], // sometimes doesn't match level of surrounding water
    ["Mobj_OrbTowerWhitecapsA", { fska: "C1" }],
    ["Mobj_RingIslandWhitecapsA", { fska: "C1" }],
    ["Mobj_SpadeIslandWhitecapsA", { fska: "C1" }],
    ["Mobj_MoonIslandWhitecapsA", { fska: "C1" }],
    ["Mobj_MoonIslandWhitecapsB", { fska: "C1" }],
    ["Mobj_CloverIslandWhitecapsA", { fska: "C1" }],
    ["Mobj_HatenaIslandWhitecapsA", { fska: "C1" }],
    ["Mobj_HammerIslandWhitecapsA", { fska: "C1" }],
    ["Mobj_KinokoIslandWhitecapsA", { fska: "C1" }],
    ["Mobj_HeartIslandWhitecapsA", { fska: "C1" }],
    ["Mobj_DokuroIslandWhitecapsA", { fska: "C1" }],
    ["Mobj_MoonIslandWavcA", { fska: "C1" }],
    ["Mobj_TreeCoconutA", { fska: "C1" }],
    ["Mobj_TreeCoconutE", { fska: "C1" }],
    ["Mobj_TreeA", { fska: "C1" }],
    ["Mobj_PaperTapeLockOceanA", { fska: "C1" }],
    ["Mobj_PaperTapeLockOceanB", { fska: "C1" }],
    ["Mobj_PaperTapeLockOceanC", { fska: "C1" }],
    ["Mobj_PaperTapeLockOceanD", { fska: "C1" }],
    ["Mobj_PaperTapeLockOceanE", { fska: "C1" }],
    ["Mobj_PaperTapeLockOceanF", { fska: "C1" }],
    ["Mobj_PaperTapeLockOceanG", { fska: "C1" }],
    ["Mobj_ClubIsland", { fska: "C1" }],
    ["Mobj_MoonIsland", { fska: "C2" }],
    ["Mobj_DokuroIsland", { fska: "C1" }],
    ["Mobj_HammerIsland", { fska: "C1" }],
    ["Mobj_HeartIsland", { fska: "C1" }],
    ["Mobj_HatenaIsland", { fska: "C1" }],
    ["Mobj_KinokoIsland", { fska: "C1" }],
    ["Mobj_SpadeIsland", { fska: "C1" }],
    ["Mobj_RingIsland", { fska: "C1" }],
    ["Mobj_OrbTower", { fska: "C1" }],
    ["Mobj_PeachShip", { fska: "C1" }],
    ["Mobj_OceanFloatA", { fska: "C1" }],
    ["Mobj_OceanReefA", { fska: "C1" }],
    ["Mobj_OceanReefB", { fska: "C1" }],
    ["Mobj_OceanReefC", { fska: "C1" }],
    ["Mobj_OceanReefD", { fska: "C1" }],
    ["Mobj_OceanReefE", { fska: "C1" }],
    ["Mobj_OceanRockA", { fska: "C1" }],
    ["Mobj_OceanRockB", { fska: "C1" }],
    ["Mobj_OceanRockC", { fska: "C1" }],
    ["Mobj_OceanRockD", { fska: "C1" }],
    ["Mobj_OceanRockF", { fska: "C1" }],
    ["Mobj_OceanReefsA", { fska: "C1" }],
    ["Mobj_OceanReefsB", { fska: "C1" }],
    ["Mobj_OceanReefsC", { fska: "C1" }],
    ["Mobj_OceanReefsD", { fska: "C1" }],
    ["Mobj_OceanReefsE", { fska: "C1" }],
    ["Mobj_OceanReefsF", { fska: "C1" }],
    ["Mobj_OceanReefsG", { fska: "C1" }],
    ["Mobj_MirrorBallA", { fska: "C2" }],
    ["Mobj_BlackWaterSurfaceA", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceB", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceC", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceD", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceI", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceE", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceJ", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceK", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceF", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceG", { fska: "C1" }],
    ["Mobj_BlackWaterSurfaceH", { fska: "C1" }],
    ["Mobj_CeilingFanA", { fska: "C1" }],
    ["Mobj_WaterSurfacePoolA", { fska: "C1" }],
    ["Mobj_WaterSurfacePoolC", { fska: "C2" }],
    ["Mobj_WaterSplashB", { fska: "C1" }],
    ["Mobj_WaterSplashE", { fska: "C5" }],
    ["Mobj_PoolFloatWhitecapsA", { fska: "C1" }],
    ["Mobj_PaperTapeLockDesertA", { fska: "C1" }],
    ["Mobj_WaterSurfaceTownA", { fska: "C1" }],
    ["Mobj_WaterSurfaceTownB", { fska: "C1" }],
    ["Mobj_WaterSurfaceTownC", { fska: "C1" }],
    ["Mobj_WaterSurfaceTownD", { fska: "C1" }],
    ["Mobj_WaterSurfaceTownE", { fska: "C1" }],
    ["Mobj_WaterSurfaceTownF", { fska: "C1" }],
    ["Mobj_WaterSplashD", { fska: "C2" }],
    ["Mobj_WaterMillA", { fska: "C1" }],
    ["Mobj_GearB", { fska: "C1" }],
    ["Mobj_SetWindmill", { fska: "C1_Rotate" }],
    ["Sobj_CloudA", { fska: "C1" }],
    ["Sobj_CloudB", { fska: "C1" }],
    ["Sobj_CloudC", { fska: "C1" }],
    ["Sobj_CloudF", { fska: "C1" }],
    ["Sobj_CloudE", { fska: "C1" }],
    ["Sobj_CloudShadowA", { fska: "C1" }],
    ["Sobj_CloudShadowB", { fska: "C1" }],
    ["Sobj_CloudShadowD", { fska: "C1" }],
    ["Sobj_TreeConiferB", { fska: "C1" }],
    ["Mobj_WaterSurfaceA", { fska: "C1" }],
    ["Sobj_WaterfallA", { fska: "C1" }],
    ["Sobj_GondolaSceneryA", { fska: "C5" }],
    ["Mobj_NinjaSingboardA", { fska: "C1" }],
    ["Mobj_WaterSurfacePoolB", { fska: "C1" }],
    ["Mobj_PeachShipWhitecapsA", { fska: "C1" }],
    ["Mobj_ShipFlagA", { fska: "C1" }],
    ["Mobj_CanyonRiverA", { fska: "C1" }],
    ["Sobj_CloudU", { fska: "C1" }],
    ["Mobj_FenceC", { fska: "C1" }],
    ["Mobj_KoopaShipWhitecapsA", { fska: "C1" }],
    ["Mobj_LavaFallA", { fska: "C1" }],
    ["Mobj_LavaFallB", { fska: "C1" }],
    ["Mobj_LavaFallC", { fska: "C1" }],
    ["Mobj_LavaFallD", { fska: "C1" }],
    ["Mobj_CollaspeRockA", { fska: "C1" }],
    ["Mobj_VolcanoRockA", { fska: "C1" }],
    ["Sobj_CloudO", { fska: "C1" }],
    ["Sobj_CloudV", { fska: "C1" }],
    ["Sobj_CloudW", { fska: "C1" }],
    ["Sobj_CloudX", { fska: "C1" }],
    ["Mobj_RideA", { fska: "C1" }],
    ["Sobj_BlackWaterBubbleA", { fska: "C1_Expand" }],
    ["Sobj_BlackWaterBubbleB", { fska: "C1_Expand" }],
    ["Sobj_FireBlackWaterA", { fska: "C1" }],
    ["Sobj_FireBlackWaterB", { fska: "C1" }],
    ["Sobj_FireBlackWaterC", { fska: "C1" }],
    ["Sobj_FireBlackWaterD", { fska: "C1" }],
    ["Sobj_FireBlackWaterE", { fska: "C1" }],
    ["O_HEI", { materialBlacklist: ["Mt_ColorPattern1", "Mt_HEI_BS"], fska: "N_WaitA1" }],
    ["O_PCH", { materialBlacklist: ["Mt_ColorPattern", "Mt_PCH_BS"], fska: "N_WaitA1" }],
    ["P_MET", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_KUR", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_NOK", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_BRSH", { materialBlacklist: ["Mt_HimPera"], shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1", materialBind: 1 }],
    ["P_GBN", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_LUG", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_KPA", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_PCH", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_KMK", { materialBlacklist: ["Mt_Decal"], shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1", materialBind: 1 }],
    ["P_KPAJ", { materialBlacklist: ["Mt_Decal"], shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1", materialBind: 1 }],
    ["P_KNPOLI", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["O_KNG", { materialBlacklist: ["Mt_KNG_BS"], fska: "N_WaitA1" }],
    ["O_KUR", { materialBlacklist: ["Mt_KUR_BS"], fska: "N_WaitA1" }],
    ["O_BSA", { materialBlacklist: ["Mt_BSA_BS"], fska: "N_WaitA1" }],
    ["O_CHU", { materialBlacklist: ["Mt_CHU_BS"], fska: "N_WaitA1" }],
    ["P_KPAO", { materialBlacklist: ["Mt_decal"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["O_NOK", { materialBlacklist: ["Mt_ColorPattern", "Mt_NOK_BS", "Mt_NOK_Shell_BS"], fska: "N_WaitA1" }],
    ["O_BRSH", { materialBlacklist: ["Mt_BRSH_BS", "lambert1"], fska: "N_WaitA1" }],
    ["O_GBN", { materialBlacklist: ["Mt_GBN_BS", "Mt_GBN_W", "Mt_GBN_W_BS"], fska: "N_WaitA1" }],
    ["P_KNP", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_KNPC", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_KNPCAP", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_KNP_Town", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "Gallery_Stand_1", texturePattern: "Gallery_Stand_1" }],
    ["P_KNPN", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_KNP_Saisyo", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_KNP_Maki", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "WRY_Stand_1", texturePattern: "WRY_Stand_1" }],
    ["P_KNP_Shop", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["O_KNP_Semi", { materialBlacklist: ["Mt_O_KNP_Semi_BS", "Mt_ColorPattern"], fska: "N_WalkA1" }],
    ["O_KNP_FlowerB", { materialBlacklist: ["Mt_KNP_FlowerB_BS", "Mt_ColorPattern"], fska: "N_WaitA1" }],
    ["OG_FIR", { materialBlacklist: ["Mt_FIR_BDY_Cap_BS", "Mt_ColorPattern", "Mt_FIR_KNG_Crown_BS"], fska: "N_WaitA1" }],
    ["P_CRN", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["P_HEI", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Stand_1", texturePattern: "NML_Stand_1" }],
    ["Mobj_KingSealF1", { fbvs: "C1" }],
    ["Mobj_StretchPassageA", { fska: "C1", texturePattern: "C1" }],
    ["W1G1_KartRoad", { fbvs: "C1" }],
    ["P_KNP_E", { shapeWhitelist: ["Pera01_Shape__Mt_Pera"], fska: "NML_Walk_1", texturePattern: "NML_Walk_1" }],
]);

export function getOrigamiModelConfig(id: string): OrigamiModelConfig | undefined {
    return ORIGAMI_MODEL_CONFIGS.get(id);
}
