export interface OrigamiModelConfig {
    shapeWhitelist?: string[];
    shapeBlacklist?: string[];
    materialWhitelist?: string[];
    materialBlacklist?: string[];
    fska?: string;
    fbvs?: string;
    texturePattern?: string;
    shaderParam?: string;
}

const C1 = "C1";
const IDLE1 = "NML_Stand_1";
const IDLE2 = "N_WaitA1";
const PERA_SHAPE = ["Pera01_Shape__Mt_Pera"];

// static fbvs's are cheaper than static fska's, use when fska doesn't do any srt
// see modeldata for materials always ignored like shadows
// bone visibilities are automatic when fska/fbvs is specified and one exists with the same name

// model configs are needed to know which animations to load by default and which shapes or materials to whitelist or blacklist

// common configs grouped by name, checked before the other map
const SHARED_ORIGAMI_MODEL_CONFIGS: Map<OrigamiModelConfig, string[]> = new Map<OrigamiModelConfig, string[]>([
    [{ fska: IDLE2 },
    ["B_GOM", "B_HPC", "B_TAP_Last_new", "B_TAP_new", "B_TAP_Part", "H_BBL", "H_BOM", "H_GBNG", "H_GBNR", "H_GESB",
        "H_GESB_Foot1", "H_HEI", "H_HEID", "H_HEIM", "H_KURG", "H_KURM", "H_MET", "H_METF_Face", "H_MUTG", "H_NOK", "H_NOKG",
        "H_PAT", "H_SNBB", "H_TRS", "O_BDY", "O_BDY_COSA", "O_BDY_COSB", "O_BDY_COSC", "O_BDY_COSD", "O_BDY_COSE", "O_BRSB",
        "O_BRSF", "O_BRSH", "O_BRSI", "O_BRSM", "O_BSA", "O_BSAD", "O_BUL", "O_CBN", "O_CHU", "O_HEI", "O_KBN", "O_KNG",
        "O_KNK", "O_KNP_Butterfly", "O_KNP_Dog", "O_KNP_Dragonfly", "O_KNP_FlowerA", "O_KNP_FlowerB", "O_KNP_Monkey",
        "O_KNP_Prairiedog", "O_KNP_Scarab", "O_KNP_Waterfowl", "O_KUR", "O_KURP", "O_NOK", "O_PCH", "O_PUK", "O_PUK_Fishing",
        "O_TGZ", "OG_ETH", "OG_FIR", "OG_WTR", "O_CHUD", "O_FPAC", "O_GES", "O_GSG", "O_HCN", "O_HEIP", "O_HKN", "O_KNG_Last",
        "O_KNP_Cat", "O_KNP_Excavator", "O_KNP_Lizard", "O_KNP_Rabbit", "O_KNP_Scorpion", "O_KNP_Snake", "O_KNP_Throwingstar",
        "O_KPAM", "O_KRN", "O_KSK", "O_KURB", "O_KURK", "O_MET", "O_METT", "O_MUC", "O_MUCI", "O_PAT", "O_PKF", "O_POO",
        "O_PPK", "O_SMO", "O_SMOM", "O_SNB", "O_TRS", "OG_ICE", "PC_HND", "PC_HND2", "PC_SLD", "PC_SLDP"]],
    [{ shapeWhitelist: PERA_SHAPE, fska: IDLE1, texturePattern: IDLE1 },
    ["P_BOME", "P_CRN", "P_CRP", "P_GBN", "P_HEI", "P_HEISOM", "P_KNP", "P_KNP_Break", "P_KNP_Saisyo", "P_KNP_Shop",
        "P_KNPBT", "P_KNPC", "P_KNPCAP", "P_KNPCK", "P_KNPG", "P_KNPN", "P_KNPOLI", "P_KPA", "P_KUR", "P_KURB", "P_LUG",
        "P_MET", "P_NOK", "P_PCH", "P_PUK", "P_BOM", "P_BOM_Cosplay", "P_BOM_END", "P_BOMG", "P_CRP_END", "P_CRP_Shop",
        "P_FPAC", "P_GES", "P_GES_Fishing", "P_HEIL", "P_HKN", "P_WAN", "P_KNPST", "P_TGZ", "P_PAT", "P_PAT_END", "P_NOKC",
        "P_NOKC_END", "P_NOK_END", "P_MUCL", "P_MUCC", "P_LUG_Kart", "P_LUG_HatLose", "P_LUG_Gear", "P_LIT", "P_KURC",
        "P_KUR_END", "P_KNP_Sumi", "P_KNP_Hole", "P_KNP_HeadBrk", "P_KNP_Head", "P_KNP_END", "P_KNPE", "P_KNPE_END",
        "P_KNPNIN", "P_KNPST_GOM", "P_KNPP", "P_KNPSK", "P_KPA_Crown", "P_KNPASS"]],
    // lots of these should probably be checked again for fbvs instead of fska. Most were checked before fbvs's were parsed
    [{ fska: C1 },
    ["Item_Coin1", "Item_Coin10", "Item_Coin100", "Item_Coin10000", "Item_FireSet", "Item_Flower", "Item_FlowerSuper",
        "Item_Hammer", "Item_HeartLarge", "Item_HeartMiddle", "Item_HeartSmall", "Item_HPMaxUp", "Item_HPMaxUPLarge",
        "Item_HPMaxUPSmall", "Item_Kinoko", "Item_KinokoDoubleSet", "Item_KinokoDry", "Item_KinokoGreat", "Item_KinokoSuper",
        "Item_OrigamiBookEarth", "Item_OrigamiBookFire", "Item_OrigamiBookIce", "Item_OrigamiBookWater", "Item_PaperLarge",
        "Item_PaperMiddle", "Item_PaperSmall", "Item_PaperTank", "Item_Star", "Item_SuperKinokoSet", "Item_Tail", "Item_TailSuper",
        "Mobj_BathPlugA", "Mobj_BlackWaterSurfaceA", "Mobj_BlackWaterSurfaceB", "Mobj_BlackWaterSurfaceC", "Mobj_BlackWaterSurfaceD",
        "Mobj_BlackWaterSurfaceE", "Mobj_BlackWaterSurfaceF", "Mobj_BlackWaterSurfaceG", "Mobj_BlackWaterSurfaceH",
        "Mobj_BlackWaterSurfaceI", "Mobj_BlackWaterSurfaceJ", "Mobj_BlackWaterSurfaceK", "Mobj_BoatWaveA", "Mobj_BoatWaveB",
        "Mobj_CanyonRiverA", "Mobj_CastleFlagA", "Mobj_CeilingFanA", "Mobj_ClockPendulumA", "Mobj_CloverIslandWhitecapsA",
        "Mobj_ClubIsland", "Mobj_CollapseWallTurtleBoss", "Mobj_CollaspeRockA", "Mobj_DokuroIsland", "Mobj_DokuroIslandWhitecapsA",
        "Mobj_FlowerC", "Mobj_GearB", "Mobj_GrassB", "Mobj_HammerIsland", "Mobj_HammerIslandWhitecapsA", "Mobj_HatenaIsland",
        "Mobj_HatenaIslandWhitecapsA", "Mobj_HeartIsland", "Mobj_HeartIslandWhitecapsA", "Mobj_HillPondA", "Mobj_HillRiverA",
        "Mobj_KinokoIsland", "Mobj_KinokoIslandWhitecapsA", "Mobj_KoopaShipWhitecapsA", "Mobj_LanternE", "Mobj_MoonIslandWavcA",
        "Mobj_MoonIslandWhitecapsA", "Mobj_MoonIslandWhitecapsB", "Mobj_NinjaSingboardA", "Mobj_OarWhitecapsA", "Mobj_ObservatoryRiverA",
        "Mobj_OceanFloatA", "Mobj_OceanReefA", "Mobj_OceanReefB", "Mobj_OceanReefC", "Mobj_OceanReefD", "Mobj_OceanReefE",
        "Mobj_OceanReefsA", "Mobj_OceanReefsB", "Mobj_OceanReefsC", "Mobj_OceanReefsD", "Mobj_OceanReefsE", "Mobj_OceanReefsF",
        "Mobj_OceanReefsG", "Mobj_OceanRockA", "Mobj_OceanRockB", "Mobj_OceanRockC", "Mobj_OceanRockD", "Mobj_OceanRockF", "Mobj_OrbTower",
        "Mobj_OrbTowerWhitecapsA", "Mobj_OrigamiCastle", "Mobj_OrigamiPakupaku", "Mobj_PaperTapeLockA", "Mobj_PaperTapeLockB",
        "Mobj_PaperTapeLockC", "Mobj_PaperTapeLockD", "Mobj_PaperTapeLockDesertA", "Mobj_PaperTapeLockE", "Mobj_PaperTapeLockF",
        "Mobj_PaperTapeLockG", "Mobj_PaperTapeLockH", "Mobj_PaperTapeLockI", "Mobj_PaperTapeLockJ", "Mobj_PaperTapeLockMountainA",
        "Mobj_PaperTapeLockMountainB", "Mobj_PaperTapeLockMountainC", "Mobj_PaperTapeLockMountainD", "Mobj_PaperTapeLockMountainE",
        "Mobj_PaperTapeLockN", "Mobj_PaperTapeLockOceanA", "Mobj_PaperTapeLockOceanB", "Mobj_PaperTapeLockOceanC", "Mobj_PaperTapeLockOceanD",
        "Mobj_PaperTapeLockOceanE", "Mobj_PaperTapeLockOceanF", "Mobj_PaperTapeLockOceanG", "Mobj_PaperTapeLockP", "Mobj_PaperTapeLockR",
        "Mobj_PaperTapeLockS", "Mobj_PaperTapeLockT", "Mobj_PaperTapeLockTowerA", "Mobj_PaperTapeLockTowerB", "Mobj_PaperTapeLockTowerC",
        "Mobj_PaperTapeLockTowerD", "Mobj_PaperTapeLockTowerE", "Mobj_PaperTapeLockTowerF", "Mobj_PaperTapeLockU", "Mobj_PaperTapeLockV",
        "Mobj_PaperTapeLockW", "Mobj_PaperTapeLockX", "Mobj_PaperTapeLockZ", "Mobj_PeachShip", "Mobj_PeachShipWhitecapsA",
        "Mobj_PoolFloatWhitecapsA", "Mobj_RideA", "Mobj_RingIsland", "Mobj_RingIslandWhitecapsA", "Mobj_RiverA", "Mobj_RiverB", "Mobj_RiverC",
        "Mobj_RiverD", "Mobj_RiverDriftwoodA", "Mobj_RiverDriftwoodB", "Mobj_RiverWhirlingTidesA", "Mobj_RiverWhirlingTidesB", "Mobj_ShipFlagA",
        "Mobj_SmallShipWhitecapsA", "Mobj_SpadeIsland", "Mobj_SpadeIslandWhitecapsA", "Mobj_TreeA", "Mobj_TreeC", "Mobj_TreeCoconutA",
        "Mobj_TreeCoconutE", "Mobj_TreeConiferA", "Mobj_TreeConiferC", "Mobj_TreeConiferD", "Mobj_TreeJungleA", "Mobj_TreeMapleA", "Mobj_TreeMountainA",
        "Mobj_TreeMountainB", "Mobj_TreeMountainC", "Mobj_VolcanoRockA", "Mobj_WaterFallTurnValveA", "Mobj_WaterFlowingC", "Mobj_WaterFlowingSpaD",
        "Mobj_WaterMillA", "Mobj_WaterPondA", "Mobj_WaterSpaA", "Mobj_WaterSpaD", "Mobj_WaterSpaE", "Mobj_WaterSplashA", "Mobj_WaterSplashB",
        "Mobj_WaterSurfaceA", "Mobj_WaterSurfaceB", "Mobj_WaterSurfaceCastleA", "Mobj_WaterSurfaceHelpKinopioA", "Mobj_WaterSurfaceKoopaCastleA",
        "Mobj_WaterSurfaceMomijiA", "Mobj_WaterSurfaceMomijiB", "Mobj_WaterSurfaceNinjaA", "Mobj_WaterSurfaceParkA",
        "Mobj_WaterSurfaceParkB", "Mobj_WaterSurfaceParkC", "Mobj_WaterSurfacePoolA", "Mobj_WaterSurfacePoolB", "Mobj_WaterSurfaceThirdA",
        "Mobj_WaterSurfaceTownA", "Mobj_WaterSurfaceTownB", "Mobj_WaterSurfaceTownC", "Mobj_WaterSurfaceTownD", "Mobj_WaterSurfaceTownE",
        "Mobj_WaterSurfaceTownF", "Mobj_WaterSurfaceTurnValveA", "Mobj_WaterSurfaceTurnValveB", "Mobj_WaterSurfaceWaterCaveC",
        "Mobj_WaterSurfaceWaterCaveD", "Sobj_CloudA", "Sobj_CloudB", "Sobj_CloudC", "Sobj_CloudE", "Sobj_CloudF", "Sobj_CloudI", "Sobj_CloudO",
        "Sobj_CloudShadowA", "Sobj_CloudShadowB", "Sobj_CloudShadowD", "Sobj_CloudR", "Sobj_CloudU", "Sobj_CloudV", "Sobj_CloudW", "Sobj_CloudX",
        "Sobj_CloudJ", "Sobj_CloudZ", "Sobj_FireBlackWaterA", "Sobj_FireBlackWaterB", "Sobj_FireBlackWaterC", "Sobj_FireBlackWaterD",
        "Sobj_FireBlackWaterE", "Sobj_SandStormA", "Sobj_SandStormB", "Sobj_SandStormC", "Sobj_SandStormD", "Sobj_ShootingCloudA", "Sobj_ShootingCloudB",
        "Sobj_StormWindA", "Sobj_TreeConiferB", "Mobj_PelmanismLeaf", "Mobj_TheaterCurtainA", "Mobj_CactusE", "Mobj_CactusA", "Mobj_CactusB",
        "Mobj_CactusC", "Mobj_CactusD"]]
]);

const ORIGAMI_MODEL_CONFIGS: Map<string, OrigamiModelConfig> = new Map<string, OrigamiModelConfig>([
    // boss origamis
    ["B_PEN", { fska: "N_Close_WaitA1" }],
    ["B_PENP", { materialBlacklist: ["Mt_Decal1"] }],
    ["B_SCS_new", { fska: "N_WaitB1" }],
    ["B_STP_new", { fska: "N_WaitB1" }],
    // paper maches
    ["H_GESB_Foot2", { fska: "N_WaitB1" }],
    ["H_HEIMM", { fska: "E_WaitA1" }],
    ["H_KUR", { fska: "N_StandA1" }],
    ["H_PKF", { fska: "N_WaitB1" }],
    ["H_WAN", { fska: "N_RunA1" }],
    // mobjs/aobjs
    ["Mobj_AccordionWallA", { materialBlacklist: ["Mt_Shade"] }],
    ["Mobj_BarrelA", { shapeWhitelist: ["Wood1__Mt_Wood", "Wire1__Mt_Wire", "Metal1__Mt_Metal"] }],
    ["Mobj_BarrelKNP", { shapeWhitelist: ["EdgeA__Mt_Edge", "Metal1__Mt_Metal", "Wood1__Mt_Wood"] }],
    ["Mobj_BlockHatena", { fbvs: C1, texturePattern: C1 }],
    ["Mobj_BlockHatenaOrigami", { fska: "C2" }],
    ["Mobj_BlockPow", { shapeWhitelist: ["BlockL__Mt_PowBlock"] }],
    ["Mobj_BlockRenga", { fbvs: C1 }],
    ["Mobj_BlockSave", { fbvs: C1, texturePattern: "Color", shaderParam: "Color" }],
    ["Mobj_BlockTomeiHatena", { fbvs: "C2", texturePattern: "C2" }],
    ["Mobj_BoatA", { shapeWhitelist: ["Boat__Mt_Boat"] }],
    ["Mobj_ChestnutBur", { fbvs: C1 }],
    ["Mobj_CoffinA", { shapeBlacklist: ["MarkG__Mt_OrnamentGold", "MarkA__Mt_OrnamentGold", "MarkB__Mt_OrnamentGold", "MarkC__Mt_OrnamentGold", "MarkD__Mt_OrnamentGold", "MarkE__Mt_OrnamentGold"] }],
    ["Mobj_CollapseWallFooting", { fska: "C2" }],
    ["Mobj_ElevatorDoorA", { fbvs: C1 }],
    ["Mobj_FallenLeavesA", { fbvs: C1 }],
    ["Mobj_FenceC", { fbvs: C1 }],
    ["Mobj_FloatingPierA", { shapeWhitelist: ["FloatingPierA1__Mt_FloatingPierA"], fska: "C4" }],
    ["Mobj_GearC", { fska: "C2" }],
    ["Mobj_GrassC", { fbvs: C1 }],
    ["Mobj_GrassF", { shapeWhitelist: ["Grass__Mt_Grass"] }],
    ["Mobj_GrassH", { fbvs: C1 }],
    ["Mobj_HangRope", { fska: "C2_End_C1" }],
    ["Mobj_HugeRockA", { materialWhitelist: ["Mt_HugeRockA"], shapeWhitelist: ["Rock__Mt_HugeRockA"] }],
    ["Mobj_IceRockA", { shapeWhitelist: ["IceRock__Mt_Main_Albedo_Blue", "WireBase__Mt_Wire"] }],
    ["Mobj_IndoorPlantB", { fbvs: C1 }],
    ["Mobj_KingSealA1", { fbvs: C1 }],
    ["Mobj_KingSealB7", { fbvs: C1 }],
    ["Mobj_KingSealB8", { fbvs: C1 }],
    ["Mobj_KingSealC1", { fbvs: C1 }],
    ["Mobj_KingSealC2", { fbvs: C1 }],
    ["Mobj_KingSealC3", { fbvs: C1 }],
    ["Mobj_KingSealC4", { fbvs: C1 }],
    ["Mobj_KingSealC6", { fbvs: C1 }],
    ["Mobj_KingSealC7", { fbvs: C1 }],
    ["Mobj_KingSealC8", { fbvs: C1 }],
    ["Mobj_KingSealC9", { fbvs: C1 }],
    ["Mobj_KingSealC10", { fbvs: C1 }],
    ["Mobj_KingSealF1", { fbvs: C1 }],
    ["Mobj_KingSealF2", { fbvs: C1 }],
    ["Mobj_KingSealF3", { fbvs: C1 }],
    ["Mobj_KinopioStatueA", { shapeBlacklist: ["BaseB__Mt_Statue"], fbvs: C1 }],
    ["Mobj_LabMachineA", { fska: "C2" }],
    ["Mobj_LanternD", { materialBlacklist: ["Mt_Shasow"], fska: C1 }],
    ["Mobj_LavaFallA", { fska: C1, shaderParam: C1 }],
    ["Mobj_LavaFallB", { fska: C1, shaderParam: C1 }],
    ["Mobj_LavaFallC", { fska: C1, shaderParam: C1 }],
    ["Mobj_LavaFallD", { fska: C1, shaderParam: C1 }],
    ["Mobj_MirrorBallA", { fska: "C2" }],
    ["Mobj_MoonIsland", { fska: "C2" }],
    ["Mobj_ParasolA", { materialBlacklist: ["Mt_ParasolClose"] }],
    ["Mobj_PotA", { fbvs: C1 }],
    ["Mobj_RiverFallingRocksA", { fska: "C2" }],
    ["Mobj_RockA", { shapeWhitelist: ["PaperAlpha__Mt_RockA", "Wire__Mt_Wire"] }],
    ["Mobj_RockB", { shapeWhitelist: ["Paper__Mt_Rock", "Wire__Mt_Wire"] }],
    ["Mobj_RockC", { shapeWhitelist: ["PaperStatic__Mt_RockC", "WireStatic__Mt_Wire"] }],
    ["Mobj_RubbleA", { fbvs: C1 }],
    ["Mobj_SetWindmill", { fska: "C1_Rotate" }],
    ["Mobj_StallObjectA", { shapeWhitelist: ["Box__Mt_Box"] }],
    ["Mobj_StatueA", { fbvs: C1 }],
    ["Mobj_StatueB", { fbvs: C1 }],
    ["Mobj_StatueBody", { fbvs: C1 }],
    ["Mobj_StretchPassageA", { fska: C1, texturePattern: C1 }],
    ["Mobj_ThirdFloor", { fska: "C2" }],
    ["Mobj_TreeDeku", { fbvs: "C2" }],
    ["Mobj_TreeGirlA", { fska: "N_WaitB1" }],
    ["Mobj_TreePelmanismA", { fska: "C2" }],
    ["Mobj_TurtleStatueA", { fbvs: C1 }],
    ["Mobj_WaterBottleA", { fska: "C4", shaderParam: "C4" }],
    ["Mobj_WaterCaveBoxA", { fbvs: C1 }],
    ["Mobj_WaterCaveTurbineA", { fska: "C2" }],
    ["Mobj_WaterCaveTurbineC", { fska: "C1_Rotation_L1" }],
    ["Mobj_WaterCaveTurbineD", { fska: "C1_Rotation" }],
    ["Mobj_WaterFlowingA", { fska: "C2_Flowing" }],
    ["Mobj_WaterFlowingB", { fska: "C2" }],
    ["Mobj_WaterFlowingE", { fska: "C2" }],
    ["Mobj_WaterFlowingJungleB", { fska: C1, shaderParam: C1 }],
    ["Mobj_WaterFlowingPuzzleA", { fska: "C2" }],
    ["Mobj_WaterFlowingPuzzleB", { fska: "C2" }],
    ["Mobj_WaterFlowingSpaA", { fska: "C2", shaderParam: "C2" }],
    ["Mobj_WaterFlowingSpaB", { fska: C1, shaderParam: C1 }],
    ["Mobj_WaterIceMapA", { materialBlacklist: ["Mt_WaterIceMapA"] }], // hide entire model for now
    ["Mobj_WaterSpaC", { fska: "C3" }],
    ["Mobj_WaterSplashC", { fska: C1, shaderParam: C1 }],
    ["Mobj_WaterSplashD", { fska: "C2" }],
    ["Mobj_WaterSplashE", { fska: "C5" }],
    ["Mobj_WaterSplashF", { fska: "C2" }],
    ["Mobj_WaterSplashRippleA", { fska: "C1_Flow_C2" }],
    ["Mobj_WaterSurfacePoolC", { fska: "C2" }],
    ["Mobj_WaterSurfaceWaterCaveA", { fska: "C2" }],
    ["Mobj_WaterSurfaceWaterCaveB", { fska: "C4" }],
    ["Mobj_WoodBoxA", { fbvs: C1 }],
    ["Mobj_WoodBoxAWaterWay", { materialBlacklist: ["Mt_BG"], fbvs: C1 }],
    ["Mobj_WoodBoxB", { fbvs: C1 }],
    ["Mojb_PotB", { fbvs: C1 }],
    ["Mobj_JapanesePalasolA", { fbvs: "C2" }],
    // origamis
    ["O_BDY_Doll", { fbvs: IDLE2 }],
    ["O_BDY_HMR", { fbvs: IDLE2 }],
    ["O_GBN", { materialBlacklist: ["Mt_GBN_W"], fska: IDLE2 }],
    ["O_GBNI", { materialBlacklist: ["Mt_GBNI_W"], fska: IDLE2 }],
    ["O_GBNR", { materialBlacklist: ["Mt_GBNR_W"], fska: IDLE2 }],
    ["O_KNG_Damage", { fska: "W_TalkA1" }],
    ["O_KNG_Doll", { fbvs: IDLE2 }],
    ["O_KNP_Bonsai", { fska: "N_ActionA1" }],
    ["O_KNP_Cactus", { fska: "N_ActionA1" }],
    ["O_KNP_Chestnut", { fska: "N_ActionA1" }],
    ["O_KNP_Fall", { fska: "N_ActionA1" }],
    ["O_KNP_FishA", { fska: "N_WalkA1" }],
    ["O_KNP_FishB", { fska: "N_WalkA1" }],
    ["O_KNP_FishC", { fska: "N_WalkA1" }],
    ["O_KNP_Flag", { fska: "N_WindA1" }],
    ["O_KNP_Heart", { fska: "N_ActionA1" }],
    ["O_KNP_Locust", { fska: "N_WalkA1" }],
    ["O_KNP_Maple", { fska: "N_MoveA1" }],
    ["O_KNP_Mushroom", { fska: "N_ActionA1" }],
    ["O_KNP_Semi", { fska: "N_WalkA1" }],
    ["O_KNP_Signboard", { fska: "N_ActionA1" }],
    ["O_KNP_Skull", { fska: "N_ActionA1" }],
    ["O_KNP_Tower", { fska: "N_ActionA1" }],
    ["O_KNP_Tyouchin", { fska: "N_ActionA1" }],
    ["O_KNP_Vase", { fska: "N_ActionA1" }],
    ["O_PUK_Ball", { fska: "N_SwimA1" }],
    ["O_PKFP", { fska: "N_WaitB1" }],
    // 2d paper npcs
    ["P_BRSH", { materialBlacklist: ["Mt_HimPera"], shapeWhitelist: PERA_SHAPE, fska: IDLE1, texturePattern: IDLE1 }],
    ["P_BRSM", { materialBlacklist: ["Mt_HmrPera"], shapeWhitelist: PERA_SHAPE, fska: IDLE1, texturePattern: IDLE1 }],
    ["P_CRN_END", { shapeWhitelist: PERA_SHAPE, fska: "HPY_Walk_2", texturePattern: "HPY_Walk_2" }],
    ["P_CRP_Roll", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_CRN_Shop_END", { shapeWhitelist: PERA_SHAPE, fska: "NML_Talk_1", texturePattern: "NML_Talk_1" }],
    ["P_DSN", { fska: "NML_Stand_4", texturePattern: "NML_Stand_4" }],
    ["P_GBN_END", { shapeWhitelist: PERA_SHAPE, fska: "NML_Talk_1", texturePattern: "NML_Talk_1" }],
    ["P_GES_E", { fbvs: IDLE1, texturePattern: IDLE1 }],
    ["P_GES_E", { fska: "Cover_On_1", texturePattern: "Cover_On_1" }],
    ["P_KMK", { materialBlacklist: ["Mt_Decal"], shapeWhitelist: PERA_SHAPE, fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KMK_Division", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KMK_END", { shapeWhitelist: PERA_SHAPE, fska: "CLN_Clean_2", texturePattern: "CLN_Clean_2" }],
    ["P_KNP_Accordion", { fska: "NML_Stand_2", texturePattern: "NML_Stand_2" }],
    ["P_KNP_Ball", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Break", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Bundle", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Bundle2", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Bundle3", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Crew", { fska: "NML_Salute_2", texturePattern: "NML_Salute_2" }],
    ["P_KNP_Cylinder", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Dance", { shapeWhitelist: PERA_SHAPE, fska: "Dance_Disco_1", texturePattern: "Dance_Disco_1" }],
    ["P_KNP_Dead", { shapeWhitelist: PERA_SHAPE, fska: "Dead_Normal_1A", texturePattern: "Dead_Normal_1A" }],
    ["P_KNP_E", { shapeWhitelist: PERA_SHAPE, fska: "NML_Walk_1", texturePattern: "NML_Walk_1" }],
    ["P_KNP_Eat", { shapeWhitelist: PERA_SHAPE, fska: "Eat_Stand_1", texturePattern: "Eat_Stand_1" }],
    ["P_KNP_Factory", { shapeWhitelist: PERA_SHAPE, fska: "EVT_Command_1A", texturePattern: "EVT_Command_1A" }],
    ["P_KNP_Fold", { shapeWhitelist: PERA_SHAPE, fska: "NML_Fold_1", texturePattern: "NML_Fold_1" }],
    ["P_KNP_Foldbox", { fbvs: "NML_Open", texturePattern: "NML_Open" }],
    ["P_KNP_Hide", { fska: "Bury_Stand_1", texturePattern: "Bury_Stand_1" }],
    ["P_KNP_Hole_Dance", { shapeWhitelist: PERA_SHAPE, fska: "Dance_Stand_1", texturePattern: "Dance_Stand_1" }],
    ["P_KNP_HoleHead", { shapeWhitelist: PERA_SHAPE, fska: "NML_Struggle_1", texturePattern: "NML_Struggle_1" }],
    ["P_KNP_HoleBundle", { fska: "NML_Stand_1_1", texturePattern: "NML_Stand_1_1" }],
    ["P_KNP_Keijiban", { fska: "NML_StopA1", texturePattern: "NML_StopA1" }],
    ["P_KNP_L", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_LL", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Mado", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Maki", { shapeWhitelist: PERA_SHAPE, fska: "WRY_Stand_1", texturePattern: "WRY_Stand_1" }],
    ["P_KNP_News", { shapeWhitelist: PERA_SHAPE, fska: "NewsSit_Stand_1", texturePattern: "NewsSit_Stand_1" }],
    ["P_KNP_Paste", { shapeWhitelist: PERA_SHAPE, fska: "Paste_On_1", texturePattern: "Paste_On_1" }],
    ["P_KNP_Roll", { shapeWhitelist: PERA_SHAPE, fska: "Serious_Stand_1", texturePattern: "Serious_Stand_1" }],
    ["P_KNP_Roll", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Tegami", { fbvs: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Telescope", { fbvs: IDLE1, texturePattern: IDLE1 }],
    ["P_KNP_Town", { shapeWhitelist: PERA_SHAPE, fska: "Gallery_Stand_1", texturePattern: "Gallery_Stand_1" }],
    ["P_KNP_Unique", { shapeWhitelist: PERA_SHAPE, fska: "HAT_Stand_1", texturePattern: "HAT_Stand_1" }],
    ["P_KPA_END", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KPAJ", { materialBlacklist: ["Mt_Decal"], shapeWhitelist: PERA_SHAPE, fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KPAJ_END", { shapeWhitelist: PERA_SHAPE, fska: "END_Rantan_1", texturePattern: "END_Rantan_1" }],
    ["P_KPAO", { materialBlacklist: ["Mt_decal"], fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KRN", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_KRN_END", { fska: "EVT_Juggling_1", texturePattern: "EVT_Juggling_1" }],
    ["P_KURC_END", { shapeWhitelist: PERA_SHAPE, fska: "NML_Walk_1", texturePattern: "NML_Walk_1" }],
    ["P_MARF", { shapeWhitelist: PERA_SHAPE, fska: "FIR_Stand_1", texturePattern: "FIR_Stand_1" }],
    ["P_MARI", { shapeWhitelist: PERA_SHAPE, fska: "ICE_Stand_1", texturePattern: "ICE_Stand_1" }],
    ["P_MARS", { shapeWhitelist: PERA_SHAPE, fska: "SPO_Stand_1", texturePattern: "SPO_Stand_1" }],
    ["P_MART", { shapeWhitelist: PERA_SHAPE, fska: "TGE_Stand_1", texturePattern: "TGE_Stand_1" }],
    ["P_MUC", { materialBlacklist: ["Mt_Pera1", "Mt_Pera2"], fska: IDLE1, texturePattern: IDLE1 }],
    ["P_MUC_Big", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_MUC_END", { materialBlacklist: ["Mt_Pera1", "Mt_Pera2"], fska: IDLE1, texturePattern: IDLE1 }],
    ["P_MUC_Shop", { materialBlacklist: ["Mt_Pera1", "Mt_Pera2"], fska: IDLE1, texturePattern: IDLE1 }],
    ["P_MUC_Shop_END", { fska: "NML_Talk_1", texturePattern: "NML_Talk_1" }],
    ["P_POO", { shapeWhitelist: PERA_SHAPE, fska: "PNC_Stand_1", texturePattern: "PNC_Stand_1" }],
    ["P_PUK_E", { fska: "NML_Graspswim_1", texturePattern: "NML_Graspswim_1" }],
    ["P_PUK_Fishing", { fska: IDLE1, texturePattern: IDLE1 }],
    ["P_WAN_END", { shapeWhitelist: PERA_SHAPE, fska: "Head_Stand_1", texturePattern: "Head_Stand_1" }],
    // sobjs
    ["Sobj_BlackWaterBubbleA", { fska: "C1_Expand" }],
    ["Sobj_BlackWaterBubbleB", { fska: "C1_Expand" }],
    ["Sobj_CloudQ", { fbvs: "C4" }],
    ["Sobj_GondolaSceneryA", { fska: "C5" }],
    ["Sobj_WaterfallA", { fska: C1, shaderParam: "C1" }],
    // level models (how many ways can they misspell "shadow"???)
    ["W1G1_KartRoad", { fbvs: C1 }],
    ["W3G2_Desert_0001", { texturePattern: C1, fbvs: C1 }],
    ["W3G2_Desert_0002", { texturePattern: "C2", fbvs: "C2" }],
    ["W3C3_FireJump", { materialBlacklist: ["Mt_Sdw"] }],
    ["W3G3_HouseA", { materialBlacklist: ["Mt_Sahdow"] }],
    ["W3G3_HouseB", { materialBlacklist: ["Mt_Sahdow"] }],
    ["W4C1_GessoArea", { materialBlacklist: ["Mt_Mask"] }],
    ["W4C1_StoreRoom", { shapeBlacklist: ["PipeFlameB__Mt_Pipe"] }],
    ["W6C2_PopUpBox", { materialBlacklist: ["Mt_Shasow"] }],
]);

export function getOrigamiModelConfig(id: string): OrigamiModelConfig | undefined {
    for (const [k, v] of SHARED_ORIGAMI_MODEL_CONFIGS.entries()) {
        if (v.includes(id)) {
            return k;
        }
    }
    return ORIGAMI_MODEL_CONFIGS.get(id);
}
