export interface OrigamiModelConfig {
    shapeWhitelist?: string[];
    shapeBlacklist?: string[];
    materialWhitelist?: string[];
    materialBlacklist?: string[];
    skeletonAnimation?: string;
}

const ORIGAMI_MODEL_CONFIGS: Map<string, OrigamiModelConfig> = new Map<string, OrigamiModelConfig>([
    ["Mobj_WoodBoxA", { shapeWhitelist: ["Box__Mt_WoodBoxA", "Wire__Mt_Wire"] }],
    ["Mobj_WoodBoxB", { shapeWhitelist: ["Box__Mt_WoodBoxB", "Wire__Mt_Wire"] }],
    ["Mobj_BlockHatena", {
        materialWhitelist: ["Mt_HatenaBis", "Mt_HatenaBlock"],
        shapeBlacklist: ["HatenaBis2__Mt_HatenaBis", "HatenaBis3__Mt_HatenaBis"]
    }],
    ["Mobj_BlockTomeiHatena", {
        materialWhitelist: ["Mt_Hatena", "Mt_HatenaBis", "Mt_HatenaBlock"],
        shapeWhitelist: ["HatenaBlock__Mt_HatenaBlock", "Hatena1__Mt_Hatena", "HatenaBis1__Mt_HatenaBis", "HatenaBlockTop__Mt_HatenaBlock"]
    }],
    ["Mobj_BlockSave", { shapeWhitelist: ["Box__Mt_Block", "Font_S1_13__Mt_Font", "Rivet1__Mt_Rivet", "BoxTop__Mt_Block"] }],
    ["Mobj_TreeDeku", {
        materialBlacklist: ["Mt_TreeDeku2", "Mt_TreeDeku3_scroll"],
        shapeWhitelist: ["TreeDeku1_Face1_Eye_L__Mt_TreeDeku1", "TreeDeku1_Face1_Eye_R__Mt_TreeDeku1", "TreeDeku1_Face2_Beard_L__Mt_TreeDeku1", "TreeDeku1_Face2_Beard_R__Mt_TreeDeku1",
            "TreeDeku1_Face2_EyeBrow_L__Mt_TreeDeku1", "TreeDeku1_Face2_EyeBrow_R__Mt_TreeDeku1", "TreeDeku1_Bark__Mt_TreeDeku1", "TreeDeku1_Body__Mt_TreeDeku1", "TreeDeku1_Body2__Mt_TreeDeku1",
            "TreeDeku1_HandTop__Mt_TreeDeku1", "TreeDeku1_SubTop__Mt_TreeDeku1", "TreeDeku1_Top1__Mt_TreeDeku1"]
    }],
    ["Mobj_GrassH", { shapeWhitelist: ["LeafAll__Mt_GrassH"] }],
    ["Mobj_GrassC", { shapeWhitelist: ["LeafAll__Mt_GrassC"] }],
    ["Mobj_IndoorPlantB", { materialBlacklist: ["Mt_Ink"], shapeBlacklist: ["PotInk__Mt_Ink", "LeafAInk__Mt_Ink", "LeafBInk__Mt_Ink", "LeafCInk__Mt_Ink", "LeafDInk__Mt_Ink"] }],
    ["Mobj_RubbleA", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["Rubble__Mt_Rubble", "Wire__Mt_Wire"] }],
    ["Mobj_PotA", { shapeWhitelist: ["Pot__Mt_Pot", "Wire__Mt_Wire"] }],
    ["Mobj_WoodBoxAWaterWay", { materialBlacklist: ["Mt_BG", "lambert1"], shapeWhitelist: ["Box__Mt_WoodBoxA", "Wire__Mt_Wire"] }],
    ["Mobj_RockA", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["PaperAlpha__Mt_RockA", "Wire__Mt_Wire"] }],
    ["Mobj_RockB", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["Paper__Mt_Rock", "Wire__Mt_Wire"] }],
    ["Mobj_RockC", { shapeWhitelist: ["PaperStatic__Mt_RockC", "WireStatic__Mt_Wire"] }],
    ["Mobj_BoatA", { shapeWhitelist: ["Boat__Mt_Boat"] }],
    ["Mobj_BlockPow", { shapeWhitelist: ["BlockL__Mt_PowBlock"] }],
    ["Mobj_WaterCaveBoxA", { materialWhitelist: ["Mt_WaterCaveBoxA", "Mt_Wire"], shapeWhitelist: ["BoxBase__Mt_WaterCaveBoxA", "WireBase__Mt_Wire"] }],
    ["W4C1_StoreRoom", { shapeBlacklist: ["PipeFlameB__Mt_Pipe"] }],
    ["Mobj_GrassF", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["Grass__Mt_Grass"] }],
    ["Mobj_HugeRockA", { materialWhitelist: ["Mt_HugeRockA"], shapeWhitelist: ["Rock__Mt_HugeRockA"] }],
    ["Mojb_PotB", { shapeWhitelist: ["Pot__Mt_PotB", "Wire__Mt_Wire"] }],
    ["Mobj_StallObjectA", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["Box__Mt_Box"] }],
    ["Mobj_CoffinA", { shapeBlacklist: ["MarkG__Mt_OrnamentGold", "MarkA__Mt_OrnamentGold", "MarkB__Mt_OrnamentGold", "MarkC__Mt_OrnamentGold", "MarkD__Mt_OrnamentGold", "MarkE__Mt_OrnamentGold"] }],
    ["Mobj_BarrelA", { shapeWhitelist: ["Wood1__Mt_Wood", "Wire1__Mt_Wire", "Metal1__Mt_Metal"] }],
    ["Mobj_StatueBody", {
        materialBlacklist: ["Mt_EyeLight", "Mt_ColorPattern"],
        shapeBlacklist: ["TextOff__Mt_Statue", "TextOn__Mt_Statue", "PedestalC__Mt_Statue", "PedestalA__Mt_Statue", "ColorPattern__Mt_ColorPattern"]
    }],
    ["Mobj_BarrelKNP", { shapeWhitelist: ["EdgeA__Mt_Edge", "Metal1__Mt_Metal", "Wood1__Mt_Wood"] }],
    ["Mobj_IceRockA", { materialBlacklist: ["Mt_ColorPattern"], shapeWhitelist: ["IceRock__Mt_Main_Albedo_Blue", "WireBase__Mt_Wire"] }],
    ["Mobj_ParasolA", { materialBlacklist: ["Mt_ParasolClose"] }],
    ["Mobj_KinopioStatueA", { shapeBlacklist: ["BaseB__Mt_Statue"] }],
    ["W3G3_HouseA", { materialBlacklist: ["Mt_Sahdow"] }], // they misspelled shadow, whoops!
    ["W3G3_HouseB", { materialBlacklist: ["Mt_Sahdow"] }], // they misspelled shadow, whoops!
    ["Mobj_TreeMountainA", { skeletonAnimation: "C1" }],
    ["Mobj_TreeMountainB", { skeletonAnimation: "C1" }],
    ["Mobj_TreeMountainC", { skeletonAnimation: "C1" }],
    ["Mobj_TreeGirlA", { skeletonAnimation: "NML_Action_3" }],
    ["Mobj_ClockPendulumA", { skeletonAnimation: "C1" }],
    ["Mobj_LabMachineA", { skeletonAnimation: "C2" }],
    ["Mobj_FlowerC", { skeletonAnimation: "C1" }],
    ["Mobj_OrigamiCastle", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockMountainA", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockMountainB", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockMountainC", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockMountainD", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockMountainE", { skeletonAnimation: "C1" }],
    ["Mobj_CastleFlagA", { skeletonAnimation: "C1" }],
    ["Mobj_HangRope", { skeletonAnimation: "C2_End_C1" }],
    ["Item_Coin1", { skeletonAnimation: "C1" }],
    ["Item_Coin10", { skeletonAnimation: "C1" }],
    ["Item_Coin100", { skeletonAnimation: "C1" }],
    ["Item_Coin10000", { skeletonAnimation: "C1" }],
    ["Item_PaperTank", { skeletonAnimation: "C1" }],
    ["Item_Hammer", { skeletonAnimation: "C1" }],
    ["Item_Tail", { skeletonAnimation: "C1" }],
    ["Item_TailSuper", { skeletonAnimation: "C1" }],
    ["Item_SuperKinokoSet", { skeletonAnimation: "C1" }],
    ["Item_Star", { skeletonAnimation: "C1" }],
    ["Item_PaperSmall", { skeletonAnimation: "C1" }],
    ["Item_PaperMiddle", { skeletonAnimation: "C1" }],
    ["Item_PaperLarge", { skeletonAnimation: "C1" }],
    ["Item_OrigamiBookWater", { skeletonAnimation: "C1" }],
    ["Item_OrigamiBookFire", { skeletonAnimation: "C1" }],
    ["Item_OrigamiBookIce", { skeletonAnimation: "C1" }],
    ["Item_OrigamiBookEarth", { skeletonAnimation: "C1" }],
    ["Item_KinokoSuper", { skeletonAnimation: "C1" }],
    ["Item_KinokoGreat", { skeletonAnimation: "C1" }],
    ["Item_KinokoDry", { skeletonAnimation: "C1" }],
    ["Item_Kinoko", { skeletonAnimation: "C1" }],
    ["Item_KinokoDoubleSet", { skeletonAnimation: "C1" }],
    ["Item_HPMaxUPLarge", { skeletonAnimation: "C1" }],
    ["Item_HPMaxUPSmall", { skeletonAnimation: "C1" }],
    ["Item_HPMaxUp", { skeletonAnimation: "C1" }],
    ["Item_HeartSmall", { skeletonAnimation: "C1" }],
    ["Item_HeartMiddle", { skeletonAnimation: "C1" }],
    ["Item_HeartLarge", { skeletonAnimation: "C1" }],
    ["Item_Flower", { skeletonAnimation: "C1" }],
    ["Item_FlowerSuper", { skeletonAnimation: "C1" }],
    ["Item_FireSet", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceCastleA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceThirdA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceHelpKinopioA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceTurnValveA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceTurnValveB", { skeletonAnimation: "C1" }],
    ["Mobj_WaterFallTurnValveA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSplashA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSplashRippleA", { skeletonAnimation: "C1_Flow_C2" }], // need to look at again
    ["Mobj_TreeConiferA", { skeletonAnimation: "C1" }],
    ["Mobj_TreeConiferC", { skeletonAnimation: "C1" }],
    ["Mobj_TreeConiferD", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockA", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockB", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockC", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockD", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockE", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockF", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockG", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockH", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockI", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockJ", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockR", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockN", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockP", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockS", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockT", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockU", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockV", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockW", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockX", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockZ", { skeletonAnimation: "C1" }],
    ["Mobj_HillPondA", { skeletonAnimation: "C1" }],
    ["Mobj_HillRiverA", { skeletonAnimation: "C1" }],
    ["Mobj_ObservatoryRiverA", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockTowerA", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockTowerB", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockTowerC", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockTowerD", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockTowerE", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockTowerF", { skeletonAnimation: "C1" }],
    ["Mobj_TreeMapleA", { skeletonAnimation: "C1" }],
    ["Mobj_TreeC", { skeletonAnimation: "C1" }],
    ["Mobj_OarWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_BoatWaveA", { skeletonAnimation: "C1" }],
    ["Mobj_BoatWaveB", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceMomijiA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceMomijiB", { skeletonAnimation: "C1" }],
    ["Mobj_RiverA", { skeletonAnimation: "C1" }],
    ["Mobj_RiverB", { skeletonAnimation: "C1" }],
    ["Mobj_RiverC", { skeletonAnimation: "C1" }],
    ["Mobj_RiverD", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSplashF", { skeletonAnimation: "C2" }],
    ["Mobj_RiverDriftwoodA", { skeletonAnimation: "C1" }],
    ["Mobj_RiverDriftwoodB", { skeletonAnimation: "C1" }],
    ["Mobj_RiverWhirlingTidesA", { skeletonAnimation: "C1" }],
    ["Mobj_RiverWhirlingTidesB", { skeletonAnimation: "C1" }],
    ["Mobj_RiverFallingRocksA", { skeletonAnimation: "C2" }],
    ["Mobj_WaterSurfaceWaterCaveA", { skeletonAnimation: "C2" }],
    ["Mobj_WaterSurfaceWaterCaveB", { skeletonAnimation: "C4" }],
    ["Mobj_WaterSurfaceWaterCaveC", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceWaterCaveD", { skeletonAnimation: "C1" }],
    ["Mobj_WaterFlowingA", { skeletonAnimation: "C2_Flowing" }],
    ["Mobj_WaterFlowingB", { skeletonAnimation: "C2" }],
    ["Mobj_WaterFlowingC", { skeletonAnimation: "C1" }],
    ["Mobj_WaterBottleA", { skeletonAnimation: "C4" }], // might not be matched with surface water flow level
    ["Mobj_WaterCaveTurbineA", { skeletonAnimation: "C2" }],
    ["Mobj_WaterCaveTurbineD", { skeletonAnimation: "C1_Rotation" }],
    ["Mobj_WaterCaveTurbineC", { skeletonAnimation: "C1_Rotation_L1" }],
    ["Mobj_WaterFlowingPuzzleA", { skeletonAnimation: "C2" }],
    ["Mobj_WaterFlowingPuzzleB", { skeletonAnimation: "C2" }],
    ["Mobj_FloatingPierA", { shapeWhitelist: ["FloatingPierA1__Mt_FloatingPierA"], skeletonAnimation: "C4" }],
    ["Mobj_WaterSurfaceParkA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceParkB", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceParkC", { skeletonAnimation: "C1" }],
    ["Mobj_LanternD", { materialBlacklist: ["Mt_Shasow"], skeletonAnimation: "C1" }], // they misspelled shadow, whoops!
    ["Mobj_LanternE", { skeletonAnimation: "C1" }],
    ["Mobj_BlockHatenaOrigami", { materialBlacklist: ["Mt_HatenaBox_BS"], shapeBlacklist: ["Box1__Mt_HatenaBox"], skeletonAnimation: "C0" }], // still looks weird, need the bone vis animations to be parsed
    ["Mobj_OrigamiPakupaku", { skeletonAnimation: "C1" }],
    ["Mobj_AccordionWallA", { materialBlacklist: ["Mt_Shade"] }],
    ["Mobj_WaterSurfaceKoopaCastleA", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeRoll", { materialBlacklist: ["Mt_ColorPattern"] }],
    ["Mobj_GearC", { skeletonAnimation: "C2" }],
    ["Mobj_WaterSpaA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSpaC", { skeletonAnimation: "C3" }],
    ["Mobj_WaterSpaD", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSpaE", { skeletonAnimation: "C1" }],
    ["Mobj_TreeJungleA", { skeletonAnimation: "C1" }],
    ["Mobj_GrassB", { skeletonAnimation: "C1" }],
    ["Mobj_BathPlugA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterFlowingJungleB", { skeletonAnimation: "C1" }],
    ["Mobj_TreePelmanismA", { skeletonAnimation: "C2" }],
    ["Mobj_WaterFlowingSpaA", { skeletonAnimation: "C2" }],
    ["Mobj_WaterFlowingSpaD", { skeletonAnimation: "C1" }],
    ["Mobj_WaterPondA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSplashC", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceB", { skeletonAnimation: "C1" }],
    ["Mobj_WaterFlowingE", { skeletonAnimation: "C2" }],
    ["Mobj_SmallShipWhitecapsA", { skeletonAnimation: "C1" }], // sometimes doesn't match level of surrounding water
    ["Mobj_OrbTowerWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_RingIslandWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_SpadeIslandWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_MoonIslandWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_MoonIslandWhitecapsB", { skeletonAnimation: "C1" }],
    ["Mobj_CloverIslandWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_HatenaIslandWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_HammerIslandWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_KinokoIslandWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_HeartIslandWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_DokuroIslandWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_MoonIslandWavcA", { skeletonAnimation: "C1" }],
    ["Mobj_TreeCoconutA", { skeletonAnimation: "C1" }],
    ["Mobj_TreeCoconutE", { skeletonAnimation: "C1" }],
    ["Mobj_TreeA", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockOceanA", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockOceanB", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockOceanC", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockOceanD", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockOceanE", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockOceanF", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockOceanG", { skeletonAnimation: "C1" }],
    ["Mobj_ClubIsland", { skeletonAnimation: "C1" }],
    ["Mobj_MoonIsland", { skeletonAnimation: "C2" }],
    ["Mobj_DokuroIsland", { skeletonAnimation: "C1" }],
    ["Mobj_HammerIsland", { skeletonAnimation: "C1" }],
    ["Mobj_HeartIsland", { skeletonAnimation: "C1" }],
    ["Mobj_HatenaIsland", { skeletonAnimation: "C1" }],
    ["Mobj_KinokoIsland", { skeletonAnimation: "C1" }],
    ["Mobj_SpadeIsland", { skeletonAnimation: "C1" }],
    ["Mobj_RingIsland", { skeletonAnimation: "C1" }],
    ["Mobj_OrbTower", { skeletonAnimation: "C1" }],
    ["Mobj_PeachShip", { skeletonAnimation: "C1" }],
    ["Mobj_OceanFloatA", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefA", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefB", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefC", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefD", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefE", { skeletonAnimation: "C1" }],
    ["Mobj_OceanRockA", { skeletonAnimation: "C1" }],
    ["Mobj_OceanRockB", { skeletonAnimation: "C1" }],
    ["Mobj_OceanRockC", { skeletonAnimation: "C1" }],
    ["Mobj_OceanRockD", { skeletonAnimation: "C1" }],
    ["Mobj_OceanRockF", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefsA", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefsB", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefsC", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefsD", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefsE", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefsF", { skeletonAnimation: "C1" }],
    ["Mobj_OceanReefsG", { skeletonAnimation: "C1" }],
    ["Mobj_MirrorBallA", { skeletonAnimation: "C2" }],
    ["Mobj_BlackWaterSurfaceA", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceB", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceC", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceD", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceI", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceE", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceJ", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceK", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceF", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceG", { skeletonAnimation: "C1" }],
    ["Mobj_BlackWaterSurfaceH", { skeletonAnimation: "C1" }],
    ["Mobj_CeilingFanA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfacePoolA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfacePoolC", { skeletonAnimation: "C2" }],
    ["Mobj_WaterSplashB", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSplashE", { skeletonAnimation: "C5" }],
    ["Mobj_PoolFloatWhitecapsA", { skeletonAnimation: "C1" }],
    ["Mobj_PaperTapeLockDesertA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceTownA", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceTownB", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceTownC", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceTownD", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceTownE", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSurfaceTownF", { skeletonAnimation: "C1" }],
    ["Mobj_WaterSplashD", { skeletonAnimation: "C2" }],
    ["Mobj_WaterMillA", { skeletonAnimation: "C1" }],
]);

export function getOrigamiModelConfig(id: string): OrigamiModelConfig | undefined {
    return ORIGAMI_MODEL_CONFIGS.get(id);
}
