import type { MapCategory } from "./mapcategory.js";

export interface RagnarokMapEntry {
    id: string;
    name: string;
    category: MapCategory;

    era?: "classic";
}

export const maps: RagnarokMapEntry[] = [
    { id: "06guild_r", name: "06guild_r - Guild War Arena - Waiting Room", category: "other" },
    { id: "1@4cdn", name: "1@4cdn - Last Ordeal Phantom Cave", category: "dungeon" },
    { id: "1@4drk", name: "1@4drk - Dragon's Test", category: "dungeon" },
    { id: "1@4igd", name: "1@4igd - Tourney Hall of Justice", category: "dungeon" },
    { id: "1@4inq", name: "1@4inq - Monastery Basemen", category: "dungeon" },
    { id: "1@4mag", name: "1@4mag - Mana Spring", category: "dungeon" },
    { id: "1@4mst", name: "1@4mst - Juperos Core VT", category: "dungeon" },
    { id: "1@4sac", name: "1@4sac - Shadow Manor", category: "dungeon" },
    { id: "1@4tro", name: "1@4tro - Kvasir's Chest", category: "dungeon" },
    { id: "1@4win", name: "1@4win - Deep Luluka Forest", category: "dungeon" },
    { id: "1@adv", name: "1@adv - High Priest Villa", category: "dungeon" },
    { id: "1@advs", name: "1@advs - Villa of Deception", category: "dungeon" },
    { id: "1@air1", name: "1@air1 - Aircraft", category: "dungeon" },
    { id: "1@air2", name: "1@air2 - Aircraft", category: "dungeon" },
    { id: "1@ba_go", name: "1@ba_go - Garden of Time - Hall of Life", category: "dungeon" },
    { id: "1@bamn", name: "1@bamn - Garden at Dusk", category: "dungeon" },
    { id: "1@bamq", name: "1@bamq - Airship Depot", category: "dungeon" },
    { id: "1@begi", name: "1@begi - Poring Village", category: "dungeon" },
    { id: "1@cash", name: "1@cash - Octopus Cave", category: "dungeon" },
    { id: "1@cata", name: "1@cata - Catacomb", category: "dungeon" },
    { id: "1@ch_t", name: "1@ch_t - Constellation Tower", category: "dungeon" },
    { id: "1@ch_u", name: "1@ch_u - Sunken Tower", category: "dungeon" },
    { id: "1@cor", name: "1@cor - Cor Memorial", category: "dungeon" },
    { id: "1@crd", name: "1@crd - Volcanic Island Korodo", category: "dungeon" },
    { id: "1@def01", name: "1@def01 - Wave Dungeon - forest", category: "dungeon" },
    { id: "1@def02", name: "1@def02 - Wave Dungeon - Sky", category: "dungeon" },
    { id: "1@drdo", name: "1@drdo - Legendary Dorado", category: "dungeon" },
    { id: "1@dth1", name: "1@dth1 - Bios Island", category: "dungeon" },
    { id: "1@dth2", name: "1@dth2 - Bios Island", category: "dungeon" },
    { id: "1@dth3", name: "1@dth3 - Bios Island", category: "dungeon" },
    { id: "1@ecl", name: "1@ecl - Eclage Interior", category: "dungeon" },
    { id: "1@eom", name: "1@eom - Masin war", category: "dungeon" },
    { id: "1@exds", name: "1@exds - The Foot of an Unknown Mountain", category: "dungeon" },
    { id: "1@exhn", name: "1@exhn - Novice's Memories", category: "dungeon" },
    { id: "1@exnw", name: "1@exnw - Clana Nemieri", category: "dungeon" },
    { id: "1@exse", name: "1@exse - Eunha Celestial Branch Office", category: "dungeon" },
    { id: "1@exsh", name: "1@exsh - Deep Forest", category: "dungeon" },
    { id: "1@exsr", name: "1@exsr - Inner World", category: "dungeon" },
    { id: "1@f_lake", name: "1@f_lake - Garden of Time - Lake of Fire", category: "dungeon" },
    { id: "1@face", name: "1@face - Faceworm's Nest", category: "dungeon" },
    { id: "1@ffp", name: "1@ffp - Remnants Hideout", category: "dungeon" },
    { id: "1@ge_sn", name: "1@ge_sn - Geffen Night Arena", category: "dungeon" },
    { id: "1@ge_st", name: "1@ge_st - Geffen Magic  Competition", category: "dungeon" },
    { id: "1@gef", name: "1@gef - Geffen Magic  Competition", category: "dungeon" },
    { id: "1@gef_in", name: "1@gef_in - Geffen Magic  Competition", category: "dungeon" },
    { id: "1@ghg", name: "1@ghg - Ortus Aqua", category: "dungeon" },
    { id: "1@gl_he", name: "1@gl_he - Glastheim Challenge", category: "dungeon" },
    { id: "1@gl_k", name: "1@gl_k - 2nd floor of Old Glast Heim Chivalry", category: "dungeon" },
    { id: "1@gl_kh", name: "1@gl_kh - Old Chivalry Floor 1", category: "dungeon" },
    { id: "1@gl_prq", name: "1@gl_prq - Fall of Glast Heim", category: "dungeon" },
    { id: "1@glast", name: "1@glast - Old Glastheim", category: "dungeon" },
    { id: "1@gol1", name: "1@gol1 - Bio Test Chamber", category: "dungeon" },
    { id: "1@gol2", name: "1@gol2 - Morgue", category: "dungeon" },
    { id: "1@halo", name: "1@halo - Halloween Festival", category: "dungeon" },
    { id: "1@herbs", name: "1@herbs - Hidden Flower Garden", category: "dungeon" },
    { id: "1@infi", name: "1@infi - Infinite Space", category: "dungeon" },
    { id: "1@iwp", name: "1@iwp - Frozen Scale Hill", category: "dungeon" },
    { id: "1@jorchs", name: "1@jorchs - Chaotic Serpent's Nest", category: "dungeon" },
    { id: "1@jorlab", name: "1@jorlab - Bagot's Laboratory", category: "dungeon" },
    { id: "1@jtb", name: "1@jtb - The Shadowed Dream", category: "dungeon" },
    { id: "1@lab", name: "1@lab - Center Lab", category: "dungeon" },
    { id: "1@lhz", name: "1@lhz - Wolfchev's Lab", category: "dungeon" },
    { id: "1@lost", name: "1@lost - Farm Forgotten in Time", category: "dungeon" },
    { id: "1@ma_b", name: "1@ma_b - Bakonawa Hideout", category: "dungeon" },
    { id: "1@ma_c", name: "1@ma_c - Buwaya Cave", category: "dungeon" },
    { id: "1@ma_h", name: "1@ma_h - Bangungot Hospital 2F", category: "dungeon" },
    { id: "1@mcd", name: "1@mcd - Charlston Factory", category: "dungeon" },
    { id: "1@md_gef", name: "1@md_gef - Fri-Memorial", category: "dungeon" },
    { id: "1@md_pay", name: "1@md_pay - Weekend Memorial", category: "dungeon" },
    { id: "1@mir", name: "1@mir - Ritual Room", category: "dungeon" },
    { id: "1@mist", name: "1@mist - The Hazy Maze Forest", category: "dungeon" },
    { id: "1@mjo1", name: "1@mjo1 - Mjolnir Mountains Airplane Crash Site", category: "dungeon" },
    { id: "1@mjo2", name: "1@mjo2 - Mjolnir Mountains Forgotten Cavity", category: "dungeon" },
    { id: "1@nyd", name: "1@nyd - Nidhoggur's Nest", category: "dungeon" },
    { id: "1@nyr", name: "1@nyr - Sanctuary Sessrumnir Garden", category: "dungeon" },
    { id: "1@orcs", name: "1@orcs - Subterranean Orc Cave", category: "dungeon" },
    { id: "1@os_a", name: "1@os_a - Os Occupation", category: "dungeon" },
    { id: "1@os_b", name: "1@os_b - Blockaded Os", category: "dungeon" },
    { id: "1@oz", name: "1@oz - Oz Labyrinth", category: "dungeon" },
    { id: "1@pop1", name: "1@pop1 - Pope's Office", category: "dungeon" },
    { id: "1@pop2", name: "1@pop2 - The Way Home", category: "dungeon" },
    { id: "1@pop3", name: "1@pop3 - Sky Garden", category: "dungeon" },
    { id: "1@pump", name: "1@pump - Culvert", category: "dungeon" },
    { id: "1@rev", name: "1@rev - Mors Cave", category: "dungeon" },
    { id: "1@rgsr", name: "1@rgsr - Regenschirm", category: "dungeon" },
    { id: "1@sara", name: "1@sara - Sara's Memory", category: "dungeon" },
    { id: "1@slw", name: "1@slw - Werner_Laboratory central_room", category: "dungeon" },
    { id: "1@soul", name: "1@soul - Passage Of Soul", category: "dungeon" },
    { id: "1@spa", name: "1@spa - Palace of Ghost", category: "dungeon" },
    { id: "1@spa2", name: "1@spa2 - Tomb of Remorse", category: "dungeon" },
    { id: "1@sthb", name: "1@sthb - Inside Air Portress", category: "dungeon" },
    { id: "1@sthc", name: "1@sthc - Secret Room Air Portress", category: "dungeon" },
    { id: "1@sthd", name: "1@sthd - Top Floor Air Portress", category: "dungeon" },
    { id: "1@swat", name: "1@swat - Heart_Hunter War_Base", category: "dungeon" },
    { id: "1@tcamp", name: "1@tcamp - Thor Volcano Military Base", category: "dungeon" },
    { id: "1@thts", name: "1@thts - Thanatos Tower", category: "dungeon" },
    { id: "1@tnm1", name: "1@tnm1 - Masin Tower Top floor", category: "dungeon" },
    { id: "1@tnm2", name: "1@tnm2 - Masin Tower Top floor", category: "dungeon" },
    { id: "1@tnm3", name: "1@tnm3 - Morocc Castle's basement", category: "dungeon" },
    { id: "1@tower", name: "1@tower - Endless Tower", category: "dungeon" },
    { id: "1@tre", name: "1@tre - Suspicious Shipwreck", category: "dungeon" },
    { id: "1@uns", name: "1@uns - The Last Room", category: "dungeon" },
    { id: "1@vrac1", name: "1@vrac1 - Fantasy Series-Academy 1st floor", category: "dungeon" },
    { id: "1@vrac2", name: "1@vrac2 - Fantasy Series-Academy 2nd floor", category: "dungeon" },
    { id: "1@vrcas", name: "1@vrcas - Fantasy - Lilium Palace", category: "dungeon" },
    { id: "1@vrclo", name: "1@vrclo - Fantasy Series - Mirror Monastery", category: "dungeon" },
    { id: "1@vrev", name: "1@vrev - Fantasy - Amicitia's Secret Lab", category: "dungeon" },
    { id: "1@vrgen", name: "1@vrgen - Fantasy - Genetic Lab", category: "dungeon" },
    { id: "1@vrhha", name: "1@vrhha - Fantasy Series-Heart Hunter Training Center", category: "dungeon" },
    { id: "1@vrpo", name: "1@vrpo - Fantasy Series-Poring Terra", category: "dungeon" },
    { id: "1@vrsn", name: "1@vrsn", category: "dungeon" },
    { id: "1@whl", name: "1@whl - Inside the Airship Wild (No. 1)", category: "dungeon" },
    { id: "1@xm_d", name: "1@xm_d - Horror Toy Factory", category: "dungeon" },
    { id: "2@cata", name: "2@cata - Sealed Shrine", category: "dungeon" },
    { id: "2@ch_t", name: "2@ch_t - Constellation Tower", category: "dungeon" },
    { id: "2@exds", name: "2@exds - The Foot of an Unknown Mountain", category: "dungeon" },
    { id: "2@gl_k", name: "2@gl_k - 1st floor of Old Glast Heim Chivalry", category: "dungeon" },
    { id: "2@gl_kh", name: "2@gl_kh - Old Chivalry Floor 2", category: "dungeon" },
    { id: "2@mir", name: "2@mir - Ritual Room", category: "dungeon" },
    { id: "2@nyd", name: "2@nyd - Nidhoggur's Nest", category: "dungeon" },
    { id: "2@nyr", name: "2@nyr - Sanctuary Sessrumnir Heart Storage", category: "dungeon" },
    { id: "2@orcs", name: "2@orcs - Subterranean Orc Cave", category: "dungeon" },
    { id: "2@pump", name: "2@pump - Culvert", category: "dungeon" },
    { id: "2@thts", name: "2@thts - Angel's Warning", category: "dungeon" },
    { id: "2@tower", name: "2@tower - Endless Tower", category: "dungeon" },
    { id: "2@vrclo", name: "2@vrclo - Fantasy Series-All those moments", category: "dungeon" },
    { id: "2009rwc_02", name: "2009rwc_02", category: "other" },
    { id: "2009rwc_03", name: "2009rwc_03", category: "other" },
    { id: "3@ch_t", name: "3@ch_t - Constellation Tower", category: "dungeon" },
    { id: "3@thts", name: "3@thts - Memory of Hatred", category: "dungeon" },
    { id: "3@tower", name: "3@tower - Endless Tower", category: "dungeon" },
    { id: "4@thts", name: "4@thts - Memory of Agony", category: "dungeon" },
    { id: "4@tower", name: "4@tower - Endless Tower", category: "dungeon" },
    { id: "5@thts", name: "5@thts - Memory of Sorrow", category: "dungeon" },
    { id: "5@tower", name: "5@tower - Endless Tower", category: "dungeon" },
    { id: "6@thts", name: "6@thts - Memory of Despair", category: "dungeon" },
    { id: "6@tower", name: "6@tower - Endless Tower(Unknown Area)", category: "dungeon" },
    { id: "7@thts", name: "7@thts - Memory of Anger", category: "dungeon" },
    { id: "8@thts", name: "8@thts - Thanatos Tower", category: "dungeon" },
    { id: "abbey01", name: "abbey01 - Cursed Monastery", category: "dungeon" },
    { id: "abbey02", name: "abbey02 - Cursed Monastery", category: "dungeon" },
    { id: "abbey03", name: "abbey03 - Cursed Monastery", category: "dungeon" },
    { id: "abyss_01", name: "abyss_01 - Abyss Lake Underground Cave", category: "dungeon" },
    { id: "abyss_02", name: "abyss_02 - Abyss Lake Underground Cave", category: "dungeon" },
    { id: "abyss_03", name: "abyss_03 - Abyss Lake Underground Cave", category: "dungeon" },
    { id: "abyss_04", name: "abyss_04 - Abyss Lake Underground Cave", category: "dungeon" },
    { id: "air_evt", name: "air_evt", category: "other" },
    { id: "air_if", name: "air_if - Inside the Airship IF", category: "other" },
    { id: "airplane", name: "airplane - Airship", category: "other" },
    { id: "airport", name: "airport - Airport", category: "other" },
    { id: "alb_ship", name: "alb_ship - Alberta Ship", category: "city" },
    { id: "alb_ship2", name: "alb_ship2", category: "city" },
    { id: "alb2trea", name: "alb2trea - Alberta Island", category: "other" },
    { id: "alberta", name: "alberta - Alberta", category: "city" },
    { id: "alberta_in", name: "alberta_in - Inside Alberta", category: "indoor" },
    { id: "alde_alche", name: "alde_alche - Alchemist Realm", category: "city" },
    { id: "alde_dun01", name: "alde_dun01 - Clock Tower B1f", category: "dungeon" },
    { id: "alde_dun02", name: "alde_dun02 - Clock Tower B2f", category: "dungeon" },
    { id: "alde_dun03", name: "alde_dun03 - Clock Tower B3f", category: "dungeon" },
    { id: "alde_dun04", name: "alde_dun04 - Clock Tower B4f", category: "dungeon" },
    { id: "alde_gld", name: "alde_gld - Luina the satellite of Al De Baran", category: "castle" },
    { id: "alde_tt02", name: "alde_tt02", category: "city" },
    { id: "alde_tt03", name: "alde_tt03", category: "city" },
    { id: "aldeba_in", name: "aldeba_in - Inside Al De Baran", category: "indoor" },
    { id: "aldebaran", name: "aldebaran - Al De Baran", category: "city" },
    { id: "aldeg_cas01", name: "aldeg_cas01 - Luina Guild", category: "castle" },
    { id: "aldeg_cas02", name: "aldeg_cas02 - Luina Guild", category: "castle" },
    { id: "aldeg_cas03", name: "aldeg_cas03 - Luina Guild", category: "castle" },
    { id: "aldeg_cas04", name: "aldeg_cas04 - Luina Guild", category: "castle" },
    { id: "aldeg_cas05", name: "aldeg_cas05 - Luina Guild", category: "castle" },
    { id: "ama_dun01", name: "ama_dun01 - Tatami Maze", category: "dungeon" },
    { id: "ama_dun02", name: "ama_dun02 - Battle Field in the Underground Forest", category: "dungeon" },
    { id: "ama_dun03", name: "ama_dun03 - Amatsu Underground Shrine", category: "dungeon" },
    { id: "ama_fild01", name: "ama_fild01 - Amatsu Field", category: "field" },
    { id: "ama_in01", name: "ama_in01 - Inside Amatsu", category: "indoor" },
    { id: "ama_in02", name: "ama_in02 - Inside Himezi Castle", category: "indoor" },
    { id: "ama_test", name: "ama_test - Momotaro Experience Place", category: "city" },
    { id: "amatsu", name: "amatsu - Amatsu, the Land of Destiny", category: "city" },
    { id: "amicit01", name: "amicit01", category: "other" },
    { id: "amicit02", name: "amicit02", category: "other" },
    { id: "amicitia1", name: "amicitia1 - Abandoned Lab Amicitia", category: "other" },
    { id: "amicitia2", name: "amicitia2 - Abandoned Lab Amicitia", category: "other" },
    { id: "ant_d02_i", name: "ant_d02_i - Garden of Awareness", category: "other" },
    { id: "anthell01", name: "anthell01 - Ant Hell", category: "dungeon" },
    { id: "anthell02", name: "anthell02 - Ant Hell", category: "dungeon" },
    { id: "arena_room", name: "arena_room - Waiting room", category: "instance" },
    { id: "aru_gld", name: "aru_gld - Valfreyja", category: "castle" },
    { id: "arug_cas01", name: "arug_cas01 - Valfreyja Guild", category: "castle" },
    { id: "arug_cas02", name: "arug_cas02 - Valfreyja Guild", category: "castle" },
    { id: "arug_cas03", name: "arug_cas03 - Valfreyja Guild", category: "castle" },
    { id: "arug_dun01", name: "arug_dun01 - Subterranean Guild Dungeon", category: "dungeon" },
    { id: "arug_que01", name: "arug_que01 - Morestone Prairie", category: "other" },
    { id: "auction_01", name: "auction_01 - Auction Hall", category: "instance" },
    { id: "auction_02", name: "auction_02 - Auction Hall", category: "instance" },
    { id: "ayo_dun01", name: "ayo_dun01 - Ancient Shrine Maze", category: "dungeon" },
    { id: "ayo_dun02", name: "ayo_dun02 - Inside Ancient Shrine", category: "dungeon" },
    { id: "ayo_fild01", name: "ayo_fild01 - Ayotaya Field", category: "field" },
    { id: "ayo_fild02", name: "ayo_fild02 - Ayotaya Field", category: "field" },
    { id: "ayo_in01", name: "ayo_in01 - Inside Ayotaya", category: "indoor" },
    { id: "ayo_in02", name: "ayo_in02 - Inside Ayotaya", category: "indoor" },
    { id: "ayothaya", name: "ayothaya - Ayotaya", category: "city" },
    { id: "ayothaya_e", name: "ayothaya_e - Ayothaya Excavation Site", category: "other" },
    { id: "ba_2whs01", name: "ba_2whs01 - Tartaros Storage Upper Floor", category: "other" },
    { id: "ba_2whs02", name: "ba_2whs02 - Tartaros Storage Lower Floor", category: "other" },
    { id: "ba_bath", name: "ba_bath - Large Meditatio Bath", category: "other" },
    { id: "ba_chess", name: "ba_chess - Checkmate", category: "other" },
    { id: "ba_go", name: "ba_go - Palm Line Battlefield", category: "other" },
    { id: "ba_in01", name: "ba_in01 - Inside Barmund Mansion", category: "indoor" },
    { id: "ba_lib", name: "ba_lib - Library Hall of Memories", category: "other" },
    { id: "ba_lost", name: "ba_lost - Farm Lost Valley", category: "other" },
    { id: "ba_maison", name: "ba_maison - Barmund Mansion Garden", category: "other" },
    { id: "ba_pw01", name: "ba_pw01 - Magic Power Plant 1", category: "other" },
    { id: "ba_pw02", name: "ba_pw02 - Sewage Treatment Plant", category: "other" },
    { id: "ba_pw03", name: "ba_pw03 - Magic Power Plant 2", category: "other" },
    { id: "bat_a01", name: "bat_a01 - Tierra Canyon", category: "instance" },
    { id: "bat_b01", name: "bat_b01 - Flavian", category: "instance" },
    { id: "bat_c01", name: "bat_c01 - Krieger von Midgards", category: "instance" },
    { id: "bat_room", name: "bat_room - Battle Field Waiting Room", category: "instance" },
    { id: "beach_dun", name: "beach_dun - Karu, the West cave", category: "dungeon" },
    { id: "beach_dun2", name: "beach_dun2 - Ruande the northern cave", category: "dungeon" },
    { id: "beach_dun3", name: "beach_dun3 - Mao, the East Cave", category: "dungeon" },
    { id: "bif_fild01", name: "bif_fild01 - Bifrost Bridge", category: "field" },
    { id: "bif_fild02", name: "bif_fild02 - Bifrost Bridge", category: "field" },
    { id: "bl_death", name: "bl_death - Biosphere Environment - Death", category: "other" },
    { id: "bl_grass", name: "bl_grass - Biosphere Environment - Grass", category: "other" },
    { id: "bl_ice", name: "bl_ice - Biosphere Environment - Ice", category: "other" },
    { id: "bl_lava", name: "bl_lava - Biosphere Environment - Fire", category: "other" },
    { id: "bl_soul", name: "bl_soul - Biosphere Environment - Soul", category: "other" },
    { id: "bl_temple", name: "bl_temple - Biosphere Environment - Temple", category: "other" },
    { id: "bl_venom", name: "bl_venom - Biosphere Environment - Venom", category: "other" },
    { id: "bra_dun01", name: "bra_dun01 - Beyond the Waterfall", category: "dungeon" },
    { id: "bra_dun02", name: "bra_dun02 - Beyond the Waterfall", category: "dungeon" },
    { id: "bra_fild01", name: "bra_fild01 - Brasilis Field", category: "field" },
    { id: "bra_in01", name: "bra_in01 - Inside Brasilis", category: "indoor" },
    { id: "brasilis", name: "brasilis - Brasilis", category: "city" },
    { id: "c_tower1", name: "c_tower1 - Clock Tower 1f", category: "dungeon" },
    { id: "c_tower2", name: "c_tower2 - Clock Tower 2f", category: "dungeon" },
    { id: "c_tower2_", name: "c_tower2_ - Clock Town of twisted time 2nd floor", category: "dungeon" },
    { id: "c_tower3", name: "c_tower3 - Clock Tower 3f", category: "dungeon" },
    { id: "c_tower3_", name: "c_tower3_ - Clock Town of twisted time 3rd floor", category: "dungeon" },
    { id: "c_tower4", name: "c_tower4 - Clock Tower 4f", category: "dungeon" },
    { id: "cave", name: "cave - Cave village", category: "dungeon" },
    { id: "clock_01", name: "clock_01 - Clock Tower Unknown Basement", category: "other" },
    { id: "cmd_fild01", name: "cmd_fild01 - Papuchicha Forest", category: "field" },
    { id: "cmd_fild02", name: "cmd_fild02 - Kokomo beach", category: "field" },
    { id: "cmd_fild03", name: "cmd_fild03 - Zenhai Marsh", category: "field" },
    { id: "cmd_fild04", name: "cmd_fild04 - Kokomo beach", category: "field" },
    { id: "cmd_fild05", name: "cmd_fild05 - Border of Papuchica forest", category: "field" },
    { id: "cmd_fild06", name: "cmd_fild06 - Fortress Saint Darmain(West)", category: "field" },
    { id: "cmd_fild07", name: "cmd_fild07 - Beacon Island, Pharos", category: "field" },
    { id: "cmd_fild08", name: "cmd_fild08 - Fortress Saint Darmain (East)", category: "field" },
    { id: "cmd_fild09", name: "cmd_fild09 - Fortress Saint Darmain (South)", category: "field" },
    { id: "cmd_in01", name: "cmd_in01 - Inside Comodo", category: "indoor" },
    { id: "cmd_in02", name: "cmd_in02 - Inside Comodo", category: "indoor" },
    { id: "com_d02_i", name: "com_d02_i - North Cave Luanda", category: "other" },
    { id: "comodo", name: "comodo - Beach town,Comodo", category: "city" },
    { id: "conch_in", name: "conch_in - Inside the Kon-Kilina", category: "indoor" },
    { id: "dali", name: "dali - Dimensional Gap", category: "other" },
    { id: "dali02", name: "dali02 - Dimensional Gap", category: "other" },
    { id: "dew_dun01", name: "dew_dun01 - Krakatau Volcanic Island", category: "dungeon" },
    { id: "dew_dun02", name: "dew_dun02 - Istana Cave", category: "dungeon" },
    { id: "dew_fild01", name: "dew_fild01 - Dewata Field_Zati Tribe's Village", category: "field" },
    { id: "dew_in01", name: "dew_in01 - Inside the Zati Tribe's Village", category: "indoor" },
    { id: "dewata", name: "dewata - Dewata", category: "city" },
    { id: "dic_dun01", name: "dic_dun01 - Kamidal Tunnel", category: "dungeon" },
    { id: "dic_dun02", name: "dic_dun02 - Scaraba Hall", category: "dungeon" },
    { id: "dic_fild01", name: "dic_fild01 - Outskirts of Kamidal Mountain", category: "field" },
    { id: "dic_fild02", name: "dic_fild02 - Outskirts of Kamidal Mountain", category: "field" },
    { id: "dic_in01", name: "dic_in01 - Inside of El Dicastes", category: "indoor" },
    { id: "dicastes01", name: "dicastes01 - El Dicastes, the Sapha Capital", category: "city" },
    { id: "dicastes02", name: "dicastes02 - Dicastes Diel", category: "other" },
    { id: "e_tower", name: "e_tower - Misty Island", category: "other" },
    { id: "ealde_dun02m", name: "ealde_dun02m", category: "dungeon" },
    { id: "ecl_fild01", name: "ecl_fild01 - Blooming Flower Land", category: "field" },
    { id: "ecl_hub01", name: "ecl_hub01 - Eclage Perimeter", category: "city" },
    { id: "ecl_in01", name: "ecl_in01 - Inside of Eclage", category: "indoor" },
    { id: "ecl_in02", name: "ecl_in02 - Inside of Eclage", category: "indoor" },
    { id: "ecl_in03", name: "ecl_in03 - Inside of Eclage", category: "indoor" },
    { id: "ecl_in04", name: "ecl_in04 - Inside of Eclage", category: "indoor" },
    { id: "ecl_tdun01", name: "ecl_tdun01 - Bifrost Floor 1", category: "dungeon" },
    { id: "ecl_tdun02", name: "ecl_tdun02 - Bifrost Floor 2", category: "dungeon" },
    { id: "ecl_tdun03", name: "ecl_tdun03 - Bifrost Floor 3", category: "dungeon" },
    { id: "ecl_tdun04", name: "ecl_tdun04 - Bifrost Floor 4", category: "dungeon" },
    { id: "eclage", name: "eclage - Eclage", category: "city" },
    { id: "egld2_aldl", name: "egld2_aldl", category: "other" },
    { id: "ein_d02_i", name: "ein_d02_i - Nasarian Empire", category: "city" },
    { id: "ein_dun01", name: "ein_dun01 - Mine Dungeon", category: "dungeon" },
    { id: "ein_dun02", name: "ein_dun02 - Mine Dungeon", category: "dungeon" },
    { id: "ein_dun03", name: "ein_dun03 - Mine Dungeon", category: "dungeon" },
    { id: "ein_fild01", name: "ein_fild01 - Einbroch Field", category: "field" },
    { id: "ein_fild02", name: "ein_fild02 - Einbroch Field", category: "field" },
    { id: "ein_fild03", name: "ein_fild03 - Einbroch Field", category: "field" },
    { id: "ein_fild04", name: "ein_fild04 - Einbroch Field", category: "field" },
    { id: "ein_fild05", name: "ein_fild05 - Einbroch Field", category: "field" },
    { id: "ein_fild06", name: "ein_fild06 - Einbroch Field", category: "field" },
    { id: "ein_fild07", name: "ein_fild07 - Einbroch Field", category: "field" },
    { id: "ein_fild08", name: "ein_fild08 - Einbroch Field", category: "field" },
    { id: "ein_fild09", name: "ein_fild09 - Einbroch Field", category: "field" },
    { id: "ein_fild10", name: "ein_fild10 - Einbroch Field", category: "field" },
    { id: "ein_in01", name: "ein_in01 - Inside Einbroch", category: "indoor" },
    { id: "einbech", name: "einbech - Einbech, the mining village", category: "city" },
    { id: "einbroch", name: "einbroch - Einbroch, the city of steel", category: "city" },
    { id: "emal_dun01h", name: "emal_dun01h", category: "dungeon" },
    { id: "etur_dun01", name: "etur_dun01", category: "dungeon" },
    { id: "evt_mobroom", name: "evt_mobroom", category: "other" },
    { id: "for_dun01", name: "for_dun01 - Garden of Time - Forgotten Time Zone 1", category: "dungeon" },
    { id: "for_dun02", name: "for_dun02 - Garden of Time - Forgotten Time Zone 2", category: "dungeon" },
    { id: "force_map1", name: "force_map1", category: "instance" },
    { id: "force_map2", name: "force_map2", category: "instance" },
    { id: "force_map3", name: "force_map3", category: "instance" },
    { id: "gef_d01_i", name: "gef_d01_i - 250 Page", category: "city" },
    { id: "gef_dun00", name: "gef_dun00 - Geffen Dungeon", category: "dungeon" },
    { id: "gef_dun01", name: "gef_dun01 - Geffen Dungeon", category: "dungeon" },
    { id: "gef_dun02", name: "gef_dun02 - Geffenia", category: "dungeon" },
    { id: "gef_dun03", name: "gef_dun03 - Geffenia", category: "dungeon" },
    { id: "gef_fild00", name: "gef_fild00 - Geffen Field", category: "field" },
    { id: "gef_fild01", name: "gef_fild01 - Geffen Field", category: "field" },
    { id: "gef_fild02", name: "gef_fild02 - Geffen Field", category: "field" },
    { id: "gef_fild03", name: "gef_fild03 - Geffen Field", category: "field" },
    { id: "gef_fild04", name: "gef_fild04 - Geffen Field", category: "field" },
    { id: "gef_fild05", name: "gef_fild05 - Geffen Field", category: "field" },
    { id: "gef_fild06", name: "gef_fild06 - Geffen Field", category: "field" },
    { id: "gef_fild07", name: "gef_fild07 - Geffen Field", category: "field" },
    { id: "gef_fild08", name: "gef_fild08 - Geffen Field", category: "field" },
    { id: "gef_fild09", name: "gef_fild09 - Geffen Field", category: "field" },
    { id: "gef_fild10", name: "gef_fild10 - Geffen Field", category: "field" },
    { id: "gef_fild11", name: "gef_fild11 - Geffen Field", category: "field" },
    { id: "gef_fild12", name: "gef_fild12 - Kordt Forest", category: "field" },
    { id: "gef_fild13", name: "gef_fild13 - Britoniah", category: "field" },
    { id: "gef_fild14", name: "gef_fild14 - West Orc Village", category: "field" },
    { id: "gef_tower", name: "gef_tower - Geffen Tower", category: "city" },
    { id: "gefenia01", name: "gefenia01 - Geffenia", category: "dungeon" },
    { id: "gefenia02", name: "gefenia02 - Geffenia", category: "dungeon" },
    { id: "gefenia03", name: "gefenia03 - Geffenia", category: "dungeon" },
    { id: "gefenia04", name: "gefenia04 - Geffenia", category: "dungeon" },
    { id: "geffen", name: "geffen - Geffen", category: "city" },
    { id: "geffen_in", name: "geffen_in - Inside Geffen", category: "indoor" },
    { id: "gefg_cas01", name: "gefg_cas01 - Britoniah Guild", category: "castle" },
    { id: "gefg_cas02", name: "gefg_cas02 - Britoniah Guild", category: "castle" },
    { id: "gefg_cas03", name: "gefg_cas03 - Britoniah Guild", category: "castle" },
    { id: "gefg_cas04", name: "gefg_cas04 - Britoniah Guild", category: "castle" },
    { id: "gefg_cas05", name: "gefg_cas05 - Britoniah Guild", category: "castle" },
    { id: "gl_cas01", name: "gl_cas01 - Glast Heim 1f", category: "castle" },
    { id: "gl_cas01_", name: "gl_cas01_ - Glast Heim Abyss", category: "castle" },
    { id: "gl_cas02", name: "gl_cas02 - Glast Heim 2f", category: "castle" },
    { id: "gl_cas02_", name: "gl_cas02_ - 2nd Hall", category: "castle" },
    { id: "gl_church", name: "gl_church - Glast Heim St. Abbey", category: "dungeon" },
    { id: "gl_chyard", name: "gl_chyard - Glast Heim Churchyard", category: "dungeon" },
    { id: "gl_chyard_", name: "gl_chyard_ - Churchyard", category: "dungeon" },
    { id: "gl_dun01", name: "gl_dun01 - The Lowest Cave in Glast Heim", category: "dungeon" },
    { id: "gl_dun02", name: "gl_dun02 - The Lowest Cave in Glast Heim", category: "dungeon" },
    { id: "gl_in01", name: "gl_in01 - Inside Glast Heim", category: "dungeon" },
    { id: "gl_knt01", name: "gl_knt01 - Inside Glast Heim Chivalry", category: "dungeon" },
    { id: "gl_knt02", name: "gl_knt02 - Inside Glast Heim Chivalry", category: "dungeon" },
    { id: "gl_prison", name: "gl_prison - Glast Heim Underprison", category: "dungeon" },
    { id: "gl_prison1", name: "gl_prison1 - Glast Heim Underprison", category: "dungeon" },
    { id: "gl_sew01", name: "gl_sew01 - Glast Heim Culvert", category: "dungeon" },
    { id: "gl_sew02", name: "gl_sew02 - Glast Heim Culvert", category: "dungeon" },
    { id: "gl_sew03", name: "gl_sew03 - Glast Heim Culvert", category: "dungeon" },
    { id: "gl_sew04", name: "gl_sew04 - Glast Heim Culvert", category: "dungeon" },
    { id: "gl_step", name: "gl_step - Glast Heim Staircase Dungeon", category: "dungeon" },
    { id: "glast_01", name: "glast_01 - Glast Heim", category: "city" },
    { id: "gld_dun01", name: "gld_dun01 - Guild Dungeon", category: "castle" },
    { id: "gld_dun02", name: "gld_dun02 - Guild Dungeon", category: "castle" },
    { id: "gld_dun03", name: "gld_dun03 - Guild Dungeon", category: "castle" },
    { id: "gld_dun04", name: "gld_dun04 - Guild Dungeon", category: "castle" },
    { id: "gld2_ald", name: "gld2_ald - Hall of the Abyss : Tear of Hero", category: "other" },
    { id: "gld2_gef", name: "gld2_gef - Hall of the Abyss : Hill of death", category: "other" },
    { id: "gld2_pay", name: "gld2_pay - Hall of the Abyss : Wind of beginning", category: "other" },
    { id: "gld2_prt", name: "gld2_prt - Hall of the Abyss : Warrior road", category: "other" },
    { id: "gon_dun01", name: "gon_dun01 - Shrine of Gonryun Queen", category: "dungeon" },
    { id: "gon_dun02", name: "gon_dun02 - Hermit's Checkers", category: "dungeon" },
    { id: "gon_dun03", name: "gon_dun03 - Arcadia", category: "dungeon" },
    { id: "gon_fild01", name: "gon_fild01 - Gonryun Field", category: "field" },
    { id: "gon_in", name: "gon_in - Inside Gonryun", category: "indoor" },
    { id: "gon_test", name: "gon_test - Arena", category: "city" },
    { id: "gonryun", name: "gonryun - Gonryun, the Hermit Land", category: "city" },
    { id: "grademk", name: "grademk - Grade-up Center", category: "other" },
    { id: "guild_vs1", name: "guild_vs1 - Guild Arena", category: "instance" },
    { id: "guild_vs2", name: "guild_vs2 - Guild Arena", category: "instance" },
    { id: "guild_vs3", name: "guild_vs3 - Guild Arena", category: "instance" },
    { id: "guild_vs3_1", name: "guild_vs3_1", category: "instance" },
    { id: "guild_vs3_2", name: "guild_vs3_2", category: "instance" },
    { id: "guild_vs3_3", name: "guild_vs3_3", category: "instance" },
    { id: "guild_vs3_4", name: "guild_vs3_4", category: "instance" },
    { id: "guild_vs3_5", name: "guild_vs3_5", category: "instance" },
    { id: "guild_vs3_6", name: "guild_vs3_6", category: "instance" },
    { id: "guild_vs3_7", name: "guild_vs3_7", category: "instance" },
    { id: "guild_vs3_8", name: "guild_vs3_8", category: "instance" },
    { id: "guild_vs4", name: "guild_vs4 - Guild War Arena", category: "instance" },
    { id: "guild_vs5", name: "guild_vs5 - Guild War Arena", category: "instance" },
    { id: "gw_fild01", name: "gw_fild01 - Gray Wolf Forest", category: "field" },
    { id: "gw_fild02", name: "gw_fild02 - Gray Wolf Forest", category: "field" },
    { id: "har_in01", name: "har_in01 - Rock Ridge", category: "indoor" },
    { id: "harboro1", name: "harboro1 - Rock Ridge", category: "other" },
    { id: "harboro2", name: "harboro2 - Culvert", category: "other" },
    { id: "hero_dun1", name: "hero_dun1 - Sanctuary Herosria PvP", category: "dungeon" },
    { id: "hero_ent1", name: "hero_ent1 - Herosria 1st Hero's Gate", category: "other" },
    { id: "hero_ent2", name: "hero_ent2 - Herosria 2nd Hero's Gate", category: "other" },
    { id: "hero_ent3", name: "hero_ent3 - Herosria 3rd Hero's Gate", category: "other" },
    { id: "hero_in1", name: "hero_in1 - Herosria Spring Garden", category: "indoor" },
    { id: "hero_in2", name: "hero_in2 - Herosria Summer Garden", category: "indoor" },
    { id: "hero_in3", name: "hero_in3 - Herosria Autumn Garden", category: "indoor" },
    { id: "hero_in4", name: "hero_in4 - Herosria Winter Garden", category: "indoor" },
    { id: "hero_lb", name: "hero_lb - Herosria Garden of Dawn", category: "other" },
    { id: "hero_out1", name: "hero_out1 - Herosria Silvarium", category: "other" },
    { id: "hero_out2", name: "hero_out2 - Herosria Lacusarium", category: "other" },
    { id: "hero_out3", name: "hero_out3 - Herosria Bastitarium", category: "other" },
    { id: "hero_out4", name: "hero_out4 - Herosria Lavinarium", category: "other" },
    { id: "hero_tra", name: "hero_tra - Herosria Training Ground", category: "other" },
    { id: "herosria", name: "herosria - Sanctuary Herosria Room", category: "other" },
    { id: "hu_fild01", name: "hu_fild01 - Thanatos Tower", category: "field" },
    { id: "hu_fild02", name: "hu_fild02 - Hugel Field", category: "field" },
    { id: "hu_fild03", name: "hu_fild03 - Hugel Field", category: "field" },
    { id: "hu_fild04", name: "hu_fild04 - Hugel Field", category: "field" },
    { id: "hu_fild05", name: "hu_fild05 - The Abyss Lake", category: "field" },
    { id: "hu_fild06", name: "hu_fild06 - Hugel Field", category: "field" },
    { id: "hu_fild07", name: "hu_fild07 - Hugel Field", category: "field" },
    { id: "hu_in01", name: "hu_in01 - Inside Hugel", category: "indoor" },
    { id: "hugel", name: "hugel - Hugel, the Quaint Garden Village", category: "city" },
    { id: "icas_in", name: "icas_in - Inside the Ice Castle", category: "indoor" },
    { id: "ice_d03_i", name: "ice_d03_i - Frozen Memory", category: "other" },
    { id: "ice_dun01", name: "ice_dun01 - Ice Cave", category: "dungeon" },
    { id: "ice_dun02", name: "ice_dun02 - Ice Cave", category: "dungeon" },
    { id: "ice_dun03", name: "ice_dun03 - Ice Cave", category: "dungeon" },
    { id: "ice_dun04", name: "ice_dun04 - Ice Cave", category: "dungeon" },
    { id: "icecastle", name: "icecastle - Issgard, the Ice Castle", category: "other" },
    { id: "in_hunter", name: "in_hunter - Hunter Guild", category: "indoor" },
    { id: "in_moc_16", name: "in_moc_16 - Assassin Clan", category: "indoor" },
    { id: "in_orcs01", name: "in_orcs01 - Orc village", category: "dungeon" },
    { id: "in_rogue", name: "in_rogue - Inside the Rogue Guild", category: "dungeon" },
    { id: "in_sphinx1", name: "in_sphinx1 - Sphinx", category: "dungeon" },
    { id: "in_sphinx2", name: "in_sphinx2 - Sphinx", category: "dungeon" },
    { id: "in_sphinx3", name: "in_sphinx3 - Sphinx", category: "dungeon" },
    { id: "in_sphinx4", name: "in_sphinx4 - Sphinx", category: "dungeon" },
    { id: "in_sphinx5", name: "in_sphinx5 - Sphinx", category: "dungeon" },
    { id: "int_land", name: "int_land - Remote Island", category: "other" },
    { id: "int_land01", name: "int_land01 - Remote Island", category: "other" },
    { id: "int_land02", name: "int_land02 - Remote Island", category: "other" },
    { id: "int_land03", name: "int_land03 - Remote Island", category: "other" },
    { id: "int_land04", name: "int_land04 - Remote Island", category: "other" },
    { id: "iz_ac01", name: "iz_ac01 - Academy1st floor", category: "other" },
    { id: "iz_ac01_a", name: "iz_ac01_a - Academy1st floor", category: "other" },
    { id: "iz_ac01_b", name: "iz_ac01_b - Academy1st floor", category: "other" },
    { id: "iz_ac01_c", name: "iz_ac01_c - Academy1st floor", category: "other" },
    { id: "iz_ac01_d", name: "iz_ac01_d - Academy1st floor", category: "other" },
    { id: "iz_ac02", name: "iz_ac02 - Academy2nd floor", category: "other" },
    { id: "iz_ac02_a", name: "iz_ac02_a - Academy2nd floor", category: "other" },
    { id: "iz_ac02_b", name: "iz_ac02_b - Academy2nd floor", category: "other" },
    { id: "iz_ac02_c", name: "iz_ac02_c - Academy2nd floor", category: "other" },
    { id: "iz_ac02_d", name: "iz_ac02_d - Academy2nd floor", category: "other" },
    { id: "iz_d04_i", name: "iz_d04_i - Illusion of Underwater 1F", category: "other" },
    { id: "iz_d05_i", name: "iz_d05_i - Illusion of Underwater 2F", category: "other" },
    { id: "iz_dun00", name: "iz_dun00 - Undersea Tunnel", category: "dungeon" },
    { id: "iz_dun00t", name: "iz_dun00t - Overlook Water Dungeon", category: "dungeon" },
    { id: "iz_dun01", name: "iz_dun01 - Undersea Tunnel", category: "dungeon" },
    { id: "iz_dun01t", name: "iz_dun01t - Overlook Water Dungeon", category: "dungeon" },
    { id: "iz_dun02", name: "iz_dun02 - Undersea Tunnel", category: "dungeon" },
    { id: "iz_dun02t", name: "iz_dun02t - Overlook Water Dungeon", category: "dungeon" },
    { id: "iz_dun03", name: "iz_dun03 - Undersea Tunnel", category: "dungeon" },
    { id: "iz_dun03t", name: "iz_dun03t - Overlook Water Dungeon", category: "dungeon" },
    { id: "iz_dun04", name: "iz_dun04 - Undersea Tunnel", category: "dungeon" },
    { id: "iz_dun04t", name: "iz_dun04t - Overlook Water Dungeon", category: "dungeon" },
    { id: "iz_dun05", name: "iz_dun05 - Undersea Tunnel", category: "dungeon" },
    { id: "iz_int", name: "iz_int - Intro", category: "other" },
    { id: "iz_int01", name: "iz_int01 - Intro", category: "other" },
    { id: "iz_int02", name: "iz_int02 - Intro", category: "other" },
    { id: "iz_int03", name: "iz_int03 - Intro", category: "other" },
    { id: "iz_int04", name: "iz_int04 - Intro", category: "other" },
    { id: "iz_ng01", name: "iz_ng01 - Ninja Tutorial map", category: "other" },
    { id: "izlu2dun", name: "izlu2dun - Byalan Island", category: "dungeon" },
    { id: "izlude", name: "izlude - Izlude Town", category: "city" },
    { id: "izlude_a", name: "izlude_a - Satellite city Izlude", category: "city" },
    { id: "izlude_b", name: "izlude_b - Satellite city Izlude", category: "city" },
    { id: "izlude_c", name: "izlude_c - Satellite city Izlude", category: "city" },
    { id: "izlude_d", name: "izlude_d - Satellite city Izlude", category: "city" },
    { id: "izlude_in", name: "izlude_in - Inside Izlude", category: "indoor" },
    { id: "jawaii", name: "jawaii - Jawaii, the Honeymoon Island", category: "city" },
    { id: "jawaii_in", name: "jawaii_in - Inside Jawaii", category: "indoor" },
    { id: "job_cru", name: "job_cru - Crusader Realm", category: "instance" },
    { id: "job_duncer", name: "job_duncer - Comodo Theatre", category: "instance" },
    { id: "job_gun", name: "job_gun - Shelter of Liberation", category: "instance" },
    { id: "job_hunte", name: "job_hunte - Hunter Job Change Place", category: "instance" },
    { id: "job_hunter", name: "job_hunter", category: "instance" },
    { id: "job_knight", name: "job_knight", category: "instance" },
    { id: "job_knt", name: "job_knt - Knight Realm", category: "instance" },
    { id: "job_ko", name: "job_ko - Hidden Place", category: "instance" },
    { id: "job_monk", name: "job_monk - Saint Capitolina Abbey", category: "instance" },
    { id: "job_priest", name: "job_priest", category: "instance" },
    { id: "job_prist", name: "job_prist - Priest Realm", category: "instance" },
    { id: "job_sage", name: "job_sage - Sage Realm", category: "instance" },
    { id: "job_soul", name: "job_soul - Your Heart", category: "instance" },
    { id: "job_star", name: "job_star - The Sun, the Moon and the Stars", category: "instance" },
    { id: "job_sword1", name: "job_sword1", category: "instance" },
    { id: "job_thief1", name: "job_thief1 - Mushroom Farm", category: "instance" },
    { id: "job_wiz", name: "job_wiz - Wizard Realm", category: "instance" },
    { id: "job_wizard", name: "job_wizard", category: "instance" },
    { id: "job3_arch01", name: "job3_arch01 - Waiting room for Arch Bishop Job Change", category: "instance" },
    { id: "job3_arch02", name: "job3_arch02 - Odin Temple", category: "instance" },
    { id: "job3_gen01", name: "job3_gen01 - Geneticist Lab", category: "instance" },
    { id: "job3_guil01", name: "job3_guil01 - Secret Tavern", category: "instance" },
    { id: "job3_guil02", name: "job3_guil02 - Inside the Old Warehouse", category: "instance" },
    { id: "job3_guil03", name: "job3_guil03 - An isolated mansion", category: "instance" },
    { id: "job3_rang01", name: "job3_rang01 - Waiting room for Ranger Job Change", category: "instance" },
    { id: "job3_rang02", name: "job3_rang02 - Test room for Ranger Job Change", category: "instance" },
    { id: "job3_rune01", name: "job3_rune01 - Inside of Rune Knight Templar", category: "instance" },
    { id: "job3_rune02", name: "job3_rune02 - Test room for Rune Knight Job Change", category: "instance" },
    { id: "job3_sha01", name: "job3_sha01", category: "instance" },
    { id: "job3_war01", name: "job3_war01 - Test room for Warlock Job Change", category: "instance" },
    { id: "job4_bio", name: "job4_bio - Secret Flower Garden", category: "other" },
    { id: "job4_mag", name: "job4_mag - Mana Spring", category: "other" },
    { id: "job4_tro", name: "job4_tro - Empty Kvasir's Chest", category: "other" },
    { id: "jor_ab01", name: "jor_ab01 - Abandoned Pit - 1st Floor", category: "other" },
    { id: "jor_ab02", name: "jor_ab02 - Abandoned Pit - 2nd Floor", category: "other" },
    { id: "jor_back1", name: "jor_back1 - Frozen Scale Hill", category: "other" },
    { id: "jor_back2", name: "jor_back2 - Frozen Scale Plains", category: "other" },
    { id: "jor_back3", name: "jor_back3 - Frozen Scale Glacier", category: "other" },
    { id: "jor_dun01", name: "jor_dun01 - Warmth of the Serpent God - 1st Floor", category: "dungeon" },
    { id: "jor_dun02", name: "jor_dun02 - Warmth of the Serpent God - 2nd Floor", category: "dungeon" },
    { id: "jor_dun03", name: "jor_dun03 - Inside the Serpent's Nest", category: "dungeon" },
    { id: "jor_nest", name: "jor_nest - Serpent's Nest", category: "other" },
    { id: "jor_que", name: "jor_que - Abandoned Warmth of the Serpent God", category: "other" },
    { id: "jor_tail", name: "jor_tail - Frozen Tail", category: "other" },
    { id: "jupe_area1", name: "jupe_area1 - Juperos, Restricted Zone", category: "dungeon" },
    { id: "jupe_area2", name: "jupe_area2 - Juperos, Restricted Zone", category: "dungeon" },
    { id: "jupe_cave", name: "jupe_cave - Ruins of Juperos Entrance", category: "dungeon" },
    { id: "jupe_core", name: "jupe_core - Center of Juperos", category: "dungeon" },
    { id: "jupe_ele", name: "jupe_ele - Juperos Elevator", category: "dungeon" },
    { id: "jupe_ele_r", name: "jupe_ele_r - Juperos Elevator", category: "dungeon" },
    { id: "jupe_gate", name: "jupe_gate - Juperos, Restricted Zone", category: "dungeon" },
    { id: "juperos_01", name: "juperos_01 - Ruins of Juperos", category: "dungeon" },
    { id: "juperos_02", name: "juperos_02 - Ruins of Juperos", category: "dungeon" },
    { id: "kh_dun01", name: "kh_dun01 - Robot Factory level 1", category: "dungeon" },
    { id: "kh_dun02", name: "kh_dun02 - Robot Factory level 2", category: "dungeon" },
    { id: "kh_kiehl01", name: "kh_kiehl01 - Kiehl's Room", category: "dungeon" },
    { id: "kh_kiehl02", name: "kh_kiehl02 - Kiehl's Room", category: "dungeon" },
    { id: "kh_mansion", name: "kh_mansion - Kiel Hyre's Mansion", category: "dungeon" },
    { id: "kh_rossi", name: "kh_rossi - The Rosimier's Mansion", category: "dungeon" },
    { id: "kh_school", name: "kh_school - Kiel Hyre Academy", category: "dungeon" },
    { id: "kh_vila", name: "kh_vila - Kiel Hyre's Cottage", category: "dungeon" },
    { id: "lasa_dun_q", name: "lasa_dun_q - Dragon's Nest", category: "dungeon" },
    { id: "lasa_dun01", name: "lasa_dun01 - Dragon's Nest", category: "dungeon" },
    { id: "lasa_dun02", name: "lasa_dun02 - Dragon's Nest", category: "dungeon" },
    { id: "lasa_dun03", name: "lasa_dun03 - Dragon's Nest", category: "dungeon" },
    { id: "lasa_fild01", name: "lasa_fild01 - Ravioli Plain Watch", category: "field" },
    { id: "lasa_fild02", name: "lasa_fild02 - Ravioli Forest", category: "field" },
    { id: "lasa_in01", name: "lasa_in01 - Inside Lasagna", category: "indoor" },
    { id: "lasa_sea", name: "lasa_sea - Nyail Cave", category: "other" },
    { id: "lasagna", name: "lasagna - Port city of Lasagna", category: "other" },
    { id: "lhz_airport", name: "lhz_airport - Lighthalzen Airport", category: "city" },
    { id: "lhz_cube", name: "lhz_cube - Cube Room", category: "city" },
    { id: "lhz_d_n2", name: "lhz_d_n2 - Space of Thoughts", category: "city" },
    { id: "lhz_dun_n", name: "lhz_dun_n - The Bed of Honor", category: "dungeon" },
    { id: "lhz_dun01", name: "lhz_dun01 - Somatology Laboratory", category: "dungeon" },
    { id: "lhz_dun02", name: "lhz_dun02 - Somatology Laboratory", category: "dungeon" },
    { id: "lhz_dun03", name: "lhz_dun03 - Somatology Laboratory", category: "dungeon" },
    { id: "lhz_dun04", name: "lhz_dun04 - Human Experimentation Laboratory B4", category: "dungeon" },
    { id: "lhz_fild01", name: "lhz_fild01 - Lighthalzen Field", category: "field" },
    { id: "lhz_fild02", name: "lhz_fild02 - Lighthalzen Field (Grim Reaper's Valley)", category: "field" },
    { id: "lhz_fild03", name: "lhz_fild03 - Lighthalzen Field", category: "field" },
    { id: "lhz_in01", name: "lhz_in01 - Rekenber Corporation Headquarters", category: "indoor" },
    { id: "lhz_in02", name: "lhz_in02 - Inside Lighthalzen", category: "indoor" },
    { id: "lhz_in03", name: "lhz_in03 - Inside Lighthalzen", category: "indoor" },
    { id: "lhz_que01", name: "lhz_que01 - Inside Lighthalzen", category: "city" },
    { id: "lighthalzen", name: "lighthalzen - Lightharlzen, the City-State of Prosperity", category: "city" },
    { id: "lou_dun01", name: "lou_dun01 - The Royal Tomb", category: "dungeon" },
    { id: "lou_dun02", name: "lou_dun02 - Inside the Royal Tomb", category: "dungeon" },
    { id: "lou_dun03", name: "lou_dun03 - Suei Long Gon", category: "dungeon" },
    { id: "lou_fild01", name: "lou_fild01 - Louyang Field", category: "field" },
    { id: "lou_in01", name: "lou_in01 - Inside Louyang", category: "indoor" },
    { id: "lou_in02", name: "lou_in02 - Inside Louyang", category: "indoor" },
    { id: "louyang", name: "louyang - Louyang, the highland", category: "city" },
    { id: "louyang_e", name: "louyang_e - Louyang Excavation Site", category: "other" },
    { id: "ma_dun01", name: "ma_dun01 - Bangungot Hospital 1F", category: "dungeon" },
    { id: "ma_fild01", name: "ma_fild01 - Baryo Mahiwaga", category: "field" },
    { id: "ma_fild02", name: "ma_fild02 - Forest", category: "field" },
    { id: "ma_in01", name: "ma_in01 - Inside of Malaya", category: "indoor" },
    { id: "ma_scene01", name: "ma_scene01 - Bakonawa Lake", category: "other" },
    { id: "ma_zif01", name: "ma_zif01 - Inside of Jeepney", category: "other" },
    { id: "ma_zif02", name: "ma_zif02 - Inside of Jeepney", category: "other" },
    { id: "ma_zif03", name: "ma_zif03 - Inside of Jeepney", category: "other" },
    { id: "ma_zif04", name: "ma_zif04 - Inside of Jeepney", category: "other" },
    { id: "ma_zif05", name: "ma_zif05 - Inside of Jeepney", category: "other" },
    { id: "ma_zif06", name: "ma_zif06 - Inside of Jeepney", category: "other" },
    { id: "ma_zif07", name: "ma_zif07 - Inside of Jeepney", category: "other" },
    { id: "ma_zif08", name: "ma_zif08 - Inside of Jeepney", category: "other" },
    { id: "ma_zif09", name: "ma_zif09 - Inside of Jeepney", category: "other" },
    { id: "mag_dun01", name: "mag_dun01 - Nogg Road", category: "dungeon" },
    { id: "mag_dun02", name: "mag_dun02 - Nogg Road", category: "dungeon" },
    { id: "mag_dun03", name: "mag_dun03 - Nogg Road", category: "dungeon" },
    { id: "mal_dun01", name: "mal_dun01 - Starry Coral Area", category: "dungeon" },
    { id: "mal_in01", name: "mal_in01 - Malangdo Inside", category: "indoor" },
    { id: "mal_in02", name: "mal_in02 - Inside the Ship", category: "indoor" },
    { id: "malangdo", name: "malangdo - Malangdo", category: "city" },
    { id: "malaya", name: "malaya - Port Malaya", category: "city" },
    { id: "man_fild01", name: "man_fild01 - Manuk Field", category: "field" },
    { id: "man_fild02", name: "man_fild02 - Manuk Field", category: "field" },
    { id: "man_fild03", name: "man_fild03 - Manuk Field", category: "field" },
    { id: "man_in01", name: "man_in01 - Inside Manuk", category: "indoor" },
    { id: "manuk", name: "manuk - Manuk", category: "city" },
    { id: "mid_camp", name: "mid_camp - Rune Midgard Allied Forces Post", category: "city" },
    { id: "mid_campin", name: "mid_campin - Inside of the Rune Midgard Allied Forces Post", category: "other" },
    { id: "mjo_dun01", name: "mjo_dun01 - Mjolnir Dead Pit", category: "dungeon" },
    { id: "mjo_dun02", name: "mjo_dun02 - Mjolnir Dead Pit", category: "dungeon" },
    { id: "mjo_dun03", name: "mjo_dun03 - Mjolnir Dead Pit", category: "dungeon" },
    { id: "mjo_wst01", name: "mjo_wst01 - Mjolnir Underground Caverns", category: "other" },
    { id: "mjolnir_01", name: "mjolnir_01 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_02", name: "mjolnir_02 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_03", name: "mjolnir_03 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_04", name: "mjolnir_04 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_04_1", name: "mjolnir_04_1", category: "other" },
    { id: "mjolnir_05", name: "mjolnir_05 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_06", name: "mjolnir_06 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_07", name: "mjolnir_07 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_08", name: "mjolnir_08 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_09", name: "mjolnir_09 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_10", name: "mjolnir_10 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_11", name: "mjolnir_11 - Mt.Mjolnir", category: "other" },
    { id: "mjolnir_12", name: "mjolnir_12 - Mt.Mjolnir", category: "other" },
    { id: "moc_castle", name: "moc_castle - Morroc Castle", category: "city" },
    { id: "moc_fild01", name: "moc_fild01 - Sograt Desert", category: "field" },
    { id: "moc_fild02", name: "moc_fild02 - Sograt Desert", category: "field" },
    { id: "moc_fild03", name: "moc_fild03 - Sograt Desert", category: "field" },
    { id: "moc_fild04", name: "moc_fild04 - Sograt Desert", category: "field" },
    { id: "moc_fild05", name: "moc_fild05 - Sograt Desert", category: "field" },
    { id: "moc_fild06", name: "moc_fild06 - Sograt Desert", category: "field" },
    { id: "moc_fild07", name: "moc_fild07 - Sograt Desert", category: "field" },
    { id: "moc_fild08", name: "moc_fild08 - Sograt Desert", category: "field" },
    { id: "moc_fild09", name: "moc_fild09 - Sograt Desert", category: "field" },
    { id: "moc_fild10", name: "moc_fild10 - Sograt Desert", category: "field" },
    { id: "moc_fild11", name: "moc_fild11 - Sograt Desert", category: "field" },
    { id: "moc_fild12", name: "moc_fild12 - Sograt Desert", category: "field" },
    { id: "moc_fild13", name: "moc_fild13 - Sograt Desert", category: "field" },
    { id: "moc_fild14", name: "moc_fild14 - Sograt Desert", category: "field" },
    { id: "moc_fild15", name: "moc_fild15 - Sograt Desert", category: "field" },
    { id: "moc_fild16", name: "moc_fild16 - Sograt Desert", category: "field" },
    { id: "moc_fild17", name: "moc_fild17 - Sograt Desert", category: "field" },
    { id: "moc_fild18", name: "moc_fild18 - Sograt Desert", category: "field" },
    { id: "moc_fild19", name: "moc_fild19 - Sograt Desert", category: "field" },
    { id: "moc_fild20", name: "moc_fild20 - Sograt Desert - Continental Guard Quarantine", category: "field" },
    { id: "moc_fild21", name: "moc_fild21 - Dimensional Gorge", category: "field" },
    { id: "moc_fild22", name: "moc_fild22 - Dimensional Gorge", category: "field" },
    { id: "moc_fild22b", name: "moc_fild22b - Dimensional Gorge", category: "field" },
    { id: "moc_para01", name: "moc_para01 - Inside of Paradise Group Building in Morroc", category: "city" },
    { id: "moc_pryd01", name: "moc_pryd01 - Inside Pyramid", category: "dungeon" },
    { id: "moc_pryd02", name: "moc_pryd02 - Inside Pyramid", category: "dungeon" },
    { id: "moc_pryd03", name: "moc_pryd03 - Inside Pyramid", category: "dungeon" },
    { id: "moc_pryd04", name: "moc_pryd04 - Inside Pyramid", category: "dungeon" },
    { id: "moc_pryd05", name: "moc_pryd05 - Inside Pyramid", category: "dungeon" },
    { id: "moc_pryd06", name: "moc_pryd06 - Inside Pyramid", category: "dungeon" },
    { id: "moc_prydb1", name: "moc_prydb1 - Thief Guild", category: "dungeon" },
    { id: "moc_prydn1", name: "moc_prydn1 - Morocc Pyramid Underground 1st Floor - Challenge", category: "dungeon" },
    { id: "moc_prydn2", name: "moc_prydn2 - Morocc Pyramid Underground 2nd Floor - Challenge", category: "dungeon" },
    { id: "moc_ruins", name: "moc_ruins - Morroc Ruins", category: "city" },
    { id: "monk_in", name: "monk_in - Inside St. Abbey", category: "indoor" },
    { id: "monk_test", name: "monk_test - Saint Capitolina Abbey", category: "other" },
    { id: "mora", name: "mora - Mora Village", category: "city" },
    { id: "moro_cav", name: "moro_cav - Flame cave", category: "other" },
    { id: "moro_vol", name: "moro_vol - Flame Basin", category: "other" },
    { id: "morocc", name: "morocc - Morroc Town", category: "city" },
    { id: "morocc_in", name: "morocc_in - Inside Morroc", category: "indoor" },
    { id: "morocc_mem", name: "morocc_mem - Memory of Morroc", category: "other" },
    { id: "moscovia", name: "moscovia - Moscovia", category: "city" },
    { id: "mosk_dun01", name: "mosk_dun01 - Les Forest", category: "dungeon" },
    { id: "mosk_dun02", name: "mosk_dun02 - Temny Forest", category: "dungeon" },
    { id: "mosk_dun03", name: "mosk_dun03 - Dremuci Forest", category: "dungeon" },
    { id: "mosk_fild01", name: "mosk_fild01 - somewhere in Moscovia", category: "field" },
    { id: "mosk_fild02", name: "mosk_fild02 - Okrestnosti of Moscovia", category: "field" },
    { id: "mosk_in", name: "mosk_in - Inside Moscovia", category: "indoor" },
    { id: "mosk_que", name: "mosk_que - Marozka's Cave", category: "city" },
    { id: "mosk_ship", name: "mosk_ship - Charabel", category: "city" },
    { id: "n_castle", name: "n_castle", category: "other" },
    { id: "nameless_i", name: "nameless_i - Nameless Island", category: "other" },
    { id: "nameless_in", name: "nameless_in - Inside Nameless Island", category: "indoor" },
    { id: "nameless_n", name: "nameless_n - Nameless Island", category: "other" },
    { id: "new_1-2_evt", name: "new_1-2_evt", category: "other" },
    { id: "new_event", name: "new_event", category: "other" },
    { id: "new_zone01", name: "new_zone01", category: "city" },
    { id: "new_zone02", name: "new_zone02", category: "other" },
    { id: "new_zone03", name: "new_zone03", category: "other" },
    { id: "new_zone04", name: "new_zone04", category: "other" },
    { id: "nif_dun01", name: "nif_dun01 - Nifflheim Dungeon Banquet Hall of the Dead", category: "dungeon" },
    { id: "nif_dun02", name: "nif_dun02 - Nifflheim Dungeon Collapsed Opera House", category: "dungeon" },
    { id: "nif_fild01", name: "nif_fild01 - Skellington, a Solitary Village in Nifflheim", category: "field" },
    { id: "nif_fild02", name: "nif_fild02 - Vally of Gyoll", category: "field" },
    { id: "nif_in", name: "nif_in - Inside Nifflheim", category: "indoor" },
    { id: "niflheim", name: "niflheim - Nifflheim, Realm of the Dead", category: "city" },
    { id: "nyd_dun01", name: "nyd_dun01 - Yggdrasil Root", category: "dungeon" },
    { id: "nyd_dun02", name: "nyd_dun02 - Yggdrasil Root", category: "dungeon" },
    { id: "nydevent_01", name: "nydevent_01", category: "other" },
    { id: "odin_past", name: "odin_past - Ancient Odin's Temple", category: "other" },
    { id: "odin_tem01", name: "odin_tem01 - Odin Shirine", category: "other" },
    { id: "odin_tem02", name: "odin_tem02 - Odin Shirine", category: "other" },
    { id: "odin_tem03", name: "odin_tem03 - Odin Shirine", category: "other" },
    { id: "orcsdun01", name: "orcsdun01 - Orc Dungeon", category: "dungeon" },
    { id: "orcsdun02", name: "orcsdun02 - Orc Dungeon", category: "dungeon" },
    { id: "ordeal_a00", name: "ordeal_a00", category: "instance" },
    { id: "ordeal_a02", name: "ordeal_a02", category: "instance" },
    { id: "oz_dun01", name: "oz_dun01 - Oz Labyrinth 1F", category: "dungeon" },
    { id: "oz_dun02", name: "oz_dun02 - Oz Labyrinth 2F", category: "dungeon" },
    { id: "p_track01", name: "p_track01 - Monster Race Arena", category: "other" },
    { id: "paramk", name: "paramk - Para Market", category: "other" },
    { id: "pay_arche", name: "pay_arche - Archer Village", category: "city" },
    { id: "pay_d03_i", name: "pay_d03_i - Nightmare_of_the_Moonlight_Flower", category: "city" },
    { id: "pay_dun00", name: "pay_dun00 - Payon Cave", category: "dungeon" },
    { id: "pay_dun01", name: "pay_dun01 - Payon Cave", category: "dungeon" },
    { id: "pay_dun02", name: "pay_dun02 - Payon Cave", category: "dungeon" },
    { id: "pay_dun03", name: "pay_dun03 - Payon Cave", category: "dungeon" },
    { id: "pay_dun04", name: "pay_dun04 - Payon Cave", category: "dungeon" },
    { id: "pay_fild01", name: "pay_fild01 - Payon Forest", category: "field" },
    { id: "pay_fild02", name: "pay_fild02 - Payon Forest", category: "field" },
    { id: "pay_fild03", name: "pay_fild03 - Payon Forest", category: "field" },
    { id: "pay_fild04", name: "pay_fild04 - Sograt Desert", category: "field" },
    { id: "pay_fild05", name: "pay_fild05 - Payon Forest", category: "field" },
    { id: "pay_fild06", name: "pay_fild06 - Payon Forest", category: "field" },
    { id: "pay_fild07", name: "pay_fild07 - Payon Forest", category: "field" },
    { id: "pay_fild08", name: "pay_fild08 - Payon Forest", category: "field" },
    { id: "pay_fild09", name: "pay_fild09 - Payon Forest", category: "field" },
    { id: "pay_fild10", name: "pay_fild10 - Payon Forest", category: "field" },
    { id: "pay_fild11", name: "pay_fild11 - Payon Forest", category: "field" },
    { id: "pay_gld", name: "pay_gld - Greenwood Lake", category: "castle" },
    { id: "payg_cas01", name: "payg_cas01 - Greenwood Lake Guild", category: "castle" },
    { id: "payg_cas02", name: "payg_cas02 - Greenwood Lake Guild", category: "castle" },
    { id: "payg_cas03", name: "payg_cas03 - Greenwood Lake Guild", category: "castle" },
    { id: "payg_cas04", name: "payg_cas04 - Greenwood Lake Guild", category: "castle" },
    { id: "payg_cas05", name: "payg_cas05 - Greenwood Lake Guild", category: "castle" },
    { id: "payon", name: "payon - Payon Town", category: "city" },
    { id: "payon_in01", name: "payon_in01 - Inside Payon", category: "indoor" },
    { id: "payon_in02", name: "payon_in02 - Inside Payon", category: "indoor" },
    { id: "payon_in03", name: "payon_in03 - Inside Payon", category: "indoor" },
    { id: "payon_mem", name: "payon_mem - Memory of Payon", category: "other" },
    { id: "poring_c01", name: "poring_c01", category: "other" },
    { id: "poring_c02", name: "poring_c02", category: "other" },
    { id: "poring_w01", name: "poring_w01 - Poring War - Waiting Room", category: "instance" },
    { id: "poring_w02", name: "poring_w02 - Poring War", category: "instance" },
    { id: "pprontera", name: "pprontera", category: "other" },
    { id: "prontera", name: "prontera - Prontera City, Capitol of Rune-Midgarts", category: "city" },
    { id: "prt_are_in", name: "prt_are_in - Waiting room", category: "instance" },
    { id: "prt_are01", name: "prt_are01 - ARENA", category: "instance" },
    { id: "prt_cas", name: "prt_cas - Prontera Center Palace", category: "city" },
    { id: "prt_cas_q", name: "prt_cas_q - Prontera Royal Villa", category: "city" },
    { id: "prt_castle", name: "prt_castle - Prontera Castle", category: "city" },
    { id: "prt_church", name: "prt_church - the Sanctuary", category: "city" },
    { id: "prt_elib", name: "prt_elib - Prontera East Library", category: "city" },
    { id: "prt_evt_in", name: "prt_evt_in - Hunting Ground Cabin", category: "indoor" },
    { id: "prt_fild00", name: "prt_fild00 - Prontera Field", category: "field" },
    { id: "prt_fild01", name: "prt_fild01 - Prontera Field", category: "field" },
    { id: "prt_fild02", name: "prt_fild02 - Prontera Field", category: "field" },
    { id: "prt_fild03", name: "prt_fild03 - Prontera Field", category: "field" },
    { id: "prt_fild04", name: "prt_fild04 - Prontera Field", category: "field" },
    { id: "prt_fild05", name: "prt_fild05 - Prontera Field", category: "field" },
    { id: "prt_fild06", name: "prt_fild06 - Prontera Field", category: "field" },
    { id: "prt_fild07", name: "prt_fild07 - Prontera Field", category: "field" },
    { id: "prt_fild08", name: "prt_fild08 - Prontera Field", category: "field" },
    { id: "prt_fild09", name: "prt_fild09 - Prontera Field", category: "field" },
    { id: "prt_fild10", name: "prt_fild10 - Prontera Field", category: "field" },
    { id: "prt_fild11", name: "prt_fild11 - Prontera Field", category: "field" },
    { id: "prt_gld", name: "prt_gld - Valkyrie Realm", category: "castle" },
    { id: "prt_in", name: "prt_in - Inside Prontera", category: "indoor" },
    { id: "prt_lib", name: "prt_lib - Royal Memory", category: "city" },
    { id: "prt_lib_q", name: "prt_lib_q - Old Memoir of Royal Family", category: "city" },
    { id: "prt_maze01", name: "prt_maze01 - Labyrinth Forest", category: "dungeon" },
    { id: "prt_maze02", name: "prt_maze02 - Labyrinth Forest", category: "dungeon" },
    { id: "prt_maze03", name: "prt_maze03 - Labyrinth Forest", category: "dungeon" },
    { id: "prt_monk", name: "prt_monk - St. Capitolina Abbey", category: "city" },
    { id: "prt_mz03_i", name: "prt_mz03_i - Illusion Labyrinth", category: "city" },
    { id: "prt_pri00", name: "prt_pri00 - Prontera Prison", category: "city" },
    { id: "prt_prison", name: "prt_prison - Prontera Underground Prison", category: "city" },
    { id: "prt_q", name: "prt_q - Prontera Invasion", category: "city" },
    { id: "prt_sewb1", name: "prt_sewb1 - Prontera Culvert", category: "dungeon" },
    { id: "prt_sewb2", name: "prt_sewb2 - Prontera Culvert", category: "dungeon" },
    { id: "prt_sewb3", name: "prt_sewb3 - Prontera Culvert", category: "dungeon" },
    { id: "prt_sewb4", name: "prt_sewb4 - Prontera Culvert", category: "dungeon" },
    { id: "prtg_cas01", name: "prtg_cas01 - Valkyrie Realm Guild", category: "castle" },
    { id: "prtg_cas02", name: "prtg_cas02 - Valkyrie Realm Guild", category: "castle" },
    { id: "prtg_cas03", name: "prtg_cas03 - Valkyrie Realm Guild", category: "castle" },
    { id: "prtg_cas04", name: "prtg_cas04 - Valkyrie Realm Guild", category: "castle" },
    { id: "prtg_cas05", name: "prtg_cas05 - Valkyrie Realm Guild", category: "castle" },
    { id: "pub_cat", name: "pub_cat - Cat on a Bullet", category: "other" },
    { id: "pvp_2vs2", name: "pvp_2vs2 - PvP : Event Coliseum", category: "instance" },
    { id: "pvp_room", name: "pvp_room", category: "instance" },
    { id: "pvp_y_1-2", name: "pvp_y_1-2 - PvP : Room Izlude", category: "instance" },
    { id: "pvp_y_2-2", name: "pvp_y_2-2 - PvP : Room Izlude", category: "instance" },
    { id: "pvp_y_3-2", name: "pvp_y_3-2 - PvP : Room Izlude", category: "instance" },
    { id: "pvp_y_4-2", name: "pvp_y_4-2 - PvP : Room Izlude", category: "instance" },
    { id: "pvp_y_5-2", name: "pvp_y_5-2 - PvP : Room Izlude", category: "instance" },
    { id: "pvp_y_6-2", name: "pvp_y_6-2 - PvP : Room Izlude", category: "instance" },
    { id: "pvp_y_7-2", name: "pvp_y_7-2 - PvP : Room Izlude", category: "instance" },
    { id: "pvp_y_8-2", name: "pvp_y_8-2 - PvP : Room Izlude", category: "instance" },
    { id: "que_avan01", name: "que_avan01 - Avant's Laboratory", category: "instance" },
    { id: "que_ba", name: "que_ba", category: "instance" },
    { id: "que_bingo", name: "que_bingo - Bingo Game Room", category: "instance" },
    { id: "que_dan01", name: "que_dan01 - Hugel Field", category: "instance" },
    { id: "que_dan02", name: "que_dan02 - Inside of the Abandoned House in Juno", category: "instance" },
    { id: "que_god01", name: "que_god01 - Quest Map", category: "instance" },
    { id: "que_god01t", name: "que_god01t - Quest Map", category: "instance" },
    { id: "que_god02", name: "que_god02 - Quest Map", category: "instance" },
    { id: "que_house_s", name: "que_house_s - Weird house", category: "instance" },
    { id: "que_hugel", name: "que_hugel - Odin Shrine's Underground", category: "instance" },
    { id: "que_job01", name: "que_job01 - Private Pub", category: "instance" },
    { id: "que_job02", name: "que_job02", category: "instance" },
    { id: "que_lhz", name: "que_lhz - Human Experimentation Laboratory B4", category: "instance" },
    { id: "que_ng", name: "que_ng - Unknown Area", category: "instance" },
    { id: "que_qsch01", name: "que_qsch01 - Fallacious Okolnir", category: "instance" },
    { id: "que_rachel", name: "que_rachel - Inside Temple", category: "instance" },
    { id: "que_sign01", name: "que_sign01", category: "instance" },
    { id: "que_swat", name: "que_swat - Heart_Hunter War_Base", category: "instance" },
    { id: "que_thor", name: "que_thor - Thor Volcano Dungeon", category: "instance" },
    { id: "que_thr", name: "que_thr - Inside Thor Volcano", category: "instance" },
    { id: "quiz_00", name: "quiz_00 - Quiz Revolrution", category: "other" },
    { id: "quiz_01", name: "quiz_01 - Quiz Revolrutiona", category: "other" },
    { id: "quiz_02", name: "quiz_02 - Quiz Arena", category: "other" },
    { id: "ra_fild01", name: "ra_fild01 - Audhumbla Grassland", category: "field" },
    { id: "ra_fild02", name: "ra_fild02 - Od Canyon", category: "field" },
    { id: "ra_fild03", name: "ra_fild03 - The Plain of Ida", category: "field" },
    { id: "ra_fild04", name: "ra_fild04 - Audhumbla Grassland", category: "field" },
    { id: "ra_fild05", name: "ra_fild05 - Audhumbla Grassland", category: "field" },
    { id: "ra_fild06", name: "ra_fild06 - Portus Luna", category: "field" },
    { id: "ra_fild07", name: "ra_fild07 - Od Canyon", category: "field" },
    { id: "ra_fild08", name: "ra_fild08 - The Plain of Ida", category: "field" },
    { id: "ra_fild09", name: "ra_fild09 - Audhumbla Grassland", category: "field" },
    { id: "ra_fild10", name: "ra_fild10 - Od Canyon", category: "field" },
    { id: "ra_fild11", name: "ra_fild11 - The Plain of Ida", category: "field" },
    { id: "ra_fild12", name: "ra_fild12 - The Plain of Ida", category: "field" },
    { id: "ra_fild13", name: "ra_fild13 - Shore of Tears", category: "field" },
    { id: "ra_in01", name: "ra_in01 - Inside Rachel", category: "indoor" },
    { id: "ra_pol01", name: "ra_pol01 - Power Twisted Plains", category: "city" },
    { id: "ra_san01", name: "ra_san01 - Holy Ground", category: "dungeon" },
    { id: "ra_san02", name: "ra_san02 - Holy Ground", category: "dungeon" },
    { id: "ra_san03", name: "ra_san03 - Holy Ground", category: "dungeon" },
    { id: "ra_san04", name: "ra_san04 - Holy Ground", category: "dungeon" },
    { id: "ra_san05", name: "ra_san05 - Holy Ground", category: "dungeon" },
    { id: "ra_temin", name: "ra_temin - Inside Temple", category: "city" },
    { id: "ra_temple", name: "ra_temple - Freya Grand Temple - Cheshrumnir", category: "city" },
    { id: "ra_temsky", name: "ra_temsky - Pope's Office - The Garden of Heaven", category: "city" },
    { id: "rachel", name: "rachel - Capital of Arunafeltz States, Rachel", category: "city" },
    { id: "rebel_in", name: "rebel_in - Clana Nemieri", category: "indoor" },
    { id: "rgsr_in", name: "rgsr_in - Regenschirm Laboratory", category: "indoor" },
    { id: "rockmi1", name: "rockmi1 - Rock Ridge Mine", category: "other" },
    { id: "rockmi2", name: "rockmi2 - Rock Ridge Mine", category: "other" },
    { id: "rockrdg1", name: "rockrdg1 - Kiwawa Desert", category: "other" },
    { id: "rockrdg2", name: "rockrdg2 - Kiwawa Desert", category: "other" },
    { id: "rwc01", name: "rwc01", category: "other" },
    { id: "rwc02", name: "rwc02", category: "other" },
    { id: "rwc03", name: "rwc03", category: "other" },
    { id: "s_atelier", name: "s_atelier - Shadow Workshop", category: "other" },
    { id: "sch_gld", name: "sch_gld - Nidhoggur", category: "castle" },
    { id: "schg_cas01", name: "schg_cas01 - Nidhoggur Guild", category: "castle" },
    { id: "schg_cas02", name: "schg_cas02 - Nidhoggur Guild", category: "castle" },
    { id: "schg_cas03", name: "schg_cas03 - Nidhoggur Guild", category: "castle" },
    { id: "schg_dun01", name: "schg_dun01 - Subterranean Guild Dungeon", category: "dungeon" },
    { id: "sec_in01", name: "sec_in01 - Inside Valhalla", category: "instance" },
    { id: "sec_in02", name: "sec_in02 - Inside Valhalla", category: "instance" },
    { id: "sec_pri", name: "sec_pri - Room of Meditation (Valhalla Prison)", category: "instance" },
    { id: "siege_test", name: "siege_test", category: "other" },
    { id: "slabw01", name: "slabw01 - Werner Laboratory", category: "other" },
    { id: "sp_cor", name: "sp_cor - Special Security Area, Cor", category: "other" },
    { id: "sp_os", name: "sp_os - Special Security Area, Os", category: "other" },
    { id: "sp_rudus", name: "sp_rudus - Laboratory Waste Disposal Plant Rudus Floor 1", category: "other" },
    { id: "sp_rudus2", name: "sp_rudus2 - Laboratory Waste Disposal Plant Rudus Floor 2", category: "other" },
    { id: "sp_rudus3", name: "sp_rudus3 - Laboratory Waste Disposal Plant Rudus Floor 3", category: "other" },
    { id: "sp_rudus4", name: "sp_rudus4 - Laboratory Waste Disposal Plant Rudus Floor 4", category: "other" },
    { id: "spl_fild01", name: "spl_fild01 - Splendide Field", category: "field" },
    { id: "spl_fild02", name: "spl_fild02 - Splendide Field", category: "field" },
    { id: "spl_fild03", name: "spl_fild03 - Splendide Field", category: "field" },
    { id: "spl_in01", name: "spl_in01 - Inside Splendide", category: "dungeon" },
    { id: "spl_in02", name: "spl_in02 - Inside Splendide", category: "dungeon" },
    { id: "splendide", name: "splendide - Splendide", category: "city" },
    { id: "star_frst", name: "star_frst - Meteor Forest", category: "other" },
    { id: "star_in", name: "star_in - Meteor Forest indoor", category: "indoor" },
    { id: "summon_01", name: "summon_01", category: "other" },
    { id: "summon_02", name: "summon_02", category: "other" },
    { id: "t_garden", name: "t_garden - Garden of Time", category: "other" },
    { id: "te_alde_gld", name: "te_alde_gld - Kafragarten", category: "castle" },
    { id: "te_aldecas1", name: "te_aldecas1 - Leilah", category: "other" },
    { id: "te_aldecas2", name: "te_aldecas2 - Pavianne", category: "other" },
    { id: "te_aldecas3", name: "te_aldecas3 - Jasmine", category: "other" },
    { id: "te_aldecas4", name: "te_aldecas4 - Roxie", category: "other" },
    { id: "te_aldecas5", name: "te_aldecas5 - Curly Sue", category: "other" },
    { id: "te_prt_gld", name: "te_prt_gld - Gloria", category: "castle" },
    { id: "te_prtcas01", name: "te_prtcas01 - Gaebolg", category: "other" },
    { id: "te_prtcas02", name: "te_prtcas02 - Richard", category: "other" },
    { id: "te_prtcas03", name: "te_prtcas03 - Wigner", category: "other" },
    { id: "te_prtcas04", name: "te_prtcas04 - Heine", category: "other" },
    { id: "te_prtcas05", name: "te_prtcas05 - Nerious", category: "other" },
    { id: "teg_dun01", name: "teg_dun01 - Subterranean Guild Dungeon", category: "dungeon" },
    { id: "teg_dun02", name: "teg_dun02 - Subterranean Guild Dungeon", category: "dungeon" },
    { id: "tha_scene01", name: "tha_scene01", category: "other" },
    { id: "tha_t01", name: "tha_t01 - Thanatos Tower - Lower Level", category: "dungeon" },
    { id: "tha_t02", name: "tha_t02 - Thanatos Tower - Lower Level", category: "dungeon" },
    { id: "tha_t03", name: "tha_t03 - Thanatos Tower - Lower Level", category: "dungeon" },
    { id: "tha_t04", name: "tha_t04 - Thanatos Tower - Lower Level", category: "dungeon" },
    { id: "tha_t05", name: "tha_t05 - Thanatos Tower - Upper Level", category: "dungeon" },
    { id: "tha_t06", name: "tha_t06 - Thanatos Tower - Upper Level", category: "dungeon" },
    { id: "tha_t07", name: "tha_t07 - Thanatos Tower - Upper Level", category: "dungeon" },
    { id: "tha_t08", name: "tha_t08 - Thanatos Tower - Upper Level", category: "dungeon" },
    { id: "tha_t09", name: "tha_t09 - Thanatos Tower - Upper Level", category: "dungeon" },
    { id: "tha_t10", name: "tha_t10 - Thanatos Tower - Upper Level", category: "dungeon" },
    { id: "tha_t11", name: "tha_t11 - Thanatos Tower - Upper Level", category: "dungeon" },
    { id: "tha_t12", name: "tha_t12 - Thanatos Tower - Upper Level", category: "dungeon" },
    { id: "thana_boss", name: "thana_boss - Thanatos Tower - Unknown Area", category: "dungeon" },
    { id: "thana_step", name: "thana_step - Thanatos Tower - Upper Level", category: "dungeon" },
    { id: "thor_camp", name: "thor_camp - Thor Volcano Camp", category: "other" },
    { id: "thor_v01", name: "thor_v01 - Thor Volcano Dungeon", category: "dungeon" },
    { id: "thor_v02", name: "thor_v02 - Thor Volcano Dungeon", category: "dungeon" },
    { id: "thor_v03", name: "thor_v03 - Thor Volcano Dungeon", category: "dungeon" },
    { id: "tra_fild", name: "tra_fild - Prontera Training Ground", category: "other" },
    { id: "treasure_n1", name: "treasure_n1 - Izlude wreck 1st floor", category: "dungeon" },
    { id: "treasure_n2", name: "treasure_n2 - Izlude wreck 2nd floor", category: "dungeon" },
    { id: "treasure01", name: "treasure01 - Sunken Ship", category: "dungeon" },
    { id: "treasure02", name: "treasure02 - Sunken Ship", category: "dungeon" },
    { id: "tur_d03_i", name: "tur_d03_i - Lonesome Good Turtles Village", category: "city" },
    { id: "tur_d04_i", name: "tur_d04_i - Gloomy Turtle Palace", category: "city" },
    { id: "tur_dun01", name: "tur_dun01 - Turtle Island", category: "dungeon" },
    { id: "tur_dun02", name: "tur_dun02 - Turtle Island Dungeon", category: "dungeon" },
    { id: "tur_dun03", name: "tur_dun03 - Good Turtles Village", category: "dungeon" },
    { id: "tur_dun04", name: "tur_dun04 - Turtle Palace", category: "dungeon" },
    { id: "tur_dun05", name: "tur_dun05 - Underground swamp zone", category: "dungeon" },
    { id: "tur_dun06", name: "tur_dun06 - Underground swamp zone", category: "dungeon" },
    { id: "turbo_room", name: "turbo_room - Waiting Room", category: "instance" },
    { id: "um_dun01", name: "um_dun01 - Carpenter's Shop in the Tree", category: "dungeon" },
    { id: "um_dun02", name: "um_dun02 - Passage to a Foreign World", category: "dungeon" },
    { id: "um_fild01", name: "um_fild01 - Luluka Forest", category: "field" },
    { id: "um_fild02", name: "um_fild02 - Hoomga Forest", category: "field" },
    { id: "um_fild03", name: "um_fild03 - Kalala Swamp", category: "field" },
    { id: "um_fild04", name: "um_fild04 - Hoomga Jungle", category: "field" },
    { id: "um_in", name: "um_in - Inside Umbala", category: "indoor" },
    { id: "umbala", name: "umbala - Wootan Tribe's Village, Umbala", category: "city" },
    { id: "un_bk_q", name: "un_bk_q - Under Bunker", category: "other" },
    { id: "un_bunker", name: "un_bunker - Under Bunker", category: "other" },
    { id: "un_myst", name: "un_myst - Under Tunnel", category: "other" },
    { id: "valkyrie", name: "valkyrie - Valkyrie Hall, the Hall of Honor", category: "other" },
    { id: "ve_fild01", name: "ve_fild01 - Veins Field", category: "field" },
    { id: "ve_fild02", name: "ve_fild02 - Veins Field", category: "field" },
    { id: "ve_fild03", name: "ve_fild03 - Veins Field", category: "field" },
    { id: "ve_fild04", name: "ve_fild04 - Veins Field", category: "field" },
    { id: "ve_fild05", name: "ve_fild05 - Veins Field", category: "field" },
    { id: "ve_fild06", name: "ve_fild06 - Veins Field", category: "field" },
    { id: "ve_fild07", name: "ve_fild07 - Veins Field", category: "field" },
    { id: "ve_in", name: "ve_in - Inside Veins", category: "indoor" },
    { id: "ve_in02", name: "ve_in02 - Inside Veins", category: "indoor" },
    { id: "veins", name: "veins - Veins, the Canyon Village", category: "city" },
    { id: "ver_eju", name: "ver_eju - Yuperos Eastern Ruin", category: "other" },
    { id: "ver_tunn", name: "ver_tunn - Verus Outter tunnel", category: "other" },
    { id: "verus01", name: "verus01 - Lab-OPTATIO", category: "other" },
    { id: "verus02", name: "verus02 - R&D-WISH", category: "other" },
    { id: "verus03", name: "verus03 - Verus Center Square", category: "other" },
    { id: "verus04", name: "verus04 - Verus Findspot", category: "other" },
    { id: "vis_h01", name: "vis_h01 - Corridor of Phantoms Floor 1", category: "other" },
    { id: "vis_h02", name: "vis_h02 - Corridor of Phantoms Floor 2", category: "other" },
    { id: "vis_h03", name: "vis_h03 - Corridor of Phantoms Floor 3", category: "other" },
    { id: "vis_h04", name: "vis_h04 - Corridor of Phantoms Floor 4", category: "other" },
    { id: "vr_bob", name: "vr_bob - Fantasy Series - Today's Table", category: "other" },
    { id: "wolfvill", name: "wolfvill - Gray Wolf Village", category: "other" },
    { id: "x_lhz", name: "x_lhz - Lighthalzen of Parallell World", category: "other" },
    { id: "x_prt", name: "x_prt - Prontera of Parallell World", category: "other" },
    { id: "x_prt_evt", name: "x_prt_evt", category: "other" },
    { id: "x_prt_in", name: "x_prt_in", category: "indoor" },
    { id: "x_ra", name: "x_ra - Rachel of Parallell World", category: "other" },
    { id: "xmas", name: "xmas - Lutie, Snow Village", category: "city" },
    { id: "xmas_dun01", name: "xmas_dun01 - Toy Factory Warehouse", category: "dungeon" },
    { id: "xmas_dun02", name: "xmas_dun02 - Toy Monitoring Room", category: "dungeon" },
    { id: "xmas_fild01", name: "xmas_fild01 - Lutie Field", category: "field" },
    { id: "xmas_in", name: "xmas_in - Inside Lutie", category: "indoor" },
    { id: "yggdrasil01", name: "yggdrasil01 - Hvergelmir's Fountain (Trunk of Yggdrasil)", category: "other" },
    { id: "yuno", name: "yuno - Juno, the capital of Schwarzwald Republic", category: "city" },
    { id: "yuno_fild01", name: "yuno_fild01 - Border Posts", category: "field" },
    { id: "yuno_fild02", name: "yuno_fild02 - Kiel Hyre's Cottage", category: "field" },
    { id: "yuno_fild03", name: "yuno_fild03 - El Mes Plateau", category: "field" },
    { id: "yuno_fild04", name: "yuno_fild04 - El Mes Plateau", category: "field" },
    { id: "yuno_fild05", name: "yuno_fild05 - El Mes Plateau", category: "field" },
    { id: "yuno_fild06", name: "yuno_fild06 - El Mes Plateau", category: "field" },
    { id: "yuno_fild07", name: "yuno_fild07 - El Mes Gorge (Valley of Abyss)", category: "field" },
    { id: "yuno_fild08", name: "yuno_fild08 - Kiel Hyre's Academy", category: "field" },
    { id: "yuno_fild09", name: "yuno_fild09 - Schwaltzwald Guards Camp", category: "field" },
    { id: "yuno_fild10", name: "yuno_fild10 - Juno Field", category: "field" },
    { id: "yuno_fild11", name: "yuno_fild11 - Juno Field", category: "field" },
    { id: "yuno_fild12", name: "yuno_fild12 - Border Checkpoint", category: "field" },
    { id: "yuno_in01", name: "yuno_in01 - Inside Juno", category: "indoor" },
    { id: "yuno_in02", name: "yuno_in02 - Inside the Sage Castle", category: "indoor" },
    { id: "yuno_in03", name: "yuno_in03 - Inside Juno", category: "indoor" },
    { id: "yuno_in04", name: "yuno_in04 - Republic Library", category: "indoor" },
    { id: "yuno_in05", name: "yuno_in05 - Power Plant of Ymir's Heart", category: "indoor" },
    { id: "yuno_pre", name: "yuno_pre - Schwaltzvalt Government Buildings", category: "city" },
    { id: "alberta@classic", name: "alberta - Alberta (Pre-Renewal)", category: "city", era: "classic" },
    { id: "alde_gld@classic", name: "alde_gld - Luina the satellite of Al De Baran (Pre-Renewal)", category: "castle", era: "classic" },
    { id: "aru_gld@classic", name: "aru_gld - Valfreyja (Pre-Renewal)", category: "castle", era: "classic" },
    { id: "bat_c01@classic", name: "bat_c01 - Krieger von Midgards (Pre-Renewal)", category: "instance", era: "classic" },
    { id: "bra_in01@classic", name: "bra_in01 - Inside Brasilis (Pre-Renewal)", category: "indoor", era: "classic" },
    { id: "brasilis@classic", name: "brasilis - Brasilis (Pre-Renewal)", category: "city", era: "classic" },
    { id: "cmd_fild08@classic", name: "cmd_fild08 - Fortress Saint Darmain (East) (Pre-Renewal)", category: "field", era: "classic" },
    { id: "ein_fild01@classic", name: "ein_fild01 - Einbroch Field (Pre-Renewal)", category: "field", era: "classic" },
    { id: "gl_cas02@classic", name: "gl_cas02 - Glast Heim 2f (Pre-Renewal)", category: "castle", era: "classic" },
    { id: "iz_dun03@classic", name: "iz_dun03 - Undersea Tunnel (Pre-Renewal)", category: "dungeon", era: "classic" },
    { id: "izlude@classic", name: "izlude - Izlude Town (Pre-Renewal)", category: "city", era: "classic" },
    { id: "manuk@classic", name: "manuk - Manuk (Pre-Renewal)", category: "city", era: "classic" },
    { id: "moc_castle@classic", name: "moc_castle - Morroc Castle (Pre-Renewal)", category: "city", era: "classic" },
    { id: "moc_fild20@classic", name: "moc_fild20 - Sograt Desert - Continental Guard Quarantine (Pre-Renewal)", category: "field", era: "classic" },
    { id: "morocc@classic", name: "morocc - Morroc Town (Pre-Renewal)", category: "city", era: "classic" },
    { id: "prt_fild05@classic", name: "prt_fild05 - Prontera Field (Pre-Renewal)", category: "field", era: "classic" },
    { id: "prt_in@classic", name: "prt_in - Inside Prontera (Pre-Renewal)", category: "indoor", era: "classic" },
    { id: "ra_in01@classic", name: "ra_in01 - Inside Rachel (Pre-Renewal)", category: "indoor", era: "classic" },
    { id: "rachel@classic", name: "rachel - Capital of Arunafeltz States, Rachel (Pre-Renewal)", category: "city", era: "classic" },
    { id: "spl_fild01@classic", name: "spl_fild01 - Splendide Field (Pre-Renewal)", category: "field", era: "classic" },
    { id: "splendide@classic", name: "splendide - Splendide (Pre-Renewal)", category: "city", era: "classic" },
    { id: "ve_fild02@classic", name: "ve_fild02 - Veins Field (Pre-Renewal)", category: "field", era: "classic" },
];
