export type DataType = {
    name: string;
    size?: number;
    terminator?: number;
    vecOf?: string;
};

type OldToken = { name: string } & ({ type: "scope"; end: boolean } | { type: "symbol" } | ({ type: "data-type" } & DataType));

export const oldTokens: Record<number, OldToken> = {
    ["{".charCodeAt(0)]: { name: "{", type: "scope", end: false },
    ["}".charCodeAt(0)]: { name: "}", type: "scope", end: true },
    [0x80]: { name: "error", type: "symbol" },
    [0x81]: { name: "undefined", type: "symbol" },
    [0x82]: { name: "STRING", type: "data-type", terminator: 0 },
    [0x83]: { name: "NUMBER", type: "data-type", size: 4 },
    [0x84]: { name: "INTEGER", type: "data-type", size: 4 },
    [0x85]: { name: "SCENE", type: "symbol" },
    [0x86]: { name: "NAME", type: "symbol" },
    [0x87]: { name: "PARENT", type: "symbol" },
    [0x88]: { name: "ANIMINTERVAL", type: "symbol" },
    [0x89]: { name: "FRAMERATE", type: "symbol" },
    [0x8a]: { name: "AMBIENT", type: "symbol" },
    [0x8b]: { name: "TEXTUREFOLDERS", type: "symbol" },
    [0x8c]: { name: "OBJECT", type: "symbol" },
    [0x8d]: { name: "TRANSFORM", type: "symbol" },
    [0x8e]: { name: "TRANS", type: "symbol" },
    [0x8f]: { name: "ROT", type: "symbol" },
    [0x90]: { name: "SCALE", type: "symbol" },
    [0x91]: { name: "ANIM", type: "symbol" },
    [0x92]: { name: "TARGETANIM", type: "symbol" },
    [0x93]: { name: "CHANNEL", type: "symbol" },
    [0x94]: { name: "XTRANS", type: "symbol" },
    [0x95]: { name: "YTRANS", type: "symbol" },
    [0x96]: { name: "ZTRANS", type: "symbol" },
    [0x97]: { name: "XROT", type: "symbol" },
    [0x98]: { name: "YROT", type: "symbol" },
    [0x99]: { name: "ZROT", type: "symbol" },
    [0x9a]: { name: "XSCALE", type: "symbol" },
    [0x9b]: { name: "YSCALE", type: "symbol" },
    [0x9c]: { name: "ZSCALE", type: "symbol" },
    [0x9d]: { name: "EXTRAPPRE", type: "symbol" },
    [0x9e]: { name: "EXTRAPPOST", type: "symbol" },
    [0x9f]: { name: "INTERP", type: "symbol" },
    [0xa0]: { name: "HERMITE", type: "symbol" },
    [0xa1]: { name: "CONSTANT", type: "symbol" },
    [0xa2]: { name: "CYCLE", type: "symbol" },
    [0xa3]: { name: "OSCILLATE", type: "symbol" },
    [0xa4]: { name: "LINEAR", type: "symbol" },
    [0xa5]: { name: "KEYCOUNT", type: "symbol" },
    [0xa6]: { name: "KEYS", type: "symbol" },
    [0xa7]: { name: "MESH", type: "symbol" },
    [0xa8]: { name: "VERTEXCOUNT", type: "symbol" },
    [0xa9]: { name: "POLYCOUNT", type: "symbol" },
    [0xaa]: { name: "VERTEXPOINTS", type: "symbol" },
    [0xab]: { name: "NORMALS", type: "symbol" },
    [0xac]: { name: "UVCOORDS", type: "symbol" },
    [0xad]: { name: "UVCOORDS2", type: "symbol" },
    [0xae]: { name: "POLYGON", type: "symbol" },
    [0xaf]: { name: "VERTS", type: "symbol" },
    [0xb0]: { name: "SMGROUP", type: "symbol" },
    [0xb1]: { name: "SHADER", type: "symbol" },
    [0xb2]: { name: "TEXTURE", type: "symbol" },
    [0xb3]: { name: "ID", type: "symbol" },
    [0xb4]: { name: "DIFFUSE", type: "symbol" },
    [0xb5]: { name: "SPECULAR", type: "symbol" },
    [0xb6]: { name: "LUMINANCE", type: "symbol" },
    [0xb7]: { name: "BLEND", type: "symbol" },
    [0xb8]: { name: "OPACITY", type: "symbol" },
    [0xb9]: { name: "LIGHT", type: "symbol" },
    [0xba]: { name: "TYPE", type: "symbol" },
    [0xbb]: { name: "DIR", type: "symbol" },
    [0xbc]: { name: "UMBRA", type: "symbol" },
    [0xbd]: { name: "PENUMBRA", type: "symbol" },
    [0xbe]: { name: "COLOR", type: "symbol" },
    [0xbf]: { name: "INTENSITY", type: "symbol" },
    [0xc0]: { name: "OFF", type: "symbol" },
    [0xc1]: { name: "POINT", type: "symbol" },
    [0xc2]: { name: "SPOT", type: "symbol" },
    [0xc3]: { name: "DIRECTIONAL", type: "symbol" },
    [0xc4]: { name: "ATTENSTART", type: "symbol" },
    [0xc5]: { name: "ATTENEND", type: "symbol" },
    [0xc6]: { name: "CAMERA", type: "symbol" },
    [0xc7]: { name: "FOV", type: "symbol" },
    [0xc8]: { name: "NEARCLIP", type: "symbol" },
    [0xc9]: { name: "FARCLIP", type: "symbol" },
    [0xca]: { name: "POS", type: "symbol" },
    [0xcb]: { name: "TARGETPOS", type: "symbol" },
    [0xcc]: { name: "TRUE", type: "symbol" },
    [0xcd]: { name: "FALSE", type: "symbol" },
    [0xce]: { name: "NUMBERLIST", type: "data-type", vecOf: "NUMBER", size: 4 },
    [0xcf]: { name: "BYTE", type: "data-type" },
    [0xd0]: { name: "UNSIGNEDBYTE", type: "data-type" },
    [0xd1]: { name: "WORD", type: "data-type", size: 2 },
    [0xd2]: { name: "UNSIGNEDWORD", type: "data-type", size: 2 },
    [0xd3]: { name: "PARENTID", type: "symbol" },
    [0xd4]: { name: "WEIGHTS", type: "symbol" },
    [0xd5]: { name: "1BONE", type: "symbol" },
    [0xd6]: { name: "2BONE", type: "symbol" },
    [0xd7]: { name: "3BONE", type: "symbol" },
    [0xd8]: { name: "4BONE", type: "symbol" },
    [0xd9]: { name: "BONEMATRIX", type: "symbol" },
    [0xda]: { name: "EXTRAANIMCOUNT", type: "symbol" },
    [0xdb]: { name: "EXTRAINTERVALS", type: "symbol" },
    [0xdc]: { name: "ANIMINDEX", type: "symbol" },
    [0xdd]: { name: "QUATERNION", type: "symbol" },
    [0xde]: { name: "QUATKEYS", type: "symbol" },
    [0xdf]: { name: "EXTRAANIMNAMES", type: "symbol" },
    [0xe0]: { name: "0BONE", type: "symbol" },
    [0xe1]: { name: "EMISSIVE", type: "symbol" },
} as const;

export enum Token {
    PushScope = 0x7b,
    PopScope = 0x7d,
    Error = 0x80,
    Undefined = 0x81,
    String = 0x82,
    Number = 0x83,
    Integer = 0x84,
    Scene = 0x85,
    Name = 0x86,
    Parent = 0x87,
    AnimInterval = 0x88,
    Framerate = 0x89,
    Ambient = 0x8a,
    TextureFolders = 0x8b,
    Object = 0x8c,
    Transform = 0x8d,
    Trans = 0x8e,
    Rot = 0x8f,
    Scale = 0x90,
    Anim = 0x91,
    TargetAnim = 0x92,
    Channel = 0x93,
    TransX = 0x94,
    TransY = 0x95,
    TransZ = 0x96,
    RotX = 0x97,
    RotY = 0x98,
    RotZ = 0x99,
    ScaleX = 0x9a,
    ScaleY = 0x9b,
    ScaleZ = 0x9c,
    ExtrapPre = 0x9d,
    ExtrapPost = 0x9e,
    Interp = 0x9f,
    Hermite = 0xa0,
    Constant = 0xa1,
    Cycle = 0xa2,
    Oscillate = 0xa3,
    Linear = 0xa4,
    KeyCount = 0xa5,
    Keys = 0xa6,
    Mesh = 0xa7,
    VertexCount = 0xa8,
    PolyCount = 0xa9,
    VertexPoints = 0xaa,
    Normals = 0xab,
    UVCoords = 0xac,
    UVCoords2 = 0xad,
    Polygon = 0xae,
    Verts = 0xaf,
    SMGroup = 0xb0,
    Shader = 0xb1,
    Texture = 0xb2,
    ID = 0xb3,
    Diffuse = 0xb4,
    Specular = 0xb5,
    Luminance = 0xb6,
    Blend = 0xb7,
    Opacity = 0xb8,
    Light = 0xb9,
    Type = 0xba,
    Dir = 0xbb,
    Umbra = 0xbc,
    Penumbra = 0xbd,
    Color = 0xbe,
    Intensity = 0xbf,
    Off = 0xc0,
    Point = 0xc1,
    Spot = 0xc2,
    Directional = 0xc3,
    AttenStart = 0xc4,
    AttenEnd = 0xc5,
    Camera = 0xc6,
    Fov = 0xc7,
    NearClip = 0xc8,
    FarClip = 0xc9,
    Pos = 0xca,
    TargetPos = 0xcb,
    True = 0xcc,
    False = 0xcd,
    NumberList = 0xce,
    Byte = 0xcf,
    UnsignedByte = 0xd0,
    Word = 0xd1,
    UnsignedWord = 0xd2,
    ParentID = 0xd3,
    Weights = 0xd4,
    Bone1 = 0xd5,
    Bone2 = 0xd6,
    Bone3 = 0xd7,
    Bone4 = 0xd8,
    BoneMatrix = 0xd9,
    ExtraAnimCount = 0xda,
    ExtraIntervals = 0xdb,
    AnimIndex = 0xdc,
    Quaternion = 0xdd,
    QuatKeys = 0xde,
    ExtraAnimNames = 0xdf,
    Bone0 = 0xe0,
    Emissive = 0xe1,
}
