import {
  HOOD_ID_DAISY_GARDENS,
  HOOD_ID_DONALDS_DOCK,
  HOOD_ID_DONALDS_DREAMLAND,
  HOOD_ID_MINNIES_MELODYLAND,
  HOOD_ID_THE_BRRRGH,
  HOOD_ID_TOONTOWN_CENTRAL,
} from "./Globals";
import {
  type IdleAnimDef,
  InteractiveAnimatedProp,
} from "./InteractiveAnimatedProp";

export class HydrantInteractiveProp extends InteractiveAnimatedProp {
  protected override _hoodToIdles: Record<number, IdleAnimDef[]> = {
    [HOOD_ID_TOONTOWN_CENTRAL]: [
      {
        name: "tt_a_ara_ttc_hydrant_idle0",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_ttc_hydrant_idle2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_ttc_hydrant_idle1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_ttc_hydrant_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_DONALDS_DOCK]: [
      {
        name: "tt_a_ara_ttc_hydrant_idle0",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_ttc_hydrant_idle2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_ttc_hydrant_idle1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_ttc_hydrant_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_MINNIES_MELODYLAND]: [
      {
        name: "tt_a_ara_mml_hydrant_idle0",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: "tt_a_ara_mml_hydrant_idle0settle",
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_mml_hydrant_idle2",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: "tt_a_ara_mml_hydrant_idle2settle",
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_mml_hydrant_idle1",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: "tt_a_ara_mml_hydrant_idle1settle",
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_mml_hydrant_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_DAISY_GARDENS]: [
      {
        name: "tt_a_ara_dga_hydrant_idle0",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: "tt_a_ara_dga_hydrant_idle0settle",
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_dga_hydrant_idleLook1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_dga_hydrant_idleSneeze2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_dga_hydrant_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_THE_BRRRGH]: [
      {
        name: "tt_a_ara_tbr_hydrant_idleShiver1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_tbr_hydrant_idleRubNose0",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_tbr_hydrant_idleSneeze2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_tbr_hydrant_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_DONALDS_DREAMLAND]: [
      {
        name: "tt_a_ara_ddl_hydrant_idle0",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: null,
        minPauseTime: 0,
        maxPauseTime: 0,
      },
      {
        name: "tt_a_ara_ddl_hydrant_idle1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 0,
        maxPauseTime: 0,
      },
      {
        name: "tt_a_ara_ddl_hydrant_idle2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 0,
        maxPauseTime: 0,
      },
      {
        name: "tt_a_ara_ddl_hydrant_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 0,
        maxPauseTime: 0,
      },
    ],
  };
}
