import {
  HOOD_ID_DAISY_GARDENS,
  HOOD_ID_DONALDS_DOCK,
  HOOD_ID_DONALDS_DREAMLAND,
  HOOD_ID_MINNIES_MELODYLAND,
  HOOD_ID_THE_BRRRGH,
  HOOD_ID_TOONTOWN_CENTRAL,
} from "../Globals";
import {
  type IdleAnimDef,
  InteractiveAnimatedProp,
} from "./InteractiveAnimatedProp";

export class MailboxInteractiveProp extends InteractiveAnimatedProp {
  protected override _hoodToIdles: Record<number, IdleAnimDef[]> = {
    [HOOD_ID_TOONTOWN_CENTRAL]: [
      {
        name: "tt_a_ara_ttc_mailbox_idle0",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: "tt_a_ara_ttc_mailbox_idle0settle",
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_ttc_mailbox_idleTake2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_ttc_mailbox_idleLook1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_ttc_mailbox_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_DONALDS_DOCK]: [
      {
        name: "tt_a_ara_dod_mailbox_idle0",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: "tt_a_ara_dod_mailbox_idle0settle",
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_dod_mailbox_idle2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_dod_mailbox_idle1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_dod_mailbox_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_MINNIES_MELODYLAND]: [
      {
        name: "tt_a_ara_mml_mailbox_idle0",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: "tt_a_ara_mml_mailbox_idle0settle",
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_mml_mailbox_idleTake1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_mml_mailbox_idleLook2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_mml_mailbox_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_DAISY_GARDENS]: [
      {
        name: "tt_a_ara_dga_mailbox_idle0",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: "tt_a_ara_dga_mailbox_idle0settle",
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_dga_mailbox_idleTake1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_dga_mailbox_idleLook2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_dga_mailbox_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_THE_BRRRGH]: [
      {
        name: "tt_a_ara_tbr_mailbox_idleShiver1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_tbr_mailbox_idleSneeze2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_tbr_mailbox_idleSpin0",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
      {
        name: "tt_a_ara_tbr_mailbox_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 3,
        maxPauseTime: 10,
      },
    ],
    [HOOD_ID_DONALDS_DREAMLAND]: [
      {
        name: "tt_a_ara_ddl_mailbox_idleSleep0",
        minLoops: 3,
        maxLoops: 10,
        settleAnim: null,
        minPauseTime: 0,
        maxPauseTime: 0,
      },
      {
        name: "tt_a_ara_ddl_mailbox_idleShake2",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 0,
        maxPauseTime: 0,
      },
      {
        name: "tt_a_ara_ddl_mailbox_idleSnore1",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 0,
        maxPauseTime: 0,
      },
      {
        name: "tt_a_ara_ddl_mailbox_idleAwesome3",
        minLoops: 1,
        maxLoops: 1,
        settleAnim: null,
        minPauseTime: 0,
        maxPauseTime: 0,
      },
    ],
  };
}
