export interface SceneEntry {
    id: string;
    name: string;
    geometry: string;
    libraries: string[];
    placements: string;
}

export const SCENES: (string | SceneEntry)[] = [
    "Bada Bing!",
    {
        id: "p_0bing1_hub",
        name: "Bada Bing! Interior 1 (A)",
        geometry: "p_0bing1_hub/p_0Bing1_Hub.EGP2",
        libraries: ["p_0bing1_hub/p_0Bing1_Hub.SGP2", "p_cbing1/p_cBing1.SGP2", "p_1bing1_hub/p_1Bing1_Hub.SGP2", "p_2bing1_hub/p_2Bing1_Hub.SGP2", "p_3bing1_hub/p_3Bing1_Hub.SGP2", "p_4bing1_hub/p_4Bing1_Hub.SGP2", "p_5bing1_hub/p_5Bing1_Hub.SGP2", "p_6bing1_hub/p_6Bing1_Hub.SGP2", "p_7bing1_hub/p_7Bing1_Hub.SGP2", "p_8bing1_hub/p_8Bing1_Hub.SGP2", "p_9bing1_hub/p_9Bing1_Hub.SGP2", "p_abing1_hub/p_aBing1_Hub.SGP2", "p_bbing1_hub/p_bBing1_Hub.SGP2", "p_xbing1/p_xBing1.SGP2"],
        placements: "p_cbing1/p_cBing1.OLV",
    },
    {
        id: "p_1bing1_hub",
        name: "Bada Bing! Interior 1 (B)",
        geometry: "p_1bing1_hub/p_1Bing1_Hub.EGP2",
        libraries: ["p_1bing1_hub/p_1Bing1_Hub.SGP2", "p_cbing1/p_cBing1.SGP2", "p_0bing1_hub/p_0Bing1_Hub.SGP2", "p_2bing1_hub/p_2Bing1_Hub.SGP2", "p_3bing1_hub/p_3Bing1_Hub.SGP2", "p_4bing1_hub/p_4Bing1_Hub.SGP2", "p_5bing1_hub/p_5Bing1_Hub.SGP2", "p_6bing1_hub/p_6Bing1_Hub.SGP2", "p_7bing1_hub/p_7Bing1_Hub.SGP2", "p_8bing1_hub/p_8Bing1_Hub.SGP2", "p_9bing1_hub/p_9Bing1_Hub.SGP2", "p_abing1_hub/p_aBing1_Hub.SGP2", "p_bbing1_hub/p_bBing1_Hub.SGP2", "p_xbing1/p_xBing1.SGP2"],
        placements: "p_cbing1/p_cBing1.OLV",
    },
    {
        id: "p_0bing2_hub",
        name: "Bada Bing! Interior 2 (A)",
        geometry: "p_0bing2_hub/p_0Bing2_Hub.EGP2",
        libraries: ["p_0bing2_hub/p_0Bing2_Hub.SGP2", "p_cbing2/p_cBing2.SGP2", "p_1bing2_hub/p_1Bing2_Hub.SGP2", "p_2bing2_hub/p_2Bing2_Hub.SGP2", "p_3bing2_hub/p_3Bing2_Hub.SGP2", "p_4bing2_hub/p_4Bing2_Hub.SGP2", "p_5bing2_hub/p_5Bing2_Hub.SGP2", "p_6bing2_hub/p_6Bing2_Hub.SGP2", "p_7bing2_hub/p_7Bing2_Hub.SGP2", "p_8bing2_hub/p_8Bing2_Hub.SGP2", "p_9bing2_hub/p_9Bing2_Hub.SGP2", "p_abing2_hub/p_aBing2_Hub.SGP2", "p_bbing2_hub/p_bBing2_Hub.SGP2", "p_xbing2/p_xBing2.SGP2"],
        placements: "p_cbing2/p_cBing2.OLV",
    },
    {
        id: "p_1bing2_hub",
        name: "Bada Bing! Interior 2 (B)",
        geometry: "p_1bing2_hub/p_1Bing2_Hub.EGP2",
        libraries: ["p_1bing2_hub/p_1Bing2_Hub.SGP2", "p_cbing2/p_cBing2.SGP2", "p_0bing2_hub/p_0Bing2_Hub.SGP2", "p_2bing2_hub/p_2Bing2_Hub.SGP2", "p_3bing2_hub/p_3Bing2_Hub.SGP2", "p_4bing2_hub/p_4Bing2_Hub.SGP2", "p_5bing2_hub/p_5Bing2_Hub.SGP2", "p_6bing2_hub/p_6Bing2_Hub.SGP2", "p_7bing2_hub/p_7Bing2_Hub.SGP2", "p_8bing2_hub/p_8Bing2_Hub.SGP2", "p_9bing2_hub/p_9Bing2_Hub.SGP2", "p_abing2_hub/p_aBing2_Hub.SGP2", "p_bbing2_hub/p_bBing2_Hub.SGP2", "p_xbing2/p_xBing2.SGP2"],
        placements: "p_cbing2/p_cBing2.OLV",
    },
    {
        id: "p_0bing3_hub",
        name: "Bada Bing! Exterior (A)",
        geometry: "p_0bing3_hub/p_0Bing3_Hub.EGP2",
        libraries: ["p_0bing3_hub/p_0Bing3_Hub.SGP2", "p_cbing3/p_cBing3.SGP2", "p_1bing3_hub/p_1Bing3_Hub.SGP2", "p_2bing3_hub/p_2Bing3_Hub.SGP2", "p_3bing3_hub/p_3Bing3_Hub.SGP2", "p_4bing3_hub/p_4Bing3_Hub.SGP2", "p_5bing3_hub/p_5Bing3_Hub.SGP2", "p_6bing3_hub/p_6Bing3_Hub.SGP2", "p_7bing3_hub/p_7Bing3_Hub.SGP2", "p_8bing3_hub/p_8Bing3_Hub.SGP2", "p_9bing3_hub/p_9Bing3_Hub.SGP2", "p_abing3_hub/p_aBing3_Hub.SGP2", "p_bbing3_hub/p_bBing3_Hub.SGP2", "p_xbing3/p_xBing3.SGP2"],
        placements: "p_cbing3/p_cBing3.OLV",
    },
    {
        id: "p_1bing3_hub",
        name: "Bada Bing! Exterior (B)",
        geometry: "p_1bing3_hub/p_1Bing3_Hub.EGP2",
        libraries: ["p_1bing3_hub/p_1Bing3_Hub.SGP2", "p_cbing3/p_cBing3.SGP2", "p_0bing3_hub/p_0Bing3_Hub.SGP2", "p_2bing3_hub/p_2Bing3_Hub.SGP2", "p_3bing3_hub/p_3Bing3_Hub.SGP2", "p_4bing3_hub/p_4Bing3_Hub.SGP2", "p_5bing3_hub/p_5Bing3_Hub.SGP2", "p_6bing3_hub/p_6Bing3_Hub.SGP2", "p_7bing3_hub/p_7Bing3_Hub.SGP2", "p_8bing3_hub/p_8Bing3_Hub.SGP2", "p_9bing3_hub/p_9Bing3_Hub.SGP2", "p_abing3_hub/p_aBing3_Hub.SGP2", "p_bbing3_hub/p_bBing3_Hub.SGP2", "p_xbing3/p_xBing3.SGP2"],
        placements: "p_cbing3/p_cBing3.OLV",
    },
    "Body Dump",
    {
        id: "p_cbodydump",
        name: "Body Dump",
        geometry: "p_cbodydump/p_BodyDump.EGP2",
        libraries: ["p_cbodydump/p_cBodyDump.SGP2", "p_cbodydump/p_cBodyDump.SGP2", "p_bbodydump/p_bBodyDump.SGP2"],
        placements: "p_cbodydump/p_cBodyDump.OLV",
    },
    "Shapiro's Gym",
    {
        id: "p_cgym1",
        name: "Gym 1",
        geometry: "p_cgym1/p_Gym1.EGP2",
        libraries: ["p_cgym1/p_cGym1.SGP2", "p_cgym1/p_cGym1.SGP2", "p_bgym1/p_bGym1.SGP2"],
        placements: "p_cgym1/p_cGym1.OLV",
    },
    {
        id: "p_cgym2",
        name: "Gym 2",
        geometry: "p_cgym2/p_Gym2.EGP2",
        libraries: ["p_cgym2/p_cGym2.SGP2", "p_cgym2/p_cGym2.SGP2", "p_bgym2/p_bGym2.SGP2"],
        placements: "p_cgym2/p_cGym2.OLV",
    },
    {
        id: "p_cgym3",
        name: "Gym 3",
        geometry: "p_cgym3/p_Gym3.EGP2",
        libraries: ["p_cgym3/p_cGym3.SGP2", "p_cgym3/p_cGym3.SGP2", "p_bgym3/p_bGym3.SGP2"],
        placements: "p_cgym3/p_cGym3.OLV",
    },
    {
        id: "p_cgymnight",
        name: "Gym at Night",
        geometry: "p_cgymnight/p_GymNight.EGP2",
        libraries: ["p_cgymnight/p_cGymNight.SGP2", "p_cgymnight/p_cGymNight.SGP2", "p_bgymnight/p_bGymNight.SGP2"],
        placements: "p_cgymnight/p_cGymNight.OLV",
    },
    "Satriale's",
    {
        id: "p_0satrialesexterior_hub",
        name: "Satriale's Exterior",
        geometry: "p_0satrialesexterior_hub/p_0SatrialesExterior_Hub.EGP2",
        libraries: ["p_0satrialesexterior_hub/p_0SatrialesExterior_Hub.SGP2", "p_csatrialesexterior/p_cSatrialesExterior.SGP2", "p_1satrialesexterior_hub/p_1SatrialesExterior_Hub.SGP2", "p_xsatrialesexterior/p_xSatrialesExterior.SGP2"],
        placements: "p_csatrialesexterior/p_cSatrialesExterior.OLV",
    },
    {
        id: "p_0satriales_hub",
        name: "Satriale's",
        geometry: "p_0satriales_hub/p_0Satriales_Hub.EGP2",
        libraries: ["p_0satriales_hub/p_0Satriales_Hub.SGP2", "p_csatriales/p_cSatriales.SGP2", "p_1satriales_hub/p_1Satriales_Hub.SGP2", "p_xsatriales/p_xSatriales.SGP2"],
        placements: "p_csatriales/p_cSatriales.OLV",
    },
    "Vesuvio",
    {
        id: "p_cvesuviosexterior",
        name: "Vesuvio Exterior",
        geometry: "p_cvesuviosexterior/p_VesuviosExterior.EGP2",
        libraries: ["p_cvesuviosexterior/p_cVesuviosExterior.SGP2", "p_cvesuviosexterior/p_cVesuviosExterior.SGP2", "p_bvesuviosexterior/p_bVesuviosExterior.SGP2"],
        placements: "p_cvesuviosexterior/p_cVesuviosExterior.OLV",
    },
    {
        id: "p_0vesuvio2_hub",
        name: "Vesuvio (A)",
        geometry: "p_0vesuvio2_hub/p_0VESUVIO2_Hub.EGP2",
        libraries: ["p_0vesuvio2_hub/p_0VESUVIO2_Hub.SGP2", "p_cvesuvio2/p_cVESUVIO2.SGP2", "p_1vesuvio2_hub/p_1VESUVIO2_Hub.SGP2", "p_2vesuvio2_hub/p_2VESUVIO2_Hub.SGP2", "p_xvesuvio2/p_xVESUVIO2.SGP2"],
        placements: "p_cvesuvio2/p_cVESUVIO2.OLV",
    },
    {
        id: "p_2vesuvio2_hub",
        name: "Vesuvio (B)",
        geometry: "p_2vesuvio2_hub/p_2VESUVIO2_Hub.EGP2",
        libraries: ["p_2vesuvio2_hub/p_2VESUVIO2_Hub.SGP2", "p_cvesuvio2/p_cVESUVIO2.SGP2", "p_0vesuvio2_hub/p_0VESUVIO2_Hub.SGP2", "p_1vesuvio2_hub/p_1VESUVIO2_Hub.SGP2", "p_xvesuvio2/p_xVESUVIO2.SGP2"],
        placements: "p_cvesuvio2/p_cVESUVIO2.OLV",
    },
    "AJ's Rave",
    {
        id: "p_0rave1_hub",
        name: "Rave 1",
        geometry: "p_0rave1_hub/p_0Rave1_Hub.EGP2",
        libraries: ["p_0rave1_hub/p_0Rave1_Hub.SGP2", "p_crave1/p_cRave1.SGP2", "p_1rave1_hub/p_1Rave1_Hub.SGP2", "p_xrave1/p_xRave1.SGP2"],
        placements: "p_crave1/p_cRave1.OLV",
    },
    {
        id: "p_crave2",
        name: "Rave 2",
        geometry: "p_crave2/p_rave2.EGP2",
        libraries: ["p_crave2/p_crave2.SGP2", "p_crave2/p_crave2.SGP2", "p_brave2/p_brave2.SGP2"],
        placements: "p_crave2/p_crave2.OLV",
    },
    {
        id: "p_crave3",
        name: "Rave 3",
        geometry: "p_crave3/p_Rave3.EGP2",
        libraries: ["p_crave3/p_cRave3.SGP2", "p_crave3/p_cRave3.SGP2", "p_brave3/p_bRave3.SGP2", "p_srave3/p_sRave3.SGP2"],
        placements: "p_crave3/p_cRave3.OLV",
    },
    {
        id: "p_crave4",
        name: "Rave 4",
        geometry: "p_crave4/p_Rave4.EGP2",
        libraries: ["p_crave4/p_cRave4.SGP2", "p_crave4/p_cRave4.SGP2", "p_brave4/p_bRave4.SGP2"],
        placements: "p_crave4/p_cRave4.OLV",
    },
    "Chop Shop",
    {
        id: "p_cchop1",
        name: "Chop Shop 1",
        geometry: "p_cchop1/p_Chop1.EGP2",
        libraries: ["p_cchop1/p_cChop1.SGP2", "p_cchop1/p_cChop1.SGP2", "p_bchop1/p_bChop1.SGP2"],
        placements: "p_cchop1/p_cChop1.OLV",
    },
    {
        id: "p_cchop2",
        name: "Chop Shop 2",
        geometry: "p_cchop2/p_Chop2.EGP2",
        libraries: ["p_cchop2/p_cChop2.SGP2", "p_cchop2/p_cChop2.SGP2", "p_bchop2/p_bChop2.SGP2"],
        placements: "p_cchop2/p_cChop2.OLV",
    },
    {
        id: "p_cchop3",
        name: "Chop Shop 3",
        geometry: "p_cchop3/p_Chop3.EGP2",
        libraries: ["p_cchop3/p_cChop3.SGP2", "p_cchop3/p_cChop3.SGP2", "p_bchop3/p_bChop3.SGP2"],
        placements: "p_cchop3/p_cChop3.OLV",
    },
    "Cherry Hill Studio",
    {
        id: "p_ccherryhill1",
        name: "Cherry Hill 1",
        geometry: "p_ccherryhill1/p_CherryHill1.EGP2",
        libraries: ["p_ccherryhill1/p_cCherryHill1.SGP2", "p_ccherryhill1/p_cCherryHill1.SGP2", "p_bcherryhill1/p_bCherryHill1.SGP2"],
        placements: "p_ccherryhill1/p_cCherryHill1.OLV",
    },
    {
        id: "p_ccherryhill2",
        name: "Cherry Hill 2",
        geometry: "p_ccherryhill2/p_CherryHill2.EGP2",
        libraries: ["p_ccherryhill2/p_cCherryHill2.SGP2", "p_ccherryhill2/p_cCherryHill2.SGP2", "p_bcherryhill2/p_bCherryHill2.SGP2"],
        placements: "p_ccherryhill2/p_cCherryHill2.OLV",
    },
    "Hospital",
    {
        id: "p_0hospital1_hub",
        name: "Hospital 1",
        geometry: "p_0hospital1_hub/p_0Hospital1_Hub.EGP2",
        libraries: ["p_0hospital1_hub/p_0Hospital1_Hub.SGP2", "p_chospital1/p_cHospital1.SGP2", "p_1hospital1_hub/p_1Hospital1_Hub.SGP2", "p_xhospital1/p_xHospital1.SGP2"],
        placements: "p_chospital1/p_cHospital1.OLV",
    },
    {
        id: "p_chospital2",
        name: "Hospital 2",
        geometry: "p_chospital2/p_Hospital2.EGP2",
        libraries: ["p_chospital2/p_cHospital2.SGP2", "p_chospital2/p_cHospital2.SGP2", "p_bhospital2/p_bHospital2.SGP2"],
        placements: "p_chospital2/p_cHospital2.OLV",
    },
    {
        id: "p_chospital3",
        name: "Hospital 3",
        geometry: "p_chospital3/p_Hospital3.EGP2",
        libraries: ["p_chospital3/p_cHospital3.SGP2", "p_chospital3/p_cHospital3.SGP2", "p_bhospital3/p_bHospital3.SGP2"],
        placements: "p_chospital3/p_cHospital3.OLV",
    },
    "Docks",
    {
        id: "p_cdocks1",
        name: "Docks 1",
        geometry: "p_cdocks1/p_Docks1.EGP2",
        libraries: ["p_cdocks1/p_cDocks1.SGP2", "p_cdocks1/p_cDocks1.SGP2", "p_bdocks1/p_bDocks1.SGP2"],
        placements: "p_cdocks1/p_cDocks1.OLV",
    },
    {
        id: "p_cdocks2",
        name: "Docks 2",
        geometry: "p_cdocks2/p_Docks2.EGP2",
        libraries: ["p_cdocks2/p_cDocks2.SGP2", "p_cdocks2/p_cDocks2.SGP2", "p_bdocks2/p_bDocks2.SGP2"],
        placements: "p_cdocks2/p_cDocks2.OLV",
    },
    {
        id: "p_cdocks3",
        name: "Docks 3",
        geometry: "p_cdocks3/p_Docks3.EGP2",
        libraries: ["p_cdocks3/p_cDocks3.SGP2", "p_cdocks3/p_cDocks3.SGP2", "p_bdocks3/p_bDocks3.SGP2"],
        placements: "p_cdocks3/p_cDocks3.OLV",
    },
    {
        id: "p_cdocks4",
        name: "Docks 4",
        geometry: "p_cdocks4/p_Docks4.EGP2",
        libraries: ["p_cdocks4/p_cDocks4.SGP2", "p_cdocks4/p_cDocks4.SGP2", "p_bdocks4/p_bDocks4.SGP2"],
        placements: "p_cdocks4/p_cDocks4.OLV",
    },
    "Casino",
    {
        id: "p_ccasino1",
        name: "Casino 1",
        geometry: "p_ccasino1/p_casino1.EGP2",
        libraries: ["p_ccasino1/p_ccasino1.SGP2", "p_ccasino1/p_ccasino1.SGP2", "p_bcasino1/p_bcasino1.SGP2", "p_rcasino1/p_rcasino1.SGP2"],
        placements: "p_ccasino1/p_ccasino1.OLV",
    },
    {
        id: "p_ccasino2",
        name: "Casino 2",
        geometry: "p_ccasino2/p_casino2.EGP2",
        libraries: ["p_ccasino2/p_ccasino2.SGP2", "p_ccasino2/p_ccasino2.SGP2", "p_bcasino2/p_bcasino2.SGP2"],
        placements: "p_ccasino2/p_ccasino2.OLV",
    },
    {
        id: "p_ccasino3",
        name: "Casino 3",
        geometry: "p_ccasino3/p_Casino3.EGP2",
        libraries: ["p_ccasino3/p_cCasino3.SGP2", "p_ccasino3/p_cCasino3.SGP2", "p_bcasino3/p_bCasino3.SGP2"],
        placements: "p_ccasino3/p_cCasino3.OLV",
    },
    "Reggie's Apartment",
    {
        id: "p_creggiesapt1",
        name: "Reggie's Apartment 1",
        geometry: "p_creggiesapt1/p_reggiesapt1.EGP2",
        libraries: ["p_creggiesapt1/p_creggiesapt1.SGP2", "p_creggiesapt1/p_creggiesapt1.SGP2", "p_breggiesapt1/p_breggiesapt1.SGP2"],
        placements: "p_creggiesapt1/p_creggiesapt1.OLV",
    },
    {
        id: "p_creggiesapt2",
        name: "Reggie's Apartment 2",
        geometry: "p_creggiesapt2/p_reggiesapt2.EGP2",
        libraries: ["p_creggiesapt2/p_creggiesapt2.SGP2", "p_creggiesapt2/p_creggiesapt2.SGP2", "p_breggiesapt2/p_breggiesapt2.SGP2"],
        placements: "p_creggiesapt2/p_creggiesapt2.OLV",
    },
    "Law Offices",
    {
        id: "p_claw1",
        name: "Law Offices 1",
        geometry: "p_claw1/p_Law1.EGP2",
        libraries: ["p_claw1/p_cLaw1.SGP2", "p_claw1/p_cLaw1.SGP2", "p_blaw1/p_bLaw1.SGP2"],
        placements: "p_claw1/p_cLaw1.OLV",
    },
    {
        id: "p_claw2",
        name: "Law Offices 2",
        geometry: "p_claw2/p_Law2.EGP2",
        libraries: ["p_claw2/p_cLaw2.SGP2", "p_claw2/p_cLaw2.SGP2", "p_blaw2/p_bLaw2.SGP2"],
        placements: "p_claw2/p_cLaw2.OLV",
    },
    {
        id: "p_claw3",
        name: "Law Offices 3",
        geometry: "p_claw3/p_Law3.EGP2",
        libraries: ["p_claw3/p_cLaw3.SGP2", "p_claw3/p_cLaw3.SGP2", "p_blaw3/p_bLaw3.SGP2"],
        placements: "p_claw3/p_cLaw3.OLV",
    },
];
