
import * as Viewer from '../viewer';
import { GfxDevice, GfxHostAccessPass } from '../gfx/platform/GfxPlatform';
import Progressable from '../Progressable';
import { fetchData } from '../fetch';
import * as MapShape from './map_shape';
import * as Tex from './tex';
import { BasicRendererHelper } from '../oot3d/render';
import { PaperMario64TextureHolder, PaperMario64ModelTreeRenderer, BackgroundBillboardRenderer } from './render';
import ArrayBufferSlice from '../ArrayBufferSlice';
import { makeClearRenderPassDescriptor } from '../gfx/helpers/RenderTargetHelpers';
import { OpaqueBlack } from '../Color';

const pathBase = `pm64`;

class PaperMario64Renderer extends BasicRendererHelper {
    public textureHolder = new PaperMario64TextureHolder();
    public modelTreeRenderers: PaperMario64ModelTreeRenderer[] = [];
    public bgTextureRenderer: BackgroundBillboardRenderer | null = null;

    constructor() {
        super();
        this.clearRenderPassDescriptor = makeClearRenderPassDescriptor(true, OpaqueBlack);
    }

    public prepareToRender(hostAccessPass: GfxHostAccessPass, viewerInput: Viewer.ViewerRenderInput): void {
        if (this.bgTextureRenderer !== null)
            this.bgTextureRenderer.prepareToRender(hostAccessPass, viewerInput);
        for (let i = 0; i < this.modelTreeRenderers.length; i++)
            this.modelTreeRenderers[i].prepareToRender(hostAccessPass, viewerInput);
    }

    public destroy(device: GfxDevice): void {
        super.destroy(device);
        this.textureHolder.destroy(device);
        if (this.bgTextureRenderer !== null)
            this.bgTextureRenderer.destroy(device);
        for (let i = 0; i < this.modelTreeRenderers.length; i++)
            this.modelTreeRenderers[i].destroy(device);
    }
}

class PaperMario64SceneDesc implements Viewer.SceneDesc {
    constructor(public id: string, public name: string, public bgName: string | null = null) {
    }

    public createScene(device: GfxDevice, abortSignal: AbortSignal): Progressable<Viewer.SceneGfx> {
        const areaId = this.id.slice(0, 3);

        const p: Progressable<ArrayBufferSlice>[] = [
            fetchData(`${pathBase}/${this.id}_shape`, abortSignal),
            fetchData(`${pathBase}/${areaId}_tex`, abortSignal),
        ];

        if (this.bgName !== null)
            p.push(fetchData(`${pathBase}/${this.bgName}`, abortSignal));

        return Progressable.all(p).then(([shapeData, texData, bgData]) => {
            const renderer = new PaperMario64Renderer();

            const tex = Tex.parseTextureArchive(texData);
            renderer.textureHolder.addTextureArchive(device, tex);

            if (bgData !== undefined) {
                const bgTexture = Tex.parseBackground(bgData, this.bgName);
                renderer.textureHolder.addTextures(device, [bgTexture]);

                renderer.bgTextureRenderer = new BackgroundBillboardRenderer(device, renderer.viewRenderer, renderer.textureHolder, this.bgName);
            }

            const mapShape = MapShape.parse(shapeData);
            const modelTreeRenderer = new PaperMario64ModelTreeRenderer(device, tex, renderer.textureHolder, mapShape.rootNode);
            renderer.modelTreeRenderers.push(modelTreeRenderer);
            modelTreeRenderer.addToViewRenderer(device, renderer.viewRenderer);

            return renderer;
        });
    }
}

// Scene names provided by MGMoaks on Discord.
const id = 'pm64';
const name = 'Paper Mario 64';
const sceneDescs = [
    "Goomba Village",
    new PaperMario64SceneDesc('kmr_00', 'Mario Impact Site', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_02', 'Goomba Village', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_03', 'Goomba Village Cliff', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_04', "Jr. Troopa's Hideout", 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_05', 'Goomba Village Outskirts', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_09', 'Goomba Road 1', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_06', 'Goomba Road 2', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_07', 'Goomba Road 3', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_12', 'Goomba Road 4', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_11', "Goomba King's Fortress", 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_10', 'Toad Town West Gate', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_bt04', 'Normal Encounter BG'),
    new PaperMario64SceneDesc('kmr_bt05', 'Jr. Troopa Battle BG'),
    new PaperMario64SceneDesc('kmr_bt03', 'Red & Blue Goomba Battle BG'),
    new PaperMario64SceneDesc('kmr_bt06', 'Goomba King Battle BG'),

    "Toad Town",
    new PaperMario64SceneDesc('kmr_20', "Mario's House", 'kmr_bg'),
    new PaperMario64SceneDesc('mac_00', 'West Toad Town', 'nok_bg'),
    new PaperMario64SceneDesc('mac_01', 'Toad Town Plaza', 'nok_bg'),
    new PaperMario64SceneDesc('mac_02', 'South Toad Town', 'nok_bg'),
    new PaperMario64SceneDesc('mac_03', 'Toad Town Station', 'nok_bg'),
    new PaperMario64SceneDesc('mac_04', 'Southwest Toad Town', 'nok_bg'),
    new PaperMario64SceneDesc('mac_05', 'Toad Town Port', 'nok_bg'),
    new PaperMario64SceneDesc('osr_00', "Peach's Castle Courtyard (Normal)", 'nok_bg'),
    new PaperMario64SceneDesc('osr_01', "Peach's Castle Courtyard (Ruined)", 'nok_bg'),
    new PaperMario64SceneDesc('mgm_00', 'Playroom Reception'),
    new PaperMario64SceneDesc('mgm_01', 'Jump Attack Minigame'),
    new PaperMario64SceneDesc('mgm_02', 'Smash Attack Minigame'),
    new PaperMario64SceneDesc('kmr_30', "Credits Scene"),
    new PaperMario64SceneDesc('mac_bt01', 'Jr. Troopa Battle BG (Chapter 5)'),
    new PaperMario64SceneDesc('mac_bt02', 'Dojo Battle BG'),

    "Toad Town Tunnels",
    new PaperMario64SceneDesc('tik_06', 'Tunnels Entrance'),
    new PaperMario64SceneDesc('tik_18', 'Toad Town Tunnels 1/3/16'),
    new PaperMario64SceneDesc('tik_01', 'Toad Town Tunnels 1'),
    new PaperMario64SceneDesc('tik_02', 'Toad Town Tunnels 2'),
    new PaperMario64SceneDesc('tik_03', 'Toad Town Tunnels 4'),
    new PaperMario64SceneDesc('tik_04', 'Toad Town Tunnels 5'),
    new PaperMario64SceneDesc('tik_05', 'Toad Town Tunnels 6'),
    new PaperMario64SceneDesc('tik_07', 'Toad Town Tunnels 7'),
    new PaperMario64SceneDesc('tik_12', 'Toad Town Tunnels 8'),
    new PaperMario64SceneDesc('tik_08', 'Toad Town Tunnels 9'),
    new PaperMario64SceneDesc('tik_09', 'Toad Town Tunnels 10'),
    new PaperMario64SceneDesc('tik_10', 'Toad Town Tunnels 11'),
    new PaperMario64SceneDesc('tik_20', 'Toad Town Tunnels 12'),
    new PaperMario64SceneDesc('tik_21', 'Toad Town Tunnels 13'),
    new PaperMario64SceneDesc('tik_14', 'Toad Town Tunnels 14'),
    new PaperMario64SceneDesc('tik_15', "Rip Cheato's Room"),
    new PaperMario64SceneDesc('tik_23', 'Toad Town Tunnels 15'),
    new PaperMario64SceneDesc('tik_25', 'Ultra Boots Room'),
    new PaperMario64SceneDesc('tik_22', 'Pipe to Frozen Corridor'),
    new PaperMario64SceneDesc('tik_17', 'Pipe to Shiver City'),
    new PaperMario64SceneDesc('tik_19', 'Super Block Room'),
    new PaperMario64SceneDesc('tik_bt01', 'tik_bt01'),
    new PaperMario64SceneDesc('tik_bt02', 'tik_bt02'),
    new PaperMario64SceneDesc('tik_bt03', 'tik_bt03'),
    new PaperMario64SceneDesc('tik_bt04', 'tik_bt04'),
    new PaperMario64SceneDesc('tik_bt05', 'tik_bt05'),

    "Peach's Castle",
    new PaperMario64SceneDesc('osr_02', "Outside Peach's Castle (Night)", 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_00', 'First Floor (Day)', 'nok_bg'),
    new PaperMario64SceneDesc('kkj_01', 'Second Floor (Day)', 'nok_bg'),
    new PaperMario64SceneDesc('kkj_02', 'Third Floor Stairs (Day)', 'nok_bg'),
    new PaperMario64SceneDesc('kkj_03', 'Third Floor Hallway (Day) ', 'nok_bg'),
    new PaperMario64SceneDesc('kkj_10', 'First Floor (Night)'),
    new PaperMario64SceneDesc('kkj_11', 'Second Floor (Night)'),
    new PaperMario64SceneDesc('kkj_12', 'Third Floor Stairs (Night)'),
    new PaperMario64SceneDesc('kkj_13', 'Third Floor Hallway (Night)', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_22', 'Fourth Floor Staircase', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_23', 'Roof Walkway', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_24', 'Spire Staircase', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_25', "Top of the Castle", 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_14', "Princess Peach's Room"),
    new PaperMario64SceneDesc('kkj_26', "Peach's Balcony", 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_27', 'Secret Hallway'),
    new PaperMario64SceneDesc('kkj_15', "Bowser's Room"),
    new PaperMario64SceneDesc('kkj_16', 'Library'),
    new PaperMario64SceneDesc('kkj_17', 'Storeroom'),
    new PaperMario64SceneDesc('kkj_18', 'Dining Room', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_19', 'Kitchen'),
    new PaperMario64SceneDesc('kkj_20', 'Guest Bedroom'),
    new PaperMario64SceneDesc('kkj_29', 'Quiz Show Room (Chapter 5)'),
    new PaperMario64SceneDesc('kkj_21', 'Quiz Show Room (Chapter 8)'),
    new PaperMario64SceneDesc('kkj_28', 'Quiz Show Room (???)'),
    new PaperMario64SceneDesc('osr_03', "Peach's Castle (Bowser Cutscene)", 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_bt01', 'Bowser Battle BG (Hallway)'),
    new PaperMario64SceneDesc('kkj_bt02', 'Bowser Battle BG (Roof)'),

    "Shooting Star Summit",
    new PaperMario64SceneDesc('hos_00', 'Shooting Star Path', 'nok_bg'),
    new PaperMario64SceneDesc('hos_01', 'Shooting Star Summit', 'hos_bg'),
    new PaperMario64SceneDesc('hos_06', "Merluvlee's House", 'hos_bg'),
    new PaperMario64SceneDesc('hos_02', 'Star Way', 'hos_bg'),
    new PaperMario64SceneDesc('hos_03', 'Star Haven', 'hos_bg'),
    new PaperMario64SceneDesc('hos_04', 'Outside Star Sanctuary', 'hos_bg'),
    new PaperMario64SceneDesc('hos_05', 'Inside Star Sanctuary', 'hos_bg'),
    new PaperMario64SceneDesc('hos_10', 'Pre-Prologue Cutscene', 'hos_bg'),
    new PaperMario64SceneDesc('hos_20', 'Star Ship Cutscene', 'hos_bg'),
    new PaperMario64SceneDesc('hos_bt01', 'Star Way Encounter BG'),
    new PaperMario64SceneDesc('hos_bt02', 'Shooting Star Path Battle BG'),

    "Koopa Village",
    new PaperMario64SceneDesc('nok_01', 'South Koopa Village', 'nok_bg'),
    new PaperMario64SceneDesc('nok_02', 'North Koopa Village', 'nok_bg'),
    new PaperMario64SceneDesc('nok_03', 'Koopa Village Outskirts', 'nok_bg'),
    new PaperMario64SceneDesc('nok_04', 'Fuzzy Woods', 'nok_bg'),
    new PaperMario64SceneDesc('nok_11', 'Pleasant Path 1', 'nok_bg'),
    new PaperMario64SceneDesc('nok_12', 'Pleasant Path 2', 'nok_bg'),
    new PaperMario64SceneDesc('nok_13', 'Pleasant Path 3', 'nok_bg'),
    new PaperMario64SceneDesc('nok_14', 'Pleasant Path 4', 'nok_bg'),
    new PaperMario64SceneDesc('nok_15', 'Pleasant Path 5', 'nok_bg'),
    new PaperMario64SceneDesc('nok_bt01', 'nok_bt01'),
    new PaperMario64SceneDesc('nok_bt02', 'nok_bt02'),
    new PaperMario64SceneDesc('nok_bt03', 'Bridge Encounter BG'),
    new PaperMario64SceneDesc('nok_bt04', 'Fuzzy Woods Battle BG'),

    "Koopa Bros. Fortress",
    new PaperMario64SceneDesc('trd_00', 'Outside Koopa Bros. Fortress', 'nok_bg'),
    new PaperMario64SceneDesc('trd_01', 'Left Spire'),
    new PaperMario64SceneDesc('trd_02', 'Fortress Left Hall'),
    new PaperMario64SceneDesc('trd_03', 'Fortress Central Hall'),
    new PaperMario64SceneDesc('trd_04', 'Fortress Right Hall'),
    new PaperMario64SceneDesc('trd_05', 'Right Spire Center'),
    new PaperMario64SceneDesc('trd_06', 'Right Spire Basement'),
    new PaperMario64SceneDesc('trd_07', 'Basement Chamber'),
    new PaperMario64SceneDesc('trd_08', 'Basement Hallway'),
    new PaperMario64SceneDesc('trd_09', 'Fortress Bridge', 'nok_bg'),
    new PaperMario64SceneDesc('trd_10', 'Right Spire Top'),
    new PaperMario64SceneDesc('trd_bt00', 'Koopa Bros. Battle BG'),
    new PaperMario64SceneDesc('trd_bt01', 'trd_bt01'),
    new PaperMario64SceneDesc('trd_bt02', 'trd_bt02'),
    new PaperMario64SceneDesc('trd_bt03', 'trd_bt03'),
    new PaperMario64SceneDesc('trd_bt04', 'trd_bt04'),
    new PaperMario64SceneDesc('trd_bt05', 'trd_bt05'),

    "Mt. Rugged",
    new PaperMario64SceneDesc('iwa_00', 'Mt. Rugged 1', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_01', 'Mt. Rugged 2', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_02', 'Mt. Rugged 3', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_03', 'Mt. Rugged 4', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_04', 'Mt. Rugged Bridge', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_10', 'Mt. Rugged Station', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_11', 'Dry Dry Railroad line', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_bt01', 'iwa_bt01'),
    new PaperMario64SceneDesc('iwa_bt02', 'iwa_bt02'),

    "Dry Dry Outpost",
    new PaperMario64SceneDesc('dro_01', 'West Dry Dry Outpost', 'sbk_bg'),
    new PaperMario64SceneDesc('dro_02', 'East Dry Dry Outpost', 'sbk_bg'),

    "Dry Dry Desert",
    new PaperMario64SceneDesc('sbk_99', 'Dry Dry Desert Gateway', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_02', 'Dry Dry Ruins Entrance', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_56', 'Desert Oasis', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_00', 'sbk_00', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_01', 'sbk_01', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_02', 'sbk_02', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_04', 'sbk_04', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_05', 'sbk_05', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_06', 'sbk_06', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_10', 'sbk_10', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_11', 'sbk_11', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_12', 'sbk_12', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_13', 'sbk_13', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_14', 'sbk_14', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_15', 'sbk_15', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_16', 'sbk_16', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_20', 'sbk_20', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_21', 'sbk_21', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_22', 'sbk_22', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_23', 'sbk_23', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_24', 'sbk_24', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_25', 'sbk_25', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_26', 'sbk_26', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_30', 'sbk_30', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_31', 'sbk_31', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_32', 'sbk_32', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_33', 'sbk_33', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_34', 'sbk_34', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_35', 'sbk_35', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_36', 'sbk_36', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_40', 'sbk_40', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_41', 'sbk_41', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_42', 'sbk_42', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_43', 'sbk_43', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_44', 'sbk_44', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_45', 'sbk_45', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_46', 'sbk_46', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_50', 'sbk_50', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_51', 'sbk_51', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_52', 'sbk_52', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_53', 'sbk_53', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_54', 'sbk_54', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_55', 'sbk_55', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_60', 'sbk_60', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_61', 'sbk_61', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_62', 'sbk_62', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_63', 'sbk_63', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_64', 'sbk_64', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_65', 'sbk_65', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_66', 'sbk_66', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_bt02', 'sbk_bt02'),

    "Dry Dry Ruins",
    new PaperMario64SceneDesc('isk_01', 'Ruins Entrance', 'sbk3_bg'),
    new PaperMario64SceneDesc('isk_02', 'Pokey Mummy Corridor 1', 'sbk3_bg'),
    new PaperMario64SceneDesc('isk_03', 'Sand Room 1'),
    new PaperMario64SceneDesc('isk_04', 'Staircase Chamber', 'sbk3_bg'),
    new PaperMario64SceneDesc('isk_05', 'Pyramid Stone Room'),
    new PaperMario64SceneDesc('isk_06', 'Sand Room 2'),
    new PaperMario64SceneDesc('isk_07', 'Pokey Mummy Corridor 2'),
    new PaperMario64SceneDesc('isk_08', 'Junction Room'),
    new PaperMario64SceneDesc('isk_09', 'Super Hammer Room'),
    new PaperMario64SceneDesc('isk_10', 'Drop-down Chamber'),
    new PaperMario64SceneDesc('isk_11', 'Statue Room'),
    new PaperMario64SceneDesc('isk_12', 'Sand Room 3'),
    new PaperMario64SceneDesc('isk_13', 'Lunar Stone Room'),
    new PaperMario64SceneDesc('isk_14', 'Diamond Stone Room'),
    new PaperMario64SceneDesc('isk_16', "Tutankoopa's Chamber"),
    new PaperMario64SceneDesc('isk_18', 'Basement Hallway'),
    new PaperMario64SceneDesc('isk_19', 'Save Point Corridor'),
    new PaperMario64SceneDesc('isk_bt01', 'isk_bt01'),
    new PaperMario64SceneDesc('isk_bt02', 'isk_bt02'),
    new PaperMario64SceneDesc('isk_bt03', 'isk_bt03'),
    new PaperMario64SceneDesc('isk_bt04', 'isk_bt04'),
    new PaperMario64SceneDesc('isk_bt05', 'isk_bt05'),
    new PaperMario64SceneDesc('isk_bt06', 'isk_bt06'),
    new PaperMario64SceneDesc('isk_bt07', 'isk_bt07'),
    new PaperMario64SceneDesc('isk_bt08', 'isk_bt08'),

    "Forever Forest",
    new PaperMario64SceneDesc('mim_10', 'Forever Forest Entrance', 'nok_bg'),
    new PaperMario64SceneDesc('mim_01', 'Forever Forest 1', 'obk_bg'),
    new PaperMario64SceneDesc('mim_02', 'Forever Forest 2', 'obk_bg'),
    new PaperMario64SceneDesc('mim_03', 'Forever Forest 3', 'obk_bg'),
    new PaperMario64SceneDesc('mim_04', 'Forever Forest 4', 'obk_bg'),
    new PaperMario64SceneDesc('mim_05', 'Forever Forest 5', 'obk_bg'),
    new PaperMario64SceneDesc('mim_08', 'Forever Forest 6', 'obk_bg'),
    new PaperMario64SceneDesc('mim_06', 'Forever Forest 7', 'obk_bg'),
    new PaperMario64SceneDesc('mim_07', 'Forever Forest 8', 'obk_bg'),
    new PaperMario64SceneDesc('mim_09', 'Forever Forest 9', 'obk_bg'),
    new PaperMario64SceneDesc('mim_bt01', 'mim_bt01'),

    "Boo's Mansion",
    new PaperMario64SceneDesc('mim_11', "Outside Boo's Mansion", 'obk_bg'),
    new PaperMario64SceneDesc('mim_12', "Boo's Mansion Back Gate", 'arn_bg'),
    new PaperMario64SceneDesc('obk_01', 'Mansion Foyer'),
    new PaperMario64SceneDesc('obk_02', 'Stairs to Basement', 'obk_bg'),
    new PaperMario64SceneDesc('obk_03', 'Basement Shop'),
    new PaperMario64SceneDesc('obk_04', 'Super Boots Room'),
    new PaperMario64SceneDesc('obk_05', 'Storage Room', 'obk_bg'),
    new PaperMario64SceneDesc('obk_06', 'Library'),
    new PaperMario64SceneDesc('obk_07', 'Phonograph Room', 'obk_bg'),
    new PaperMario64SceneDesc('obk_08', 'Record Room', 'obk_bg'),
    new PaperMario64SceneDesc('obk_09', 'Third Floor'),

    "Gusty Gulch",
    new PaperMario64SceneDesc('arn_07', 'Outside Windy Mill', 'arn_bg'),
    new PaperMario64SceneDesc('arn_03', 'Gusty Gulch 1', 'arn_bg'),
    new PaperMario64SceneDesc('arn_05', 'Gusty Gulch 2', 'arn_bg'),
    new PaperMario64SceneDesc('arn_02', 'Gusty Gulch 3', 'arn_bg'),
    new PaperMario64SceneDesc('arn_04', 'Gusty Gulch 4', 'arn_bg'),
    new PaperMario64SceneDesc('arn_20', "Tubba Blubba's Castle Entrance"),
    new PaperMario64SceneDesc('arn_08', 'Inside Windy Mill'),
    new PaperMario64SceneDesc('arn_09', 'Windy Mill Well Entrance'),
    new PaperMario64SceneDesc('arn_10', 'Windy Mill Well 1'),
    new PaperMario64SceneDesc('arn_12', 'Windy Mill Well 2'),
    new PaperMario64SceneDesc('arn_13', 'Windy Mill Well 3'),
    new PaperMario64SceneDesc('arn_11', 'Windy Mill Well Arena'),
    new PaperMario64SceneDesc('arn_bt01', 'Gusty Gulch Encounter BG'),
    new PaperMario64SceneDesc('arn_bt02', 'Outside Windy Mill Encounter BG'),
    new PaperMario64SceneDesc('arn_bt03', '(unused?) Gusty Gulch Encounter BG'),
    new PaperMario64SceneDesc('arn_bt04', '(unused?) Windy Mill Well Encounter BG'),
    new PaperMario64SceneDesc('arn_bt05', 'Windy Mill Well Encounter BG'),
    new PaperMario64SceneDesc('arn_bt06', "Tubba Blubba's Heart Battle BG"),

    "Tubba Blubba's Castle",
    new PaperMario64SceneDesc('dgb_01', 'Main Hall', 'arn_bg'),
    new PaperMario64SceneDesc('dgb_02', '1st Floor Hallway'),
    new PaperMario64SceneDesc('dgb_07', 'Dining Room'),
    new PaperMario64SceneDesc('dgb_03', 'Dual-layer Room'),
    new PaperMario64SceneDesc('dgb_05', 'Staircase above Basement'),
    new PaperMario64SceneDesc('dgb_06', 'Basement'),
    new PaperMario64SceneDesc('dgb_04', 'Staircase to Basement'),
    new PaperMario64SceneDesc('dgb_08', '2nd Floor Staircase'),
    new PaperMario64SceneDesc('dgb_09', '2nd Floor Hallway'),
    new PaperMario64SceneDesc('dgb_11', 'Table Room'),
    new PaperMario64SceneDesc('dgb_10', 'Room above Table Room'),
    new PaperMario64SceneDesc('dgb_12', 'Spike Room'),
    new PaperMario64SceneDesc('dgb_13', 'Guest Bedroom'),
    new PaperMario64SceneDesc('dgb_14', '3rd Floor Staircase'),
    new PaperMario64SceneDesc('dgb_15', '3rd Floor Hallway'),
    new PaperMario64SceneDesc('dgb_16', 'Nap Room'),
    new PaperMario64SceneDesc('dgb_17', 'Save Point Corridor'),
    new PaperMario64SceneDesc('dgb_18', "Tubba Blubba's Room"),
    new PaperMario64SceneDesc('dgb_bt01', 'dgb_bt01'),
    new PaperMario64SceneDesc('dgb_bt02', 'dgb_bt02'),
    new PaperMario64SceneDesc('dgb_bt03', 'dgb_bt03'),
    new PaperMario64SceneDesc('dgb_bt04', 'dgb_bt04'),
    new PaperMario64SceneDesc('dgb_bt05', 'dgb_bt05'),

    "Shy Guy's Toybox",
    new PaperMario64SceneDesc('omo_03', 'Blue Station', 'omo_bg'),
    new PaperMario64SceneDesc('omo_13', 'Blue Station Left Wing', 'omo_bg'),
    new PaperMario64SceneDesc('omo_01', 'Shy Guy playroom', 'omo_bg'),
    new PaperMario64SceneDesc('omo_04', 'Blue Station Right Wing', 'omo_bg'),
    new PaperMario64SceneDesc('omo_06', 'Pink Station', 'omo_bg'),
    new PaperMario64SceneDesc('omo_17', 'Pink Station Left Wing', 'omo_bg'),
    new PaperMario64SceneDesc('omo_05', 'Train Track Crossing', 'omo_bg'),
    new PaperMario64SceneDesc('omo_07', 'Pink Station Right Wing', 'omo_bg'),
    new PaperMario64SceneDesc('omo_08', 'Green Station', 'omo_bg'),
    new PaperMario64SceneDesc('omo_09', 'Green Station Right Wing', 'omo_bg'),
    new PaperMario64SceneDesc('omo_10', 'Red Station', 'omo_bg'),
    new PaperMario64SceneDesc('omo_11', 'Red Station Left Wing', 'omo_bg'),
    new PaperMario64SceneDesc('omo_12', "Big Lantern Guy's Room"),
    new PaperMario64SceneDesc('omo_02', 'Red Station Right Wing', 'omo_bg'),
    new PaperMario64SceneDesc('omo_14', 'Dark Hallway'),
    new PaperMario64SceneDesc('omo_15', "General Guy's Arena", 'omo_bg'),
    new PaperMario64SceneDesc('omo_16', 'Train Track Cutscene', 'omo_bg'),
    new PaperMario64SceneDesc('omo_bt01', 'omo_bt01'),
    new PaperMario64SceneDesc('omo_bt02', 'omo_bt02'),
    new PaperMario64SceneDesc('omo_bt03', 'omo_bt03'),
    new PaperMario64SceneDesc('omo_bt04', 'omo_bt04'),
    new PaperMario64SceneDesc('omo_bt05', 'omo_bt05'),
    new PaperMario64SceneDesc('omo_bt06', 'omo_bt06'),
    new PaperMario64SceneDesc('omo_bt07', 'omo_bt07'),

    "Lavalava Island",
    new PaperMario64SceneDesc('kgr_01', 'Whale Entrance'),
    new PaperMario64SceneDesc('kgr_02', 'Whale Belly'),
    new PaperMario64SceneDesc('mac_06', 'Sea Cutscene', 'nok_bg'),
    new PaperMario64SceneDesc('jan_00', 'Lavalava Island Beach 1', 'yos_bg'),
    new PaperMario64SceneDesc('jan_01', 'Lavalava Island Beach 2', 'yos_bg'),
    new PaperMario64SceneDesc('jan_02', "West Yoshi's Village", 'yos_bg'),
    new PaperMario64SceneDesc('jan_03', "East Yoshi's Village", 'yos_bg'),
    new PaperMario64SceneDesc('jan_05', 'Jade Jungle 1', 'yos_bg'),
    new PaperMario64SceneDesc('jan_04', 'Jade Jungle 2', 'yos_bg'),
    new PaperMario64SceneDesc('jan_08', 'Jade Jungle 3', 'yos_bg'),
    new PaperMario64SceneDesc('jan_09', 'Jade Jungle 4', 'yos_bg'),
    new PaperMario64SceneDesc('jan_10', 'Jade Jungle 5', 'yos_bg'),
    new PaperMario64SceneDesc('jan_11', 'Jade Jungle 5 (Underground)', 'jan_bg'),
    new PaperMario64SceneDesc('jan_06', 'Jade Jungle 6', 'jan_bg'),
    new PaperMario64SceneDesc('jan_07', 'Jade Jungle 7', 'yos_bg'),
    new PaperMario64SceneDesc('jan_12', 'Deep Jungle 1', 'jan_bg'),
    new PaperMario64SceneDesc('jan_13', 'Deep Jungle 2', 'jan_bg'),
    new PaperMario64SceneDesc('jan_14', 'Deep Jungle 3', 'jan_bg'),
    new PaperMario64SceneDesc('jan_15', 'Deep Jungle 4', 'jan_bg'),
    new PaperMario64SceneDesc('jan_16', 'Raven Tree Base', 'jan_bg'),
    new PaperMario64SceneDesc('jan_17', 'Inside the Tree 1', 'jan_bg'),
    new PaperMario64SceneDesc('jan_18', 'Raven Tree Middle', 'yos_bg'),
    new PaperMario64SceneDesc('jan_19', 'Inside the Tree 2', 'jan_bg'),
    new PaperMario64SceneDesc('jan_23', "Raphael's Nest", 'yos_bg'),
    new PaperMario64SceneDesc('jan_22', 'Path to Mt. Lavalava', 'jan_bg'),
    new PaperMario64SceneDesc('kgr_bt01', 'Fuzzipede Battle BG'),
    new PaperMario64SceneDesc('jan_bt00', 'jan_bt00'),
    new PaperMario64SceneDesc('jan_bt01', 'jan_bt01'),
    new PaperMario64SceneDesc('jan_bt02', 'jan_bt02'),
    new PaperMario64SceneDesc('jan_bt03', 'jan_bt03'),
    new PaperMario64SceneDesc('jan_bt04', 'jan_bt04'),

    "Mt. Lavalava",
    new PaperMario64SceneDesc('kzn_01', 'Mt. Lavalava Entrance'),
    new PaperMario64SceneDesc('kzn_02', 'Lava Corridor 1'),
    new PaperMario64SceneDesc('kzn_03', 'Central Cavern (Left)'),
    new PaperMario64SceneDesc('kzn_09', 'Central Cavern (Right)'),
    new PaperMario64SceneDesc('kzn_04', 'Fire Bar Corridor'),
    new PaperMario64SceneDesc('kzn_05', 'Slope to Block Puzzle'),
    new PaperMario64SceneDesc('kzn_06', 'Block Puzzle Room'),
    new PaperMario64SceneDesc('kzn_07', 'Ultra Hammer Room'),
    new PaperMario64SceneDesc('kzn_08', 'Dizzy Stomp Room'),
    new PaperMario64SceneDesc('kzn_10', 'Spiny Tromp Corridor'),
    new PaperMario64SceneDesc('kzn_11', 'Lava Corridor 2'),
    new PaperMario64SceneDesc('kzn_17', 'Spiny Tromp Puzzle'),
    new PaperMario64SceneDesc('kzn_18', 'Save Point Corridor'),
    new PaperMario64SceneDesc('kzn_19', 'Lava Piranha Arena'),
    new PaperMario64SceneDesc('kzn_20', 'Escape Sequence 1'),
    new PaperMario64SceneDesc('kzn_22', 'Escape Sequence 2'),
    new PaperMario64SceneDesc('kzn_23', 'Volcano Shaft', 'yos_bg'),
    new PaperMario64SceneDesc('kzn_bt01', 'kzn_bt01'),
    new PaperMario64SceneDesc('kzn_bt02', 'kzn_bt02'),
    new PaperMario64SceneDesc('kzn_bt04', 'kzn_bt04'),
    new PaperMario64SceneDesc('kzn_bt05', 'kzn_bt05'),

    "Flower Fields",
    new PaperMario64SceneDesc('flo_00', 'Central Flower Fields', 'fla_bg'),
    new PaperMario64SceneDesc('flo_03', "Petunia's Room", 'fla_bg'),
    new PaperMario64SceneDesc('flo_22', 'Well Room', 'fla_bg'),
    new PaperMario64SceneDesc('flo_07', "Posie's Room", 'fla_bg'),
    new PaperMario64SceneDesc('flo_08', 'Yellow Berry Gate', 'fla_bg'),
    new PaperMario64SceneDesc('flo_09', 'East Path', 'fla_bg'),
    new PaperMario64SceneDesc('flo_10', "Lily's Spring", 'fla_bg'),
    new PaperMario64SceneDesc('flo_11', 'Hedge Maze', 'fla_bg'),
    new PaperMario64SceneDesc('flo_12', "Rosie's Room", 'fla_bg'),
    new PaperMario64SceneDesc('flo_13', 'Path to Sun Tower', 'fla_bg'),
    new PaperMario64SceneDesc('flo_14', 'Bubble Flower Room', 'fla_bg'),
    new PaperMario64SceneDesc('flo_15', 'Sun Tower', 'fla_bg'),
    new PaperMario64SceneDesc('flo_16', 'Platform Puzzle Room', 'fla_bg'),
    new PaperMario64SceneDesc('flo_17', 'Path to Puff Puff Machine', 'fla_bg'),
    new PaperMario64SceneDesc('flo_18', 'Puff Puff Machine Room', 'fla_bg'),
    new PaperMario64SceneDesc('flo_19', 'Cloudy Climb', 'sra_bg'),
    new PaperMario64SceneDesc('flo_21', "Huff N. Puff's Arena", 'sra_bg'),
    new PaperMario64SceneDesc('flo_23', 'Path to Hedge Maze', 'fla_bg'),
    new PaperMario64SceneDesc('flo_24', 'Bubble Tree Room', 'fla_bg'),
    new PaperMario64SceneDesc('flo_25', "Path to Posie's Room", 'fla_bg'),
    new PaperMario64SceneDesc('flo_bt01', 'flo_bt01'),
    new PaperMario64SceneDesc('flo_bt02', 'flo_bt02'),
    new PaperMario64SceneDesc('flo_bt03', 'flo_bt03'),
    new PaperMario64SceneDesc('flo_bt04', 'flo_bt04'),
    new PaperMario64SceneDesc('flo_bt05', 'flo_bt05'),
    new PaperMario64SceneDesc('flo_bt06', 'flo_bt06'),

    "Shiver City",
    new PaperMario64SceneDesc('sam_01', 'West Shiver City', 'yki_bg'),
    new PaperMario64SceneDesc('sam_02', 'Central Shiver City', 'yki_bg'),
    new PaperMario64SceneDesc('sam_11', 'East Shiver City', 'yki_bg'),
    new PaperMario64SceneDesc('sam_03', 'Shiver Snowfield Path', 'yki_bg'),
    new PaperMario64SceneDesc('sam_04', 'Entrance to Shiver Mountain', 'yki_bg'),
    new PaperMario64SceneDesc('sam_05', 'Shiver Snowfield', 'sam_bg'),
    new PaperMario64SceneDesc('sam_06', 'Starborn Valley', 'sam_bg'),
    new PaperMario64SceneDesc('sam_07', 'Shiver Mountain 1', 'yki_bg'),
    new PaperMario64SceneDesc('sam_08', 'Shiver Mountain 2', 'yki_bg'),
    new PaperMario64SceneDesc('sam_09', 'Shiver Mountain 3', 'yki_bg'),
    new PaperMario64SceneDesc('sam_10', 'Shiver Mountain 4', 'yki_bg'),
    new PaperMario64SceneDesc('sam_12', "Madam Merlar's Chamber", 'yki_bg'),
    new PaperMario64SceneDesc('sam_bt01', 'sam_bt01'),
    new PaperMario64SceneDesc('sam_bt02', 'sam_bt02'),
    new PaperMario64SceneDesc('sam_bt03', 'sam_bt03'),
    new PaperMario64SceneDesc('sam_bt04', 'sam_bt04'),

    "Crystal Palace",
    new PaperMario64SceneDesc('pra_01', 'Crystal Palace Entrance', 'yki_bg'),
    new PaperMario64SceneDesc('pra_15', 'Secret Cave', 'yki_bg'),
    new PaperMario64SceneDesc('pra_02', 'Crystal Palace Foyer'),
    new PaperMario64SceneDesc('pra_03', 'Reflection Puzzle Room (Front)'),
    new PaperMario64SceneDesc('pra_04', 'Reflection Puzzle Room (Back)'),
    new PaperMario64SceneDesc('pra_10', 'Normal Hallway'),
    new PaperMario64SceneDesc('pra_05', 'Normal Chest Room'),
    new PaperMario64SceneDesc('pra_09', 'Bomb Hallway'),
    new PaperMario64SceneDesc('pra_11', 'Bomb Chest Room'),
    new PaperMario64SceneDesc('pra_13', 'Blue Door Corridor'),
    new PaperMario64SceneDesc('pra_14', 'Blue Flipping Room'),
    new PaperMario64SceneDesc('pra_16', 'Red Door Corridor'),
    new PaperMario64SceneDesc('pra_18', 'Clubba Bridge Room'),
    new PaperMario64SceneDesc('pra_33', 'Red Flipping Room'),
    new PaperMario64SceneDesc('pra_35', 'Triple Dip Room'),
    new PaperMario64SceneDesc('pra_19', 'Kooper Clone Puzzle'),
    new PaperMario64SceneDesc('pra_20', 'Junction Room'),
    new PaperMario64SceneDesc('pra_21', 'Dual-Statue Puzzle (Front)'),
    new PaperMario64SceneDesc('pra_22', 'Dual-Statue Puzzle (Back)'),
    new PaperMario64SceneDesc('pra_29', 'Switch Bridge Room'),
    new PaperMario64SceneDesc('pra_34', 'Free Flipping Room'),
    new PaperMario64SceneDesc('pra_31', 'Albino Dino Room'),
    new PaperMario64SceneDesc('pra_40', 'Save Point Corridor'),
    new PaperMario64SceneDesc('pra_32', 'Crystal King Arena', 'sam_bg'),
    new PaperMario64SceneDesc('pra_bt01', 'pra_bt01'),
    new PaperMario64SceneDesc('pra_bt02', 'pra_bt02'),
    new PaperMario64SceneDesc('pra_bt03', 'pra_bt03'),
    new PaperMario64SceneDesc('pra_bt04', 'pra_bt04'),

    "Bowser's Castle",
    new PaperMario64SceneDesc('kpa_63', "Bowser's Castle Hangar"),
    new PaperMario64SceneDesc('kpa_60', 'Castle Courtyard (l/nl)', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_62', 'Castle Courtyard (l/nl)', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_11', 'Lava Corridor 1 (Lava)'),
    new PaperMario64SceneDesc('kpa_10', 'Lava Corridor 1 (No Lava)'),
    new PaperMario64SceneDesc('kpa_70', 'Gear Room'),
    new PaperMario64SceneDesc('kpa_01', 'Lower Caves'),
    new PaperMario64SceneDesc('kpa_03', 'Upper Caves'),
    new PaperMario64SceneDesc('kpa_04', 'Block Push Room'),
    new PaperMario64SceneDesc('kpa_08', 'Rising Block Puzzle (Right)'),
    new PaperMario64SceneDesc('kpa_09', 'Rising Block Puzzle (Left)'),
    new PaperMario64SceneDesc('kpa_12', 'Lava Corridor 2'),
    new PaperMario64SceneDesc('kpa_13', 'Lava Corridor 3'),
    new PaperMario64SceneDesc('kpa_14', 'Lava Corridor 4'),
    new PaperMario64SceneDesc('kpa_15', 'Lava Chest Room'),
    new PaperMario64SceneDesc('kpa_16', 'Lava Control Room'),
    new PaperMario64SceneDesc('kpa_17', 'Toad Prison Cell'),
    new PaperMario64SceneDesc('kpa_32', 'Central Hall 1', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_33', 'Central Hall 2', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_40', 'Loop Room'),
    new PaperMario64SceneDesc('kpa_41', 'Loop Room 2'),
    new PaperMario64SceneDesc('kpa_50', 'Castle Hallway'),
    new PaperMario64SceneDesc('kpa_52', 'Room Before Loop Room'),
    new PaperMario64SceneDesc('kpa_61', 'Outside Walkway', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_80', 'Bowser Door Room'),
    new PaperMario64SceneDesc('kpa_90', 'Stairs to Toad House (Right)'),
    new PaperMario64SceneDesc('kpa_91', 'Castle Toad House (Right)'),
    new PaperMario64SceneDesc('kpa_94', 'Stairs to Toad House (Left)'),
    new PaperMario64SceneDesc('kpa_95', 'Castle Toad House (Left)'),
    new PaperMario64SceneDesc('kpa_96', 'Storage Room Shop'),
    new PaperMario64SceneDesc('kpa_102', '2nd to last Corridor'),
    new PaperMario64SceneDesc('kpa_111', 'Block Room 1'),
    new PaperMario64SceneDesc('kpa_112', 'Block Room 2 Hallway'),
    new PaperMario64SceneDesc('kpa_113', 'Block Room 2'),
    new PaperMario64SceneDesc('kpa_115', 'Block Room 3'),
    new PaperMario64SceneDesc('kpa_116', 'Block Room 3 Right Hall'),
    new PaperMario64SceneDesc('kpa_117', 'Treasure Room (Right)'),
    new PaperMario64SceneDesc('kpa_118', 'Block Room 3 Left Hall'),
    new PaperMario64SceneDesc('kpa_119', 'Treasure Room (Left)'),
    new PaperMario64SceneDesc('kpa_121', "Stairs to Peach's Castle"),
    new PaperMario64SceneDesc('kpa_130', 'B. Bill Blaster Room'),
    new PaperMario64SceneDesc('kpa_133', 'Water Puzzle (Right)'),
    new PaperMario64SceneDesc('kpa_134', 'Water Puzzle (Left)'),
    new PaperMario64SceneDesc('kpa_bt01', 'kpa_bt01'),
    new PaperMario64SceneDesc('kpa_bt02', 'kpa_bt02'),
    new PaperMario64SceneDesc('kpa_bt03', 'kpa_bt03'),
    new PaperMario64SceneDesc('kpa_bt04', 'kpa_bt04'),
    new PaperMario64SceneDesc('kpa_bt05', 'kpa_bt05'),
    new PaperMario64SceneDesc('kpa_bt07', 'kpa_bt07'),
    new PaperMario64SceneDesc('kpa_bt08', 'kpa_bt08'),
    new PaperMario64SceneDesc('kpa_bt09', 'kpa_bt09'),
    new PaperMario64SceneDesc('kpa_bt11', 'kpa_bt11'),
    new PaperMario64SceneDesc('kpa_bt13', 'kpa_bt13'),
    new PaperMario64SceneDesc('kpa_bt14', 'kpa_bt14'),
    
    "System & Debug Maps",
    new PaperMario64SceneDesc('machi',  'machi',  'nok_bg'),
    new PaperMario64SceneDesc('tst_01', 'tst_01', 'nok_bg'),
    new PaperMario64SceneDesc('tst_02', 'tst_02', 'nok_bg'),
    new PaperMario64SceneDesc('tst_03', 'tst_03', 'nok_bg'),
    new PaperMario64SceneDesc('tst_04', 'tst_04', 'nok_bg'),
    new PaperMario64SceneDesc('tst_10', 'tst_10', 'nok_bg'),
    new PaperMario64SceneDesc('tst_11', 'tst_11', 'nok_bg'),
    new PaperMario64SceneDesc('tst_12', 'tst_12', 'nok_bg'),
    new PaperMario64SceneDesc('tst_13', 'tst_13', 'nok_bg'),
    new PaperMario64SceneDesc('tst_20', 'tst_20', 'nok_bg'),
    new PaperMario64SceneDesc('end_00', 'end_00'),
    new PaperMario64SceneDesc('end_01', 'end_01'),
    new PaperMario64SceneDesc('gv_01', 'gv_01'),
    new PaperMario64SceneDesc('mgm_03', 'mgm_03'),
];

export const sceneGroup: Viewer.SceneGroup = { id, name, sceneDescs };
