
import * as Viewer from '../viewer';
import { GfxDevice, GfxHostAccessPass } from '../gfx/platform/GfxPlatform';
import Progressable from '../Progressable';
import { fetchData } from '../fetch';
import * as MapShape from './map_shape';
import * as Tex from './tex';
import { BasicRendererHelper } from '../oot3d/render';
import { PaperMario64TextureHolder, PaperMario64ModelTreeRenderer, BackgroundBillboardRenderer } from './render';
import ArrayBufferSlice from '../ArrayBufferSlice';

const pathBase = `pm64`;

class PaperMario64Renderer extends BasicRendererHelper {
    public textureHolder = new PaperMario64TextureHolder();
    public modelTreeRenderers: PaperMario64ModelTreeRenderer[] = [];
    public bgTextureRenderer: BackgroundBillboardRenderer | null = null;

    public prepareToRender(hostAccessPass: GfxHostAccessPass, viewerInput: Viewer.ViewerRenderInput): void {
        if (this.bgTextureRenderer !== null)
            this.bgTextureRenderer.prepareToRender(hostAccessPass, viewerInput);
        for (let i = 0; i < this.modelTreeRenderers.length; i++)
            this.modelTreeRenderers[i].prepareToRender(hostAccessPass, viewerInput);
    }

    public destroy(device: GfxDevice): void {
        super.destroy(device);
        this.textureHolder.destroy(device);
        if (this.bgTextureRenderer !== null)
            this.bgTextureRenderer.destroy(device);
        for (let i = 0; i < this.modelTreeRenderers.length; i++)
            this.modelTreeRenderers[i].destroy(device);
    }
}

class PaperMario64SceneDesc implements Viewer.SceneDesc {
    constructor(public id: string, public name: string, public bgName: string | null = null) {
    }

    public createScene(device: GfxDevice, abortSignal: AbortSignal): Progressable<Viewer.SceneGfx> {
        const areaId = this.id.slice(0, 3);

        const p: Progressable<ArrayBufferSlice>[] = [
            fetchData(`${pathBase}/${this.id}_shape`, abortSignal),
            fetchData(`${pathBase}/${areaId}_tex`, abortSignal),
        ];

        if (this.bgName !== null)
            p.push(fetchData(`${pathBase}/${this.bgName}`, abortSignal));

        return Progressable.all(p).then(([shapeData, texData, bgData]) => {
            const renderer = new PaperMario64Renderer();

            const tex = Tex.parseTextureArchive(texData);
            renderer.textureHolder.addTextureArchive(device, tex);

            if (bgData !== undefined) {
                const bgTexture = Tex.parseBackground(bgData, this.bgName);
                renderer.textureHolder.addTextures(device, [bgTexture]);

                renderer.bgTextureRenderer = new BackgroundBillboardRenderer(device, renderer.viewRenderer, renderer.textureHolder, this.bgName);
            }

            const mapShape = MapShape.parse(shapeData);
            const modelTreeRenderer = new PaperMario64ModelTreeRenderer(device, tex, renderer.textureHolder, mapShape.rootNode);
            renderer.modelTreeRenderers.push(modelTreeRenderer);
            modelTreeRenderer.addToViewRenderer(device, renderer.viewRenderer);

            return renderer;
        });
    }
}

const id = 'pm64';
const name = 'Paper Mario 64';
const sceneDescs = [
    "Goomba Village",
    new PaperMario64SceneDesc('kmr_00', 'kmr_00', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_02', 'kmr_02', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_03', 'kmr_03', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_04', 'kmr_04', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_05', 'kmr_05', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_06', 'kmr_06', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_07', 'kmr_07', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_09', 'kmr_09', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_10', 'kmr_10', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_11', 'kmr_11', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_12', 'kmr_12', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_20', 'kmr_20', 'kmr_bg'),
    new PaperMario64SceneDesc('kmr_30', 'kmr_30'),
    new PaperMario64SceneDesc('kmr_bt03', 'kmr_bt03'),
    new PaperMario64SceneDesc('kmr_bt04', 'kmr_bt04'),
    new PaperMario64SceneDesc('kmr_bt05', 'kmr_bt05'),
    new PaperMario64SceneDesc('kmr_bt06', 'kmr_bt06'),

    "Toad Town",
    new PaperMario64SceneDesc('mac_00', 'mac_00', 'nok_bg'),
    new PaperMario64SceneDesc('mac_01', 'mac_01', 'nok_bg'),
    new PaperMario64SceneDesc('mac_02', 'mac_02', 'nok_bg'),
    new PaperMario64SceneDesc('mac_03', 'mac_03', 'nok_bg'),
    new PaperMario64SceneDesc('mac_04', 'mac_04', 'nok_bg'),
    new PaperMario64SceneDesc('mac_05', 'mac_05', 'nok_bg'),
    new PaperMario64SceneDesc('mac_06', 'mac_06', 'nok_bg'),
    new PaperMario64SceneDesc('mac_bt01', 'mac_bt01'),
    new PaperMario64SceneDesc('mac_bt02', 'mac_bt02'),

    "Toad Town Sewers",
    new PaperMario64SceneDesc('tik_01', 'tik_01'),
    new PaperMario64SceneDesc('tik_02', 'tik_02'),
    new PaperMario64SceneDesc('tik_03', 'tik_03'),
    new PaperMario64SceneDesc('tik_04', 'tik_04'),
    new PaperMario64SceneDesc('tik_05', 'tik_05'),
    new PaperMario64SceneDesc('tik_06', 'tik_06'),
    new PaperMario64SceneDesc('tik_07', 'tik_07'),
    new PaperMario64SceneDesc('tik_08', 'tik_08'),
    new PaperMario64SceneDesc('tik_09', 'tik_09'),
    new PaperMario64SceneDesc('tik_10', 'tik_10'),
    new PaperMario64SceneDesc('tik_12', 'tik_12'),
    new PaperMario64SceneDesc('tik_14', 'tik_14'),
    new PaperMario64SceneDesc('tik_15', 'tik_15'),
    new PaperMario64SceneDesc('tik_17', 'tik_17'),
    new PaperMario64SceneDesc('tik_18', 'tik_18'),
    new PaperMario64SceneDesc('tik_19', 'tik_19'),
    new PaperMario64SceneDesc('tik_20', 'tik_20'),
    new PaperMario64SceneDesc('tik_21', 'tik_21'),
    new PaperMario64SceneDesc('tik_22', 'tik_22'),
    new PaperMario64SceneDesc('tik_23', 'tik_23'),
    new PaperMario64SceneDesc('tik_25', 'tik_25'),
    new PaperMario64SceneDesc('tik_bt01', 'tik_bt01'),
    new PaperMario64SceneDesc('tik_bt02', 'tik_bt02'),
    new PaperMario64SceneDesc('tik_bt03', 'tik_bt03'),
    new PaperMario64SceneDesc('tik_bt04', 'tik_bt04'),
    new PaperMario64SceneDesc('tik_bt05', 'tik_bt05'),

    "Whale Belly",
    new PaperMario64SceneDesc('kgr_01', 'kgr_01'),
    new PaperMario64SceneDesc('kgr_02', 'kgr_02'),
    new PaperMario64SceneDesc('kgr_bt01', 'kgr_bt01'),

    "Peach's Castle",
    new PaperMario64SceneDesc('kkj_00', 'kkj_00', 'nok_bg'),
    new PaperMario64SceneDesc('kkj_01', 'kkj_01', 'nok_bg'),
    new PaperMario64SceneDesc('kkj_02', 'kkj_02', 'nok_bg'),
    new PaperMario64SceneDesc('kkj_03', 'kkj_03', 'nok_bg'),
    new PaperMario64SceneDesc('kkj_10', 'kkj_10'),
    new PaperMario64SceneDesc('kkj_11', 'kkj_11'),
    new PaperMario64SceneDesc('kkj_12', 'kkj_12'),
    new PaperMario64SceneDesc('kkj_13', 'kkj_13', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_14', 'kkj_14'),
    new PaperMario64SceneDesc('kkj_15', 'kkj_15'),
    new PaperMario64SceneDesc('kkj_16', 'kkj_16'),
    new PaperMario64SceneDesc('kkj_17', 'kkj_17'),
    new PaperMario64SceneDesc('kkj_18', 'kkj_18', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_19', 'kkj_19'),
    new PaperMario64SceneDesc('kkj_20', 'kkj_20'),
    new PaperMario64SceneDesc('kkj_21', 'kkj_21'),
    new PaperMario64SceneDesc('kkj_22', 'kkj_22', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_23', 'kkj_23', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_24', 'kkj_24', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_25', 'kkj_25', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_26', 'kkj_26', 'kpa_bg'),
    new PaperMario64SceneDesc('kkj_27', 'kkj_27'),
    new PaperMario64SceneDesc('kkj_28', 'kkj_28'),
    new PaperMario64SceneDesc('kkj_29', 'kkj_29'),
    new PaperMario64SceneDesc('kkj_bt01', 'kkj_bt01'),
    new PaperMario64SceneDesc('kkj_bt02', 'kkj_bt02'),

    "Shooting Star Summit",
    new PaperMario64SceneDesc('hos_00', 'hos_00', 'nok_bg'),
    new PaperMario64SceneDesc('hos_01', 'hos_01', 'hos_bg'),
    new PaperMario64SceneDesc('hos_02', 'hos_02', 'hos_bg'),
    new PaperMario64SceneDesc('hos_03', 'hos_03', 'hos_bg'),
    new PaperMario64SceneDesc('hos_04', 'hos_04', 'hos_bg'),
    new PaperMario64SceneDesc('hos_05', 'hos_05', 'hos_bg'),
    new PaperMario64SceneDesc('hos_06', 'hos_06', 'hos_bg'),
    new PaperMario64SceneDesc('hos_10', 'hos_10', 'hos_bg'),
    new PaperMario64SceneDesc('hos_20', 'hos_20', 'hos_bg'),
    new PaperMario64SceneDesc('hos_bt01', 'hos_bt01'),
    new PaperMario64SceneDesc('hos_bt02', 'hos_bt02'),

    "Koopa Village",
    new PaperMario64SceneDesc('nok_01', 'nok_01', 'nok_bg'),
    new PaperMario64SceneDesc('nok_02', 'nok_02', 'nok_bg'),
    new PaperMario64SceneDesc('nok_03', 'nok_03', 'nok_bg'),
    new PaperMario64SceneDesc('nok_04', 'nok_04', 'nok_bg'),
    new PaperMario64SceneDesc('nok_11', 'nok_11', 'nok_bg'),
    new PaperMario64SceneDesc('nok_12', 'nok_12', 'nok_bg'),
    new PaperMario64SceneDesc('nok_13', 'nok_13', 'nok_bg'),
    new PaperMario64SceneDesc('nok_14', 'nok_14', 'nok_bg'),
    new PaperMario64SceneDesc('nok_15', 'nok_15', 'nok_bg'),
    new PaperMario64SceneDesc('nok_bt01', 'nok_bt01'),
    new PaperMario64SceneDesc('nok_bt02', 'nok_bt02'),
    new PaperMario64SceneDesc('nok_bt03', 'nok_bt03'),
    new PaperMario64SceneDesc('nok_bt04', 'nok_bt04'),

    "Koopa Bros. Fortress",
    new PaperMario64SceneDesc('trd_00', 'trd_00', 'nok_bg'),
    new PaperMario64SceneDesc('trd_01', 'trd_01'),
    new PaperMario64SceneDesc('trd_02', 'trd_02'),
    new PaperMario64SceneDesc('trd_03', 'trd_03'),
    new PaperMario64SceneDesc('trd_04', 'trd_04'),
    new PaperMario64SceneDesc('trd_05', 'trd_05'),
    new PaperMario64SceneDesc('trd_06', 'trd_06'),
    new PaperMario64SceneDesc('trd_07', 'trd_07'),
    new PaperMario64SceneDesc('trd_08', 'trd_08'),
    new PaperMario64SceneDesc('trd_09', 'trd_09', 'nok_bg'),
    new PaperMario64SceneDesc('trd_10', 'trd_10'),
    new PaperMario64SceneDesc('trd_bt00', 'trd_bt00'),
    new PaperMario64SceneDesc('trd_bt01', 'trd_bt01'),
    new PaperMario64SceneDesc('trd_bt02', 'trd_bt02'),
    new PaperMario64SceneDesc('trd_bt03', 'trd_bt03'),
    new PaperMario64SceneDesc('trd_bt04', 'trd_bt04'),
    new PaperMario64SceneDesc('trd_bt05', 'trd_bt05'),

    "Mt. Rugged",
    new PaperMario64SceneDesc('iwa_00', 'iwa_00', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_01', 'iwa_01', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_02', 'iwa_02', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_03', 'iwa_03', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_04', 'iwa_04', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_10', 'iwa_10', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_11', 'iwa_11', 'iwa_bg'),
    new PaperMario64SceneDesc('iwa_bt01', 'iwa_bt01'),
    new PaperMario64SceneDesc('iwa_bt02', 'iwa_bt02'),

    "Dry Dry Oasis",
    new PaperMario64SceneDesc('dro_01', 'dro_01', 'sbk_bg'),
    new PaperMario64SceneDesc('dro_02', 'dro_02', 'sbk_bg'),

    "Dry Dry Desert",
    new PaperMario64SceneDesc('sbk_00', 'sbk_00', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_01', 'sbk_01', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_02', 'sbk_02', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_03', 'sbk_03', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_04', 'sbk_04', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_05', 'sbk_05', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_06', 'sbk_06', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_10', 'sbk_10', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_11', 'sbk_11', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_12', 'sbk_12', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_13', 'sbk_13', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_14', 'sbk_14', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_15', 'sbk_15', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_16', 'sbk_16', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_20', 'sbk_20', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_21', 'sbk_21', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_22', 'sbk_22', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_23', 'sbk_23', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_24', 'sbk_24', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_25', 'sbk_25', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_26', 'sbk_26', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_30', 'sbk_30', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_31', 'sbk_31', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_32', 'sbk_32', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_33', 'sbk_33', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_34', 'sbk_34', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_35', 'sbk_35', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_36', 'sbk_36', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_40', 'sbk_40', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_41', 'sbk_41', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_42', 'sbk_42', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_43', 'sbk_43', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_44', 'sbk_44', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_45', 'sbk_45', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_46', 'sbk_46', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_50', 'sbk_50', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_51', 'sbk_51', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_52', 'sbk_52', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_53', 'sbk_53', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_54', 'sbk_54', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_55', 'sbk_55', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_56', 'sbk_56', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_60', 'sbk_60', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_61', 'sbk_61', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_62', 'sbk_62', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_63', 'sbk_63', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_64', 'sbk_64', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_65', 'sbk_65', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_66', 'sbk_66', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_99', 'sbk_99', 'sbk_bg'),
    new PaperMario64SceneDesc('sbk_bt02', 'sbk_bt02'),

    "Dry Dry Ruins",
    new PaperMario64SceneDesc('isk_01', 'isk_01', 'sbk3_bg'),
    new PaperMario64SceneDesc('isk_02', 'isk_02', 'sbk3_bg'),
    new PaperMario64SceneDesc('isk_03', 'isk_03'),
    new PaperMario64SceneDesc('isk_04', 'isk_04', 'sbk3_bg'),
    new PaperMario64SceneDesc('isk_05', 'isk_05'),
    new PaperMario64SceneDesc('isk_06', 'isk_06'),
    new PaperMario64SceneDesc('isk_07', 'isk_07'),
    new PaperMario64SceneDesc('isk_08', 'isk_08'),
    new PaperMario64SceneDesc('isk_09', 'isk_09'),
    new PaperMario64SceneDesc('isk_10', 'isk_10'),
    new PaperMario64SceneDesc('isk_11', 'isk_11'),
    new PaperMario64SceneDesc('isk_12', 'isk_12'),
    new PaperMario64SceneDesc('isk_13', 'isk_13'),
    new PaperMario64SceneDesc('isk_14', 'isk_14'),
    new PaperMario64SceneDesc('isk_16', 'isk_16'),
    new PaperMario64SceneDesc('isk_18', 'isk_18'),
    new PaperMario64SceneDesc('isk_19', 'isk_19'),
    new PaperMario64SceneDesc('isk_bt01', 'isk_bt01'),
    new PaperMario64SceneDesc('isk_bt02', 'isk_bt02'),
    new PaperMario64SceneDesc('isk_bt03', 'isk_bt03'),
    new PaperMario64SceneDesc('isk_bt04', 'isk_bt04'),
    new PaperMario64SceneDesc('isk_bt05', 'isk_bt05'),
    new PaperMario64SceneDesc('isk_bt06', 'isk_bt06'),
    new PaperMario64SceneDesc('isk_bt07', 'isk_bt07'),
    new PaperMario64SceneDesc('isk_bt08', 'isk_bt08'),

    "Forever Forest",
    new PaperMario64SceneDesc('mim_01', 'mim_01', 'obk_bg'),
    new PaperMario64SceneDesc('mim_02', 'mim_02', 'obk_bg'),
    new PaperMario64SceneDesc('mim_03', 'mim_03', 'obk_bg'),
    new PaperMario64SceneDesc('mim_04', 'mim_04', 'obk_bg'),
    new PaperMario64SceneDesc('mim_05', 'mim_05', 'obk_bg'),
    new PaperMario64SceneDesc('mim_06', 'mim_06', 'obk_bg'),
    new PaperMario64SceneDesc('mim_07', 'mim_07', 'obk_bg'),
    new PaperMario64SceneDesc('mim_08', 'mim_08', 'obk_bg'),
    new PaperMario64SceneDesc('mim_09', 'mim_09', 'obk_bg'),
    new PaperMario64SceneDesc('mim_10', 'mim_10', 'nok_bg'),
    new PaperMario64SceneDesc('mim_11', 'mim_11', 'obk_bg'),
    new PaperMario64SceneDesc('mim_12', 'mim_12', 'arn_bg'),
    new PaperMario64SceneDesc('mim_bt01', 'mim_bt01'),

    "Boo's Mansion",
    new PaperMario64SceneDesc('obk_01', 'obk_01'),
    new PaperMario64SceneDesc('obk_02', 'obk_02', 'obk_bg'),
    new PaperMario64SceneDesc('obk_03', 'obk_03'),
    new PaperMario64SceneDesc('obk_04', 'obk_04'),
    new PaperMario64SceneDesc('obk_05', 'obk_05', 'obk_bg'),
    new PaperMario64SceneDesc('obk_06', 'obk_06'),
    new PaperMario64SceneDesc('obk_07', 'obk_07', 'obk_bg'),
    new PaperMario64SceneDesc('obk_08', 'obk_08', 'obk_bg'),
    new PaperMario64SceneDesc('obk_09', 'obk_09'),

    "Gusty Gulch",
    new PaperMario64SceneDesc('arn_02', 'arn_02', 'arn_bg'),
    new PaperMario64SceneDesc('arn_03', 'arn_03', 'arn_bg'),
    new PaperMario64SceneDesc('arn_04', 'arn_04', 'arn_bg'),
    new PaperMario64SceneDesc('arn_05', 'arn_05', 'arn_bg'),
    new PaperMario64SceneDesc('arn_07', 'arn_07', 'arn_bg'),
    new PaperMario64SceneDesc('arn_08', 'arn_08'),
    new PaperMario64SceneDesc('arn_09', 'arn_09'),
    new PaperMario64SceneDesc('arn_10', 'arn_10'),
    new PaperMario64SceneDesc('arn_11', 'arn_11'),
    new PaperMario64SceneDesc('arn_12', 'arn_12'),
    new PaperMario64SceneDesc('arn_13', 'arn_13'),
    new PaperMario64SceneDesc('arn_20', 'arn_20'),
    new PaperMario64SceneDesc('arn_bt01', 'arn_bt01'),
    new PaperMario64SceneDesc('arn_bt02', 'arn_bt02'),
    new PaperMario64SceneDesc('arn_bt03', 'arn_bt03'),
    new PaperMario64SceneDesc('arn_bt04', 'arn_bt04'),
    new PaperMario64SceneDesc('arn_bt05', 'arn_bt05'),
    new PaperMario64SceneDesc('arn_bt06', 'arn_bt06'),

    "Tubba Bubba's Castle",
    new PaperMario64SceneDesc('dgb_01', 'dgb_01', 'arn_bg'),
    new PaperMario64SceneDesc('dgb_02', 'dgb_02'),
    new PaperMario64SceneDesc('dgb_03', 'dgb_03'),
    new PaperMario64SceneDesc('dgb_04', 'dgb_04'),
    new PaperMario64SceneDesc('dgb_05', 'dgb_05'),
    new PaperMario64SceneDesc('dgb_06', 'dgb_06'),
    new PaperMario64SceneDesc('dgb_07', 'dgb_07'),
    new PaperMario64SceneDesc('dgb_08', 'dgb_08'),
    new PaperMario64SceneDesc('dgb_09', 'dgb_09'),
    new PaperMario64SceneDesc('dgb_10', 'dgb_10'),
    new PaperMario64SceneDesc('dgb_11', 'dgb_11'),
    new PaperMario64SceneDesc('dgb_12', 'dgb_12'),
    new PaperMario64SceneDesc('dgb_13', 'dgb_13'),
    new PaperMario64SceneDesc('dgb_14', 'dgb_14'),
    new PaperMario64SceneDesc('dgb_15', 'dgb_15'),
    new PaperMario64SceneDesc('dgb_16', 'dgb_16'),
    new PaperMario64SceneDesc('dgb_17', 'dgb_17'),
    new PaperMario64SceneDesc('dgb_18', 'dgb_18'),
    new PaperMario64SceneDesc('dgb_bt01', 'dgb_bt01'),
    new PaperMario64SceneDesc('dgb_bt02', 'dgb_bt02'),
    new PaperMario64SceneDesc('dgb_bt03', 'dgb_bt03'),
    new PaperMario64SceneDesc('dgb_bt04', 'dgb_bt04'),
    new PaperMario64SceneDesc('dgb_bt05', 'dgb_bt05'),

    "Shy Guy's Toybox",
    new PaperMario64SceneDesc('omo_01', 'omo_01', 'omo_bg'),
    new PaperMario64SceneDesc('omo_02', 'omo_02', 'omo_bg'),
    new PaperMario64SceneDesc('omo_03', 'omo_03', 'omo_bg'),
    new PaperMario64SceneDesc('omo_04', 'omo_04', 'omo_bg'),
    new PaperMario64SceneDesc('omo_05', 'omo_05', 'omo_bg'),
    new PaperMario64SceneDesc('omo_06', 'omo_06', 'omo_bg'),
    new PaperMario64SceneDesc('omo_07', 'omo_07', 'omo_bg'),
    new PaperMario64SceneDesc('omo_08', 'omo_08', 'omo_bg'),
    new PaperMario64SceneDesc('omo_09', 'omo_09', 'omo_bg'),
    new PaperMario64SceneDesc('omo_10', 'omo_10', 'omo_bg'),
    new PaperMario64SceneDesc('omo_11', 'omo_11', 'omo_bg'),
    new PaperMario64SceneDesc('omo_12', 'omo_12'),
    new PaperMario64SceneDesc('omo_13', 'omo_13', 'omo_bg'),
    new PaperMario64SceneDesc('omo_14', 'omo_14'),
    new PaperMario64SceneDesc('omo_15', 'omo_15', 'omo_bg'),
    new PaperMario64SceneDesc('omo_16', 'omo_16', 'omo_bg'),
    new PaperMario64SceneDesc('omo_17', 'omo_17', 'omo_bg'),
    new PaperMario64SceneDesc('omo_bt01', 'omo_bt01'),
    new PaperMario64SceneDesc('omo_bt02', 'omo_bt02'),
    new PaperMario64SceneDesc('omo_bt03', 'omo_bt03'),
    new PaperMario64SceneDesc('omo_bt04', 'omo_bt04'),
    new PaperMario64SceneDesc('omo_bt05', 'omo_bt05'),
    new PaperMario64SceneDesc('omo_bt06', 'omo_bt06'),
    new PaperMario64SceneDesc('omo_bt07', 'omo_bt07'),

    "Lavalava Island",
    new PaperMario64SceneDesc('jan_00', 'jan_00', 'yos_bg'),
    new PaperMario64SceneDesc('jan_01', 'jan_01', 'yos_bg'),
    new PaperMario64SceneDesc('jan_02', 'jan_02', 'yos_bg'),
    new PaperMario64SceneDesc('jan_03', 'jan_03', 'yos_bg'),
    new PaperMario64SceneDesc('jan_04', 'jan_04', 'yos_bg'),
    new PaperMario64SceneDesc('jan_05', 'jan_05', 'yos_bg'),
    new PaperMario64SceneDesc('jan_06', 'jan_06', 'jan_bg'),
    new PaperMario64SceneDesc('jan_07', 'jan_07', 'yos_bg'),
    new PaperMario64SceneDesc('jan_08', 'jan_08', 'yos_bg'),
    new PaperMario64SceneDesc('jan_09', 'jan_09', 'yos_bg'),
    new PaperMario64SceneDesc('jan_10', 'jan_10', 'yos_bg'),
    new PaperMario64SceneDesc('jan_11', 'jan_11', 'jan_bg'),
    new PaperMario64SceneDesc('jan_12', 'jan_12', 'jan_bg'),
    new PaperMario64SceneDesc('jan_13', 'jan_13', 'jan_bg'),
    new PaperMario64SceneDesc('jan_14', 'jan_14', 'jan_bg'),
    new PaperMario64SceneDesc('jan_15', 'jan_15', 'jan_bg'),
    new PaperMario64SceneDesc('jan_16', 'jan_16', 'jan_bg'),
    new PaperMario64SceneDesc('jan_17', 'jan_17', 'jan_bg'),
    new PaperMario64SceneDesc('jan_18', 'jan_18', 'yos_bg'),
    new PaperMario64SceneDesc('jan_19', 'jan_19', 'jan_bg'),
    new PaperMario64SceneDesc('jan_22', 'jan_22', 'jan_bg'),
    new PaperMario64SceneDesc('jan_23', 'jan_23', 'yos_bg'),
    new PaperMario64SceneDesc('jan_bt00', 'jan_bt00'),
    new PaperMario64SceneDesc('jan_bt01', 'jan_bt01'),
    new PaperMario64SceneDesc('jan_bt02', 'jan_bt02'),
    new PaperMario64SceneDesc('jan_bt03', 'jan_bt03'),
    new PaperMario64SceneDesc('jan_bt04', 'jan_bt04'),

    "Mt. Lavalava",
    new PaperMario64SceneDesc('kzn_01', 'kzn_01'),
    new PaperMario64SceneDesc('kzn_02', 'kzn_02'),
    new PaperMario64SceneDesc('kzn_03', 'kzn_03'),
    new PaperMario64SceneDesc('kzn_04', 'kzn_04'),
    new PaperMario64SceneDesc('kzn_05', 'kzn_05'),
    new PaperMario64SceneDesc('kzn_06', 'kzn_06'),
    new PaperMario64SceneDesc('kzn_07', 'kzn_07'),
    new PaperMario64SceneDesc('kzn_08', 'kzn_08'),
    new PaperMario64SceneDesc('kzn_09', 'kzn_09'),
    new PaperMario64SceneDesc('kzn_10', 'kzn_10'),
    new PaperMario64SceneDesc('kzn_11', 'kzn_11'),
    new PaperMario64SceneDesc('kzn_17', 'kzn_17'),
    new PaperMario64SceneDesc('kzn_18', 'kzn_18'),
    new PaperMario64SceneDesc('kzn_19', 'kzn_19'),
    new PaperMario64SceneDesc('kzn_20', 'kzn_20'),
    new PaperMario64SceneDesc('kzn_22', 'kzn_22'),
    new PaperMario64SceneDesc('kzn_23', 'kzn_23', 'yos_bg'),
    new PaperMario64SceneDesc('kzn_bt01', 'kzn_bt01'),
    new PaperMario64SceneDesc('kzn_bt02', 'kzn_bt02'),
    new PaperMario64SceneDesc('kzn_bt04', 'kzn_bt04'),
    new PaperMario64SceneDesc('kzn_bt05', 'kzn_bt05'),

    "Flower Fields",
    new PaperMario64SceneDesc('flo_00', 'flo_00', 'fla_bg'),
    new PaperMario64SceneDesc('flo_03', 'flo_03', 'fla_bg'),
    new PaperMario64SceneDesc('flo_07', 'flo_07', 'fla_bg'),
    new PaperMario64SceneDesc('flo_08', 'flo_08', 'fla_bg'),
    new PaperMario64SceneDesc('flo_09', 'flo_09', 'fla_bg'),
    new PaperMario64SceneDesc('flo_10', 'flo_10', 'fla_bg'),
    new PaperMario64SceneDesc('flo_11', 'flo_11', 'fla_bg'),
    new PaperMario64SceneDesc('flo_12', 'flo_12', 'fla_bg'),
    new PaperMario64SceneDesc('flo_13', 'flo_13', 'fla_bg'),
    new PaperMario64SceneDesc('flo_14', 'flo_14', 'fla_bg'),
    new PaperMario64SceneDesc('flo_15', 'flo_15', 'fla_bg'),
    new PaperMario64SceneDesc('flo_16', 'flo_16', 'fla_bg'),
    new PaperMario64SceneDesc('flo_17', 'flo_17', 'fla_bg'),
    new PaperMario64SceneDesc('flo_18', 'flo_18', 'fla_bg'),
    new PaperMario64SceneDesc('flo_19', 'flo_19', 'sra_bg'),
    new PaperMario64SceneDesc('flo_21', 'flo_21', 'sra_bg'),
    new PaperMario64SceneDesc('flo_22', 'flo_22', 'fla_bg'),
    new PaperMario64SceneDesc('flo_23', 'flo_23', 'fla_bg'),
    new PaperMario64SceneDesc('flo_24', 'flo_24', 'fla_bg'),
    new PaperMario64SceneDesc('flo_25', 'flo_25', 'fla_bg'),
    new PaperMario64SceneDesc('flo_bt01', 'flo_bt01'),
    new PaperMario64SceneDesc('flo_bt02', 'flo_bt02'),
    new PaperMario64SceneDesc('flo_bt03', 'flo_bt03'),
    new PaperMario64SceneDesc('flo_bt04', 'flo_bt04'),
    new PaperMario64SceneDesc('flo_bt05', 'flo_bt05'),
    new PaperMario64SceneDesc('flo_bt06', 'flo_bt06'),

    "Shiver City",
    new PaperMario64SceneDesc('sam_01', 'sam_01', 'yki_bg'),
    new PaperMario64SceneDesc('sam_02', 'sam_02', 'yki_bg'),
    new PaperMario64SceneDesc('sam_03', 'sam_03', 'yki_bg'),
    new PaperMario64SceneDesc('sam_04', 'sam_04', 'yki_bg'),
    new PaperMario64SceneDesc('sam_05', 'sam_05', 'sam_bg'),
    new PaperMario64SceneDesc('sam_06', 'sam_06', 'sam_bg'),
    new PaperMario64SceneDesc('sam_07', 'sam_07', 'yki_bg'),
    new PaperMario64SceneDesc('sam_08', 'sam_08', 'yki_bg'),
    new PaperMario64SceneDesc('sam_09', 'sam_09', 'yki_bg'),
    new PaperMario64SceneDesc('sam_10', 'sam_10', 'yki_bg'),
    new PaperMario64SceneDesc('sam_11', 'sam_11', 'yki_bg'),
    new PaperMario64SceneDesc('sam_12', 'sam_12', 'yki_bg'),
    new PaperMario64SceneDesc('sam_bt01', 'sam_bt01'),
    new PaperMario64SceneDesc('sam_bt02', 'sam_bt02'),
    new PaperMario64SceneDesc('sam_bt03', 'sam_bt03'),
    new PaperMario64SceneDesc('sam_bt04', 'sam_bt04'),

    "Crystal Palace",
    new PaperMario64SceneDesc('pra_01', 'pra_01', 'yki_bg'),
    new PaperMario64SceneDesc('pra_02', 'pra_02'),
    new PaperMario64SceneDesc('pra_03', 'pra_03'),
    new PaperMario64SceneDesc('pra_04', 'pra_04'),
    new PaperMario64SceneDesc('pra_05', 'pra_05'),
    new PaperMario64SceneDesc('pra_09', 'pra_09'),
    new PaperMario64SceneDesc('pra_10', 'pra_10'),
    new PaperMario64SceneDesc('pra_11', 'pra_11'),
    new PaperMario64SceneDesc('pra_13', 'pra_13'),
    new PaperMario64SceneDesc('pra_14', 'pra_14'),
    new PaperMario64SceneDesc('pra_15', 'pra_15', 'yki_bg'),
    new PaperMario64SceneDesc('pra_16', 'pra_16'),
    new PaperMario64SceneDesc('pra_18', 'pra_18'),
    new PaperMario64SceneDesc('pra_19', 'pra_19'),
    new PaperMario64SceneDesc('pra_20', 'pra_20'),
    new PaperMario64SceneDesc('pra_21', 'pra_21'),
    new PaperMario64SceneDesc('pra_22', 'pra_22'),
    new PaperMario64SceneDesc('pra_29', 'pra_29'),
    new PaperMario64SceneDesc('pra_31', 'pra_31'),
    new PaperMario64SceneDesc('pra_32', 'pra_32', 'sam_bg'),
    new PaperMario64SceneDesc('pra_33', 'pra_33'),
    new PaperMario64SceneDesc('pra_34', 'pra_34'),
    new PaperMario64SceneDesc('pra_35', 'pra_35'),
    new PaperMario64SceneDesc('pra_40', 'pra_40'),
    new PaperMario64SceneDesc('pra_bt01', 'pra_bt01'),
    new PaperMario64SceneDesc('pra_bt02', 'pra_bt02'),
    new PaperMario64SceneDesc('pra_bt03', 'pra_bt03'),
    new PaperMario64SceneDesc('pra_bt04', 'pra_bt04'),

    "Outside Peach's Castle",
    new PaperMario64SceneDesc('osr_00', 'osr_00', 'nok_bg'),
    new PaperMario64SceneDesc('osr_01', 'osr_01', 'nok_bg'),
    new PaperMario64SceneDesc('osr_02', 'osr_02', 'kpa_bg'),
    new PaperMario64SceneDesc('osr_03', 'osr_03', 'kpa_bg'),

    "Bowser's Castle",
    new PaperMario64SceneDesc('kpa_01', 'kpa_01'),
    new PaperMario64SceneDesc('kpa_03', 'kpa_03'),
    new PaperMario64SceneDesc('kpa_04', 'kpa_04'),
    new PaperMario64SceneDesc('kpa_08', 'kpa_08'),
    new PaperMario64SceneDesc('kpa_09', 'kpa_09'),
    new PaperMario64SceneDesc('kpa_10', 'kpa_10'),
    new PaperMario64SceneDesc('kpa_11', 'kpa_11'),
    new PaperMario64SceneDesc('kpa_12', 'kpa_12'),
    new PaperMario64SceneDesc('kpa_13', 'kpa_13'),
    new PaperMario64SceneDesc('kpa_14', 'kpa_14'),
    new PaperMario64SceneDesc('kpa_15', 'kpa_15'),
    new PaperMario64SceneDesc('kpa_16', 'kpa_16'),
    new PaperMario64SceneDesc('kpa_17', 'kpa_17'),
    new PaperMario64SceneDesc('kpa_32', 'kpa_32', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_33', 'kpa_33', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_40', 'kpa_40'),
    new PaperMario64SceneDesc('kpa_41', 'kpa_41'),
    new PaperMario64SceneDesc('kpa_50', 'kpa_50'),
    new PaperMario64SceneDesc('kpa_52', 'kpa_52'),
    new PaperMario64SceneDesc('kpa_60', 'kpa_60', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_61', 'kpa_61', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_62', 'kpa_62', 'kpa_bg'),
    new PaperMario64SceneDesc('kpa_63', 'kpa_63'),
    new PaperMario64SceneDesc('kpa_70', 'kpa_70'),
    new PaperMario64SceneDesc('kpa_80', 'kpa_80'),
    new PaperMario64SceneDesc('kpa_90', 'kpa_90'),
    new PaperMario64SceneDesc('kpa_91', 'kpa_91'),
    new PaperMario64SceneDesc('kpa_94', 'kpa_94'),
    new PaperMario64SceneDesc('kpa_95', 'kpa_95'),
    new PaperMario64SceneDesc('kpa_96', 'kpa_96'),
    new PaperMario64SceneDesc('kpa_102', 'kpa_102'),
    new PaperMario64SceneDesc('kpa_111', 'kpa_111'),
    new PaperMario64SceneDesc('kpa_112', 'kpa_112'),
    new PaperMario64SceneDesc('kpa_113', 'kpa_113'),
    new PaperMario64SceneDesc('kpa_115', 'kpa_115'),
    new PaperMario64SceneDesc('kpa_116', 'kpa_116'),
    new PaperMario64SceneDesc('kpa_117', 'kpa_117'),
    new PaperMario64SceneDesc('kpa_118', 'kpa_118'),
    new PaperMario64SceneDesc('kpa_119', 'kpa_119'),
    new PaperMario64SceneDesc('kpa_121', 'kpa_121'),
    new PaperMario64SceneDesc('kpa_130', 'kpa_130'),
    new PaperMario64SceneDesc('kpa_133', 'kpa_133'),
    new PaperMario64SceneDesc('kpa_134', 'kpa_134'),
    new PaperMario64SceneDesc('kpa_bt01', 'kpa_bt01'),
    new PaperMario64SceneDesc('kpa_bt02', 'kpa_bt02'),
    new PaperMario64SceneDesc('kpa_bt03', 'kpa_bt03'),
    new PaperMario64SceneDesc('kpa_bt04', 'kpa_bt04'),
    new PaperMario64SceneDesc('kpa_bt05', 'kpa_bt05'),
    new PaperMario64SceneDesc('kpa_bt07', 'kpa_bt07'),
    new PaperMario64SceneDesc('kpa_bt08', 'kpa_bt08'),
    new PaperMario64SceneDesc('kpa_bt09', 'kpa_bt09'),
    new PaperMario64SceneDesc('kpa_bt11', 'kpa_bt11'),
    new PaperMario64SceneDesc('kpa_bt13', 'kpa_bt13'),
    new PaperMario64SceneDesc('kpa_bt14', 'kpa_bt14'),

    "Playroom",
    new PaperMario64SceneDesc('mgm_00', 'mgm_00'),
    new PaperMario64SceneDesc('mgm_01', 'mgm_01'),
    new PaperMario64SceneDesc('mgm_02', 'mgm_02'),
    new PaperMario64SceneDesc('mgm_03', 'mgm_03'),
    
    "System & Debug Maps",
    new PaperMario64SceneDesc('machi',  'machi',  'nok_bg'),
    new PaperMario64SceneDesc('tst_01', 'tst_01', 'nok_bg'),
    new PaperMario64SceneDesc('tst_02', 'tst_02', 'nok_bg'),
    new PaperMario64SceneDesc('tst_03', 'tst_03', 'nok_bg'),
    new PaperMario64SceneDesc('tst_04', 'tst_04', 'nok_bg'),
    new PaperMario64SceneDesc('tst_10', 'tst_10', 'nok_bg'),
    new PaperMario64SceneDesc('tst_11', 'tst_11', 'nok_bg'),
    new PaperMario64SceneDesc('tst_12', 'tst_12', 'nok_bg'),
    new PaperMario64SceneDesc('tst_13', 'tst_13', 'nok_bg'),
    new PaperMario64SceneDesc('tst_20', 'tst_20', 'nok_bg'),
    new PaperMario64SceneDesc('end_00', 'end_00'),
    new PaperMario64SceneDesc('end_01', 'end_01'),
    new PaperMario64SceneDesc('gv_01', 'gv_01'),
];

export const sceneGroup: Viewer.SceneGroup = { id, name, sceneDescs };
