export const HOOD_ID_DONALDS_DOCK = 1000;
export const HOOD_ID_TOONTOWN_CENTRAL = 2000;
export const HOOD_ID_THE_BRRRGH = 3000;
export const HOOD_ID_MINNIES_MELODYLAND = 4000;
export const HOOD_ID_DAISY_GARDENS = 5000;
export const HOOD_ID_OUTDOOR_ZONE = 6000;
export const HOOD_ID_FUNNY_FARM = 7000;
export const HOOD_ID_GOOFY_SPEEDWAY = 8000;
export const HOOD_ID_DONALDS_DREAMLAND = 9000;
export const HOOD_ID_TUTORIAL = 15000;
export const HOOD_ID_MY_ESTATE = 16000;
export const HOOD_ID_GOLF_ZONE = 17000;
export const HOOD_ID_PARTY_ZONE = 18000;

// Donald's Dock
export const ZONE_ID_BARNACLE_BOULEVARD = 1100;
export const ZONE_ID_SEAWEED_STREET = 1200;
export const ZONE_ID_LIGHTHOUSE_LANE = 1300;

// Toontown Central
export const ZONE_ID_SILLY_STREET = 2100;
export const ZONE_ID_LOOPY_LANE = 2200;
export const ZONE_ID_PUNCHLINE_PLACE = 2300;

// The Brrrgh
export const ZONE_ID_WALRUS_WAY = 3100;
export const ZONE_ID_SLEET_STREET = 3200;
export const ZONE_ID_POLAR_PLACE = 3300;

// Minnie's Melodyland
export const ZONE_ID_ALTO_AVE = 4100;
export const ZONE_ID_BARITONE_BOULEVARD = 4200;
export const ZONE_ID_TENOR_TERRACE = 4300;

// Daisy Gardens
export const ZONE_ID_ELM_STREET = 5100;
export const ZONE_ID_MAPLE_STREET = 5200;
export const ZONE_ID_OAK_STREET = 5300;

// Goofy Speedway
export const ZONE_ID_KART_SHOP = 8501;

// Donald's Dreamland
export const ZONE_ID_LULLABY_LANE = 9100;
export const ZONE_ID_PAJAMA_PLACE = 9200;

// Cog HQs
export const ZONE_ID_BOSSBOT_HQ = 10000;
export const ZONE_ID_BOSSBOT_LOBBY = 10100;
export const ZONE_ID_SELLBOT_HQ = 11000;
export const ZONE_ID_SELLBOT_LOBBY = 11100;
export const ZONE_ID_SELLBOT_FACTORY_EXT = 11200;
export const ZONE_ID_CASHBOT_HQ = 12000;
export const ZONE_ID_CASHBOT_LOBBY = 12100;
export const ZONE_ID_LAWBOT_HQ = 13000;
export const ZONE_ID_LAWBOT_LOBBY = 13100;
export const ZONE_ID_LAWBOT_OFFICE_EXT = 13200;

// Tutorial
export const ZONE_ID_TUTORIAL_TERRACE = 20000;

// Interior zones start at base zone ID + 500
export const ZONE_ID_INTERIOR_OFFSET = 500;

export const HOOD_HEIRARCHY: Map<number, number[]> = new Map([
  [
    HOOD_ID_TOONTOWN_CENTRAL,
    [
      HOOD_ID_TOONTOWN_CENTRAL,
      ZONE_ID_SILLY_STREET,
      ZONE_ID_LOOPY_LANE,
      ZONE_ID_PUNCHLINE_PLACE,
    ],
  ],
  [
    HOOD_ID_DONALDS_DOCK,
    [
      HOOD_ID_DONALDS_DOCK,
      ZONE_ID_BARNACLE_BOULEVARD,
      ZONE_ID_SEAWEED_STREET,
      ZONE_ID_LIGHTHOUSE_LANE,
    ],
  ],
  [
    HOOD_ID_MINNIES_MELODYLAND,
    [
      HOOD_ID_MINNIES_MELODYLAND,
      ZONE_ID_ALTO_AVE,
      ZONE_ID_BARITONE_BOULEVARD,
      ZONE_ID_TENOR_TERRACE,
    ],
  ],
  [
    HOOD_ID_DAISY_GARDENS,
    [
      HOOD_ID_DAISY_GARDENS,
      ZONE_ID_ELM_STREET,
      ZONE_ID_MAPLE_STREET,
      ZONE_ID_OAK_STREET,
    ],
  ],
  [
    HOOD_ID_THE_BRRRGH,
    [
      HOOD_ID_THE_BRRRGH,
      ZONE_ID_WALRUS_WAY,
      ZONE_ID_SLEET_STREET,
      ZONE_ID_POLAR_PLACE,
    ],
  ],
  [
    HOOD_ID_DONALDS_DREAMLAND,
    [HOOD_ID_DONALDS_DREAMLAND, ZONE_ID_LULLABY_LANE, ZONE_ID_PAJAMA_PLACE],
  ],
  [HOOD_ID_TUTORIAL, [ZONE_ID_TUTORIAL_TERRACE]],
  [HOOD_ID_GOOFY_SPEEDWAY, [HOOD_ID_GOOFY_SPEEDWAY, ZONE_ID_KART_SHOP]],
  [HOOD_ID_OUTDOOR_ZONE, [HOOD_ID_OUTDOOR_ZONE, HOOD_ID_GOLF_ZONE]],
  [HOOD_ID_MY_ESTATE, [HOOD_ID_MY_ESTATE, HOOD_ID_PARTY_ZONE]],
  [
    ZONE_ID_SELLBOT_HQ,
    [ZONE_ID_SELLBOT_HQ, ZONE_ID_SELLBOT_FACTORY_EXT, ZONE_ID_SELLBOT_LOBBY],
  ],
  [ZONE_ID_CASHBOT_HQ, [ZONE_ID_CASHBOT_HQ, ZONE_ID_CASHBOT_LOBBY]],
  [
    ZONE_ID_LAWBOT_HQ,
    [ZONE_ID_LAWBOT_HQ, ZONE_ID_LAWBOT_LOBBY, ZONE_ID_LAWBOT_OFFICE_EXT],
  ],
  [ZONE_ID_BOSSBOT_HQ, [ZONE_ID_BOSSBOT_HQ, ZONE_ID_BOSSBOT_LOBBY]],
]);

export const STREET_NAMES: Record<number, string> = {
  [ZONE_ID_TUTORIAL_TERRACE]: "Tutorial Terrace",
  [HOOD_ID_DONALDS_DOCK]: "Donald's Dock",
  [ZONE_ID_BARNACLE_BOULEVARD]: "Barnacle Boulevard",
  [ZONE_ID_SEAWEED_STREET]: "Seaweed Street",
  [ZONE_ID_LIGHTHOUSE_LANE]: "Lighthouse Lane",
  [HOOD_ID_TOONTOWN_CENTRAL]: "Toontown Central",
  [ZONE_ID_SILLY_STREET]: "Silly Street",
  [ZONE_ID_LOOPY_LANE]: "Loopy Lane",
  [ZONE_ID_PUNCHLINE_PLACE]: "Punchline Place",
  [HOOD_ID_THE_BRRRGH]: "The Brrrgh",
  [ZONE_ID_WALRUS_WAY]: "Walrus Way",
  [ZONE_ID_SLEET_STREET]: "Sleet Street",
  [ZONE_ID_POLAR_PLACE]: "Polar Place",
  [HOOD_ID_MINNIES_MELODYLAND]: "Minnie's Melodyland",
  [ZONE_ID_ALTO_AVE]: "Alto Avenue",
  [ZONE_ID_BARITONE_BOULEVARD]: "Baritone Boulevard",
  [ZONE_ID_TENOR_TERRACE]: "Tenor Terrace",
  [HOOD_ID_DAISY_GARDENS]: "Daisy Gardens",
  [ZONE_ID_ELM_STREET]: "Elm Street",
  [ZONE_ID_MAPLE_STREET]: "Maple Street",
  [ZONE_ID_OAK_STREET]: "Oak Street",
  [HOOD_ID_OUTDOOR_ZONE]: "Chip 'n Dale's Acorn Acres",
  [HOOD_ID_GOOFY_SPEEDWAY]: "Goofy Speedway",
  [HOOD_ID_DONALDS_DREAMLAND]: "Donald's Dreamland",
  [ZONE_ID_LULLABY_LANE]: "Lullaby Lane",
  [ZONE_ID_PAJAMA_PLACE]: "Pajama Place",
  [ZONE_ID_BOSSBOT_HQ]: "Bossbot Country Club",
  [ZONE_ID_BOSSBOT_LOBBY]: "Bossbot Clubhouse Lobby",
  [ZONE_ID_SELLBOT_HQ]: "Sellbot HQ Courtyard",
  [ZONE_ID_SELLBOT_LOBBY]: "Sellbot HQ Lobby",
  [ZONE_ID_SELLBOT_FACTORY_EXT]: "Sellbot Factory Exterior",
  [ZONE_ID_CASHBOT_HQ]: "Cashbot Train Yard",
  [ZONE_ID_CASHBOT_LOBBY]: "Cashbot HQ Lobby",
  [ZONE_ID_LAWBOT_HQ]: "Lawbot HQ Courtyard",
  [ZONE_ID_LAWBOT_LOBBY]: "Courthouse Lobby",
  [ZONE_ID_LAWBOT_OFFICE_EXT]: "DA's Office Lobby",
  [HOOD_ID_TUTORIAL]: "Tutorial",
  [HOOD_ID_MY_ESTATE]: "Estate",
  [HOOD_ID_GOLF_ZONE]: "Chip 'n Dale's MiniGolf",
  [HOOD_ID_PARTY_ZONE]: "Party Zone",
};

export function getHoodId(zoneId: number): number {
  return zoneId - (zoneId % 1000);
}

export function isCogHqZone(zoneId: number): boolean {
  return zoneId >= 10000 && zoneId < 15000;
}

export function getBranchZone(zoneId: number): number {
  let branchId = zoneId - (zoneId % 100);
  if (!isCogHqZone(zoneId) && zoneId % 1000 >= ZONE_ID_INTERIOR_OFFSET) {
    branchId -= ZONE_ID_INTERIOR_OFFSET;
  }
  return branchId;
}

export const INTERFACE_FONT_PATH = "phase_3/models/fonts/ImpressBT.ttf";
export const MINNIE_FONT_PATH = "phase_3/models/fonts/MinnieFont";
export const SUIT_FONT_PATH = "phase_3/models/fonts/vtRemingtonPortable";

export enum InteriorZoneType {
  GagShop,
  ToonHQ,
  ClothingShop,
  ToonInterior,
  PetShop,
  KartShop,
}

export const INTERIOR_ZONE_DATA: Record<number, [string, InteriorZoneType]> = {
  1506: ["Gag Shop", InteriorZoneType.GagShop],
  1507: ["Toon Headquarters", InteriorZoneType.ToonHQ],
  1508: ["Clothing Shop", InteriorZoneType.ClothingShop],
  1510: ["", InteriorZoneType.PetShop],
  1602: ["Used Life Preservers", InteriorZoneType.ToonInterior],
  1604: ["Wet Suit Dry Cleaners", InteriorZoneType.ToonInterior],
  1606: ["Hook's Clock Repair", InteriorZoneType.ToonInterior],
  1608: ["Luff 'N Stuff", InteriorZoneType.ToonInterior],
  1609: ["Every Little Bait", InteriorZoneType.ToonInterior],
  1612: ["Dime & Quarterdeck Bank", InteriorZoneType.ToonInterior],
  1613: ["Squid Pro Quo, Attorneys at Law", InteriorZoneType.ToonInterior],
  1614: ["Trim the Nail Boutique", InteriorZoneType.ToonInterior],
  1615: ["Yacht's All, Folks!", InteriorZoneType.ToonInterior],
  1616: ["Blackbeard's Beauty Parlor", InteriorZoneType.ToonInterior],
  1617: ["Out to See Optics", InteriorZoneType.ToonInterior],
  1619: ["Disembark! Tree Surgeons", InteriorZoneType.ToonInterior],
  1620: ["From Fore to Aft", InteriorZoneType.ToonInterior],
  1621: ["Poop Deck Gym", InteriorZoneType.ToonInterior],
  1622: ["Bait and Switches Electrical Shop", InteriorZoneType.ToonInterior],
  1624: ["Soles Repaired While U Wait", InteriorZoneType.ToonInterior],
  1626: ["Salmon Chanted Evening Formal Wear", InteriorZoneType.ToonInterior],
  1627: [
    "Billy Budd's Big Bargain Binnacle Barn",
    InteriorZoneType.ToonInterior,
  ],
  1628: ["Piano Tuna", InteriorZoneType.ToonInterior],
  1629: ["", InteriorZoneType.ToonHQ],
  1701: ["Buoys and Gulls Nursery School", InteriorZoneType.ToonInterior],
  1703: ["Wok the Plank Chinese Food", InteriorZoneType.ToonInterior],
  1705: ["Sails for Sale", InteriorZoneType.ToonInterior],
  1706: ["Peanut Butter and Jellyfish", InteriorZoneType.ToonInterior],
  1707: ["Gifts With a Porpoise", InteriorZoneType.ToonInterior],
  1709: ["Windjammers and Jellies", InteriorZoneType.ToonInterior],
  1710: ["Barnacle Bargains", InteriorZoneType.ToonInterior],
  1711: ["Deep Sea Diner", InteriorZoneType.ToonInterior],
  1712: ["Able-Bodied Gym", InteriorZoneType.ToonInterior],
  1713: ["Art's Smart Chart Mart", InteriorZoneType.ToonInterior],
  1714: ["Reel 'Em Inn", InteriorZoneType.ToonInterior],
  1716: ["Mermaid Swimwear", InteriorZoneType.ToonInterior],
  1717: ["Be More Pacific Ocean Notions", InteriorZoneType.ToonInterior],
  1718: ["Run Aground Taxi Service", InteriorZoneType.ToonInterior],
  1719: ["Duck's Back Water Company", InteriorZoneType.ToonInterior],
  1720: ["The Reel Deal", InteriorZoneType.ToonInterior],
  1721: ["All For Nautical", InteriorZoneType.ToonInterior],
  1723: ["Squid's Seaweed", InteriorZoneType.ToonInterior],
  1724: ["That's  a Moray!", InteriorZoneType.ToonInterior],
  1725: ["Ahab's Prefab Sea Crab Center", InteriorZoneType.ToonInterior],
  1726: ["Root Beer Afloats", InteriorZoneType.ToonInterior],
  1727: ["This Oar That", InteriorZoneType.ToonInterior],
  1728: ["Good Luck Horseshoe Crabs", InteriorZoneType.ToonInterior],
  1729: ["", InteriorZoneType.ToonHQ],
  1802: ["Nautical But Nice", InteriorZoneType.ToonInterior],
  1804: ["Mussel Beach Gymnasium", InteriorZoneType.ToonInterior],
  1805: ["Tackle Box Lunches", InteriorZoneType.ToonInterior],
  1806: ["Cap Size Hat Store", InteriorZoneType.ToonInterior],
  1807: ["Keel Deals", InteriorZoneType.ToonInterior],
  1808: ["Knots So Fast", InteriorZoneType.ToonInterior],
  1809: ["Rusty Buckets", InteriorZoneType.ToonInterior],
  1810: ["Anchor Management", InteriorZoneType.ToonInterior],
  1811: ["What's Canoe With You?", InteriorZoneType.ToonInterior],
  1813: ["Pier Pressure Plumbing", InteriorZoneType.ToonInterior],
  1814: ["The Yo Ho Stop and Go", InteriorZoneType.ToonInterior],
  1815: ["What's Up, Dock?", InteriorZoneType.ToonInterior],
  1818: ["Seven Seas Cafe", InteriorZoneType.ToonInterior],
  1819: ["Docker's Diner", InteriorZoneType.ToonInterior],
  1820: ["Hook, Line, and Sinker Prank Shop", InteriorZoneType.ToonInterior],
  1821: ["King Neptoon's Cannery", InteriorZoneType.ToonInterior],
  1823: ["The Clam Bake Diner", InteriorZoneType.ToonInterior],
  1824: ["Dog Paddles", InteriorZoneType.ToonInterior],
  1825: ["Wholly Mackerel! Fish Market", InteriorZoneType.ToonInterior],
  1826: ["Claggart's Clever Clovis Closet", InteriorZoneType.ToonInterior],
  1828: ["Alice's Ballast Palace", InteriorZoneType.ToonInterior],
  1829: ["Seagull Statue Store", InteriorZoneType.ToonInterior],
  1830: ["Lost and Flounder", InteriorZoneType.ToonInterior],
  1831: ["Kelp Around the House", InteriorZoneType.ToonInterior],
  1832: ["Melville's Massive Mizzenmast Mart", InteriorZoneType.ToonInterior],
  1833: [
    "This Transom Man Custom Tailored Suits",
    InteriorZoneType.ToonInterior,
  ],
  1834: ["Rudderly Ridiculous!", InteriorZoneType.ToonInterior],
  1835: ["", InteriorZoneType.ToonHQ],
  2513: ["Toon Hall", InteriorZoneType.ToonInterior],
  2514: ["Toontown Bank", InteriorZoneType.ToonInterior],
  2516: ["Toontown School House", InteriorZoneType.ToonInterior],
  2518: ["Toontown Library", InteriorZoneType.ToonInterior],
  2519: ["Gag Shop", InteriorZoneType.GagShop],
  2520: ["Toon HQ", InteriorZoneType.ToonHQ],
  2521: ["Clothing Shop", InteriorZoneType.ClothingShop],
  2522: ["Pet Shop", InteriorZoneType.PetShop],
  2601: ["All Smiles Tooth Repair", InteriorZoneType.ToonInterior],
  2602: ["", InteriorZoneType.ToonInterior],
  2603: ["One-Liner Miners", InteriorZoneType.ToonInterior],
  2604: ["Hogwash & Dry", InteriorZoneType.ToonInterior],
  2605: ["Toontown Sign Factory", InteriorZoneType.ToonInterior],
  2606: ["", InteriorZoneType.ToonInterior],
  2607: ["Jumping Beans", InteriorZoneType.ToonInterior],
  2610: ["Dr. Tom Foolery", InteriorZoneType.ToonInterior],
  2611: ["", InteriorZoneType.ToonInterior],
  2616: ["Weird Beard's Disguise Shop", InteriorZoneType.ToonInterior],
  2617: ["Silly Stunts", InteriorZoneType.ToonInterior],
  2618: ["All That Razz", InteriorZoneType.ToonInterior],
  2621: ["Paper Airplanes", InteriorZoneType.ToonInterior],
  2624: ["Happy Hooligans", InteriorZoneType.ToonInterior],
  2625: ["House of Bad Pies", InteriorZoneType.ToonInterior],
  2626: ["Jesse's Joke Repair", InteriorZoneType.ToonInterior],
  2629: ["The Laughin' Place", InteriorZoneType.ToonInterior],
  2632: ["Clown Class", InteriorZoneType.ToonInterior],
  2633: ["Tee-Hee Tea Shop", InteriorZoneType.ToonInterior],
  2638: ["Toontown Playhouse", InteriorZoneType.ToonInterior],
  2639: ["Monkey Tricks", InteriorZoneType.ToonInterior],
  2643: ["Canned Bottles", InteriorZoneType.ToonInterior],
  2644: ["Impractical Jokes", InteriorZoneType.ToonInterior],
  2649: ["All Fun and Games Shop", InteriorZoneType.ToonInterior],
  2652: ["", InteriorZoneType.ToonInterior],
  2653: ["", InteriorZoneType.ToonInterior],
  2654: ["Laughing Lessons", InteriorZoneType.ToonInterior],
  2655: ["Funny Money Savings & Loan", InteriorZoneType.ToonInterior],
  2656: ["Used Clown Cars", InteriorZoneType.ToonInterior],
  2657: ["Frank's Pranks", InteriorZoneType.ToonInterior],
  2659: ["Joy Buzzers to the World", InteriorZoneType.ToonInterior],
  2660: ["Tickle Machines", InteriorZoneType.ToonInterior],
  2661: ["Daffy Taffy", InteriorZoneType.ToonInterior],
  2662: ["Dr. I.M. Euphoric", InteriorZoneType.ToonInterior],
  2663: ["Toontown Cinerama", InteriorZoneType.ToonInterior],
  2664: ["The Merry Mimes", InteriorZoneType.ToonInterior],
  2665: ["Mary's Go Around Travel Company", InteriorZoneType.ToonInterior],
  2666: ["Laughing Gas Station", InteriorZoneType.ToonInterior],
  2667: ["Happy Times", InteriorZoneType.ToonInterior],
  2669: ["Muldoon's Maroon Balloons", InteriorZoneType.ToonInterior],
  2670: ["Soup Forks", InteriorZoneType.ToonInterior],
  2671: ["", InteriorZoneType.ToonHQ],
  2701: ["", InteriorZoneType.ToonInterior],
  2704: ["Movie Multiplex", InteriorZoneType.ToonInterior],
  2705: ["Wiseacre's Noisemakers", InteriorZoneType.ToonInterior],
  2708: ["Blue Glue", InteriorZoneType.ToonInterior],
  2711: ["Toontown Post Office", InteriorZoneType.ToonInterior],
  2712: ["Chortle Cafe", InteriorZoneType.ToonInterior],
  2713: ["Laughter Hours Cafe", InteriorZoneType.ToonInterior],
  2714: ["Kooky CinePlex", InteriorZoneType.ToonInterior],
  2716: ["Soup and Crack Ups", InteriorZoneType.ToonInterior],
  2717: ["Bottled Cans", InteriorZoneType.ToonInterior],
  2720: ["Crack Up Auto Repair", InteriorZoneType.ToonInterior],
  2725: ["", InteriorZoneType.ToonInterior],
  2727: ["Seltzer Bottles and Cans", InteriorZoneType.ToonInterior],
  2728: ["Vanishing Cream", InteriorZoneType.ToonInterior],
  2729: ["14 Karat Goldfish", InteriorZoneType.ToonInterior],
  2730: ["News for the Amused", InteriorZoneType.ToonInterior],
  2731: ["", InteriorZoneType.ToonInterior],
  2732: ["Spaghetti and Goofballs", InteriorZoneType.ToonInterior],
  2733: ["Cast Iron Kites", InteriorZoneType.ToonInterior],
  2734: ["Suction Cups and Saucers", InteriorZoneType.ToonInterior],
  2735: ["The Kaboomery", InteriorZoneType.ToonInterior],
  2739: ["Sidesplitter's Mending", InteriorZoneType.ToonInterior],
  2740: ["Used Firecrackers", InteriorZoneType.ToonInterior],
  2741: ["", InteriorZoneType.ToonInterior],
  2742: ["", InteriorZoneType.ToonHQ],
  2743: ["Ragtime Dry Cleaners", InteriorZoneType.ToonInterior],
  2744: ["", InteriorZoneType.ToonInterior],
  2747: ["Visible Ink", InteriorZoneType.ToonInterior],
  2748: ["Jest for Laughs", InteriorZoneType.ToonInterior],
  2801: ["Sofa Whoopee Cushions", InteriorZoneType.ToonInterior],
  2802: ["Inflatable Wrecking Balls", InteriorZoneType.ToonInterior],
  2803: ["The Karnival Kid", InteriorZoneType.ToonInterior],
  2804: ["Dr. Pulyurleg, Chiropractor", InteriorZoneType.ToonInterior],
  2805: ["", InteriorZoneType.ToonInterior],
  2809: ["The Punch Line Gym", InteriorZoneType.ToonInterior],
  2814: ["Toontown Theatre", InteriorZoneType.ToonInterior],
  2818: ["The Flying Pie", InteriorZoneType.ToonInterior],
  2821: ["", InteriorZoneType.ToonInterior],
  2822: ["Rubber Chicken Sandwiches", InteriorZoneType.ToonInterior],
  2823: ["Sundae Funnies Ice Cream", InteriorZoneType.ToonInterior],
  2824: ["Punchline Movie Palace", InteriorZoneType.ToonInterior],
  2829: ["Phony Baloney", InteriorZoneType.ToonInterior],
  2830: ["Zippy's Zingers", InteriorZoneType.ToonInterior],
  2831: ["Professor Wiggle's House of Giggles", InteriorZoneType.ToonInterior],
  2832: ["", InteriorZoneType.ToonHQ],
  2833: ["", InteriorZoneType.ToonInterior],
  2834: ["Funny Bone Emergency Room", InteriorZoneType.ToonInterior],
  2836: ["", InteriorZoneType.ToonInterior],
  2837: ["Hardy Harr Seminars", InteriorZoneType.ToonInterior],
  2839: ["Barely Palatable Pasta", InteriorZoneType.ToonInterior],
  2841: ["", InteriorZoneType.ToonInterior],
  3507: ["Gag Shop", InteriorZoneType.GagShop],
  3508: ["Toon HQ", InteriorZoneType.ToonHQ],
  3509: ["Clothing Shop", InteriorZoneType.ClothingShop],
  3511: ["", InteriorZoneType.PetShop],
  3601: ["Northern Lights Electric Company", InteriorZoneType.ToonInterior],
  3602: ["Nor'easter Bonnets", InteriorZoneType.ToonInterior],
  3605: ["", InteriorZoneType.ToonInterior],
  3607: ["The Blizzard Wizard", InteriorZoneType.ToonInterior],
  3608: ["Nothing to Luge", InteriorZoneType.ToonInterior],
  3610: ["Mike's Massive Mukluk Mart", InteriorZoneType.ToonInterior],
  3611: ["Mr. Cow's Snow Plows", InteriorZoneType.ToonInterior],
  3612: ["Igloo Design", InteriorZoneType.ToonInterior],
  3613: ["Ice Cycle Bikes", InteriorZoneType.ToonInterior],
  3614: ["Snowflakes Cereal Company", InteriorZoneType.ToonInterior],
  3615: ["Fried Baked Alaskas", InteriorZoneType.ToonInterior],
  3617: ["Cold Air Balloon Rides", InteriorZoneType.ToonInterior],
  3618: ["Snow Big Deal! Crisis Management", InteriorZoneType.ToonInterior],
  3620: ["Skiing Clinic", InteriorZoneType.ToonInterior],
  3621: ["The Melting Ice Cream Bar", InteriorZoneType.ToonInterior],
  3622: ["", InteriorZoneType.ToonInterior],
  3623: ["The Mostly Toasty Bread Company", InteriorZoneType.ToonInterior],
  3624: ["Subzero Sandwich Shop", InteriorZoneType.ToonInterior],
  3625: ["Auntie Freeze's Radiator Supply", InteriorZoneType.ToonInterior],
  3627: ["St. Bernard Kennel Club", InteriorZoneType.ToonInterior],
  3629: ["Pea Soup Cafe", InteriorZoneType.ToonInterior],
  3630: ["Icy London, Icy France Travel Agency", InteriorZoneType.ToonInterior],
  3634: ["Easy Chair Lifts", InteriorZoneType.ToonInterior],
  3635: ["Used Firewood", InteriorZoneType.ToonInterior],
  3636: ["Affordable Goosebumps", InteriorZoneType.ToonInterior],
  3637: ["Kate's Skates", InteriorZoneType.ToonInterior],
  3638: ["Toboggan or Not Toboggan", InteriorZoneType.ToonInterior],
  3641: ["Fred's Red Sled Beds", InteriorZoneType.ToonInterior],
  3642: ["Eye of the Storm Optics", InteriorZoneType.ToonInterior],
  3643: ["Snowball Hall", InteriorZoneType.ToonInterior],
  3644: ["Melted Ice Cubes", InteriorZoneType.ToonInterior],
  3647: ["The Sanguine Penguin Tuxedo Shop", InteriorZoneType.ToonInterior],
  3648: ["Instant Ice", InteriorZoneType.ToonInterior],
  3649: ["Hambrrrgers", InteriorZoneType.ToonInterior],
  3650: ["Antarctic Antiques", InteriorZoneType.ToonInterior],
  3651: ["Frosty Freddy's Frozen Frankfurters", InteriorZoneType.ToonInterior],
  3653: ["Ice House Jewelry", InteriorZoneType.ToonInterior],
  3654: ["", InteriorZoneType.ToonHQ],
  3702: ["Winter Storage", InteriorZoneType.ToonInterior],
  3703: ["", InteriorZoneType.ToonInterior],
  3705: ["Icicles Built for Two", InteriorZoneType.ToonInterior],
  3706: ["Shiverin' Shakes Malt Shop", InteriorZoneType.ToonInterior],
  3707: ["Snowplace Like Home", InteriorZoneType.ToonInterior],
  3708: ["Pluto's Place", InteriorZoneType.ToonInterior],
  3710: ["Dropping Degrees Diner", InteriorZoneType.ToonInterior],
  3711: ["", InteriorZoneType.ToonInterior],
  3712: ["Go With the Floe", InteriorZoneType.ToonInterior],
  3713: ["Chattering Teeth, Subzero Dentist", InteriorZoneType.ToonInterior],
  3715: ["Aunt Arctic's Soup Shop", InteriorZoneType.ToonInterior],
  3716: ["Road Salt and Pepper", InteriorZoneType.ToonInterior],
  3717: ["Juneau What I Mean?", InteriorZoneType.ToonInterior],
  3718: ["Designer Inner Tubes", InteriorZoneType.ToonInterior],
  3719: ["Ice Cube on a Stick", InteriorZoneType.ToonInterior],
  3721: ["Noggin's Toboggan Bargains", InteriorZoneType.ToonInterior],
  3722: ["Snow Bunny Ski Shop", InteriorZoneType.ToonInterior],
  3723: ["Shakey's Snow Globes", InteriorZoneType.ToonInterior],
  3724: ["The Chattering Chronicle", InteriorZoneType.ToonInterior],
  3725: ["You Sleigh Me", InteriorZoneType.ToonInterior],
  3726: ["Solar Powered Blankets", InteriorZoneType.ToonInterior],
  3728: ["Lowbrow Snowplows", InteriorZoneType.ToonInterior],
  3729: ["", InteriorZoneType.ToonInterior],
  3730: ["Snowmen Bought & Sold", InteriorZoneType.ToonInterior],
  3731: ["Portable Fireplaces", InteriorZoneType.ToonInterior],
  3732: ["The Frozen Nose", InteriorZoneType.ToonInterior],
  3734: ["Icy Fine, Do You? Optometry", InteriorZoneType.ToonInterior],
  3735: ["Polar Ice Caps", InteriorZoneType.ToonInterior],
  3736: ["Diced Ice at a Nice Price", InteriorZoneType.ToonInterior],
  3737: ["Downhill Diner", InteriorZoneType.ToonInterior],
  3738: ["Heat-Get It While It's Hot", InteriorZoneType.ToonInterior],
  3739: ["", InteriorZoneType.ToonHQ],
  3801: ["Toon HQ", InteriorZoneType.ToonHQ],
  3806: ["Alpine Chow Line", InteriorZoneType.ToonInterior],
  3807: ["Used Groundhog Shadows", InteriorZoneType.ToonInterior],
  3808: ["The Sweater Lodge", InteriorZoneType.ToonInterior],
  3809: ["Ice Saw It Too", InteriorZoneType.ToonInterior],
  3810: ["A Better Built Quilt", InteriorZoneType.ToonInterior],
  3811: ["Your Snow Angel", InteriorZoneType.ToonInterior],
  3812: ["Mittens for Kittens", InteriorZoneType.ToonInterior],
  3813: ["Snowshoes You Can't Refuse", InteriorZoneType.ToonInterior],
  3814: ["Malt in Your Mouth Soda Fountain", InteriorZoneType.ToonInterior],
  3815: ["The Toupee Chalet", InteriorZoneType.ToonInterior],
  3816: ["Just So Mistletoe", InteriorZoneType.ToonInterior],
  3817: ["Winter Wonderland Walking Club", InteriorZoneType.ToonInterior],
  3818: ["The Shovel Hovel", InteriorZoneType.ToonInterior],
  3819: ["Clean Sweep Chimney Service", InteriorZoneType.ToonInterior],
  3820: ["Snow Whitening", InteriorZoneType.ToonInterior],
  3821: ["Hibernation Vacations", InteriorZoneType.ToonInterior],
  3823: ["Precipitation Foundation", InteriorZoneType.ToonInterior],
  3824: ["Open Fire Chestnut Roasting", InteriorZoneType.ToonInterior],
  3825: ["Cool Cat Hats", InteriorZoneType.ToonInterior],
  3826: ["Oh My Galoshes!", InteriorZoneType.ToonInterior],
  3827: ["Choral Wreaths", InteriorZoneType.ToonInterior],
  3828: ["Snowman's Land", InteriorZoneType.ToonInterior],
  3829: ["Pinecone Zone", InteriorZoneType.ToonInterior],
  3830: ["Wait and See Goggle Defogging", InteriorZoneType.ToonInterior],
  4503: ["Gag Shop", InteriorZoneType.GagShop],
  4504: ["Toon Headquarters", InteriorZoneType.ToonHQ],
  4506: ["Clothing Shop", InteriorZoneType.ClothingShop],
  4508: ["", InteriorZoneType.PetShop],
  4603: ["Tom-Tom's Drums", InteriorZoneType.ToonInterior],
  4604: ["In Four-Four Time", InteriorZoneType.ToonInterior],
  4605: ["Fifi's Fiddles", InteriorZoneType.ToonInterior],
  4606: ["Casa De Castanets", InteriorZoneType.ToonInterior],
  4607: ["Catchy Toon Apparel", InteriorZoneType.ToonInterior],
  4609: ["Do, Rae, Me Piano Keys", InteriorZoneType.ToonInterior],
  4610: ["Please Refrain", InteriorZoneType.ToonInterior],
  4611: ["Tuning Forks and Spoons", InteriorZoneType.ToonInterior],
  4612: ["Dr. Fret's Dentistry", InteriorZoneType.ToonInterior],
  4614: ["Shave and a Haircut for a Song", InteriorZoneType.ToonInterior],
  4615: ["Piccolo's Pizza", InteriorZoneType.ToonInterior],
  4617: ["Happy Mandolins", InteriorZoneType.ToonInterior],
  4618: ["Rests Rooms", InteriorZoneType.ToonInterior],
  4619: ["More Scores", InteriorZoneType.ToonInterior],
  4622: ["Chin Rest Pillows", InteriorZoneType.ToonInterior],
  4623: ["Flats Sharpened", InteriorZoneType.ToonInterior],
  4625: ["Tuba Toothpaste", InteriorZoneType.ToonInterior],
  4626: ["Notations", InteriorZoneType.ToonInterior],
  4628: ["Accidental Insurance", InteriorZoneType.ToonInterior],
  4629: ["Riff's Paper Plates", InteriorZoneType.ToonInterior],
  4630: ["Music Is Our Forte", InteriorZoneType.ToonInterior],
  4631: ["Canto Help You", InteriorZoneType.ToonInterior],
  4632: ["Dance Around the Clock Shop", InteriorZoneType.ToonInterior],
  4635: ["Tenor Times", InteriorZoneType.ToonInterior],
  4637: ["For Good Measure", InteriorZoneType.ToonInterior],
  4638: ["Hard Rock Shop", InteriorZoneType.ToonInterior],
  4639: ["Four Score Antiques", InteriorZoneType.ToonInterior],
  4641: ["Blues News", InteriorZoneType.ToonInterior],
  4642: ["Ragtime Dry Cleaners", InteriorZoneType.ToonInterior],
  4645: ["Club 88", InteriorZoneType.ToonInterior],
  4646: ["", InteriorZoneType.ToonInterior],
  4648: ["Carry a Toon Movers", InteriorZoneType.ToonInterior],
  4649: ["", InteriorZoneType.ToonInterior],
  4652: ["Full Stop Shop", InteriorZoneType.ToonInterior],
  4653: ["", InteriorZoneType.ToonInterior],
  4654: ["Pitch Perfect Roofing", InteriorZoneType.ToonInterior],
  4655: ["The Treble Chef's Cooking School", InteriorZoneType.ToonInterior],
  4656: ["", InteriorZoneType.ToonInterior],
  4657: ["Barbershop Quartet", InteriorZoneType.ToonInterior],
  4658: ["Plummeting Pianos", InteriorZoneType.ToonInterior],
  4659: ["", InteriorZoneType.ToonHQ],
  4701: ["The Schmaltzy Waltz School of Dance", InteriorZoneType.ToonInterior],
  4702: [
    "Timbre! Equipment for the Singing Lumberjack",
    InteriorZoneType.ToonInterior,
  ],
  4703: ["I Can Handel It!", InteriorZoneType.ToonInterior],
  4704: ["Tina's Concertina Concerts", InteriorZoneType.ToonInterior],
  4705: ["Zither Here Nor There", InteriorZoneType.ToonInterior],
  4707: ["Doppler's Sound Effects Studio", InteriorZoneType.ToonInterior],
  4709: ["On Ballet! Climbing Supplies", InteriorZoneType.ToonInterior],
  4710: [
    "Hurry Up, Slow Polka! School of Driving",
    InteriorZoneType.ToonInterior,
  ],
  4712: ["C-Flat Tire Repair", InteriorZoneType.ToonInterior],
  4713: ["B-Sharp Fine Menswear", InteriorZoneType.ToonInterior],
  4716: ["Four-Part Harmonicas", InteriorZoneType.ToonInterior],
  4717: [
    "Sonata Your Fault! Discount Auto Insurance",
    InteriorZoneType.ToonInterior,
  ],
  4718: [
    "Chopin Blocks and Other Kitchen Supplies",
    InteriorZoneType.ToonInterior,
  ],
  4719: ["Madrigal Motor Homes", InteriorZoneType.ToonInterior],
  4720: ["Name That Toon", InteriorZoneType.ToonInterior],
  4722: ["Overture Understudies", InteriorZoneType.ToonInterior],
  4723: ["Haydn Go Seek Playground Supplies", InteriorZoneType.ToonInterior],
  4724: ["White Noise for Girls and Boys", InteriorZoneType.ToonInterior],
  4725: ["The Baritone Barber", InteriorZoneType.ToonInterior],
  4727: ["Vocal Chords Braided", InteriorZoneType.ToonInterior],
  4728: ["Sing Solo We Can't Hear You", InteriorZoneType.ToonInterior],
  4729: ["Double Reed Bookstore", InteriorZoneType.ToonInterior],
  4730: ["Lousy Lyrics", InteriorZoneType.ToonInterior],
  4731: ["Toon Tunes", InteriorZoneType.ToonInterior],
  4732: ["Etude Brute? Theatre Company", InteriorZoneType.ToonInterior],
  4733: ["", InteriorZoneType.ToonInterior],
  4734: ["", InteriorZoneType.ToonInterior],
  4735: [
    "Accordions, If You Want In, Just Bellow!",
    InteriorZoneType.ToonInterior,
  ],
  4736: ["Her and Hymn Wedding Planners", InteriorZoneType.ToonInterior],
  4737: ["Harp Tarps", InteriorZoneType.ToonInterior],
  4738: ["Canticle Your Fancy Gift Shop", InteriorZoneType.ToonInterior],
  4739: ["", InteriorZoneType.ToonHQ],
  4801: ["Marshall's Stacks", InteriorZoneType.ToonInterior],
  4803: ["What a Mezzo! Maid Service", InteriorZoneType.ToonInterior],
  4804: ["Mixolydian Scales", InteriorZoneType.ToonInterior],
  4807: ["Relax the Bach", InteriorZoneType.ToonInterior],
  4809: ["I Can't Understanza!", InteriorZoneType.ToonInterior],
  4812: ["", InteriorZoneType.ToonInterior],
  4817: ["The Ternary Pet Shop", InteriorZoneType.ToonInterior],
  4819: ["Yuki's Ukeleles", InteriorZoneType.ToonInterior],
  4820: ["", InteriorZoneType.ToonInterior],
  4821: ["Anna's Cruises", InteriorZoneType.ToonInterior],
  4827: ["Common Time Watches", InteriorZoneType.ToonInterior],
  4828: ["Schumann's Shoes for Men", InteriorZoneType.ToonInterior],
  4829: ["Pachelbel's Canonballs", InteriorZoneType.ToonInterior],
  4835: ["Ursatz for Kool Katz", InteriorZoneType.ToonInterior],
  4836: ["Reggae Regalia", InteriorZoneType.ToonInterior],
  4838: ["Kazoology School of Music", InteriorZoneType.ToonInterior],
  4840: ["Coda Pop Musical Beverages", InteriorZoneType.ToonInterior],
  4841: ["Lyre, Lyre, Pants on Fire!", InteriorZoneType.ToonInterior],
  4842: ["The Syncopation Corporation", InteriorZoneType.ToonInterior],
  4843: ["", InteriorZoneType.ToonInterior],
  4844: ["Con Moto Cycles", InteriorZoneType.ToonInterior],
  4845: ["Ellie's Elegant Elegies", InteriorZoneType.ToonInterior],
  4848: ["Lotsa Lute Savings & Loan", InteriorZoneType.ToonInterior],
  4849: ["", InteriorZoneType.ToonInterior],
  4850: ["The Borrowed Chord Pawn Shop", InteriorZoneType.ToonInterior],
  4852: ["Flowery Flute Fleeces", InteriorZoneType.ToonInterior],
  4853: ["Leo's Fenders", InteriorZoneType.ToonInterior],
  4854: ["Wagner's Vocational Violin Videos", InteriorZoneType.ToonInterior],
  4855: ["The Teli-Caster Network", InteriorZoneType.ToonInterior],
  4856: ["", InteriorZoneType.ToonInterior],
  4862: ["Quentin's Quintessential Quadrilles", InteriorZoneType.ToonInterior],
  4867: ["Mr. Costello's Yellow Cellos", InteriorZoneType.ToonInterior],
  4868: ["", InteriorZoneType.ToonInterior],
  4870: ["Ziggy's Zoo of Zigeunermusik", InteriorZoneType.ToonInterior],
  4871: [
    "Harry's House of Harmonious Humbuckers",
    InteriorZoneType.ToonInterior,
  ],
  4872: ["Fast Freddie's Fretless Fingerboards", InteriorZoneType.ToonInterior],
  4873: ["", InteriorZoneType.ToonHQ],
  5501: ["Gag Shop", InteriorZoneType.GagShop],
  5502: ["Toon HQ", InteriorZoneType.ToonHQ],
  5503: ["Clothing Shop", InteriorZoneType.ClothingShop],
  5505: ["", InteriorZoneType.PetShop],
  5601: ["Eye of the Potato Optometry", InteriorZoneType.ToonInterior],
  5602: ["Artie Choke's Neckties", InteriorZoneType.ToonInterior],
  5603: ["Lettuce Alone", InteriorZoneType.ToonInterior],
  5604: ["Cantaloupe Bridal Shop", InteriorZoneType.ToonInterior],
  5605: ["Vege-tables and Chairs", InteriorZoneType.ToonInterior],
  5606: ["Petals", InteriorZoneType.ToonInterior],
  5607: ["Compost Office", InteriorZoneType.ToonInterior],
  5608: ["Mom and Pop Corn", InteriorZoneType.ToonInterior],
  5609: ["Berried Treasure", InteriorZoneType.ToonInterior],
  5610: ["Black-eyed Susan's Boxing Lessons", InteriorZoneType.ToonInterior],
  5611: ["Gopher's Gags", InteriorZoneType.ToonInterior],
  5613: ["Crop Top Barbers", InteriorZoneType.ToonInterior],
  5615: ["Bud's Bird Seed", InteriorZoneType.ToonInterior],
  5616: ["Dew Drop Inn", InteriorZoneType.ToonInterior],
  5617: ["Flutterby's Butterflies", InteriorZoneType.ToonInterior],
  5618: ["Peas and Q's", InteriorZoneType.ToonInterior],
  5619: ["Jack's Beanstalks", InteriorZoneType.ToonInterior],
  5620: ["Rake It Inn", InteriorZoneType.ToonInterior],
  5621: ["Grape Expectations", InteriorZoneType.ToonInterior],
  5622: ["Petal Pusher Bicycles", InteriorZoneType.ToonInterior],
  5623: ["Bubble Bird Baths", InteriorZoneType.ToonInterior],
  5624: ["Mum's the Word", InteriorZoneType.ToonInterior],
  5625: ["Leaf It Bees", InteriorZoneType.ToonInterior],
  5626: ["Pine Needle Crafts", InteriorZoneType.ToonInterior],
  5627: ["", InteriorZoneType.ToonHQ],
  5701: ["From Start to Spinach", InteriorZoneType.ToonInterior],
  5702: ["Jake's Rakes", InteriorZoneType.ToonInterior],
  5703: ["Photo Cynthia's Camera Shop", InteriorZoneType.ToonInterior],
  5704: ["Lisa Lemon Used Cars", InteriorZoneType.ToonInterior],
  5705: ["Poison Oak Furniture", InteriorZoneType.ToonInterior],
  5706: ["14 Carrot Jewelers", InteriorZoneType.ToonInterior],
  5707: ["Musical Fruit", InteriorZoneType.ToonInterior],
  5708: ["We'd Be Gone Travel Agency", InteriorZoneType.ToonInterior],
  5709: ["Astroturf Mowers", InteriorZoneType.ToonInterior],
  5710: ["Tuft Guy Gym", InteriorZoneType.ToonInterior],
  5711: ["Garden Hosiery", InteriorZoneType.ToonInterior],
  5712: ["Silly Statues", InteriorZoneType.ToonInterior],
  5713: ["Trowels and Tribulations", InteriorZoneType.ToonInterior],
  5714: ["Spring Rain Seltzer Bottles", InteriorZoneType.ToonInterior],
  5715: ["Hayseed News", InteriorZoneType.ToonInterior],
  5716: ["Take It or Leaf It Pawn Shop", InteriorZoneType.ToonInterior],
  5717: ["The Squirting Flower", InteriorZoneType.ToonInterior],
  5718: ["The Dandy Lion Exotic Pets", InteriorZoneType.ToonInterior],
  5719: [
    "Trellis the Truth! Private Investigators",
    InteriorZoneType.ToonInterior,
  ],
  5720: ["Vine and Dandy Menswear", InteriorZoneType.ToonInterior],
  5721: ["Root 66 Diner", InteriorZoneType.ToonInterior],
  5725: ["Barley, Hops, and Malt Shop", InteriorZoneType.ToonInterior],
  5726: ["Bert's Dirt", InteriorZoneType.ToonInterior],
  5727: ["Gopher Broke Savings & Loan", InteriorZoneType.ToonInterior],
  5728: ["", InteriorZoneType.ToonHQ],
  5802: ["Toon HQ", InteriorZoneType.ToonHQ],
  5804: ["Just Vase It", InteriorZoneType.ToonInterior],
  5805: ["Snail Mail", InteriorZoneType.ToonInterior],
  5809: ["Fungi Clown School", InteriorZoneType.ToonInterior],
  5810: ["Honeydew This", InteriorZoneType.ToonInterior],
  5811: ["Lettuce Inn", InteriorZoneType.ToonInterior],
  5815: ["Grass Roots", InteriorZoneType.ToonInterior],
  5817: ["Apples and Oranges", InteriorZoneType.ToonInterior],
  5819: ["Green Bean Jeans", InteriorZoneType.ToonInterior],
  5821: ["Squash and Stretch Gym", InteriorZoneType.ToonInterior],
  5826: ["Ant Farming Supplies", InteriorZoneType.ToonInterior],
  5827: ["Dirt. Cheap.", InteriorZoneType.ToonInterior],
  5828: ["Couch Potato Furniture", InteriorZoneType.ToonInterior],
  5830: ["Spill the Beans", InteriorZoneType.ToonInterior],
  5833: ["The Salad Bar", InteriorZoneType.ToonInterior],
  5835: ["Flower Bed and Breakfast", InteriorZoneType.ToonInterior],
  5836: ["April's Showers and Tubs", InteriorZoneType.ToonInterior],
  5837: ["School of Vine Arts", InteriorZoneType.ToonInterior],
  8501: ["Goofy's Auto Shop", InteriorZoneType.KartShop],
  9501: ["Lullaby Library", InteriorZoneType.ToonInterior],
  9503: ["The Snooze Bar", InteriorZoneType.ToonInterior],
  9504: ["Gag Shop", InteriorZoneType.GagShop],
  9505: ["Toon HQ", InteriorZoneType.ToonHQ],
  9506: ["Clothing Shop", InteriorZoneType.ClothingShop],
  9508: ["", InteriorZoneType.PetShop],
  9601: ["Snuggle Inn", InteriorZoneType.ToonInterior],
  9602: ["Forty Winks for the Price of Twenty", InteriorZoneType.ToonInterior],
  9604: ["Ed's Red Bed Spreads", InteriorZoneType.ToonInterior],
  9605: ["Cloud Nine Design", InteriorZoneType.ToonInterior],
  9607: ["Big Mama's Bahama Pajamas", InteriorZoneType.ToonInterior],
  9608: ["Cat Nip for Cat Naps", InteriorZoneType.ToonInterior],
  9609: ["Deep Sleep for Cheap", InteriorZoneType.ToonInterior],
  9613: ["Clock Cleaners", InteriorZoneType.ToonInterior],
  9616: ["Lights Out Electric Co.", InteriorZoneType.ToonInterior],
  9617: ["Crib Notes - Music to Sleep By", InteriorZoneType.ToonInterior],
  9619: ["Relax to the Max", InteriorZoneType.ToonInterior],
  9620: ["PJ's Taxi Service", InteriorZoneType.ToonInterior],
  9622: ["Sleepy Time Pieces", InteriorZoneType.ToonInterior],
  9625: ["Curl Up Beauty Parlor", InteriorZoneType.ToonInterior],
  9626: ["Bed Time Stories", InteriorZoneType.ToonInterior],
  9627: ["The Sleepy Teepee", InteriorZoneType.ToonInterior],
  9628: ["Call It a Day Calendars", InteriorZoneType.ToonInterior],
  9629: ["Silver Lining Jewelers", InteriorZoneType.ToonInterior],
  9630: ["Rock to Sleep Quarry", InteriorZoneType.ToonInterior],
  9631: ["Down Time Watch Repair", InteriorZoneType.ToonInterior],
  9633: ["The Dreamland Screening Room", InteriorZoneType.ToonInterior],
  9634: ["Mind Over Mattress", InteriorZoneType.ToonInterior],
  9636: ["Insomniac Insurance", InteriorZoneType.ToonInterior],
  9639: ["House of Hibernation", InteriorZoneType.ToonInterior],
  9640: ["Nightstand Furniture Company", InteriorZoneType.ToonInterior],
  9642: ["Sawing Wood Slumber Lumber", InteriorZoneType.ToonInterior],
  9643: ["Shut-Eye Optometry", InteriorZoneType.ToonInterior],
  9644: ["Pillow Fights Nightly", InteriorZoneType.ToonInterior],
  9645: ["The All Tucked Inn", InteriorZoneType.ToonInterior],
  9647: ["Make Your Bed! Hardware Store", InteriorZoneType.ToonInterior],
  9649: ["Snore or Less", InteriorZoneType.ToonInterior],
  9650: ["Crack of Dawn Repairs", InteriorZoneType.ToonInterior],
  9651: ["For Richer or Snorer", InteriorZoneType.ToonInterior],
  9652: ["", InteriorZoneType.ToonHQ],
  9703: ["Fly By Night Travel Agency", InteriorZoneType.ToonInterior],
  9704: ["Night Owl Pet Shop", InteriorZoneType.ToonInterior],
  9705: ["Asleep At The Wheel Car Repair", InteriorZoneType.ToonInterior],
  9706: ["Tooth Fairy Dentistry", InteriorZoneType.ToonInterior],
  9707: ["Dawn's Yawn & Garden Center", InteriorZoneType.ToonInterior],
  9708: ["Bed Of Roses Florist", InteriorZoneType.ToonInterior],
  9709: ["Pipe Dream Plumbers", InteriorZoneType.ToonInterior],
  9710: ["REM Optometry", InteriorZoneType.ToonInterior],
  9711: ["Wake-Up Call Phone Company", InteriorZoneType.ToonInterior],
  9712: [
    "Counting Sheep - So You Don't Have To!",
    InteriorZoneType.ToonInterior,
  ],
  9713: [
    "Wynken, Blynken & Nod, Attorneys at Law",
    InteriorZoneType.ToonInterior,
  ],
  9714: ["Dreamboat Marine Supply", InteriorZoneType.ToonInterior],
  9715: ["First Security Blanket Bank", InteriorZoneType.ToonInterior],
  9716: ["Wet Blanket Party Planners", InteriorZoneType.ToonInterior],
  9717: ["Baker's Dozin' Doughnuts", InteriorZoneType.ToonInterior],
  9718: ["Sandman's Sandwiches", InteriorZoneType.ToonInterior],
  9719: ["Armadillo Pillow Company", InteriorZoneType.ToonInterior],
  9720: ["Talking In Your Sleep Voice Training", InteriorZoneType.ToonInterior],
  9721: ["Snug As A Bug Rug Dealer", InteriorZoneType.ToonInterior],
  9722: ["Dream On Talent Agency", InteriorZoneType.ToonInterior],
  9725: ["Cat's Pajamas", InteriorZoneType.ToonInterior],
  9727: ["You Snooze, You Lose", InteriorZoneType.ToonInterior],
  9736: ["Dream Jobs Employment Agency", InteriorZoneType.ToonInterior],
  9737: ["Waltzing Matilda's Dance School", InteriorZoneType.ToonInterior],
  9738: ["House of Zzzzzs", InteriorZoneType.ToonInterior],
  9740: ["Hit The Sack Fencing School", InteriorZoneType.ToonInterior],
  9741: [
    "Don't Let The Bed Bugs Bite Exterminators",
    InteriorZoneType.ToonInterior,
  ],
  9744: ["Rip Van Winkle's Wrinkle Cream", InteriorZoneType.ToonInterior],
  9752: ["Midnight Oil & Gas Company", InteriorZoneType.ToonInterior],
  9753: ["Moonbeam's Ice Creams", InteriorZoneType.ToonInterior],
  9754: [
    "Sleepless in the Saddle All Night Pony Rides",
    InteriorZoneType.ToonInterior,
  ],
  9755: ["Bedknobs & Broomsticks Movie House", InteriorZoneType.ToonInterior],
  9756: ["", InteriorZoneType.ToonHQ],
  9759: ["Sleeping Beauty Parlor", InteriorZoneType.ToonInterior],
};
