
import { GTA3SceneDesc } from './scenes';
import { SceneGroup } from '../viewer';
import { ItemInstance, ObjectDefinition, INTERIOR_EVERYWHERE } from './item';
import { vec4 } from 'gl-matrix';

class GTASASceneDesc extends GTA3SceneDesc {
    constructor(private interior: number, name?: string) {
        super(String(interior), name ? name : `Interior ${interior}`);
        this.pathBase = 'GrandTheftAutoSanAndreas';
        this.complete = true;
        this.water = {
            origin: vec4.fromValues(0, 0, 0, 3000),
            texture: 'waterclear256',
        };
        this.weatherTypes = [
            'Los Santos: Extra Sunny',
            'Los Santos: Sunny',
            'Los Santos: Extra Sunny Smog',
            'Los Santos: Sunny Smog',
            'Los Santos: Cloudy',

            'San Fierro: Sunny',
            'San Fierro: Extra Sunny',
            'San Fierro: Cloudy',
            'San Fierro: Rainy',
            'San Fierro: Foggy',

            'Las Venturas: Sunny',
            'Las Venturas: Extra Sunny',
            'Las Venturas: Cloudy',

            'Countryside: Extra Sunny',
            'Countryside: Sunny',
            'Countryside: Cloudy',
            'Countryside: Rainy',

            'Desert: Extra Sunny',
            'Desert: Sunny',
            'Desert: Sandstorm',

            'Underwater',
            'Interior A',
            'Interior B',
        ];
        this.weatherPeriods = 8;
        this.versionIMG = 2;
        this.paths = {
            zon: 'data/info.zon',
            dat: {
                timecyc: 'data/timecycp.dat',
                water: 'data/water.dat',
            },
            ide: [
                'country/countn2',
                'country/countrye',
                'country/countryN',
                'country/countryS',
                'country/countryW',
                'country/counxref',
                'generic/barriers',
                'generic/dynamic2',
                'generic/dynamic',
                'generic/multiobj',
                'generic/procobj',
                'generic/vegepart',
                'interior/gen_int1',
                'interior/gen_int2',
                'interior/gen_int3',
                'interior/gen_int4',
                'interior/gen_int5',
                'interior/gen_intb',
                'interior/int_cont',
                'interior/int_LA',
                'interior/int_SF',
                'interior/int_veg',
                'interior/propext',
                'interior/props2',
                'interior/props',
                'interior/savehous',
                'interior/stadint',
                'LA/LAe2',
                'LA/LAe',
                'LA/LAhills',
                'LA/LAn2',
                'LA/LAn',
                'LA/LAs2',
                'LA/LAs',
                'LA/LAw2',
                'LA/LAw',
                'LA/LaWn',
                'LA/LAxref',
                'leveldes/leveldes',
                'leveldes/levelmap',
                'leveldes/levelxre',
                'leveldes/seabed',
                'SF/SFe',
                'SF/SFn',
                'SF/SFSe',
                'SF/SFs',
                'SF/SFw',
                'SF/SFxref',
                'txd',
                'vegas/vegasE',
                'vegas/VegasN',
                'vegas/VegasS',
                'vegas/VegasW',
                'vegas/vegaxref',
                'veh_mods/veh_mods',
            ],
            ipl: [
                'Audiozon',
                'country/countn2',
                'country/countrye',
                'country/countryN',
                'country/countryS',
                'country/countryw',
                'cull',
                'interior/gen_int1',
                'interior/gen_int2',
                'interior/gen_int3',
                'interior/gen_int4',
                'interior/gen_int5',
                'interior/gen_intb',
                'interior/int_cont',
                'interior/int_LA',
                'interior/int_SF',
                'interior/int_veg',
                'interior/savehous',
                'interior/stadint',
                'LA/LAe2',
                'LA/LAe',
                'LA/LAhills',
                'LA/LAn2',
                'LA/LAn',
                'LA/LAs2',
                'LA/LAs',
                'LA/LAw2',
                'LA/LAw',
                'LA/LaWn',
                'leveldes/leveldes',
                'leveldes/levelmap',
                'leveldes/seabed',
                'occluint',
                'occlu',
                'occluLA',
                'occlusf',
                'occluveg',
                'paths2',
                'paths3',
                'paths4',
                'paths5',
                'paths',
                'SF/SFe',
                'SF/SFn',
                'SF/SFSe',
                'SF/SFs',
                'SF/SFw',
                'tunnels',
                'vegas/vegasE',
                'vegas/vegasN',
                'vegas/vegasS',
                'vegas/vegasW',
                'vegas/vegaxref',
            ],
        };
        this.ipl_stream = {
            countn2: 9,
            countrye: 14,
            countryn: 4,
            countrys: 5,
            countryw: 9,
            lae2: 7,
            lae: 6,
            lahills: 5,
            lan2: 4,
            lan: 3,
            las2: 5,
            las: 6,
            law2: 5,
            lawn: 4,
            law: 6,
            levelmap: 1,
            seabed: 1,
            sfe: 4,
            sfn: 3,
            sfse: 7,
            sfs: 9,
            sfw: 6,
            vegase: 9,
            vegasn: 9,
            vegass: 6,
            vegasw: 12,
        };
    }

    protected filter(item: ItemInstance) {
        const interior = item.interior! & 0xFF;
        return interior === this.interior || interior === INTERIOR_EVERYWHERE;
    }
}

export const sceneGroup: SceneGroup = {
    id: 'GrandTheftAutoSanAndreas',
    name: 'Grand Theft Auto: San Andreas',
    sceneDescs: [
        new GTASASceneDesc(0, 'San Andreas'),
        new GTASASceneDesc(1),
        new GTASASceneDesc(2),
        new GTASASceneDesc(3),
        new GTASASceneDesc(4),
        new GTASASceneDesc(5),
        new GTASASceneDesc(6),
        new GTASASceneDesc(7),
        new GTASASceneDesc(8),
        new GTASASceneDesc(9),
        new GTASASceneDesc(10),
        new GTASASceneDesc(11),
        new GTASASceneDesc(12),
        new GTASASceneDesc(14),
        new GTASASceneDesc(15),
        new GTASASceneDesc(16),
        new GTASASceneDesc(17),
        new GTASASceneDesc(18),
    ]
};
