
import { GTA3SceneDesc } from './scenes';
import { SceneGroup } from '../viewer';
import { vec4 } from 'gl-matrix';

class GTASASceneDesc extends GTA3SceneDesc {
    constructor(name: string, interior = 0, id?: string) {
        super(name, interior, (id === undefined) ? String(interior) : `${interior}/${id.toLowerCase()}`);
        this.pathBase = 'GrandTheftAutoSanAndreas';
        this.water = {
            origin: vec4.fromValues(0, 0, 0, 3000),
            texture: 'waterclear256',
        };
        this.weatherTypes = [
            'Los Santos: Extra Sunny',
            'Los Santos: Sunny',
            'Los Santos: Extra Sunny Smog',
            'Los Santos: Sunny Smog',
            'Los Santos: Cloudy',

            'San Fierro: Sunny',
            'San Fierro: Extra Sunny',
            'San Fierro: Cloudy',
            'San Fierro: Rainy',
            'San Fierro: Foggy',

            'Las Venturas: Sunny',
            'Las Venturas: Extra Sunny',
            'Las Venturas: Cloudy',

            'Countryside: Extra Sunny',
            'Countryside: Sunny',
            'Countryside: Cloudy',
            'Countryside: Rainy',

            'Desert: Extra Sunny',
            'Desert: Sunny',
            'Desert: Sandstorm',

            'Underwater',
            'Interior A',
            'Interior B',
        ];
        this.weatherPeriods = 8;
        this.versionIMG = 2;
        this.extraIMG = ['gta_int'];
        this.paths = {
            zon: 'data/info.zon',
            dat: {
                timecyc: 'data/timecycp.dat',
                water: 'data/water.dat',
            },
            ide: [
                'country/countn2',
                'country/countrye',
                'country/countryN',
                'country/countryS',
                'country/countryW',
                'country/counxref',
                'generic/barriers',
                'generic/dynamic2',
                'generic/dynamic',
                'generic/multiobj',
                'generic/procobj',
                'generic/vegepart',
                'interior/gen_int1',
                'interior/gen_int2',
                'interior/gen_int3',
                'interior/gen_int4',
                'interior/gen_int5',
                'interior/gen_intb',
                'interior/int_cont',
                'interior/int_LA',
                'interior/int_SF',
                'interior/int_veg',
                'interior/propext',
                'interior/props2',
                'interior/props',
                'interior/savehous',
                'interior/stadint',
                'LA/LAe2',
                'LA/LAe',
                'LA/LAhills',
                'LA/LAn2',
                'LA/LAn',
                'LA/LAs2',
                'LA/LAs',
                'LA/LAw2',
                'LA/LAw',
                'LA/LaWn',
                'LA/LAxref',
                'leveldes/leveldes',
                'leveldes/levelmap',
                'leveldes/levelxre',
                'leveldes/seabed',
                'SF/SFe',
                'SF/SFn',
                'SF/SFSe',
                'SF/SFs',
                'SF/SFw',
                'SF/SFxref',
                'txd',
                'vegas/vegasE',
                'vegas/VegasN',
                'vegas/VegasS',
                'vegas/VegasW',
                'vegas/vegaxref',
                'veh_mods/veh_mods',
            ],
            ipl: [
                'Audiozon',
                'country/countn2',
                'country/countrye',
                'country/countryN',
                'country/countryS',
                'country/countryw',
                'cull',
                'interior/gen_int1',
                'interior/gen_int2',
                'interior/gen_int3',
                'interior/gen_int4',
                'interior/gen_int5',
                'interior/gen_intb',
                'interior/int_cont',
                'interior/int_LA',
                'interior/int_SF',
                'interior/int_veg',
                'interior/savehous',
                'interior/stadint',
                'LA/LAe2',
                'LA/LAe',
                'LA/LAhills',
                'LA/LAn2',
                'LA/LAn',
                'LA/LAs2',
                'LA/LAs',
                'LA/LAw2',
                'LA/LAw',
                'LA/LaWn',
                'leveldes/leveldes',
                'leveldes/levelmap',
                'leveldes/seabed',
                'occluint',
                'occlu',
                'occluLA',
                'occlusf',
                'occluveg',
                'paths2',
                'paths3',
                'paths4',
                'paths5',
                'paths',
                'SF/SFe',
                'SF/SFn',
                'SF/SFSe',
                'SF/SFs',
                'SF/SFw',
                'tunnels',
                'vegas/vegasE',
                'vegas/vegasN',
                'vegas/vegasS',
                'vegas/vegasW',
                'vegas/vegaxref',
            ],
        };
        this.ipl_stream = {
            countn2: 9,
            countrye: 14,
            countryn: 4,
            countrys: 5,
            countryw: 9,
            lae2: 7,
            lae: 6,
            lahills: 5,
            lan2: 4,
            lan: 3,
            las2: 5,
            las: 6,
            law2: 5,
            lawn: 4,
            law: 6,
            levelmap: 1,
            seabed: 1,
            sfe: 4,
            sfn: 3,
            sfse: 7,
            sfs: 9,
            sfw: 6,
            vegase: 9,
            vegasn: 9,
            vegass: 6,
            vegasw: 12,
            // gta_int
            gen_int2: 1,
            gen_int3: 1,
            gen_int4: 3,
            gen_int5: 8,
            gen_intb: 1,
            int_la: 4,
            int_sf: 1,
            int_veg: 4,
            savehous: 2,
            stadint: 1,
        };
    }
}

export const sceneGroup: SceneGroup = {
    id: 'GrandTheftAutoSanAndreas',
    name: 'Grand Theft Auto: San Andreas',
    sceneDescs: [
        new GTASASceneDesc("San Andreas"),
        "Interiors",
        new GTASASceneDesc("Sindacco Abattoir", 1, "ABATOIR"),
        new GTASASceneDesc("Ammu-Nation", 1, "AMMUN1"),
        new GTASASceneDesc("TransFender", 1, "CARMOD1"),
        new GTASASceneDesc("World of Coq", 1, "FDREST1"),
        new GTASASceneDesc("Denise's", 1, "GF1"),
        new GTASASceneDesc("Shamal interior", 1, "JETINT"),
        new GTASASceneDesc("Sub Urban", 1, "LACS1"),
        new GTASASceneDesc("House", 1, "LAHS1B"),
        new GTASASceneDesc("Caligulas Casino", 1, "MAFCAS"),
        new GTASASceneDesc("Penthouse Suites", 1, "MAFCAS2"),
        new GTASASceneDesc("Warehouse", 1, "SMASHTV"),
        new GTASASceneDesc("Hotel Suite", 1, "SVVGHO1"),
        new GTASASceneDesc("Sweet's House", 1, "SWEETS"),
        new GTASASceneDesc("Truck Stop", 1, "TSDINER"),
        new GTASASceneDesc("Wu Zi Mu's", 1, "WUZIBET"),
        new GTASASceneDesc("Barber", 2, "BARBERS"),
        new GTASASceneDesc("B Dup's Crack Palace", 2, "BDUPS1"),
        new GTASASceneDesc("Loco Low Co.", 2, "CARMOD2"),
        new GTASASceneDesc("Smoke's Crack Palace", 2, "CARTER"),
        new GTASASceneDesc("Katie's", 2, "GF2"),
        new GTASASceneDesc("House", 2, "LAHS1A"),
        new GTASASceneDesc("Strip Club", 2, "LASTRIP"),
        new GTASASceneDesc("Ryder's Place", 2, "RYDERS"),
        new GTASASceneDesc("Hotel Suite", 2, "SVVGHO2"),
        new GTASASceneDesc("House", 2, "VGHSB1"),
        new GTASASceneDesc("House", 2, "VGHSB3"),
        new GTASASceneDesc("Barber", 3, "BARBER2"),
        new GTASASceneDesc("B Dup's apartment", 3, "BDUPS"),
        new GTASASceneDesc("Bike School", 3, "BIKESCH"),
        new GTASASceneDesc("Whore House", 3, "BROTHL1"),
        new GTASASceneDesc("The Johnson House", 3, "CARLS"),
        new GTASASceneDesc("Wheel Arch Angels", 3, "CARMOD3"),
        new GTASASceneDesc("Pro-Laps", 3, "CSSPRT"),
        new GTASASceneDesc("Driving School", 3, "DRIVES"),
        new GTASASceneDesc("Driving School", 3, "DRIVES2"),
        new GTASASceneDesc("Inside Track Betting", 3, "GENOTB"),
        new GTASASceneDesc("Helena's", 3, "GF3"),
        new GTASASceneDesc("House", 3, "LAHSB4"),
        new GTASASceneDesc("OG Loc's", 3, "OGLOCS"),
        new GTASASceneDesc("Planning Department", 3, "PAPER"),
        new GTASASceneDesc("The Pleasure Domes", 3, "PDOMES"),
        new GTASASceneDesc("The Pleasure Domes", 3, "PDOMES2"),
        new GTASASceneDesc("LVPD HQ", 3, "POLICE3"),
        new GTASASceneDesc("Sex Shop", 3, "SEXSHOP"),
        new GTASASceneDesc("Strip Club", 3, "STRIP2"),
        new GTASASceneDesc("Blastin' Fools Records studio", 3, "STUDIO"),
        new GTASASceneDesc("Tattoo Parlor", 3, "TATTO3"),
        new GTASASceneDesc("Ammu-Nation", 4, "AMMUN2"),
        new GTASASceneDesc("Diner", 4, "DINER1"),
        new GTASASceneDesc("Dirt Stadium", 4, "DIRBIKE"),
        new GTASASceneDesc("Michelle's", 4, "GF4"),
        new GTASASceneDesc("House", 4, "LAHS2A"),
        new GTASASceneDesc("House", 4, "LAHSS6"),
        new GTASASceneDesc("House", 4, "SFHSM2"),
        new GTASASceneDesc("24-7", 4, "X711S2"),
        new GTASASceneDesc("Victim", 5, "CSDESGN"),
        new GTASASceneDesc("Diner", 5, "DINER2"),
        new GTASASceneDesc("Pizza Stack", 5, "FDPIZA"),
        new GTASASceneDesc("Vagos Gang House", 5, "GANG"),
        new GTASASceneDesc("Barbara's", 5, "GF5"),
        new GTASASceneDesc("Ganton Gym", 5, "GYM1"),
        new GTASASceneDesc("Crack Den", 5, "LACRAK"),
        new GTASASceneDesc("House", 5, "LAHSB3"),
        new GTASASceneDesc("Madd Dogg's Crib", 5, "MADDOGS"),
        new GTASASceneDesc("Madd Dogg's Crib", 5, "MDDOGS"),
        new GTASASceneDesc("House", 5, "SFHSB1"),
        new GTASASceneDesc("Hotel Suite", 5, "SVHOT1"),
        new GTASASceneDesc("House", 5, "VGHSM2"),
        new GTASASceneDesc("Ammu-Nation", 6, "AMMUN3"),
        new GTASASceneDesc("Ammu-Nation", 6, "AMMUN5"),
        new GTASASceneDesc("Whore House", 6, "BROTHEL"),
        new GTASASceneDesc("Millie's", 6, "GF6"),
        new GTASASceneDesc("Cobra Martial Arts", 6, "GYM2"),
        new GTASASceneDesc("House", 6, "LAHSB1"),
        new GTASASceneDesc("LSPD HQ", 6, "POLICE1"),
        new GTASASceneDesc("Zero's RC Shop", 6, "RCPLAY"),
        new GTASASceneDesc("Secret Valley", 6, "REST2"),
        new GTASASceneDesc("House", 6, "SFHSS2"),
        new GTASASceneDesc("Safe House", 6, "SVCUNT"),
        new GTASASceneDesc("Safe House", 6, "SVSFBG"),
        new GTASASceneDesc("Safe House", 6, "SVSFSM"),
        new GTASASceneDesc("24-7", 6, "X7_11S"),
        new GTASASceneDesc("8-Track Stadium", 7, "8TRACK"),
        new GTASASceneDesc("Ammu-Nation", 7, "AMMUN4"),
        new GTASASceneDesc("Below the Belt Gym", 7, "GYM3"),
        new GTASASceneDesc("House", 7, "LAHSB2"),
        new GTASASceneDesc("Colonel Fuhrberger's", 8, "BURHOUS"),
        new GTASASceneDesc("House", 8, "SFHSS1"),
        new GTASASceneDesc("Safe House", 8, "SVLAMD"),
        new GTASASceneDesc("Cluckin' Bell", 9, "FDCHICK"),
        new GTASASceneDesc("House", 9, "LAHS2B"),
        new GTASASceneDesc("House", 9, "SFHSB3"),
        new GTASASceneDesc("Motel room", 9, "SVGNMT1"),
        new GTASASceneDesc("Safe House", 9, "SVVGMD"),
        new GTASASceneDesc("Burger Shot", 10, "FDBURG"),
        new GTASASceneDesc("SFPD HQ", 10, "POLICE2"),
        new GTASASceneDesc("Motel room", 10, "SVGNMT2"),
        new GTASASceneDesc("The Four Dragons", 10, "TRICAS"),
        new GTASASceneDesc("Safe House", 10, "SVSFMD"),
        new GTASASceneDesc("House", 10, "VGHSM3"),
        new GTASASceneDesc("24-7", 10, "X711S3"),
        new GTASASceneDesc("Bar", 11, "BAR2"),
        new GTASASceneDesc("Safe House", 11, "SVLASM"),
        new GTASASceneDesc("Barber", 12, "BARBER3"),
        new GTASASceneDesc("Casino Floor", 12, "CASINO2"),
        new GTASASceneDesc("Motel room", 12, "MOROOM"),
        new GTASASceneDesc("Safe House", 12, "SVLABIG"),
        new GTASASceneDesc("Didier Sachs", 14, "CSEXL"),
        new GTASASceneDesc("Binco", 15, "CSCHP"),
        new GTASASceneDesc("Jefferson Motel", 15, "MOTEL1"),
        new GTASASceneDesc("House", 15, "SFHSM1"),
        new GTASASceneDesc("House", 15, "VGHSS1"),
        new GTASASceneDesc("House", 15, "VGSHM2"),
        new GTASASceneDesc("House", 15, "VGSHM3"),
        new GTASASceneDesc("House", 15, "VGSHS2"),
        new GTASASceneDesc("Tattoo Parlor", 16, "TATTOO"),
        new GTASASceneDesc("24-7", 16, "X7_11C"),
        new GTASASceneDesc("Bar", 17, "BAR1"),
        new GTASASceneDesc("Rusty Brown's", 17, "FDDONUT"),
        new GTASASceneDesc("Tattoo Parlor", 17, "TATTO2"),
        new GTASASceneDesc("24-7", 17, "X7_11D"),
        new GTASASceneDesc("Atrium", 18, "ATRIUME"),
        new GTASASceneDesc("Atrium", 18, "ATRIUMX"),
        new GTASASceneDesc("Zip", 18, "CLOTHGP"),
        new GTASASceneDesc("Warehouse", 18, "GENWRHS"),
        new GTASASceneDesc("24-7 ", 18, "X7_11B"),
    ]
};
