
import { GTA3SceneDesc } from './scenes';
import { SceneGroup } from '../viewer';
import { ItemInstance, ObjectDefinition, INTERIOR_EVERYWHERE } from './item';
import { vec4 } from 'gl-matrix';

class GTASASceneDesc extends GTA3SceneDesc {
    constructor(private interior: number, name?: string) {
        super(String(interior), name ? name : `Interior ${interior}`);
        this.pathBase = 'GrandTheftAutoSanAndreas';
        this.complete = true;
        this.water = {
            origin: vec4.fromValues(0, 0, 0, 3000),
            texture: 'waterclear256',
        };
        this.weatherTypes = [
            'Los Santos: Extra Sunny',
            'Los Santos: Sunny',
            'Los Santos: Extra Sunny Smog',
            'Los Santos: Sunny Smog',
            'Los Santos: Cloudy',

            'San Fierro: Sunny',
            'San Fierro: Extra Sunny',
            'San Fierro: Cloudy',
            'San Fierro: Rainy',
            'San Fierro: Foggy',

            'Las Venturas: Sunny',
            'Las Venturas: Extra Sunny',
            'Las Venturas: Cloudy',

            'Countryside: Extra Sunny',
            'Countryside: Sunny',
            'Countryside: Cloudy',
            'Countryside: Rainy',

            'Desert: Extra Sunny',
            'Desert: Sunny',
            'Desert: Sandstorm',

            'Underwater',
            'Interior A',
            'Interior B',
        ];
        this.weatherPeriods = 8;
        this.versionIMG = 2;
        this.drawDistanceLimit = 250;
        this.paths = {
            zon: 'data/info.zon',
            dat: {
                timecyc: 'data/timecycp.dat',
                water: 'data/water.dat',
            },
            ide: [
                'country/countn2',
                'country/countrye',
                'country/countryN',
                'country/countryS',
                'country/countryW',
                'country/counxref',
                'generic/barriers',
                'generic/dynamic2',
                'generic/dynamic',
                'generic/multiobj',
                'generic/procobj',
                'generic/vegepart',
                'interior/gen_int1',
                'interior/gen_int2',
                'interior/gen_int3',
                'interior/gen_int4',
                'interior/gen_int5',
                'interior/gen_intb',
                'interior/int_cont',
                'interior/int_LA',
                'interior/int_SF',
                'interior/int_veg',
                'interior/propext',
                'interior/props2',
                'interior/props',
                'interior/savehous',
                'interior/stadint',
                'LA/LAe2',
                'LA/LAe',
                'LA/LAhills',
                'LA/LAn2',
                'LA/LAn',
                'LA/LAs2',
                'LA/LAs',
                'LA/LAw2',
                'LA/LAw',
                'LA/LaWn',
                'LA/LAxref',
                'leveldes/leveldes',
                'leveldes/levelmap',
                'leveldes/levelxre',
                'leveldes/seabed',
                'SF/SFe',
                'SF/SFn',
                'SF/SFSe',
                'SF/SFs',
                'SF/SFw',
                'SF/SFxref',
                'txd',
                'vegas/vegasE',
                'vegas/VegasN',
                'vegas/VegasS',
                'vegas/VegasW',
                'vegas/vegaxref',
                'veh_mods/veh_mods',
            ],
            ipl: [
                'Audiozon',
                'country/countn2',
                'country/countrye',
                'country/countryN',
                'country/countryS',
                'country/countryw',
                'cull',
                'interior/gen_int1',
                'interior/gen_int2',
                'interior/gen_int3',
                'interior/gen_int4',
                'interior/gen_int5',
                'interior/gen_intb',
                'interior/int_cont',
                'interior/int_LA',
                'interior/int_SF',
                'interior/int_veg',
                'interior/savehous',
                'interior/stadint',
                'LA/LAe2',
                'LA/LAe',
                'LA/LAhills',
                'LA/LAn2',
                'LA/LAn',
                'LA/LAs2',
                'LA/LAs',
                'LA/LAw2',
                'LA/LAw',
                'LA/LaWn',
                'leveldes/leveldes',
                'leveldes/levelmap',
                'leveldes/seabed',
                'occluint',
                'occlu',
                'occluLA',
                'occlusf',
                'occluveg',
                'paths2',
                'paths3',
                'paths4',
                'paths5',
                'paths',
                'SF/SFe',
                'SF/SFn',
                'SF/SFSe',
                'SF/SFs',
                'SF/SFw',
                'tunnels',
                'vegas/vegasE',
                'vegas/vegasN',
                'vegas/vegasS',
                'vegas/vegasW',
                'vegas/vegaxref',
            ],
            ipl_stream: [
                //'barriers1', 'barriers2', 'carter', 'crack', 'truthsfarm',
                'countn2_stream0',
                'countn2_stream1',
                'countn2_stream2',
                'countn2_stream3',
                'countn2_stream4',
                'countn2_stream5',
                'countn2_stream6',
                'countn2_stream7',
                'countn2_stream8',
                'countrye_stream0',
                'countrye_stream1',
                'countrye_stream2',
                'countrye_stream3',
                'countrye_stream4',
                'countrye_stream5',
                'countrye_stream6',
                'countrye_stream7',
                'countrye_stream8',
                'countrye_stream9',
                'countrye_stream10',
                'countrye_stream11',
                'countrye_stream12',
                'countrye_stream13',
                'countryn_stream0',
                'countryn_stream1',
                'countryn_stream2',
                'countryn_stream3',
                'countrys_stream0',
                'countrys_stream1',
                'countrys_stream2',
                'countrys_stream3',
                'countrys_stream4',
                'countryw_stream0',
                'countryw_stream1',
                'countryw_stream2',
                'countryw_stream3',
                'countryw_stream4',
                'countryw_stream5',
                'countryw_stream6',
                'countryw_stream7',
                'countryw_stream8',
                'lae2_stream0',
                'lae2_stream1',
                'lae2_stream2',
                'lae2_stream3',
                'lae2_stream4',
                'lae2_stream5',
                'lae2_stream6',
                'lae_stream0',
                'lae_stream1',
                'lae_stream2',
                'lae_stream3',
                'lae_stream4',
                'lae_stream5',
                'lahills_stream0',
                'lahills_stream1',
                'lahills_stream2',
                'lahills_stream3',
                'lahills_stream4',
                'lan2_stream0',
                'lan2_stream1',
                'lan2_stream2',
                'lan2_stream3',
                'lan_stream0',
                'lan_stream1',
                'lan_stream2',
                'las2_stream0',
                'las2_stream1',
                'las2_stream2',
                'las2_stream3',
                'las2_stream4',
                'las_stream0',
                'las_stream1',
                'las_stream2',
                'las_stream3',
                'las_stream4',
                'las_stream5',
                'law2_stream0',
                'law2_stream1',
                'law2_stream2',
                'law2_stream3',
                'law2_stream4',
                'lawn_stream0',
                'lawn_stream1',
                'lawn_stream2',
                'lawn_stream3',
                'law_stream0',
                'law_stream1',
                'law_stream2',
                'law_stream3',
                'law_stream4',
                'law_stream5',
                'levelmap_stream0',
                'seabed_stream0',
                'sfe_stream0',
                'sfe_stream1',
                'sfe_stream2',
                'sfe_stream3',
                'sfn_stream0',
                'sfn_stream1',
                'sfn_stream2',
                'sfse_stream0',
                'sfse_stream1',
                'sfse_stream2',
                'sfse_stream3',
                'sfse_stream4',
                'sfse_stream5',
                'sfse_stream6',
                'sfs_stream0',
                'sfs_stream1',
                'sfs_stream2',
                'sfs_stream3',
                'sfs_stream4',
                'sfs_stream5',
                'sfs_stream6',
                'sfs_stream7',
                'sfs_stream8',
                'sfw_stream0',
                'sfw_stream1',
                'sfw_stream2',
                'sfw_stream3',
                'sfw_stream4',
                'sfw_stream5',
                'vegase_stream0',
                'vegase_stream1',
                'vegase_stream2',
                'vegase_stream3',
                'vegase_stream4',
                'vegase_stream5',
                'vegase_stream6',
                'vegase_stream7',
                'vegase_stream8',
                'vegasn_stream0',
                'vegasn_stream1',
                'vegasn_stream2',
                'vegasn_stream3',
                'vegasn_stream4',
                'vegasn_stream5',
                'vegasn_stream6',
                'vegasn_stream7',
                'vegasn_stream8',
                'vegass_stream0',
                'vegass_stream1',
                'vegass_stream2',
                'vegass_stream3',
                'vegass_stream4',
                'vegass_stream5',
                'vegasw_stream0',
                'vegasw_stream1',
                'vegasw_stream2',
                'vegasw_stream3',
                'vegasw_stream4',
                'vegasw_stream5',
                'vegasw_stream6',
                'vegasw_stream7',
                'vegasw_stream8',
                'vegasw_stream9',
                'vegasw_stream10',
                'vegasw_stream11',
            ],
        };
    }

    protected filter(item: ItemInstance, obj: ObjectDefinition, zone: string) {
        const interior = item.interior! & 0xFF;
        return interior === this.interior || interior === INTERIOR_EVERYWHERE;
    }
}

export const sceneGroup: SceneGroup = {
    id: 'GrandTheftAutoSanAndreas',
    name: 'Grand Theft Auto: San Andreas',
    sceneDescs: [
        new GTASASceneDesc(0, 'San Andreas'),
        new GTASASceneDesc(1),
        new GTASASceneDesc(2),
        new GTASASceneDesc(3),
        new GTASASceneDesc(4),
        new GTASASceneDesc(5),
        new GTASASceneDesc(6),
        new GTASASceneDesc(7),
        new GTASASceneDesc(8),
        new GTASASceneDesc(9),
        new GTASASceneDesc(10),
        new GTASASceneDesc(11),
        new GTASASceneDesc(12),
        new GTASASceneDesc(14),
        new GTASASceneDesc(15),
        new GTASASceneDesc(16),
        new GTASASceneDesc(17),
        new GTASASceneDesc(18),
    ]
};
