
import { SceneDesc } from 'render';
import { SceneGroup } from '../viewer';

const id = "oot3d";
const name = "Ocarina of Time 3D";
const sceneDescs:SceneDesc[] = [
    { name: "Inside the Deku Tree", filename: "ydan_info.zsi" },
    { name: "Inside the Deku Tree (Boss)", filename: "ydan_boss_info.zsi" },
    { name: "Dodongo's Cavern", filename: "ddan_info.zsi" },
    { name: "Dodongo's Cavern (Boss)", filename: "ddan_boss_info.zsi" },
    { name: "Jabu-Jabu's Belly", filename: 'bdan_info.zsi' },
    { name: "Jabu-Jabu's Belly (Boss)", filename: 'bdan_boss_info.zsi' },
    { name: "Forest Temple", filename: 'bmori1_info.zsi' },
    { name: "Forest Temple (Boss)", filename: "moriboss_info.zsi" },
    { name: "Fire Temple", filename: "hidan_info.zsi" },
    { name: "Fire Temple (Boss)", filename: "fire_bs_info.zsi" },
    { name: "Water Temple", filename: "mizusin_info.zsi" },
    { name: "Water Temple (Boss)", filename: "mizusin_boss_info.zsi" },
    { name: "Spirit Temple", filename: "jyasinzou_info.zsi" },
    { name: "Spirit Temple (Mid-Boss)", filename: "jyasinzou_boss_info.zsi" },
    { name: "Shadow Temple", filename: "hakadan_info.zsi" },
    { name: "Shadow Temple (Boss)", filename: "hakadan_boss_info.zsi" },
    { name: "Bottom of the Well", filename: "hakadan_ch_info.zsi" },
    { name: "Ice Cavern", filename: "ice_doukutu_info.zsi" },
    { name: "Gerudo Training Grounds", filename: "men_info.zsi" },
    { name: "Thieve's Hideout", filename: "gerudoway_info.zsi" },
    { name: "Ganon's Castle", filename: "ganontika_info.zsi" },
    { name: "Ganon's Castle (Crumbling)", filename: "ganontikasonogo_info.zsi" },
    { name: "Ganon's Castle (Outside)", filename: "ganon_tou_info.zsi" },
    { name: "Ganon's Castle Tower", filename: "ganon_info.zsi" },
    { name: "Ganon's Castle Tower (Crumbling)", filename: "ganon_sonogo_info.zsi" },
    { name: "Second-To-Last Boss Ganondorf", filename: "ganon_boss_info.zsi" },
    { name: "Final Battle Against Ganon", filename: "ganon_demo_info.zsi" },
    { name: "Ganondorf's Death", filename: "ganon_final_info.zsi" },
    { name: "Hyrule Field", filename: "spot00_info.zsi" },
    { name: "Kakariko Village", filename: "spot01_info.zsi" },
    { name: "Kakariko Graveyard", filename: "spot02_info.zsi" },
    { name: "Zora's River", filename: "spot03_info.zsi" },
    { name: "Kokiri Firest", filename: "spot04_info.zsi" },
    { name: "Sacred Forest Meadow", filename: "spot05_info.zsi" },
    { name: "Lake Hylia", filename: "spot06_info.zsi" },
    { name: "Zora's Domain", filename: "spot07_info.zsi" },
    { name: "Zora's Fountain", filename: "spot08_info.zsi" },
    { name: "Gerudo Valley", filename: "spot09_info.zsi" },
    { name: "Lost Woods", filename: "spot10_info.zsi" },
    { name: "Desert Colossus", filename: "spot11_info.zsi" },
    { name: "Gerudo's Fortress", filename: "spot12_info.zsi" },
    { name: "Haunted Wasteland", filename: "spot13_info.zsi" },
    { name: "Hyrule Castle", filename: "spot15_info.zsi" },
    { name: "Death Mountain", filename: "spot16_info.zsi" },
    { name: "Death Mountain Crater", filename: "spot17_info.zsi" },
    { name: "Goron City", filename: "spot18_info.zsi" },
    { name: "Lon Lon Ranch", filename: "spot20_info.zsi" },
    { name: "", filename: "spot99_info.zsi" },

    { name: "Market Entrance (Day)", filename: "entra_day_info.zsi" },
    { name: "Market Entrance (Night)", filename: "entra_night_info.zsi" },
    { name: "Market Entrance (Ruins)", filename: "entra_ruins_info.zsi" },
    { name: "Market (Day)", filename: "market_day_info.zsi" },
    { name: "Market (Night)", filename: "market_night_info.zsi" },
    { name: "Market (Ruins)", filename: "market_ruins_info.zsi" },
    { name: "Market Back-Alley (Day)", filename: "market_alley_info.zsi" },
    { name: "Market Back-Alley (Night)", filename: "market_alley_n_info.zsi" },
    { name: "Lots'o'Pots", filename: "miharigoya_info.zsi" },
    { name: "Bombchu Bowling Alley", filename: 'bowling_info.zsi' },
    { name: "Temple of Time (Outside, Day)", filename: "shrine_info.zsi" },
    { name: "Temple of Time (Outside, Night)", filename: "shrine_n_info.zsi" },
    { name: "Temple of Time (Outside, Adult)", filename: "shrine_r_info.zsi" },
    { name: "Temple of Time (Interior)", filename: "tokinoma_info.zsi" },
    { name: "Chamber of Sages", filename: "kenjyanoma_info.zsi" },
    { name: "Zora Shop", filename: "zoora_info.zsi" },
    { name: "Dampe's Hut", filename: "hut_info.zsi" },

    { name: "Great Fairy Fountain", filename: "daiyousei_izumi_info.zsi" },
    { name: "Small Fairy Fountain", filename: "yousei_izumi_tate_info.zsi" },
    { name: "Magic Fairy Fountain", filename: "yousei_izumi_yoko_info.zsi" },

    { name: "Castle Courtyard", filename: "hairal_niwa_info.zsi" },
    { name: "Castle Courtyard (Night)", filename: "hairal_niwa_n_info.zsi" },
    { name: '', filename: "hakaana_info.zsi" },
    { name: "Grottos", filename: "kakusiana_info.zsi" },
    { name: "Royal Family's Tomb", filename: "hakaana_ouke_info.zsi" },
    { name: "Dampe's Grave & Windmill Hut", filename: "hakasitarelay_info.zsi" },
    { name: "Cutscene Map", filename: "hiral_demo_info.zsi" },
    { name: "Hylia Lakeside Laboratory", filename: "hylia_labo_info.zsi" },
    { name: "Puppy Woman's House", filename: "kakariko_impa_info.zsi" },
    { name: "Skulltula House", filename: "kinsuta_info.zsi" },
    { name: "Impa's House", filename: "labo_info.zsi" },
    { name: "Granny's Potion Shop", filename: "mahouya_info.zsi" },
    { name: "Zelda's Courtyard", filename: "nakaniwa_info.zsi" },
    { name: "Market Potion Shop", filename: "shop_alley_info.zsi" },
    { name: "Kakariko Potion Shop", filename: "shop_drag_info.zsi" },
    { name: "Happy Mask Shop", filename: "shop_face_info.zsi" },
    { name: "Goron Shop", filename: "shop_golon_info.zsi" },
    { name: "Bombchu Shop", filename: "shop_night_info.zsi" },
    { name: "Talon's House", filename: "souko_info.zsi" },
    { name: "Stables", filename: "stable_info.zsi" },
    { name: "Shooting Gallery", filename: "syatekijyou_info.zsi" },
    { name: "Treasure Chest Game", filename: "takaraya_info.zsi" },
    { name: "Carpenter's Tent", filename: "tent_info.zsi" },

    { name: '', filename: "k_home_info.zsi" },
    { name: '', filename: "kakariko_info.zsi" },
    { name: '', filename: "kokiri_info.zsi" },
    { name: '', filename: "link_info.zsi" },
    { name: '', filename: "shop_info.zsi" },
    { name: "Fishing Pond", filename: "turibori_info.zsi" },
].map((entry):SceneDesc => {
    const path = `data/oot3d/${entry.filename}`;
    const name = entry.name || entry.filename;
    return new SceneDesc(name, path);
});

export const sceneGroup:SceneGroup = { id, name, sceneDescs };
