
// Build our WAT WebAssembly modules.

const path = require('path');
const wabt = require('wabt');
const fs = require('fs');

function buildBinaryArray(binary) {
    const binData = new Uint8Array(binary.buffer);
    const binStr = binData.join(',');
    const src = `new Uint8Array([${binStr}]);`;
    return src;
}

function buildModuleExportsInterface(exportName, wasmModule) {
    const modExports = WebAssembly.Module.exports(wasmModule);

    function getModuleExportType(exp) {
        switch (exp.kind) {
        case 'global':
            return `number`;
        case 'memory':
            return `WebAssembly.Memory`;
        default:
            throw "whoops";
        }
    }

    const lines = [];
    lines.push(`export interface ${exportName}Exports {`);
    for (const exp of modExports) {
        // For now, consumers are expected to provide signatures,
        // until this information is available through the toolchain...
        if (exp.kind === 'function')
            continue;
        lines.push(`    ${exp.name}: ${getModuleExportType(exp)};`);
    }
    lines.push('}');
    return lines.join('\n');
}

function buildModuleCode(module) {
    const exportName = module.exportName;
    const filename = module.filename;

    const wat = fs.readFileSync(path.join(__dirname, filename));
    const wabtModule = wabt.parseWat(filename, wat);
    wabtModule.resolveNames();
    wabtModule.validate();
    const binary = wabtModule.toBinary({});

    const wasmModule = new WebAssembly.Module(binary.buffer);
    buildModuleExportsInterface(exportName, wasmModule);

    const binArrayStr = buildBinaryArray(binary);

    return `
// ${filename}
${buildModuleExportsInterface(exportName, wasmModule)}
const ${exportName}Code = ${binArrayStr};
const ${exportName}Module = new WebAssembly.Module(${exportName}Code);
export function ${exportName}Instance(): ${exportName}Exports {
    const instance = new WebAssembly.Instance(${exportName}Module);
    return (<${exportName}Exports> instance.exports);
}
`;
}

function buildModulesFile(modules) {
    let s = `// Generated by build_wat.js\n`;
    for (const module of modules) {
        s += buildModuleCode(module);
    }
    return s;
}

function main() {
    const out = buildModulesFile([
        { exportName: 'yaz0', filename: 'yaz0.wat' },
        { exportName: 'yaz0_as', filename: 'yaz0_as.wat' },
        { exportName: 'gx_texture', filename: 'gx/gx_texture.wat' },
    ]);
    fs.writeFileSync(path.join(__dirname, 'wat_modules.ts'), out);
}

main();
