import { Color, colorNewFromRGBA8 } from "../Color";
import {
    BackgroundConstructor,
    BgBonus,
    BgIce,
    BgJungle,
    BgMaster,
    BgNight,
    BgSand,
    BgSpace,
    BgStorm,
    BgSunset,
    BgWater,
} from "./Background";

export const enum StageId {
    St001_Plain = 1,
    St002_Diamond = 2,
    St003_Hairpin = 3,
    St004_Wide_Bridge = 4,
    St005_Slopes = 5,
    St006_Steps = 6,
    St007_Blocks = 7,
    St008_Jump_Single = 8,
    St009_Exam_A = 9,
    St010_Arcade_Spiral_Hard = 10,
    St011_Bump = 11,
    St012_Walking = 12,
    St013_Repulse = 13,
    St014_Narrow_Bridge = 14,
    St015_Break = 15,
    St016_Curves = 16,
    St017_Downhill = 17,
    St018_Blocks_Slim = 18,
    St019_Arcade_Diamond = 19,
    St020_Arcade_Tracks = 20,
    St021_Choice = 21,
    St022_Bowl = 22,
    St023_Jumpies = 23,
    St024_Stoppers = 24,
    St025_Floor_Bent = 25,
    St026_Conveyor = 26,
    St027_Exam_B = 27,
    St028_Chaser = 28,
    St029_Jump_Double = 29,
    St030_Arcade_Bridge_Master = 30,
    St031_Middle_Jam = 31,
    St032_Antlion = 32,
    St033_Collapse = 33,
    St034_Swing_Bar = 34,
    St035_Labyrinth = 35,
    St036_Spiral = 36,
    St037_Wavy_Jump = 37,
    St038_Spiky = 38,
    St039_Unrest = 39,
    St040_Polar = 40,
    St041_Ruin = 41,
    St042_Branch = 42,
    St043_Overturn = 43,
    St044_Excursion = 44,
    St045_Dodecagon = 45,
    St046_Exam_C = 46,
    St047_Skeleton = 47,
    St048_Tracks = 48,
    St049_Arcade_Narrow_Bridge = 49,
    St050_Arcade_Curl_Pipe = 50,
    St051_Downhill_Hard = 51,
    St052_Gears = 52,
    St053_Destruction = 53,
    St054_Invasion = 54,
    St055_Diving = 55,
    St056_Floor_Slant = 56,
    St057_Tram = 57,
    St058_Swing_Bar_Long = 58,
    St059_Paperwork = 59,
    St060_Arcade_Sanctuary = 60,
    St061_Twin_Attacker = 61,
    St062_Sega_Logo = 62,
    St063_Snake = 63,
    St064_Wind = 64,
    St065_Windy_Slide = 65,
    St066_Fall_Down = 66,
    St067_Twin_Cross = 67,
    St068_Spiral_Hard = 68,
    St069_Conveyor_Parts = 69,
    St070_Arcade_Hitter = 70,
    St071_Gaps = 71,
    St072_Curvature = 72,
    St073_Ant_Lion_Super = 73,
    St074_Drum = 74,
    St075_Twist_And_Spin = 75,
    St076_Speedy_Jam = 76,
    St077_Quake = 77,
    St078_Cassiopeia = 78,
    St079_Pirates = 79,
    St080_Arcade_Av_Logo = 80,
    St081_Bowl_Open = 81,
    St082_Checker = 82,
    St083_Carpet = 83,
    St084_Ridge = 84,
    St085_Mixer = 85,
    St086_Rings = 86,
    St087_Stairs = 87,
    St088_Clover = 88,
    St089_Coffee_Cup = 89,
    St090_Metamorphasis = 90,
    St091_Bonus_Basic = 91,
    St092_Bonus_Wave = 92,
    St093_Bonus_Grid = 93,
    St094_Bonus_Bumpy = 94,
    St095_Bonus_Hunting = 95,
    St096_Arcade_Snake = 96,
    St097_Arcade_Gears = 97,
    St098_Arcade_Conveyer_Parts = 98,
    St099_Jungle_Bg = 99,
    St100_Arcade_Polar_Large = 100,
    St101_Blur_Bridge = 101,
    St102_Hitter = 102,
    St103_Av_Logo = 103,
    St104_Hard_Hitter = 104,
    St105_Puzzle = 105,
    St106_Polar_Large = 106,
    St107_Breathe = 107,
    St108_Ferris_Wheel = 108,
    St109_Factory = 109,
    St110_Curl_Pipe = 110,
    St111_Magic_Hand = 111,
    St112_Sanctuary = 112,
    St113_Daa_Loo_Maa = 113,
    St114_Unused_Rings_Stage = 114,
    St115_Alternate_Edge_Master = 115,
    St116_Alternate_Roll_Master = 116,
    St117_Arcade_Curves = 117,
    St118_Arcade_Jump_Double = 118,
    St119_Arcade_Downhill_Hard = 119,
    St120_Arcade_Dodecagon = 120,
    St121_Wave_Master = 121,
    St122_Fan_Master = 122,
    St123_Stamina_Master = 123,
    St124_Spring_Master = 124,
    St125_Dance_Master = 125,
    St126_Roll_Master = 126,
    St127_Edge_Master = 127,
    St128_Dodge_Master = 128,
    St129_Bridge_Master = 129,
    St130_Monkey_Master = 130,
    St131_Race_Space = 131,
    St132_Race_Unused = 132,
    St133_Race_Jungle = 133,
    St134_Race_Ice = 134,
    St135_Race_Downtown = 135,
    St136_Race_Water = 136,
    St137_Chaser_Duplicate = 137,
    St138_Race_Desert = 138,
    St139_Exam_A_Broken = 139,
    St140_Av_Logo_Broken = 140,
    St141_Yellow_Square = 141,
    St142_Water_Test = 142,
    St143_Fight_Jungle = 143,
    St144_Fight_Ice = 144,
    St145_Fight_Space = 145,
    St150_Tutorial = 150,
    St151_Target_Circles = 151,
    St152_Target_Pyramids = 152,
    St153_Target_Hexagons = 153,
    St154_Target_Unuseds = 154,
    St155_Monkey_Target_Bg = 155,
    St161_Golf_Hole_18 = 161,
    St162_Golf_Hole_4 = 162,
    St163_Golf_Hole_6 = 163,
    St164_Golf_Hole_3 = 164,
    St165_Golf_Hole_5 = 165,
    St166_Golf_Hole_15 = 166,
    St167_Golf_Hole_1 = 167,
    St168_Golf_Hole_8 = 168,
    St169_Golf_Hole_10 = 169,
    St170_Golf_Hole_14 = 170,
    St171_Golf_Hole_16 = 171,
    St172_Golf_Hole_7 = 172,
    St173_Golf_Hole_12 = 173,
    St174_Golf_Hole_17 = 174,
    St175_Golf_Hole_9 = 175,
    St176_Golf_Hole_13 = 176,
    St177_Golf_Hole_2 = 177,
    St178_Golf_Hole_11 = 178,
    St179_Bowling = 179,
    St180_Billiards = 180,
    St197_Bonus_Bg = 197,
    St198_Ending_Cutscene_Bg = 198,
}

export const enum BgType {
    BlueSky = 1,
    Jungle = 13,
    Water = 14,
    Night = 15,
    Sunset = 16,
    Space = 17,
    Sand = 18,
    Ice = 19,
    Storm = 20,
    Bonus = 21,
    Target = 22,
    Billiards = 23,
    Golf = 24,
    Bowling = 25,
    Master = 26,
    Ending = 27,
}

export type BgInfo = {
    fileName: string;
    clearColor: Color;
    bgConstructor: BackgroundConstructor;
};

export type StageInfo = {
    bgInfo: BgInfo;
    // TODO(complexplane): Next stage
};

namespace BgInfos {
    export const Jungle: BgInfo = {
        fileName: "bg_jun",
        clearColor: colorNewFromRGBA8(0xffffffff),
        bgConstructor: BgJungle,
    };
    export const Water: BgInfo = {
        fileName: "bg_wat",
        clearColor: colorNewFromRGBA8(0x000000ff),
        bgConstructor: BgWater,
    };
    export const Night: BgInfo = {
        fileName: "bg_nig",
        clearColor: colorNewFromRGBA8(0x000000ff),
        bgConstructor: BgNight,
    };
    export const Sunset: BgInfo = {
        fileName: "bg_sun",
        clearColor: colorNewFromRGBA8(0x000000ff),
        bgConstructor: BgSunset,
    };
    export const Space: BgInfo = {
        fileName: "bg_spa",
        clearColor: colorNewFromRGBA8(0x000000ff),
        bgConstructor: BgSpace,
    };
    export const Sand: BgInfo = {
        fileName: "bg_snd",
        clearColor: colorNewFromRGBA8(0xd8bc77ff),
        bgConstructor: BgSand,
    };
    export const Ice: BgInfo = {
        fileName: "bg_ice",
        clearColor: colorNewFromRGBA8(0x000000ff),
        bgConstructor: BgIce,
    };
    export const Storm: BgInfo = {
        fileName: "bg_stm",
        clearColor: colorNewFromRGBA8(0x000000ff),
        bgConstructor: BgStorm,
    };
    export const Bonus: BgInfo = {
        fileName: "bg_bns",
        clearColor: colorNewFromRGBA8(0x000000ff),
        bgConstructor: BgBonus,
    };
    export const Target: BgInfo = {
        fileName: "bg_pil",
        clearColor: colorNewFromRGBA8(0xffffffff),
        bgConstructor: {} as any,
    };
    export const Golf: BgInfo = {
        fileName: "bg_gol",
        clearColor: colorNewFromRGBA8(0xffffffff),
        bgConstructor: {} as any,
    };
    export const Bowling: BgInfo = {
        fileName: "bg_bow",
        clearColor: colorNewFromRGBA8(0xffffffff),
        bgConstructor: {} as any,
    };
    export const Master: BgInfo = {
        fileName: "bg_mst",
        clearColor: colorNewFromRGBA8(0xffffcdff),
        bgConstructor: BgMaster,
    };
    export const Ending: BgInfo = {
        fileName: "bg_ending",
        clearColor: colorNewFromRGBA8(0xffffffff),
        bgConstructor: {} as any,
    };
}

export const STAGE_INFO_MAP: Map<StageId, StageInfo> = new Map([
    [StageId.St001_Plain, { bgInfo: BgInfos.Jungle }],
    [StageId.St002_Diamond, { bgInfo: BgInfos.Jungle }],
    [StageId.St003_Hairpin, { bgInfo: BgInfos.Jungle }],
    [StageId.St004_Wide_Bridge, { bgInfo: BgInfos.Jungle }],
    [StageId.St005_Slopes, { bgInfo: BgInfos.Sunset }],
    [StageId.St006_Steps, { bgInfo: BgInfos.Sunset }],
    [StageId.St007_Blocks, { bgInfo: BgInfos.Sunset }],
    [StageId.St008_Jump_Single, { bgInfo: BgInfos.Sunset }],
    [StageId.St009_Exam_A, { bgInfo: BgInfos.Sunset }],
    // [StageId.St010_Arcade_Spiral_Hard,     BgInfos.BlueSky],
    [StageId.St011_Bump, { bgInfo: BgInfos.Jungle }],
    [StageId.St012_Walking, { bgInfo: BgInfos.Jungle }],
    [StageId.St013_Repulse, { bgInfo: BgInfos.Jungle }],
    [StageId.St014_Narrow_Bridge, { bgInfo: BgInfos.Jungle }],
    [StageId.St015_Break, { bgInfo: BgInfos.Sunset }],
    [StageId.St016_Curves, { bgInfo: BgInfos.Sunset }],
    [StageId.St017_Downhill, { bgInfo: BgInfos.Sunset }],
    [StageId.St018_Blocks_Slim, { bgInfo: BgInfos.Sunset }],
    // [StageId.St019_Arcade_Diamond,      { bgInfo:    BgInfos.BlueSky],
    // [StageId.St020_Arcade_Tracks,       { bgInfo:    BgInfos.BlueSky],
    [StageId.St021_Choice, { bgInfo: BgInfos.Night }],
    [StageId.St022_Bowl, { bgInfo: BgInfos.Night }],
    [StageId.St023_Jumpies, { bgInfo: BgInfos.Night }],
    [StageId.St024_Stoppers, { bgInfo: BgInfos.Night }],
    [StageId.St025_Floor_Bent, { bgInfo: BgInfos.Night }],
    [StageId.St026_Conveyor, { bgInfo: BgInfos.Night }],
    [StageId.St027_Exam_B, { bgInfo: BgInfos.Night }],
    [StageId.St028_Chaser, { bgInfo: BgInfos.Night }],
    [StageId.St029_Jump_Double, { bgInfo: BgInfos.Night }],
    // [StageId.St030_Arcade_Bridge_Master,{ bgInfo:    BgInfos.BlueSky],
    [StageId.St031_Middle_Jam, { bgInfo: BgInfos.Water }],
    [StageId.St032_Antlion, { bgInfo: BgInfos.Water }],
    [StageId.St033_Collapse, { bgInfo: BgInfos.Water }],
    [StageId.St034_Swing_Bar, { bgInfo: BgInfos.Water }],
    [StageId.St035_Labyrinth, { bgInfo: BgInfos.Water }],
    [StageId.St036_Spiral, { bgInfo: BgInfos.Water }],
    [StageId.St037_Wavy_Jump, { bgInfo: BgInfos.Water }],
    [StageId.St038_Spiky, { bgInfo: BgInfos.Water }],
    [StageId.St039_Unrest, { bgInfo: BgInfos.Water }],
    [StageId.St040_Polar, { bgInfo: BgInfos.Water }],
    [StageId.St041_Ruin, { bgInfo: BgInfos.Jungle }],
    [StageId.St042_Branch, { bgInfo: BgInfos.Jungle }],
    [StageId.St043_Overturn, { bgInfo: BgInfos.Jungle }],
    [StageId.St044_Excursion, { bgInfo: BgInfos.Jungle }],
    [StageId.St045_Dodecagon, { bgInfo: BgInfos.Night }],
    [StageId.St046_Exam_C, { bgInfo: BgInfos.Night }],
    [StageId.St047_Skeleton, { bgInfo: BgInfos.Night }],
    [StageId.St048_Tracks, { bgInfo: BgInfos.Night }],
    // [StageId.St049_Arcade_Narrow_Bridge,   BgInfos.BlueSky],
    // [StageId.St050_Arcade_Curl_Pipe,       BgInfos.BlueSky],
    [StageId.St051_Downhill_Hard, { bgInfo: BgInfos.Water }],
    [StageId.St052_Gears, { bgInfo: BgInfos.Water }],
    [StageId.St053_Destruction, { bgInfo: BgInfos.Water }],
    [StageId.St054_Invasion, { bgInfo: BgInfos.Water }],
    [StageId.St055_Diving, { bgInfo: BgInfos.Water }],
    [StageId.St056_Floor_Slant, { bgInfo: BgInfos.Water }],
    [StageId.St057_Tram, { bgInfo: BgInfos.Water }],
    [StageId.St058_Swing_Bar_Long, { bgInfo: BgInfos.Water }],
    [StageId.St059_Paperwork, { bgInfo: BgInfos.Water }],
    // [StageId.St060_Arcade_Sanctuary,    { bgInfo:    BgInfos.BlueSky],
    [StageId.St061_Twin_Attacker, { bgInfo: BgInfos.Sand }],
    [StageId.St062_Sega_Logo, { bgInfo: BgInfos.Sand }],
    [StageId.St063_Snake, { bgInfo: BgInfos.Sand }],
    [StageId.St064_Wind, { bgInfo: BgInfos.Sand }],
    [StageId.St065_Windy_Slide, { bgInfo: BgInfos.Sand }],
    [StageId.St066_Fall_Down, { bgInfo: BgInfos.Sand }],
    [StageId.St067_Twin_Cross, { bgInfo: BgInfos.Sand }],
    [StageId.St068_Spiral_Hard, { bgInfo: BgInfos.Sand }],
    [StageId.St069_Conveyor_Parts, { bgInfo: BgInfos.Sand }],
    // [StageId.St070_Arcade_Hitter,       { bgInfo:    BgInfos.BlueSky],
    [StageId.St071_Gaps, { bgInfo: BgInfos.Ice }],
    [StageId.St072_Curvature, { bgInfo: BgInfos.Ice }],
    [StageId.St073_Ant_Lion_Super, { bgInfo: BgInfos.Ice }],
    [StageId.St074_Drum, { bgInfo: BgInfos.Ice }],
    [StageId.St075_Twist_And_Spin, { bgInfo: BgInfos.Ice }],
    [StageId.St076_Speedy_Jam, { bgInfo: BgInfos.Ice }],
    [StageId.St077_Quake, { bgInfo: BgInfos.Ice }],
    [StageId.St078_Cassiopeia, { bgInfo: BgInfos.Ice }],
    [StageId.St079_Pirates, { bgInfo: BgInfos.Ice }],
    // [StageId.St080_Arcade_Av_Logo,      { bgInfo:    BgInfos.BlueSky],
    [StageId.St081_Bowl_Open, { bgInfo: BgInfos.Storm }],
    [StageId.St082_Checker, { bgInfo: BgInfos.Storm }],
    [StageId.St083_Carpet, { bgInfo: BgInfos.Storm }],
    [StageId.St084_Ridge, { bgInfo: BgInfos.Storm }],
    [StageId.St085_Mixer, { bgInfo: BgInfos.Storm }],
    [StageId.St086_Rings, { bgInfo: BgInfos.Storm }],
    [StageId.St087_Stairs, { bgInfo: BgInfos.Storm }],
    [StageId.St088_Clover, { bgInfo: BgInfos.Storm }],
    [StageId.St089_Coffee_Cup, { bgInfo: BgInfos.Storm }],
    [StageId.St090_Metamorphasis, { bgInfo: BgInfos.Storm }],
    [StageId.St091_Bonus_Basic, { bgInfo: BgInfos.Bonus }],
    [StageId.St092_Bonus_Wave, { bgInfo: BgInfos.Bonus }],
    [StageId.St093_Bonus_Grid, { bgInfo: BgInfos.Bonus }],
    [StageId.St094_Bonus_Bumpy, { bgInfo: BgInfos.Bonus }],
    [StageId.St095_Bonus_Hunting, { bgInfo: BgInfos.Bonus }],
    // [StageId.St096_Arcade_Snake,        { bgInfo:       BgInfos.BlueSky],
    // [StageId.St097_Arcade_Gears,        { bgInfo:       BgInfos.BlueSky],
    // [StageId.St098_Arcade_Conveyer_Parts{ bgInfo:    ,  BgInfos.BlueSky],
    [StageId.St099_Jungle_Bg, { bgInfo: BgInfos.Jungle }],
    // [StageId.St100_Arcade_Polar_Large,  { bgInfo:       BgInfos.BlueSky],
    [StageId.St101_Blur_Bridge, { bgInfo: BgInfos.Space }],
    [StageId.St102_Hitter, { bgInfo: BgInfos.Space }],
    [StageId.St103_Av_Logo, { bgInfo: BgInfos.Space }],
    [StageId.St104_Hard_Hitter, { bgInfo: BgInfos.Space }],
    [StageId.St105_Puzzle, { bgInfo: BgInfos.Space }],
    [StageId.St106_Polar_Large, { bgInfo: BgInfos.Space }],
    [StageId.St107_Breathe, { bgInfo: BgInfos.Space }],
    [StageId.St108_Ferris_Wheel, { bgInfo: BgInfos.Space }],
    [StageId.St109_Factory, { bgInfo: BgInfos.Space }],
    [StageId.St110_Curl_Pipe, { bgInfo: BgInfos.Space }],
    [StageId.St111_Magic_Hand, { bgInfo: BgInfos.Space }],
    [StageId.St112_Sanctuary, { bgInfo: BgInfos.Space }],
    [StageId.St113_Daa_Loo_Maa, { bgInfo: BgInfos.Space }],
    // [StageId.St114_Unused_Rings_Stage,  { bgInfo:       BgInfos.BlueSky],
    [StageId.St115_Alternate_Edge_Master, { bgInfo: BgInfos.Master }],
    [StageId.St116_Alternate_Roll_Master, { bgInfo: BgInfos.Master }],
    [StageId.St117_Arcade_Curves, { bgInfo: BgInfos.Master }],
    [StageId.St118_Arcade_Jump_Double, { bgInfo: BgInfos.Master }],
    [StageId.St119_Arcade_Downhill_Hard, { bgInfo: BgInfos.Master }],
    [StageId.St120_Arcade_Dodecagon, { bgInfo: BgInfos.Master }],
    [StageId.St121_Wave_Master, { bgInfo: BgInfos.Master }],
    [StageId.St122_Fan_Master, { bgInfo: BgInfos.Master }],
    [StageId.St123_Stamina_Master, { bgInfo: BgInfos.Master }],
    [StageId.St124_Spring_Master, { bgInfo: BgInfos.Master }],
    [StageId.St125_Dance_Master, { bgInfo: BgInfos.Master }],
    [StageId.St126_Roll_Master, { bgInfo: BgInfos.Master }],
    [StageId.St127_Edge_Master, { bgInfo: BgInfos.Master }],
    [StageId.St128_Dodge_Master, { bgInfo: BgInfos.Master }],
    [StageId.St129_Bridge_Master, { bgInfo: BgInfos.Master }],
    [StageId.St130_Monkey_Master, { bgInfo: BgInfos.Master }],
    [StageId.St131_Race_Space, { bgInfo: BgInfos.Space }],
    [StageId.St132_Race_Unused, { bgInfo: BgInfos.Sand }],
    [StageId.St133_Race_Jungle, { bgInfo: BgInfos.Jungle }],
    [StageId.St134_Race_Ice, { bgInfo: BgInfos.Ice }],
    [StageId.St135_Race_Downtown, { bgInfo: BgInfos.Night }],
    [StageId.St136_Race_Water, { bgInfo: BgInfos.Water }],
    [StageId.St137_Chaser_Duplicate, { bgInfo: BgInfos.Night }],
    [StageId.St138_Race_Desert, { bgInfo: BgInfos.Sand }],
    [StageId.St139_Exam_A_Broken, { bgInfo: BgInfos.Sunset }],
    [StageId.St140_Av_Logo_Broken, { bgInfo: BgInfos.Space }],
    [StageId.St141_Yellow_Square, { bgInfo: BgInfos.Space }],
    [StageId.St142_Water_Test, { bgInfo: BgInfos.Water }],
    [StageId.St143_Fight_Jungle, { bgInfo: BgInfos.Jungle }],
    [StageId.St144_Fight_Ice, { bgInfo: BgInfos.Ice }],
    [StageId.St145_Fight_Space, { bgInfo: BgInfos.Space }],
    [StageId.St150_Tutorial, { bgInfo: BgInfos.Jungle }],
    [StageId.St151_Target_Circles, { bgInfo: BgInfos.Target }],
    [StageId.St152_Target_Pyramids, { bgInfo: BgInfos.Target }],
    [StageId.St153_Target_Hexagons, { bgInfo: BgInfos.Target }],
    [StageId.St154_Target_Unuseds, { bgInfo: BgInfos.Target }],
    [StageId.St155_Monkey_Target_Bg, { bgInfo: BgInfos.Target }],
    [StageId.St161_Golf_Hole_18, { bgInfo: BgInfos.Jungle }],
    [StageId.St162_Golf_Hole_4, { bgInfo: BgInfos.Jungle }],
    [StageId.St163_Golf_Hole_6, { bgInfo: BgInfos.Jungle }],
    [StageId.St164_Golf_Hole_3, { bgInfo: BgInfos.Jungle }],
    [StageId.St165_Golf_Hole_5, { bgInfo: BgInfos.Jungle }],
    [StageId.St166_Golf_Hole_15, { bgInfo: BgInfos.Jungle }],
    [StageId.St167_Golf_Hole_1, { bgInfo: BgInfos.Jungle }],
    [StageId.St168_Golf_Hole_8, { bgInfo: BgInfos.Jungle }],
    [StageId.St169_Golf_Hole_10, { bgInfo: BgInfos.Jungle }],
    [StageId.St170_Golf_Hole_14, { bgInfo: BgInfos.Jungle }],
    [StageId.St171_Golf_Hole_16, { bgInfo: BgInfos.Jungle }],
    [StageId.St172_Golf_Hole_7, { bgInfo: BgInfos.Jungle }],
    [StageId.St173_Golf_Hole_12, { bgInfo: BgInfos.Jungle }],
    [StageId.St174_Golf_Hole_17, { bgInfo: BgInfos.Jungle }],
    [StageId.St175_Golf_Hole_9, { bgInfo: BgInfos.Jungle }],
    [StageId.St176_Golf_Hole_13, { bgInfo: BgInfos.Jungle }],
    [StageId.St177_Golf_Hole_2, { bgInfo: BgInfos.Jungle }],
    [StageId.St178_Golf_Hole_11, { bgInfo: BgInfos.Jungle }],
    [StageId.St179_Bowling, { bgInfo: BgInfos.Bowling }],
    // [StageId.St180_Billiards,           { bgInfo:    BgInfos.Billiards],
    [StageId.St197_Bonus_Bg, { bgInfo: BgInfos.Bonus }],
    [StageId.St198_Ending_Cutscene_Bg, { bgInfo: BgInfos.Ending }],
]);
